import type { Scenario } from '../types';

export const BEAR_WITH_ME: Scenario = {
  id: 'bear-with-me', title: 'Bear with Me', subtitle: 'A warning can cross the water. You cannot.', startScene: 'campAcrossWater',
  timePhases: [{ id: 'evening', label: 'Evening Camp', atMinutes: 0 }, { id: 'night', label: 'Nightfall', atMinutes: 18 }],
  runRandomSelections: [
    { id: 'camper', values: ['Varda', 'Kestrel', 'Nollan', 'Iona', 'Odel'].map((value) => ({ value })) },
    { id: 'camperReaction', values: ['alert', 'unaware'].map((value) => ({ value })) },
    { id: 'bearEvent', values: [{ value: 'quiet', weight: 2 }, { value: 'approach', weight: 3 }] },
    { id: 'bearMood', values: ['wary', 'unbothered', 'defensive'].map((value) => ({ value })) },
    { id: 'crossing', values: ['ford', 'noFord'].map((value) => ({ value })) },
    { id: 'camperFate', values: ['escapes', 'injured', 'killed'].map((value) => ({ value })) },
  ],
  scenes: {
    campAcrossWater: { id: 'campAcrossWater', title: 'Two Camps, One River', tone: 'safe',
      text: 'You pitch your small camp on the near bank of a broad, cold river. Across the water, perhaps a hundred paces away, {{camper}} lays out a bedroll in an open patch below the trees. The current is too strong to wade here, and no bridge or boat is in sight. Your own fire and pack are beside you.',
      choices: [
        { id: 'waveAcross', label: 'Wave to the other camper', timeCost: 2, effects: { historyFlags: ['noticed_far_bank_camp'] }, next: 'eveningAtCamp' },
        { id: 'tendOwnFire', label: 'Tend your fire and settle in', timeCost: 6, effects: { setFlags: ['tended_own_fire'] }, next: 'eveningAtCamp' },
        { id: 'callAcross', label: 'Call a greeting across the river', timeCost: 2, effects: { historyFlags: ['greeted_camper_across_water'] }, next: 'eveningAtCamp' },
        { id: 'leaveRiverBank', label: 'Pack up and continue down the road', effects: { historyFlags: ['left_other_camper_across_water'] }, next: 'leftTheRiver' },
      ] },
    eveningAtCamp: { id: 'eveningAtCamp', title: 'The Far-Bank Camp', tone: 'safe',
      text: 'The evening settles over both camps. You are still on the near bank; {{camper}} is across the wide current, with no easy crossing between you.',
      textVariants: [
        { requirements: { selections: { bearEvent: 'approach', camperReaction: 'alert' } }, text: 'A bear comes out of the trees on the far bank, several dozen paces behind {{camper}}. It sniffs at the food bundle. {{camper}} has heard the rustling and begins to turn. The river is broad and swift; you cannot reach them directly from here.' },
        { requirements: { selections: { bearEvent: 'approach', camperReaction: 'unaware' } }, text: 'A bear comes out of the trees on the far bank, several dozen paces behind {{camper}}. It sniffs at the food bundle. {{camper}} has not turned around. The river is broad and swift; you cannot reach them directly from here.' },
        { requirements: { historyFlags: ['greeted_camper_across_water'] }, text: '{{camper}} answers your greeting with a raised hand. The evening settles over both camps. You are still on the near bank, with no easy crossing between you.' },
        { requirements: { flags: ['tended_own_fire'] }, text: 'Your fire catches and the evening settles over both camps. {{camper}} is across the wide current; no easy crossing lies between you.' },
      ],
      choices: [
        { id: 'shoutWarning', label: 'Shout a warning across the water', requirements: { selections: { bearEvent: 'approach' } }, hint: 'Your warning may carry—or the bear may ignore it.', timeCost: 1, effects: { historyFlags: ['warned_camper_of_bear'] }, chance: { probability: 0.56, bonusSelections: { bearMood: 'wary', camperReaction: 'alert' }, bonusProbability: 0.14, penaltySelections: { bearMood: 'defensive', camperReaction: 'unaware' }, penaltyProbability: 0.12, successNext: 'bearHesitates', failureNext: 'bearAdvances', successMessage: '{{camper}} looks up as the bear pauses. You cannot know whether your shout changed its behavior.', failureMessage: '{{camper}} turns at your shout, but the bear keeps moving.' } },
        { id: 'useWhistle', label: 'Blow your carried whistle', requirements: { selections: { bearEvent: 'approach' }, anyItems: ['trailWhistle', 'conductorWhistle', 'farmWhistle'] }, hint: 'You have it with you on your bank; sound may still carry poorly.', timeCost: 1, effects: { historyFlags: ['warned_camper_of_bear'] }, chance: { probability: 0.62, bonusSelections: { bearMood: 'wary', camperReaction: 'alert' }, bonusProbability: 0.12, penaltySelections: { bearMood: 'defensive', camperReaction: 'unaware' }, penaltyProbability: 0.16, successNext: 'bearHesitates', failureNext: 'bearAdvances', successMessage: 'The sharp whistle carries. The bear looks toward the sound; whether it is startled or merely curious is unclear.', failureMessage: 'The whistle reaches the far bank, but the bear barely pauses.', successEffects: { historyFlags: ['distracted_bear_from_distance'] } } },
        { id: 'stayAtCamp', label: 'Stay on your bank and watch', requirements: { selections: { bearEvent: 'approach' } }, effects: { historyFlags: ['stayed_on_own_bank_during_bear_encounter'] }, next: 'bearAdvances' },
        { id: 'quietEvening', label: 'Enjoy a quiet evening', requirements: { selections: { bearEvent: 'quiet' } }, timeCost: 12, effects: { historyFlags: ['spent_evening_at_river_camp'] }, next: 'quietRiverEnding' },
      ] },
    bearHesitates: { id: 'bearHesitates', title: 'A Pause Across the River', tone: 'warning',
      text: 'The bear stops to look toward your bank. {{camper}} has seen it now and backs away from the food bundle. The bear has not charged; the sound may have helped, or the animal may simply be deciding what to do.',
      choices: [
        { id: 'callCamperBack', label: 'Call for them to retreat toward the trees', timeCost: 1, effects: { historyFlags: ['warned_camper_of_bear'] }, next: 'farBankReaction' },
        { id: 'searchForFordEarly', label: 'Search downstream for a crossing', timeCost: 10, next: 'crossingSearch' },
        { id: 'keepDistance', label: 'Stay on your bank and keep watch', effects: { historyFlags: ['chose_not_to_cross_after_bear_attack'] }, next: 'farBankReaction' },
      ] },
    bearAdvances: { id: 'bearAdvances', title: 'The Bear Reaches the Camp', tone: 'danger',
      text: 'The bear lunges toward the far-bank camp. You hear a short cry before the trees hide the scene. From this distance you cannot tell whether {{camper}} is hurt, hiding, or already moving away. The current remains between you.',
      textVariants: [{ requirements: { selections: { camperFate: 'escapes' } }, text: 'The bear reaches the far-bank camp, but {{camper}} bolts into the trees. You see no clear sign of injury. You cannot safely cross here, and the current still separates both camps.' }],
      choices: [
        { id: 'callAfterBear', label: 'Call across and watch for an answer', timeCost: 2, effects: { historyFlags: ['witnessed_bear_attack'] }, next: 'callingAcross' },
        { id: 'searchAfterBear', label: 'Search downstream for a crossing', timeCost: 10, effects: { historyFlags: ['witnessed_bear_attack'] }, next: 'crossingSearch' },
        { id: 'stayFarBank', label: 'Stay put; the river is too dangerous', effects: { historyFlags: ['witnessed_bear_attack', 'chose_not_to_cross_after_bear_attack'] }, next: 'leftAcrossWater' },
      ] },
    callingAcross: { id: 'callingAcross', title: 'No Certain Answer', tone: 'warning',
      text: 'You call {{camper}}’s name. There is movement among the far-bank trees, but at this distance you cannot tell who made it. A lack of an answer does not tell you whether the camper is dead.',
      textVariants: [
        { requirements: { selections: { camperFate: 'escapes' } }, text: 'You call {{camper}}’s name. A figure moves farther up the bank but does not answer. They may be frightened or simply unable to hear you; you cannot tell whether they are hurt.' },
        { requirements: { selections: { camperFate: 'injured' } }, text: 'You call {{camper}}’s name. A faint movement appears beside the bedroll, but there is no answer. You cannot tell how badly they are hurt.' },
      ],
      choices: [
        { id: 'searchAfterCall', label: 'Look for a way across', timeCost: 8, next: 'crossingSearch' },
        { id: 'leaveAfterCall', label: 'Leave them to the far bank', effects: { historyFlags: ['chose_not_to_cross_after_bear_attack'] }, next: 'leftAcrossWater' },
      ] },
    crossingSearch: { id: 'crossingSearch', title: 'Downstream', tone: 'warning',
      text: 'You follow the near bank downstream. The water is still broad and fast; you cannot see the other camper clearly through the trees.',
      textVariants: [
        { requirements: { selections: { crossing: 'ford' } }, text: 'Downstream the river spreads over a stony shelf. The water reaches your waist and moves quickly, but the stones may make a crossing possible. Beyond them is the far bank and the trail back toward {{camper}}’s camp.' },
        { requirements: { selections: { crossing: 'noFord' } }, text: 'You find no ford. The banks stay steep and the current is too strong to wade. Swimming across would put your own life at serious risk; there is no boat or bridge nearby.' },
      ],
      choices: [
        { id: 'crossFord', label: 'Try the stony ford', requirements: { selections: { crossing: 'ford' } }, hint: 'The current is strong; a slip could sweep you downstream.', timeCost: 6, chance: { probability: 0.65, successNext: 'reachedCamper', failureNext: 'sweptDownstream', successMessage: 'You cross between the larger stones and reach the far bank, winded but upright.', failureMessage: 'A step slips and the current knocks you off balance.', successEffects: { historyFlags: ['crossed_to_far_bank_after_bear_attack'] }, failureEffects: { historyFlags: ['attempted_dangerous_river_crossing'] } } },
        { id: 'riskTheSwim', label: 'Attempt the dangerous swim', requirements: { selections: { crossing: 'noFord' } }, hint: 'The current is strong enough to drown you; no safe landing is visible.', timeCost: 7, chance: { probability: 0.24, successNext: 'reachedCamper', failureNext: 'sweptDownstream', successMessage: 'You find a slower seam in the current and reach the opposite bank exhausted.', failureMessage: 'The current takes your legs before you can reach the far side.', successEffects: { health: -3, historyFlags: ['crossed_to_far_bank_after_bear_attack'] }, failureEffects: { health: -6, historyFlags: ['attempted_dangerous_river_crossing'] } } },
        { id: 'turnBackFromRiver', label: 'Turn back to your camp', effects: { historyFlags: ['chose_not_to_cross_after_bear_attack'] }, next: 'leftAcrossWater' },
      ] },
    sweptDownstream: { id: 'sweptDownstream', title: 'The Current Breaks Your Attempt', tone: 'danger',
      text: 'You are battered against the near-bank shallows, short of breath and far downstream. The far-bank camper is now out of sight. You could try one last push for the bank, but your strength is failing.',
      choices: [
        { id: 'crawlOut', label: 'Use the shallows to crawl out', effects: { health: -2 }, next: 'leftAcrossWater' },
        { id: 'pushAgainstCurrent', label: 'Make one last push toward shore', hint: 'You are exhausted and the current is still pulling hard.', chance: { probability: 0.34, successNext: 'leftAcrossWater', failureNext: 'riverDeath', successMessage: 'You reach the mud shelf and drag yourself clear.', failureMessage: 'The current pulls you under before you can get another breath.', successEffects: { health: -2 }, failureEffects: { health: -10 } } },
      ] },
    reachedCamper: { id: 'reachedCamper', title: 'At the Far Camp', tone: 'warning',
      text: 'You reach the scattered camp and find {{camper}} alive, shaken, and able to stand. The bear has gone into the trees. You cannot know whether your warning changed what happened.',
      textVariants: [
        { requirements: { selections: { camperFate: 'injured' } }, text: 'At the far camp, {{camper}} is alive but hurt and struggling to stand. The bear has gone into the trees. You cannot know whether your warning changed what happened.' },
        { requirements: { selections: { camperFate: 'killed' } }, text: 'At the far camp you confirm that {{camper}} did not survive the attack. From the near bank you could not have known; the bear is already gone into the trees.' },
      ],
      choices: [
        { id: 'bandageCamper', label: 'Use your bandage on their injury', requirements: { selections: { camperFate: 'injured' }, items: ['fieldBandageRoll'] }, effects: { loseItems: ['fieldBandageRoll'], historyFlags: ['rescued_bear_attack_victim', 'crossed_water_for_injured_camper'] }, next: 'camperHelped' },
        { id: 'guideCamperWhoEscaped', label: 'Help them toward the nearest house', requirements: { selections: { camperFate: 'escapes' } }, effects: { historyFlags: ['rescued_bear_attack_victim'] }, next: 'camperHelped' },
        { id: 'guideInjuredCamper', label: 'Help them toward the nearest house', requirements: { selections: { camperFate: 'injured' } }, effects: { historyFlags: ['rescued_bear_attack_victim', 'crossed_water_for_injured_camper'] }, next: 'camperHelped' },
        { id: 'leaveFarCamp', label: 'Return to your own bank', effects: { historyFlags: ['returned_from_far_bank_after_bear_attack'] }, next: 'camperOutcomeEnding' },
      ] },
    camperHelped: { id: 'camperHelped', title: 'Walking to Shelter', tone: 'safe', text: 'You help {{camper}} reach a nearby farmhouse. They will need more care than you can give at camp, but they are not alone now.', ending: 'success', choices: [] },
    camperOutcomeEnding: { id: 'camperOutcomeEnding', title: 'Back Across the Water', tone: 'warning', text: 'You return to your own bank. You do not know whether the bear would have come closer or whether your actions changed anything.', ending: 'success', choices: [] },
    farBankReaction: { id: 'farBankReaction', title: 'Across the Current', tone: 'warning',
      text: '{{camper}} moves away from the food bundle. The bear pauses, and then turns toward the trees. It may have been your warning—or the camper’s movement—that sent it off.',
      textVariants: [{ requirements: { selections: { bearMood: 'defensive' } }, text: '{{camper}} backs toward the trees, but the bear is still near the camp. It watches the far bank for a moment before turning away. You cannot know whether your shout changed its choice.' }],
      choices: [
        { id: 'callCamperAfterRetreat', label: 'Call once to check they are moving', timeCost: 1, effects: { historyFlags: ['warned_camper_of_bear'] }, next: 'quietAcrossEnding' },
        { id: 'leaveAfterRetreat', label: 'Stay on your side and let the night pass', effects: { historyFlags: ['chose_not_to_cross_after_bear_attack'] }, next: 'quietAcrossEnding' },
      ] },
    quietAcrossEnding: { id: 'quietAcrossEnding', title: 'A Long Night by the River', tone: 'safe', text: 'The bear disappears among the trees. Across the water, {{camper}} gathers the scattered things and stays near the fire. You never learn whether the shout made the difference.', ending: 'success', choices: [] },
    quietRiverEnding: { id: 'quietRiverEnding', title: 'A Quiet Camp', tone: 'safe', text: 'Nothing interrupts the evening. Across the water, {{camper}} tends their small fire while you eat beside yours. The river keeps both camps apart until morning.', ending: 'success', choices: [] },
    leftTheRiver: { id: 'leftTheRiver', title: 'The Road Beyond the Bank', tone: 'safe', text: 'You leave before night settles. The other camper remains across the river. You have no reason to think trouble is coming.', ending: 'success', choices: [] },
    leftAcrossWater: { id: 'leftAcrossWater', title: 'The River Between', tone: 'safe', text: 'You return to the near bank. You cannot see the camper clearly, and the river is not safe to cross. The choice leaves an uncertain outcome on the far side.', ending: 'success', choices: [] },
    riverDeath: { id: 'riverDeath', title: 'Taken by the Current', tone: 'danger', text: 'The river pulls you under. You chose a crossing after seeing the current and knowing no safe landing was visible.', ending: 'death', choices: [] },
  },
};
