import type { Scenario, Scene } from '../types';
import { KNOWLEDGE_FACTS } from '../knowledgeFacts';
import { largeAdventure, largeEnd, largeScene, largeTags } from './largeContentTools';

type Lane = 'GEAR' | 'KNOWLEDGE' | 'LORE';
type BuildStory = {
  id:string; title:string; site:string; risk:'LOW'|'MODERATE'|'HIGH'; lane:Lane;
  job:string; sign:string; method:string; methodResult:string; turn:string; decision:string;
  safe:string; alternate:string; tool?:string; toolName?:string; toolSource?:string;
  knowledge?:keyof typeof KNOWLEDGE_FACTS; lesson?:string; lore?:string; loreCallback?:string;
  coins:number;
};

const stories:BuildStory[] = [
  {id:'the-square-at-mill-street',title:'The Square at Mill Street',site:'new shopfront on Mill Street',risk:'LOW',lane:'GEAR',job:'Carpenter Lena Voss has set the new shopfront frame, but the upper corner pulls out of square as the crew lifts the lintel.',sign:'The lower sill is level; the diagonal braces differ by a handspan, and the crew has not nailed the frame permanently.',method:'Check the corner with your Carpenter’s Square before the crew fixes the lintel',methodResult:'The square shows the left post is sound but the temporary brace has slipped in its notch.',turn:'When the crew eases the lintel down, a dark older beam appears behind the new post. Voss recognizes its tool marks from a demolished depot, but does not know why it was reused.',decision:'Hold the frame while Voss checks the reused beam’s bearing',safe:'The lintel is lowered onto trestles and the frame is trued before fastening; the old beam remains visible for the owner to inspect.',alternate:'The crew replaces the slipped brace and leaves the frame unfastened until the builder can return.',tool:'carpenterSquare',toolName:'Carpenter’s Square',toolSource:'Lena Voss signs over her personally owned spare Carpenter’s Square after the shop owner accepts the frame inspection.',lesson:'A square corner is not proof of a sound bearing; check both alignment and what carries the load.',lore:'Mill Street’s first depot was dismantled after the rail spur moved; its marked timbers were sold to local builders.',coins:2},
  {id:'the-roof-that-held-its-breath',title:'The Roof That Held Its Breath',site:'farmhouse roof after a windstorm',risk:'MODERATE',lane:'GEAR',job:'Roofer Bram Ellery needs help keeping a loosened roof edge down before rain reaches the bedroom ceiling.',sign:'The rafters still meet the ridge, but two lower ends have drawn away from the wall plate; a ladder stands on firm ground.',method:'Secure the loose edge from the low eave with the Travel Rope while Ellery checks the rafters',methodResult:'The rope holds the loose covering, not the roof frame; Ellery finds one split rafter that must be shored before anyone climbs higher.',turn:'A neighbor says this roof has always bowed. Ellery points to fresh bright splits beside old dark timber and asks whether to patch or open the ceiling.',decision:'Shore the split rafter, then open only the ceiling board beneath it for inspection',safe:'The temporary shore takes the rafter’s movement; the wet room is emptied and the permanent repair is left to the roofer.',alternate:'The owner chooses a tarp and a closed room until Ellery can bring a second carpenter.',tool:'steelWedge',toolName:'Steel Wedge',toolSource:'Ellery releases his personally owned Steel Wedge after the homeowner pays for the temporary shoring materials.',lesson:'A long-standing roof bow can hide fresh movement; compare new splits and joints instead of trusting the silhouette.',coins:2},
  {id:'three-knots-on-the-platform',title:'Three Knots on the Platform',site:'temporary fair reviewing stand',risk:'HIGH',lane:'GEAR',job:'The fair organizer asks you to help inspect a raised wooden stand before families are admitted.',sign:'One scaffold lashing is loose, one foot rests on packed earth, and the platform is still empty; the builder has stopped entry.',method:'Use the Folding Bench Clamp to hold a loose rail while the builder replaces its lashing',methodResult:'The clamp steadies the rail for fitting but cannot support the platform; the builder finds the far post sinking into the rain-soft ground.',turn:'A stage hand says the stand held last year. This year’s crowd is larger, and a painted load limit has been covered by a fresh coat.',decision:'Keep the stand closed while the builder resets the foot and posts a visible limit',safe:'The foot is moved to a broad timber pad and the lashing is replaced; the organizer opens only the lower viewing area.',alternate:'The organizer cancels the raised viewing and offers the crew a partial day wage for the inspection.',tool:'foldingBenchClamp',toolName:'Folding Bench Clamp',toolSource:'The stand builder transfers his personal spare Folding Bench Clamp after the organizer releases it from the contractor’s tool account.',lesson:'A clamp can hold pieces during fitting, but it cannot replace a footing or carry a crowd load.',coins:2},
  {id:'the-wall-beneath-the-plaster',title:'The Wall Beneath the Plaster',site:'town tailor’s renovation',risk:'MODERATE',lane:'GEAR',job:'A tailor wants a doorway widened. Mason Hett asks you to steady the trim while he checks the wall before cutting.',sign:'A hairline crack runs from the door corner, and its edges are freshly dusty; the floor above is occupied.',method:'Use the Pocket Toolkit to remove one loose trim board without disturbing the cracked plaster',methodResult:'Behind the trim, the newer partition ends short of the ceiling; Hett says the main wall may still carry the floor joists.',turn:'The owner insists an earlier carpenter called the wall “empty.” Hett finds a timber end seated over the doorway and refuses to cut until the upstairs room is cleared.',decision:'Clear the room and ask Hett to expose the bearing from the safe side',safe:'The work stops before the timber is cut; a qualified builder marks a narrower opening that avoids the bearing.',alternate:'The tailor postpones the doorway and pays for the inspection rather than risk an unverified cut.',tool:'pocketToolkit',toolName:'Pocket Toolkit',toolSource:'Mason Hett gives you his personally owned Pocket Toolkit as the agreed inspection fee; the shop’s tools remain on site.',lesson:'A partition that looks light may still receive a joist; trace what rests on it before opening a wall.',coins:2},
  {id:'the-riverward-retaining-wall',title:'The Riverward Retaining Wall',site:'stone retaining wall above a riverside lane',risk:'HIGH',lane:'GEAR',job:'After several days of rain, the lane keeper reports that the retaining wall has begun to bulge toward the road.',sign:'Water seeps from two mortar joints, and the upper course leans outward; the lane below can be closed from either end.',method:'Set a marked barrier and use the Collapsible Sounding Rod to check the ground beyond the wall from the road side',methodResult:'The rod finds soft ground behind the lower course; the wall is not safe to brace from the river edge.',turn:'A cart is waiting at the far gate. Its driver says the wall moved years ago and never fell, but fresh grit lies below the newest bulge.',decision:'Keep the lane closed and send the cart around while a mason checks the drainage',safe:'The cart takes the longer high road; the mason opens a controlled drain from firm ground and schedules the wall for rebuilding.',alternate:'The lane stays shut until the river drops; the keeper records the fresh movement rather than calling it an old harmless lean.',tool:'collapsibleSoundingRod',toolName:'Collapsible Sounding Rod',toolSource:'The lane keeper transfers his personally owned spare Collapsible Sounding Rod after the county pays for the inspection.',lesson:'A familiar lean is not proof of stability; fresh grit, new seepage, and changing ground call for a current inspection.',coins:3},
  {id:'the-barn-door-that-wasnt-square',title:'The Barn Door That Wasn’t Square',site:'livestock barn after a post replacement',risk:'MODERATE',lane:'GEAR',job:'A new barn door binds after a storm repair. Carpenter Noll asks you to help fit the hinge rail while the animals remain in the rear stalls.',sign:'The door frame is plumb at the top but the sill has lifted where water softened one post base.',method:'Check the hinge spacing with the Carpenter’s Square before Noll trims the door',methodResult:'The hinge line is true; the post base is not. Trimming the door would hide a moving frame and leave the opening weak.',turn:'An older hand says the post was replaced once already. Its cut end bears a small three-notch builder mark beneath the newer paint.',decision:'Brace the opening and let Noll inspect the post footing before refitting the door',safe:'The animals are moved to the far stalls; the post is supported and the door is left off until the footing is renewed.',alternate:'The farmer installs a temporary gate and delays the permanent door rather than shaving it to fit.',tool:'carpenterSquare',toolName:'Carpenter’s Square',toolSource:'Carpenter Noll releases his personally owned spare square when the farmer pays the repair bill.',lesson:'A door that binds after rain may be reporting movement in its frame, not a poor door fit.',lore:'Three notches under the barn paint match the mark of the Marrow crew, known locally for rebuilding storm barns after the 1868 gale.',coins:2},
  {id:'the-wedge-at-the-schoolhouse',title:'The Wedge at the Schoolhouse',site:'one-room schoolhouse floor',risk:'LOW',lane:'GEAR',job:'A schoolteacher reports a new gap beneath a floor beam. Builder Ada Pell asks you to keep children outside while she inspects the crawlspace.',sign:'The gap has widened since yesterday, and a chalk mark on the beam has shifted; the floor above is empty.',method:'Use the Steel Wedge to hold a temporary shore while Pell checks the beam ends',methodResult:'The wedge keeps the shore seated, but Pell finds damp rot where the beam enters the north wall.',turn:'A parent says the school has always settled toward the creek. Pell finds that the creek-side wall was rebuilt with different stone after an old washout.',decision:'Keep the room closed and ask the town to inspect the rebuilt wall before reopening',safe:'The children use the meeting room next door; Pell adds a second support only after checking its footing.',alternate:'The teacher accepts a one-day closure and asks the town clerk for the old repair account.',tool:'steelWedge',toolName:'Steel Wedge',toolSource:'Builder Pell gives you her own spare Steel Wedge after the school board releases it from her private kit.',lesson:'A shore transfers weight only to its footing; check the base and bearing before trusting a support.',coins:1},
  {id:'the-last-board-at-harper-yard',title:'The Last Board at Harper Yard',site:'carpenter’s yard and unfinished porch',risk:'MODERATE',lane:'GEAR',job:'The porch crew has one straight beam left, but the owner wants it used as a roof tie before the storm arrives.',sign:'The porch posts are not yet braced, and the beam has a shallow split at one end; the roof materials are already stacked above.',method:'Use the Hand Auger to bore a small test hole away from the split before the carpenter chooses its use',methodResult:'The timber is sound through the middle but the split runs farther than the painted face suggests; the carpenter refuses it as a roof tie.',turn:'The owner says the beam came from an old meeting hall and wants its carved end saved. The crew can shore the porch with shorter stock, but the roof must wait.',decision:'Use shorter sound stock for a temporary brace and preserve the carved end for the owner',safe:'The porch is held with two shorter braces and the roof work is postponed; the carved end is set aside, not discarded.',alternate:'The owner removes the carved end from the work area and hires a timber yard to source a proper tie.',tool:'handAuger',toolName:'Hand Auger',toolSource:'The carpenter transfers his personally owned Hand Auger after the owner pays for the test and replacement stock.',lesson:'A small test bore can reveal sound timber, but it cannot make a split member safe for a different load.',lore:'Harper Yard’s carved beams came from the first meeting hall, dismantled when the town moved its common green uphill.',coins:2},
  {id:'the-joint-that-opened-in-winter',title:'The Joint That Opened in Winter',site:'mountain stagecoach inn',risk:'MODERATE',lane:'KNOWLEDGE',job:'Innkeeper Sera Vale asks carpenter Vos to inspect a stair landing that has opened along one wall during a cold snap.',sign:'The gap is narrow, but a pencil mark across the joint has separated since morning; no one is using the upper rooms.',method:'Compare the joint mark with the door frame and the landing below before anyone tightens the rail',methodResult:'The door still swings freely, but the landing has shifted at its outer post; the movement is not limited to a loose handrail.',turn:'A traveler wants the upper room opened for the night. Vos explains the visible signs but cannot say from one look whether the footing has stopped moving.',decision:'Keep the upper rooms closed and ask the innkeeper to move guests downstairs',safe:'The carpenter marks the joint for a second inspection after the ground thaws; no one treats a single reading as a full diagnosis.',alternate:'Vale pays the agreed inspection wage and keeps the landing closed until a mason can check the footing.',knowledge:'winterJointMovement',lesson:'A joint mark that continues to separate shows active movement; one observation cannot establish that a footing has settled safely.',coins:2},
  {id:'the-shed-with-two-roofs',title:'The Shed with Two Roofs',site:'abandoned wagon shed at a stage stop',risk:'HIGH',lane:'KNOWLEDGE',job:'A stage owner wants to reopen an unused shed before winter. Builder Fen asks you to check the ground-level posts while he stays outside.',sign:'The outer roof looks straight, but water stains descend behind a newer board layer and the west wall leans toward the door.',method:'Inspect the base plates from outside and compare the door opening at top and bottom',methodResult:'The opening narrows upward, and the lower board is soft. The newer roof skin hides an older roof frame rather than replacing it.',turn:'Fen finds no deed or transfer for the shed; the stage owner has only a caretaker’s key. A sign inside bears another company’s faded name.',decision:'Stop the reopening and have the owner trace the property claim before anyone enters',safe:'The shed remains closed and marked; the owner sends the name to the county recorder and hires a builder only after authority is clear.',alternate:'Fen boards the entrance from stable ground and records the visible damage for the person who can establish ownership.',knowledge:'waterBehindCladding',lesson:'Water stains that continue behind a newer surface can indicate hidden decay; inspect from a safe edge before opening the wall.',lore:'The shed belonged to the North Fork Stage Company, whose route ended when the ridge road was abandoned.',coins:1},
  {id:'the-brace-before-the-bell',title:'The Brace Before the Bell',site:'town meeting hall belfry',risk:'HIGH',lane:'KNOWLEDGE',job:'The bell rope has begun rubbing a timber brace. Builder Harlan asks you to help keep the stair clear while he checks the tower.',sign:'The brace has a fresh pale line where the rope touches it; the bell is silent and the stair landing is narrow.',method:'Measure the visible gap from the landing with a plumb line before anyone climbs into the belfry',methodResult:'The brace leans a little farther than the opposite one. The line gives a comparison, not a safe load rating.',turn:'The bell committee wants the evening bell rung for a funeral. Harlan says the tower needs a closer inspection from a proper platform first.',decision:'Keep the bell silent and arrange a ground-level notice while the belfry is examined',safe:'The bell is not rung; the committee posts the notice at the doors and Harlan arranges a scaffold inspection.',alternate:'The committee accepts a brief delay and asks Harlan to report whether the tower can be used after a second check.',knowledge:'bellTowerBraceSigns',lesson:'A new rub mark and a changing lean deserve attention together; a plumb line compares position but does not certify the tower.',coins:2},
  {id:'the-stone-that-kept-the-water',title:'The Stone That Kept the Water',site:'mason’s renovation beside a cellar',risk:'MODERATE',lane:'KNOWLEDGE',job:'A mason opens a cellar wall to stop seepage and asks you to hold the lantern while he checks the stone courses.',sign:'Water enters at a mortar joint, but the stones above remain aligned; a newer patch sits over a narrow drain channel.',method:'Use the Lantern Guard to light the open joint while the mason traces the channel from outside',methodResult:'The channel turns away from the cellar, toward an older street drain. Breaking the whole wall would destroy the route before it is understood.',turn:'The owner wants the channel sealed immediately. The mason explains that water may be following the old drain rather than entering through the foundation.',decision:'Mark the wet joints and ask the town to inspect the drain route before sealing it',safe:'The cellar goods are moved away from the wall; a mason makes a temporary catch basin while the drain is traced.',alternate:'The owner accepts a limited repair on the inside face and leaves the buried channel untouched for a later inspection.',knowledge:'waterPathBeforeWall',lesson:'A wet foundation joint may show where water emerges, not where it entered; trace the route before sealing the visible point.',coins:2},
  {id:'the-ladder-in-the-west-yard',title:'The Ladder in the West Yard',site:'warehouse scaffold and loading door',risk:'MODERATE',lane:'KNOWLEDGE',job:'A delivery crew needs a scaffold ladder moved before unloading crates. Foreman Cale asks you to inspect the feet while the crew waits.',sign:'One ladder foot sits on a loose plank, and the upper lashings are hidden behind a canvas screen; no worker is on the platform.',method:'Use the Travel Rope to secure the ladder base while Cale checks each lashing from the ground',methodResult:'The base stays put, but a worn knot has been tied over a split rail; securing one point does not make the platform sound.',turn:'The warehouse owner says the scaffold stood through yesterday’s rain. Cale points out that the plank has shifted since the morning chalk mark.',decision:'Keep the loading door clear and rebuild the ladder support before the crew climbs',safe:'The crates are unloaded by the ground ramp; Cale replaces the split rail and marks the ladder for a fresh inspection.',alternate:'The delivery waits until the scaffold is rebuilt, and the crew is paid for the delay rather than asked to climb.',knowledge:'scaffoldFootAndLashing',lesson:'Check scaffold footing and lashings as separate failure points; a secured base cannot compensate for a split rail.',coins:2},
  {id:'the-chimney-that-pulled-away',title:'The Chimney That Pulled Away',site:'boarding house after a kitchen fire',risk:'HIGH',lane:'KNOWLEDGE',job:'A small kitchen fire is out, but the brick chimney has separated from the wall. Mason Elsen asks you to keep the rooms empty.',sign:'Soot marks stop at the ceiling, and a crack runs down one side of the chimney breast; no flame remains.',method:'Use Heavy Leather Gloves to remove a loose board at floor level while Elsen inspects the visible brickwork',methodResult:'The gloves protect from rough charred wood, but the chimney’s upper connection remains hidden and cannot be judged from below.',turn:'The landlord wants the rooms reopened before evening. Elsen finds a newer timber tie scorched at one end and will not call the chimney secure.',decision:'Keep the rooms closed and ask the mason to inspect the upper tie from a safe platform',safe:'Guests are moved to the neighboring inn; the damaged tie is not disturbed until the chimney is supported.',alternate:'The landlord accepts a partial day’s rent loss and leaves the rooms closed pending a proper inspection.',knowledge:'fireDamageHiddenTie',lesson:'A fire can weaken a concealed tie beyond the visible soot line; keep the area closed until the connection is inspected.',coins:2},
  {id:'the-ramp-for-the-grain-cart',title:'The Ramp for the Grain Cart',site:'mill loading ramp',risk:'LOW',lane:'KNOWLEDGE',job:'A grain cart’s new ramp flexes under a half load. The miller asks you to help the carpenter test it before harvest deliveries begin.',sign:'The ramp boards are sound, but the two supports rest on different ground levels; the cart is stopped before the incline.',method:'Set the cart’s load aside and compare both support feet before adding any weight',methodResult:'The lower support sits on loose fill. The ramp length is adequate, but the bearing beneath one end is not.',turn:'A worker suggests adding another plank on top. The carpenter says that would spread the surface but not repair the loose footing.',decision:'Re-seat the lower support on firm ground, then test with a small empty cart',safe:'The ramp is leveled at its feet and tested without a load; the miller delays full deliveries until the carpenter signs it off.',alternate:'The miller keeps using the old ground-level entrance and schedules the ramp repair for the next dry day.',knowledge:'rampLoadAtFeet',lesson:'A ramp’s boards can be strong while its supports fail; inspect where the weight reaches the ground.',coins:1},
  {id:'the-tower-without-its-shadow',title:'The Tower Without Its Shadow',site:'abandoned fire lookout above the valley',risk:'MODERATE',lane:'LORE',job:'A county surveyor asks you to help decide whether an old lookout can be used as a storm signal station.',sign:'The stair rail is loose and the tower leans toward a stand of pines; the surveyor keeps everyone on the stone apron.',method:'Compare the tower’s shadow line with the old foundation stones from the clear side',methodResult:'The stones do not match the present legs. The tower has been moved once, and the surveyor finds an earlier maker stamp beneath the paint.',turn:'Local resident Iven Rusk says the lookout was moved after the 1872 fire, not built on this ridge. The county ledger may explain why it was abandoned.',decision:'Record the old stamp and keep the tower closed until the county checks the foundation',safe:'The surveyor marks the site but does not climb; a ground signal post is planned beside the stable stones.',alternate:'The county accepts a temporary signal station at the trailhead and commissions a history search before repair.',lore:'The Crow Ridge lookout was moved after the 1872 valley fire; its first foundation still stands below the eastern pines.',lesson:'A moved structure may retain old parts without retaining its old supports; compare the frame to its current foundation.',coins:2},
  {id:'the-hall-with-the-mismatched-stone',title:'The Hall with the Mismatched Stone',site:'old town hall entrance',risk:'LOW',lane:'LORE',job:'A mason is replacing a cracked entrance step and asks you to help sort the numbered stones.',sign:'Most blocks are local gray stone; one red block bears a chisel mark and fits the step only when turned inward.',method:'Set the red block aside and ask the town clerk before cutting it to fit',methodResult:'The clerk recognizes the mark from the old courthouse, which burned before the hall was built.',turn:'The red block has a shallow inscription on its hidden face. The mason can preserve it by using a plain replacement at the entrance.',decision:'Turn the block inward in a protected interior course and record the inscription',safe:'The entry is rebuilt with a new step; the marked block is set inside where it cannot carry foot traffic.',alternate:'The clerk chooses to keep the block in the town store until the historical account is checked.',lore:'The town hall reused a red courthouse stone after the 1859 fire; its inward-facing inscription names the first public works committee.',lesson:'Reused masonry may carry a history that is not visible from its present face; ask before cutting a marked stone.',coins:1},
  {id:'the-shed-at-ash-lot',title:'The Shed at Ash Lot',site:'burned settlement edge',risk:'MODERATE',lane:'LORE',job:'A landholder asks a carpenter to remove a blackened shed before the road crew widens the lane.',sign:'The shed roof has fallen inward, but the front wall remains upright; the landholder has a deed for the lot, not the shed contents.',method:'Mark a no-entry line and inspect the outer sill for a builder’s mark before demolition',methodResult:'The sill carries the initials of a settlement cooperative, and the rear stones extend beyond the deed’s surveyed edge.',turn:'A nearby elder recalls that the cooperative left the lot after a spring flood. The landholder wants the structure gone before the road survey.',decision:'Pause demolition and compare the old cooperative boundary with the current road line',safe:'The crew removes only loose material from the public side and leaves the marked foundation undisturbed until the boundary is checked.',alternate:'The landholder agrees to a short delay and asks the surveyor to document the old stones before work resumes.',lore:'Ash Lot was the storehouse of the Bracken Cooperative, abandoned after the 1861 flood shifted the creek and boundary stones.',lesson:'A deed to land does not automatically resolve who owns marked structure materials or where an old foundation lies.',coins:2},
  {id:'the-school-bell-frame',title:'The School Bell Frame',site:'schoolhouse bell loft',risk:'MODERATE',lane:'LORE',job:'The teacher wants the bell rehung before the autumn term. Builder Mara Dey asks you to help inspect the frame from the loft hatch.',sign:'The bell hangs from a newer crosspiece; older peg holes remain in the side beams, and the loft floor has a clear walkway.',method:'Compare the peg holes and current crosspiece before anyone lifts the bell',methodResult:'The new crosspiece spans the older holes, but its ends rest on sound beams. The original bell position was lower and farther from the stair.',turn:'The teacher says a former bell ringer refused to use the old position after a child was hurt during a storm drill.',decision:'Ask the town clerk for the school record and keep the bell lowered until the history is clear',safe:'The bell remains on the ground while the town checks the record; the school uses a hand bell for the term opening.',alternate:'Dey rehanges it on the inspected crosspiece and records why the original holes were not reused.',lore:'The school bell was lowered after an 1879 storm drill injury; the old peg holes mark a position no longer considered safe.',lesson:'Old fixing holes show where something once sat, not whether that position remains safe or appropriate.',coins:1},
  {id:'the-lodge-wall-under-new-paint',title:'The Lodge Wall Under New Paint',site:'workers’ lodge renovation',risk:'LOW',lane:'LORE',job:'The lodge committee hires a painter and carpenter to repair a wall where the plaster has bubbled.',sign:'The paint is newer than the plaster, and a hand-cut timber joint appears beneath one lifted corner.',method:'Preserve the exposed joint and ask the oldest committee member before covering it',methodResult:'The member recognizes the joint as part of the lodge’s first meeting room, built by miners who shared tools after a shaft closure.',turn:'The committee disagrees whether the wall should be restored to its first layout or kept as the larger room added later.',decision:'Record both building phases and let the members choose which room layout serves them now',safe:'The joint is protected behind a removable panel; the committee keeps the later room arrangement for its meetings.',alternate:'The committee restores the partition but records the later expansion rather than calling it an error.',lore:'The workers’ lodge began as a one-room hall built by miners after the Bell Shaft closed, then expanded by member labor.',lesson:'A building’s later alteration can be part of its community history rather than a defect to erase.',coins:1},
  {id:'the-bridge-camp-post',title:'The Bridge Camp Post',site:'abandoned construction camp by a creek',risk:'MODERATE',lane:'LORE',job:'A county crew finds a squared post buried beside an old footbridge and asks you to help identify whether it can be reused.',sign:'The post has a numbered cut and an iron shoe; the creek bank has shifted, leaving its original footing unknown.',method:'Clean only the exposed face with Heavy Leather Gloves and record the cut marks before lifting it',methodResult:'The number matches an old bridge ledger entry, but the ledger names a different crossing upstream.',turn:'A resident says the bridge camp was abandoned after workers refused to move a pier during a flood season.',decision:'Keep the post out of the new footing and compare the camp record before the crew reuses it',safe:'The post is stored as evidence of the old works; the new footbridge uses fresh timber sized for its present bank.',alternate:'The county clerk records the number and releases the post only for nonstructural use after its origin is checked.',lore:'The creek bridge camp closed when its crew rejected a flood-season pier move; numbered posts were later scattered to other crossings.',lesson:'A reused post’s old number can trace its origin, but it cannot prove its timber is sound for a new structural load.',coins:2},
  {id:'the-theater-that-never-opened',title:'The Theater That Never Opened',site:'unfinished brick theater',risk:'HIGH',lane:'LORE',job:'A theater owner asks a mason to secure a half-built balcony before opening the ground floor as a market.',sign:'The balcony joists are in place but the outer rail is missing; the stair is blocked and the ground floor has a separate street exit.',method:'Keep the balcony closed and inspect the visible joist ends from the floor below',methodResult:'The joists are sound where visible, but the support posts stop short of the foundation course.',turn:'The owner says the original builder disappeared. A mason finds two different maker marks on the same wall and an unfinished invoice tucked behind a brick.',decision:'Keep the upper level closed and ask the town recorder to identify the builder and claim before altering the wall',safe:'The market opens only at ground level; the balcony remains supported from below until ownership and plans are checked.',alternate:'The owner postpones the opening and pays the crew for securing the public exit and documenting the incomplete work.',lore:'The Bellweather Theater was left unfinished after its builder and backer disputed the cost of a deeper balcony footing.',lesson:'Visible joists do not show the whole load path; verify where supports meet the foundation before allowing use.',coins:2},
  {id:'the-old-well-house',title:'The Old Well House',site:'stone well house behind the county store',risk:'LOW',lane:'LORE',job:'A caretaker asks you to help a mason repair the well-house door after a winter freeze.',sign:'The door frame is sound, but one stone has a faded blue stripe and a small iron ring set into its inner face.',method:'Keep the ring untouched and compare the stone position with the old well sketch',methodResult:'The ring is not a door fitting; it marks the former location of a hand-operated drain gate.',turn:'The caretaker says the well house was moved uphill after a flood, but the public account says it was rebuilt in place.',decision:'Ask the clerk to preserve the discrepancy in the repair record before the stone is reset',safe:'The mason fits the door without removing the marked stone; the clerk checks the flood account.',alternate:'The caretaker approves a plain replacement and keeps the marked stone in the county store for later study.',lore:'The county well house was moved uphill after the 1864 flood; its ring-marked stone belonged to the earlier drain gate.',lesson:'A fitting that looks out of place may belong to an earlier building phase; compare records before removing it.',coins:1},
  {id:'the-tower-bell-anchor',title:'The Tower Bell Anchor',site:'brick water tower service platform',risk:'HIGH',lane:'KNOWLEDGE',job:'A maintenance crew hears a clank from the tower’s outside platform and asks you to help check the anchor points from the ladder base.',sign:'One tie rod has a bright scrape and the platform moves slightly in the wind; the ladder is secured but the upper access is closed.',method:'Use the Brass Plumb Bob from the ladder base to compare the tower face before and after a gust',methodResult:'The line shows a small repeated sway, not whether the tie rod can safely carry the platform.',turn:'The crew chief wants to climb and tighten the rod. A second worker notices the platform’s lower bracket has pulled away from the brick.',decision:'Keep the platform closed and ask a mason to inspect the bracket from a separate scaffold',safe:'The crew marks the tower out of service; the water supply remains on through a ground valve.',alternate:'The chief arranges a scaffold inspection and records both the rod scrape and bracket movement.',knowledge:'tieRodAndBracketTogether',lesson:'A moving tie rod and a pulled bracket are related clues; tightening one fastener cannot verify the whole support path.',coins:2},
];

const s = (id:string,title:string,text:string,choices:Scene['choices'],variants?:Scene['textVariants']) => largeScene(id,title,text,choices,undefined,variants);
const e = (id:string,title:string,text:string) => largeEnd(id,title,text);
const itemSources:Record<string,string> = {
  carpenterSquare:'The named builder transfers their personally owned spare Carpenter’s Square after the owner accepts the completed inspection; site tools stay on site.',
  steelWedge:'The named carpenter releases a personally owned Steel Wedge after the contractor closes out the temporary-shoring job.',
  foldingBenchClamp:'The stand builder transfers a personally owned spare Folding Bench Clamp after the organizer releases it from the crew’s account.',
  pocketToolkit:'The named mason transfers a personally owned Pocket Toolkit as the agreed inspection fee; employer tools remain at the site.',
  collapsibleSoundingRod:'The lane keeper signs over a personally owned spare Collapsible Sounding Rod after the county pays for the inspection.',
  handAuger:'The named carpenter transfers a personally owned Hand Auger after the owner pays for the test and replacement stock.',
};

const make = (w:BuildStory,index:number):Scenario => {
  const nextLore = stories[(index+9)%stories.length].lore;
  const inspectVariants:NonNullable<Scene['textVariants']> = [];
  const recall:Record<string,{fact:keyof typeof KNOWLEDGE_FACTS;source:string;text:string}> = {
    'the-roof-that-held-its-breath': {fact:'winterJointMovement',source:'the-joint-that-opened-in-winter',text:'The fresh split recalls the inn landing you inspected in winter, where a mark that kept separating mattered more than the old shape of the joint.'},
    'the-riverward-retaining-wall': {fact:'waterPathBeforeWall',source:'the-stone-that-kept-the-water',text:'The seepage recalls the cellar wall you inspected with the mason, where water emerged at one joint but followed an older drain from elsewhere.'},
    'three-knots-on-the-platform': {fact:'scaffoldFootAndLashing',source:'the-ladder-in-the-west-yard',text:'The loose lashing and soft ground recall the warehouse ladder job with Cale, where securing one point did not make the whole support sound.'},
  };
  const priorLesson=recall[w.id];
  if(priorLesson){
    const factId=KNOWLEDGE_FACTS[priorLesson.fact].id;
    inspectVariants.push({requirements:{knowledgeKeys:[factId],knowledgeSources:{[factId]:[priorLesson.source]}},text:priorLesson.text});
    inspectVariants.push({requirements:{knowledgeKeys:[factId]},text:`You remember an earlier structural inspection where ${KNOWLEDGE_FACTS[priorLesson.fact].text.toLowerCase()} The present signs still need their own assessment.`});
  }
  if (w.loreCallback) inspectVariants.push({requirements:{lore:[w.loreCallback]},text:`A remembered account changes how the old marks read: ${w.loreCallback} The history gives context, not a safety certificate.`});
  const revealVariants:NonNullable<Scene['textVariants']> = [];
  if (nextLore) revealVariants.push({requirements:{lore:[nextLore]},text:`The site calls to mind what you learned before: ${nextLore} The resemblance is worth recording, not treating as proof.`});
  const revealChoices:Scene['choices'] = [
    {id:'resolve',label:w.decision,next:'settle',effects:{setFlags:['choseCautiousSequence']}},
    {id:'alternate',label:w.alternate,next:'settle',effects:{setFlags:['choseAlternateSequence']}},
    {id:'leave',label:'Stop the alteration and leave the builder a clear account of what you observed',next:'partial',effects:{setFlags:['leftStructuralReport']}},
  ];
  if(nextLore) revealChoices.push({id:'connectLocalHistory',label:'Tell the clerk how this mark connects to a place you have visited',requirements:{lore:[nextLore]},next:'settle',effects:{setFlags:['connectedRememberedConstructionLore']}});
  const actions:Scene['choices'] = [
    {id:'measure',label:w.method,next:'reveal',effects:{setFlags:['constructionMeasured']}},
    {id:'shore',label:'Hold the work and ask the named builder to expose the support from a safe side',next:'reveal',effects:{setFlags:['constructionShored']}},
    {id:'close',label:'Close the affected area and record the visible signs before work continues',next:'reveal',effects:{setFlags:['constructionClosed']}},
  ];
  if (w.tool) actions.push({id:'gear',label:`Use your ${w.toolName} to check the structure`,requirements:{items:[w.tool]},next:'reveal',effects:{setFlags:['constructionUsedGear']}});
  const scenes:Scenario['scenes'] = {
    start:s('start','A Structure Under Question',`${w.job}\n\n${w.sign} The builder tells you what has already been checked and what remains uncertain.`,[
      {id:'inspect',label:'Ask the builder to show the load path and inspect the visible sign',next:'work',effects:{setFlags:['askedBuilder']}},
      {id:'rush',label:'Begin the requested work without checking the support',next:'work',effects:{setFlags:['rushedWork']}},
      {id:'withdraw',label:'Decline the unsafe part and keep others out of the area',next:'hold',effects:{setFlags:['declinedWork']}},
    ],inspectVariants),
    work:s('work','The Work Changes the Building',`${w.methodResult} The next task changes the structure or access; the crew pauses before the changed section is loaded.`,[
      ...actions,
      {id:'force',label:'Force the planned alteration while the support is uncertain',next:'partial',effects:{setFlags:['forcedWork']}},
    ]),
    reveal:s('reveal','The New Question',`${w.turn} The physical sign supports a concern, but does not by itself establish the whole history or certify the structure.`,revealChoices,revealVariants),
    settle:s('settle','Work Accounted For',`The structure is left in a known state: ${w.safe} The owner and builder agree that the next work follows the observed condition, not an assumption.`,[
      ...(w.lane==='GEAR'&&w.tool?[{id:'keepGear',label:`Accept the released ${w.toolName} as part of your pay`,requirements:{notOwnedItems:[w.tool]},next:'gearEnding',effects:{gainItems:[w.tool],gainItemProvenance:{[w.tool]:w.toolSource??itemSources[w.tool]},historyFlags:[`construction_gear_${w.id}`]}}]:[]),
      ...(w.knowledge?[{id:'learn',label:'Keep the practical building lesson for future work',next:'knowledgeEnding',effects:{knowledgeEntries:[{id:KNOWLEDGE_FACTS[w.knowledge].id,text:KNOWLEDGE_FACTS[w.knowledge].text}],historyFlags:[`construction_knowledge_${w.id}`]}}]:[]),
      ...(w.lore?[{id:'recordLore',label:'Record the place’s history and the mark that connects it',next:'loreEnding',effects:{lore:[w.lore],historyFlags:[`construction_lore_${w.id}`]}}]:[]),
      {id:'wage',label:`Take the ${w.coins}-coin work fee`,next:'paid',effects:{money:w.coins}},
      {id:'leave',label:'Decline further work and leave the area closed for the builder',next:'partial',effects:{setFlags:['declinedFurtherWork']}},
    ],[
      {requirements:{flags:['usedRememberedConstructionKnowledge']},text:'You explain which structural sign you remembered and ask the builder to compare it here. The second check narrows the concern; the builder—not memory alone—decides what work is safe.'},
      {requirements:{flags:['connectedRememberedConstructionLore']},text:'The clerk recognizes the place you describe and adds that context to the account. The history explains the mark, but the present structure still needs its own inspection.'},
      {requirements:{flags:['rushedWork']},text:`Because you began before checking the support, the builder stops the alteration and resets the work sequence. ${w.sign}`},
      {requirements:{flags:['constructionUsedGear']},text:`Your tool helps check one part of the problem; ${w.methodResult} The builder still confirms the bearing before loading the structure.`},
      {requirements:{flags:['forcedWork']},text:`The forced alteration loosens material and costs the crew time. No one is hurt, but the affected area stays closed until the builder rechecks it. ${w.lesson??w.sign}`},
    ]),
    ...(w.lane==='GEAR'&&w.tool?{gearEnding:e('gearEnding','A Tool Released to You',`${w.toolSource??''} You take the ${w.toolName}; it helps with practical work but cannot certify a building or replace a qualified builder.`)}:{}),
    ...(w.knowledge?{knowledgeEnding:e('knowledgeEnding','A Rule Worth Remembering',`You leave the optional fee and keep a reusable lesson: ${w.lesson}`)}:{}),
    ...(w.lore?{loreEnding:e('loreEnding','The Building Remembers',`You preserve the history rather than treating it as scrap: ${w.lore}`)}:{}),
    paid:e('paid','A Work Fee and a Clear Record',`You take ${w.coins} coins. The structure remains in the state agreed with its owner, and the builder records what still needs qualified attention.`),
    partial:e('partial','The Work Stops Safely',`You do not complete the alteration. The area remains closed or the work is left to the named builder; your observations are reported without claiming more than they show.`),
    hold:e('hold','A Cautious Withdrawal',`You keep people out of the affected area and tell the builder why. The owner must arrange an inspection before construction resumes.`),
  };
  const tags=largeTags({hook:`${w.job} ${w.turn}`,role:'worker',activity:'labor/repair',tone:w.risk==='LOW'?'peaceful':'tense/dangerous',risk:w.risk,setting:w.site,combat:'NONE',structures:['multi-stage structural inspection','physical evidence changes the work plan','repair vs closure decision','historical or practical payoff'],entry:['hired/posted work','accidental encounter'],rewards:[w.lane==='GEAR'?'Gear':w.lane,w.lane==='KNOWLEDGE'?'Knowledge':'coins','Lore'],outcomes:['success/partial success','walk-away/refusal','costly success/no-perfect-outcome possible']});
  return largeAdventure(w.id,w.title,`Construction is a sequence of supports, loads, and choices; ${w.title.toLowerCase()} begins with a visible reason to stop and look.`,tags,'start',scenes);
};

export const CONSTRUCTION_BUILDING_STRUCTURAL_WORK_BATCH:Scenario[] = stories.map(make);
export const CONSTRUCTION_BATCH_PRIMARY_LANES = stories.reduce((counts,story)=>({...counts,[story.lane]:counts[story.lane]+1}),{GEAR:0,KNOWLEDGE:0,LORE:0});
