import type { Scenario, Scene } from '../types';
import { KNOWLEDGE_FACTS } from '../knowledgeFacts';
import { largeAdventure, largeEnd, largeScene, largeTags } from './largeContentTools';

type Lane='GEAR'|'KNOWLEDGE'|'LORE';
type Story={id:string;title:string;site:string;lane:Lane;risk:'LOW'|'MODERATE'|'HIGH';opening:string;complication:string;decision:string;deliver:string;delay:string;positive:string;negative:string;consequence:string;warning:string;coins:number;gear?:string;gearName?:string;knowledge?:keyof typeof KNOWLEDGE_FACTS;secondaryKnowledge?:keyof typeof KNOWLEDGE_FACTS;lore?:string;secondaryLore?:string;sealed?:boolean;revelation?:string;damageCase?:boolean;injuryRisk?:boolean;threatRisk?:boolean;expedite?:boolean};

const stories:Story[]=[
 {id:'rain-on-the-relay',title:'Rain on the Relay',site:'washed lane between relay offices',lane:'GEAR',risk:'MODERATE',opening:'The east relay office has a sealed dispatch for a mill office beyond a flooded lane. Its books close at dusk; the higher track adds an hour.',complication:'The low crossing is overtopped, while the hill route stays firm but arrives after the mill closes.',decision:'Choose a dry route, a delayed handoff, or a warning to keep the books open.',deliver:'Take the higher track and deliver it dry, after the books close',delay:'Wait for the water to fall and record the late handoff',positive:'courier_preserved_dispatch_during_rain',negative:'courier_delivered_after_mill_books_closed',consequence:'missed business opportunity; recorded handoff',warning:'The direct crossing is already overtopped; the longer ridge route is visible.',coins:2,gear:'waterproofLedgerTube',gearName:'Waterproof Ledger Tube',secondaryKnowledge:'relayDelayMarks',expedite:true},
 {id:'the-wire-that-sang-twice',title:'The Wire That Sang Twice',site:'telegraph office beside rail yard',lane:'GEAR',risk:'MODERATE',opening:'A warning about a loose freight coupling is waiting to go west. The line clicks twice after the operator stops sending.',complication:'The line tester shows an intermittent return when wind moves the pole wire; long text could repeat or vanish.',decision:'Send a short warning with a repeat request, wait for repair, or use the land route.',deliver:'Send the short warning and request confirmation',delay:'Hold the dispatch until the line is steady',positive:'courier_warning_confirmed_over_unsteady_line',negative:'courier_full_dispatch_sent_unconfirmed',consequence:'misinformation risk; preserved confirmation record',warning:'Idle clicks already repeat; a full unconfirmed dispatch may be garbled.',coins:2,gear:'telegraphLineTester',gearName:'Telegraph Line Tester',secondaryKnowledge:'telegraphRepeatConvention',expedite:true},
 {id:'blue-chalk-milepost',title:'Blue Chalk at the Milepost',site:'forked post road near Bellweather',lane:'GEAR',risk:'LOW',opening:'A route clerk sends you with a sealed packet. At the fork, faded blue chalk points toward a lane newly closed for bridge work.',complication:'The current notice redirects uphill. A rider offers a shortcut over signed private land with no post office at its end.',decision:'Use the posted road, wait for authorization, or take the rider only to the public junction.',deliver:'Follow the current public road and leave a clear delay note',delay:'Wait for the clerk to authorize another route',positive:'courier_followed_current_public_route',negative:'courier_missed_postal_collection',consequence:'lost collection window; route reliability recorded',warning:'The chalk predates the closure; the shortcut crosses signed private ground.',coins:2,gear:'foldingTrailMarker',gearName:'Folding Trail Marker',secondaryKnowledge:'undeliverableForwardingMarks',secondaryLore:'Bellweather’s post road moved uphill after a bridge washout; faded blue marks still point along the abandoned lane.'},
 {id:'mailbag-at-milepost-nine',title:'Mailbag at Milepost Nine',site:'rail embankment and public road',lane:'GEAR',risk:'HIGH',opening:'A torn mailbag lies below the rail embankment. The next train is due; several letters remain sealed, while rain has opened one envelope.',complication:'The strap is cut and mud shows a slide from the shoulder. A figure watching from the upper road turns away when noticed.',decision:'Recover the dry bundles from the road side, wait for rail crew protection, or descend while the train is distant.',deliver:'Stay on the road and secure the dry mail for the rider',delay:'Wait for the rail crew before approaching the lower slope',positive:'courier_recovered_mailbag_from_safe_side',negative:'courier_left_mailbag_for_rail_crew',consequence:'interceptor learns Traveler witnessed recovery; opportunity delayed',warning:'The slope is steep, the train is due, and a watcher has noticed you.',coins:2,gear:'signalFlagSet',gearName:'Signal Flag Set',sealed:true,revelation:'The sealed letter inside is addressed to the relay keeper, not the named passenger; its contents request that an unverified copy be held. The mismatch does not identify who placed it in the bag.',injuryRisk:true,threatRisk:true,secondaryKnowledge:'signsOfRecopiedMessage'},
 {id:'paper-boat-at-high-water',title:'Paper Boat at High Water',site:'creek ford and county route box',lane:'GEAR',risk:'HIGH',opening:'A route packet must warn a road crew before wagons approach a washed ford. The near-bank box is dry; the short crossing runs brown.',complication:'A flood line sits above the ford stones. The longer ridge route is passable; your Waterproof Ledger Tube is not sealed for submersion.',decision:'Take the ridge, send a runner back, or signal from the ridge while carrying the packet around.',deliver:'Take the ridge and deliver the warning after the first wagon leaves',delay:'Keep the packet dry and ask the near-bank post to send a rider',positive:'courier_warned_road_crew_of_ford',negative:'courier_packet_delayed_by_flood',consequence:'Gear may be damaged on knowingly flooded shortcut; public warning may arrive late',warning:'The ford is above its stones; the tube cannot protect papers underwater.',coins:2,gear:'waterproofLedgerTube',gearName:'Waterproof Ledger Tube',secondaryKnowledge:'relayDelayMarks',damageCase:true},
 {id:'station-without-a-clock',title:'The Station without a Clock',site:'small rail halt and platform bell',lane:'GEAR',risk:'MODERATE',opening:'Two sealed notes await one passenger; the station clock has stopped. A porter saw the engine couple on the siding but no departure order.',complication:'The platform bell means boarding is confirmed. A shouted message would expose private business; waiting for the bell may miss the train.',decision:'Deliver privately, wait for the bell, or confirm the passenger’s name first.',deliver:'Hand the note over privately and let the passenger decide whether to board',delay:'Wait for the platform bell before interrupting',positive:'courier_kept_departure_message_private',negative:'courier_missed_departure_window',consequence:'missed travel opportunity or privacy protected',warning:'Engine movement is not the departure signal; the note is private.',coins:2,gear:'conductorWhistle',gearName:'Conductor’s Whistle',secondaryKnowledge:'telegraphOfficeBellConvention'},
 {id:'copyists-pencil',title:'The Copyist’s Pencil',site:'county dispatch desk',lane:'GEAR',risk:'LOW',opening:'Three town boards need a public road closure notice. The original has a correction in a different hand, and the printer is waiting.',complication:'The correction changes the road name, but the sender has not confirmed it. Printing now beats the wagon departure; waiting costs the posting round.',decision:'Copy both versions as uncertain, hold for confirmation, or post a temporary warning.',deliver:'Copy both the original and correction, clearly marked unconfirmed',delay:'Hold printing until the sender confirms the road name',positive:'courier_preserved_both_dispatch_versions',negative:'courier_delayed_public_road_notice',consequence:'public misinformation risk; printing window lost',warning:'The correction is in another hand and has not been confirmed.',coins:1,gear:'lockableMapCase',gearName:'Lockable Map Case',secondaryLore:'County road notices were copied by hand during the 1864 flood when the telegraph line failed for three days.'},
 {id:'the-last-mile-pouch',title:'The Last-Mile Pouch',site:'farm lane beyond coach road',lane:'GEAR',risk:'MODERATE',opening:'A sealed pouch must reach a tenant before a hired team leaves at noon. The lane gate is newly chained; a dog barks behind the barn.',complication:'The ledger confirms the named recipient, but entering the pasture crosses a posted boundary.',decision:'Ask at the public farmhouse door, return the pouch with the gate condition, or request the farmer at the public gate.',deliver:'Ask at the public farmhouse door and keep the pouch sealed',delay:'Return it to the coach office with the gate condition recorded',positive:'courier_respected_named_recipient_boundary',negative:'courier_missed_tenant_team_departure',consequence:'lost team departure; trust kept by respecting property',warning:'The chain and boundary sign are visible; entering the pasture is not authorized.',coins:2,gear:'travelRope',gearName:'Travel Rope',secondaryKnowledge:'courierHorseChangeNotation',sealed:true,revelation:'The notice says the tenant’s hired team has been reassigned to another farm. It does not explain why, and opening it violates the instruction to deliver it sealed.'},
 {id:'station-mark-in-margin',title:'The Station Mark in the Margin',site:'telegraph counter at Larkspur station',lane:'KNOWLEDGE',risk:'LOW',opening:'A copied telegram ends with two small margin marks. The receiving clerk thinks they may request a repeat, but the sender’s office is closed.',complication:'A second confirmed copy has the marks; the first does not. The message concerns freight delay, not an emergency.',decision:'Transmit the text with uncertainty noted, hold for the morning operator, or send only the confirmed delay.',deliver:'Send the text as received and label the marks unverified',delay:'Hold it for the morning operator to compare station copies',positive:'courier_labeled_unverified_margin_marks',negative:'courier_repeated_unverified_telegram_marks',consequence:'uncertainty accurately recorded or repeated as fact',warning:'The office book does not confirm what the marks mean.',coins:1,knowledge:'telegraphRepeatConvention'},
 {id:'seal-that-cooled-wrong',title:'The Seal That Cooled Wrong',site:'inn desk and county post room',lane:'KNOWLEDGE',risk:'MODERATE',opening:'A merchant’s sealed letter arrives with flattened wax and a faint second ridge. The clerk asks you to carry it across town unopened.',complication:'The seal may have been reheated, but the mark cannot identify who handled it or whether the contents changed.',decision:'Deliver unopened with an honest note, ask the clerk to record the seal, or tell the recipient before they choose.',deliver:'Deliver it unopened and describe the seal honestly',delay:'Ask the clerk to record the seal before the recipient accepts it',positive:'courier_reported_possible_seal_change',negative:'courier_opened_reheated_seal',consequence:'recipient trust; confidentiality if opened',warning:'The doubled ridge is a clue, not proof; opening will be noticed.',coins:2,knowledge:'reheatedSealSigns',sealed:true,revelation:'The merchant’s note asks the consignee to hold a specific shipment until a new account arrives. It names neither the person who reheated the seal nor whether the instruction was obeyed.'},
 {id:'copy-that-came-back',title:'The Copy That Came Back',site:'freight office beside the depot',lane:'KNOWLEDGE',risk:'MODERATE',opening:'The sender’s freight instruction says “hold six”; the receiving copy reads “load six.” The wagon is ready.',complication:'The copies visibly differ. Holding the disputed crates costs a day; loading may send the wrong goods.',decision:'Request a read-back, load only confirmed crates, or let the consignee decide with both copies present.',deliver:'Hold the freight and request a read-back',delay:'Load only the confirmed crates while the disputed six remain',positive:'courier_preserved_sender_and_receiver_copies',negative:'courier_loaded_disputed_freight_instruction',consequence:'demurrage cost or disputed cargo release',warning:'The copies conflict; the clerk has named the cost of holding the wagon.',coins:2,knowledge:'senderReceiverCopyDifference',secondaryLore:'Bellweather kept paired freight copies after an 1872 grain dispute.'},
 {id:'flooded-relay-book',title:'The Flooded Relay Book',site:'river relay station after spring water',lane:'KNOWLEDGE',risk:'HIGH',opening:'A relay ledger is wet at the lower edge. A quarry warning appears on the page, but its acknowledgment column is smeared.',complication:'A dry sending copy lists the time, not receipt. The next quarry shift is preparing to enter.',decision:'Carry a fresh warning, keep the gate closed while the operator checks, or send a runner with the uncertainty stated.',deliver:'Carry a fresh warning before the next shift enters',delay:'Keep the quarry gate closed while the relay operator verifies the line',positive:'courier_warned_quarry_of_unconfirmed_relay',negative:'courier_treated_unacknowledged_warning_as_delivered',consequence:'delayed work versus crew acting on false assurance',warning:'No receipt mark survives and the next shift is due.',coins:2,knowledge:'relayDelayMarks',injuryRisk:true,expedite:true},
 {id:'initials-on-the-wire',title:'Initials on the Wire',site:'telegraph counter at a rural store',lane:'KNOWLEDGE',risk:'MODERATE',opening:'A telegram orders a locked crate released. Its initials match two brothers; the station receipt names the payer, not an authorized agent.',complication:'The owner’s signed account names one brother. Releasing the crate now avoids spoilage but risks giving it to the wrong person.',decision:'Ask the named agent to confirm, hold for a full-name reply, or explain what the receipt does and does not prove.',deliver:'Ask the owner’s named agent to confirm in person',delay:'Hold the crate and request full-name authorization',positive:'courier_distinguished_sender_from_authority',negative:'courier_released_crate_on_initials_only',consequence:'cargo ownership and payment disputed',warning:'Initials and a paid receipt do not establish authority.',coins:2,knowledge:'telegraphPayerNotAuthority',secondaryLore:'The store’s founding brothers shared initials on early freight orders.'},
 {id:'town-name-that-moved',title:'The Town Name That Moved',site:'post office serving a relocated settlement',lane:'KNOWLEDGE',risk:'LOW',opening:'A letter to Old Ford returns. The settlement moved after the creek changed course, but two current towns use “Ford.”',complication:'The route book marks the old settlement uphill; the directory lists Ford Crossing and New Ford separately.',decision:'Ask both offices to compare the named household, return it sealed, or send a sealed inquiry.',deliver:'Ask both offices to compare the named household, not the letter contents',delay:'Return it to the undeliverable shelf with the route discrepancy noted',positive:'courier_verified_relocated_town_by_route_book',negative:'courier_sent_letter_to_unverified_ford',consequence:'misdelivery and private information exposure',warning:'Two places share the old name; there is no sender address.',coins:1,knowledge:'undeliverableForwardingMarks',secondaryLore:'Old Ford moved uphill after the creek changed course; the former post mark remains in the route book.',sealed:true,revelation:'The letter asks for a reply to “Old Ford” but names the household as Mara Venn. Two current directories list a Mara Venn; the private text cannot determine which is intended.'},
 {id:'bell-before-the-wire',title:'The Bell before the Wire',site:'telegraph office during a line outage',lane:'KNOWLEDGE',risk:'MODERATE',opening:'A storm cuts the line. The operator rings once for “line down” and twice for “message waiting”; a new porter hears only the second ring.',complication:'A red peg shows the break, while the outgoing book is blank. The porter is about to carry a guessed message to the road crew.',decision:'Carry a blank confirmation request, wait for repair, or tell the crew only that communication is down.',deliver:'Carry a request for the road crew to report in person',delay:'Keep the porter in the office until line status is restored',positive:'courier_kept_unverified_words_off_road',negative:'courier_repeated_unverified_message_during_outage',consequence:'false information avoided or repeated',warning:'The red line-down peg is visible and no message was copied.',coins:1,knowledge:'telegraphOfficeBellConvention'},
 {id:'horse-change-ledger',title:'The Horse-Change Ledger',site:'coach station stable yard',lane:'KNOWLEDGE',risk:'LOW',opening:'A rider’s packet is marked for the north coach, but the stable ledger records a route change after a horse was pulled from service.',complication:'The current ledger points to a staffed river relay; the station map still shows the old northern stop.',decision:'Use the current ledger, hold the packet while the map is corrected, or ask the driver to sign for the new handoff.',deliver:'Follow the current stable ledger to the river relay',delay:'Hold the packet for the clerk to correct the station map',positive:'courier_used_current_horse_change_ledger',negative:'courier_followed_obsolete_route_map',consequence:'missed relay or corrected route record',warning:'The newer animal-change entry changes the staffed handoff.',coins:1,knowledge:'courierHorseChangeNotation'},
 {id:'first-words-over-the-wire',title:'First Words over the Wire',site:'restored telegraph room in Alder Crossing',lane:'LORE',risk:'LOW',opening:'An old telegram is found behind the station register. It bears the first message sent to Alder Crossing, but the addressee strip is torn away.',complication:'The date matches the station opening book; the missing strip names a family, not the message body.',decision:'Ask the family before display, preserve it unopened in the station book, or display only date and route.',deliver:'Ask the family before public display',delay:'Preserve the telegram without copying its private lines',positive:'courier_preserved_first_alder_telegram_privately',negative:'courier_exposed_first_telegram_without_family_consent',consequence:'family trust; irreversible public disclosure',warning:'The addressee is missing and public display cannot easily be undone.',coins:1,lore:'Alder Crossing’s first telegraph message arrived on opening day; the family named in its missing address never claimed the original.',secondaryKnowledge:'senderCopyDoesNotProveReceipt',sealed:true,revelation:'The message says the first train reached Alder Crossing safely and asks the addressee to tell a named family that the station was open. The strip with the family name is missing.'},
 {id:'postal-road-after-the-flood',title:'The Postal Road after the Flood',site:'abandoned hill relay and washed valley road',lane:'LORE',risk:'MODERATE',opening:'An old postal marker stands above the valley. The current map still sends riders through a buried bridge abutment.',complication:'The marker faces the hill track; the old valley road no longer connects.',decision:'Take the marked hill route, send a warning from the nearer telegraph office, or correct the lower post for the next rider.',deliver:'Take the marked hill route and explain the change at delivery',delay:'Wait for daylight and send the warning by the telegraph office',positive:'courier_corrected_flooded_postal_route',negative:'courier_followed_abandoned_valley_route',consequence:'delivery opportunity and future route safety',warning:'The bridge ends at the flood channel; the old marker points uphill.',coins:2,lore:'The postal road shifted to the ridge after the 1864 flood buried the valley bridge; maps kept the lower route for a generation.',secondaryKnowledge:'relayDelayMarks'},
 {id:'letter-from-ash-lot',title:'The Letter from Ash Lot',site:'county archive and burned settlement lot',lane:'LORE',risk:'LOW',opening:'A sealed letter for a Bracken Cooperative member is found in an archive box from Ash Lot. Its return address is gone.',complication:'The date is three days after the evacuation notice. An older resident recognizes the family name but not who remained behind.',decision:'Ask the family whether they want it, preserve only the date and source, or open it with the clerk knowing the seal will break.',deliver:'Ask the family whether they want the sealed letter returned',delay:'Keep it closed and record the date and archive source',positive:'courier_returned_ash_lot_letter_by_consent',negative:'courier_opened_archival_family_letter',consequence:'private history revealed or preserved',warning:'Opening is irreversible and may expose family matters.',coins:1,lore:'A Bracken Cooperative evacuation notice preceded the last dated letter from Ash Lot; the record never established who stayed behind.',secondaryKnowledge:'senderCopyDoesNotProveReceipt',sealed:true,revelation:'The writer asks a sibling to return before the evacuation wagon departs and says they will remain to watch the cooperative store. The letter cannot establish what happened afterward.'},
 {id:'morning-the-warning-arrived',title:'The Morning the Warning Arrived',site:'town meeting room beside old relay',lane:'LORE',risk:'MODERATE',opening:'A retired clerk finds an unsent bridge warning in the town records. A later ledger blames the ferry keeper for the delay.',complication:'The outgoing register dates the warning before dawn; its entry time is after the bridge crew left. A private family letter is folded inside.',decision:'Correct the public account, let the family review its letter, or publish the timeline but keep the letter sealed.',deliver:'Correct the public account with the documented delay',delay:'Give the family time to decide about the enclosed letter',positive:'courier_corrected_bridge_warning_record',negative:'courier_left_false_bridge_delay_account',consequence:'public history corrected or false blame preserved',warning:'The record supports the timeline; the folded letter is separate private material.',coins:2,lore:'The bridge warning was written before dawn but entered after the crew departed; the town later blamed the ferry keeper for the relay delay.',secondaryKnowledge:'lateMessageMayRetainOtherValue'},
 {id:'no-forwarding-address-for-the-founder',title:'No Forwarding Address for the Founder',site:'town post office and founder’s former house',lane:'LORE',risk:'MODERATE',opening:'A sealed notice for the town founder returns with no forwarding address. The return route loops through a settlement that closed before incorporation.',complication:'The obsolete place name does not establish the sender or prove the founder is alive. A council member wants it read aloud.',decision:'File it unopened, verify the sender before reading, or tell the meeting only that it returned under an old name.',deliver:'File the notice as undeliverable and preserve its seal',delay:'Ask the council to verify the sender before any public reading',positive:'courier_preserved_founder_notice_without_claim',negative:'courier_publicly_read_unverified_founder_notice',consequence:'privacy breach or an unverified claim enters public record',warning:'The obsolete return name does not identify a sender.',coins:1,lore:'The town founder left no forwarding address when the old settlement closed; later notices used its vanished name as civic shorthand.',secondaryKnowledge:'undeliverableForwardingMarks',sealed:true,revelation:'The notice is a request to verify an unpaid town-lot claim. It bears no reliable return signature, so the text does not establish that the founder sent it.'},
 {id:'blue-room-dispatch',title:'The Blue Room Dispatch',site:'closed newspaper office above a print shop',lane:'LORE',risk:'MODERATE',opening:'Old press dispatches are found behind a sealed blue-room door. An unsigned page contradicts the paper’s account of a mill fire but has no date.',complication:'The type matches the old office; the ink and stock span several years. A former press hand says it may be an unchecked draft.',decision:'Publish it explicitly as unverified, keep it sealed pending dating, or compare it with the mill repair ledger.',deliver:'Publish the discovery as an unverified draft and invite corroborating records',delay:'Keep the page sealed until its date can be established',positive:'courier_marked_blue_room_dispatch_unverified',negative:'courier_published_undated_fire_accusation',consequence:'reputation and threat if an unsupported accusation spreads',warning:'The page is undated and unsigned; a named accusation is difficult to retract.',coins:1,lore:'The Blue Room press office closed after a mill-fire account was disputed; its surviving unsigned dispatch may be a draft, not a correction.',secondaryKnowledge:'signsOfRecopiedMessage'},
 {id:'last-station-keepers-route',title:'The Last Station Keeper’s Route',site:'abandoned foothill telegraph relay',lane:'LORE',risk:'HIGH',opening:'A relay log lists a route erased from the county map after its station keeper vanished. A surveyor wants a final message carried to test whether the upper post remains.',complication:'The log marks a spring and stone post, then ends before the return entry. The ravine edge has fresh loose stone.',decision:'Take the safe ridge and leave a dated message, turn back with a partial report, or signal from the stable marker.',deliver:'Take the ridge and leave a dated message at the surviving post',delay:'Turn back and report only as far as the stone marker',positive:'courier_reported_last_keeper_route_limits',negative:'courier_entered_slipped_relay_path',consequence:'bodily risk and unresolved route opportunity',warning:'The ravine edge has fresh loose stone; the ridge is longer but firm.',coins:2,lore:'The last foothill relay log records a route to an upper post but no return; the station closed without confirming whether its keeper left or was lost.',injuryRisk:true,secondaryKnowledge:'courierRouteEndMark'},
 {id:'envelope-returned-five-times',title:'The Envelope Returned Five Times',site:'regional post office sorting room',lane:'LORE',risk:'LOW',opening:'An envelope returned five times over twenty years bears forwarding marks from a river settlement and three rail towns. A possible relative appears in the directory.',complication:'The letter remains sealed; the clerk cannot know whether the family wants contact.',decision:'Ask privately whether the relative wants it, hold it for a request, or disclose only that an old sealed letter bears the family name.',deliver:'Ask the relative privately whether to receive it',delay:'Keep it in the post office archive until requested',positive:'courier_offered_old_letter_without_pressure',negative:'courier_disclosed_return_history_publicly',consequence:'family trust and private history',warning:'The relationship is plausible, not certain; public disclosure exposes a private trail.',coins:1,lore:'A sealed family letter followed the rail expansion through three towns but never reached its intended recipient.',secondaryKnowledge:'undeliverableForwardingMarks',sealed:true,revelation:'The letter asks the addressee not to forward further and says only that the writer has chosen to leave. It does not explain the family’s history or identify which possible relative should receive it.'},
];

const itemSources:Record<string,string>={waterproofLedgerTube:'The relay clerk transfers a personally owned spare after closing the delivery account; no mail remains inside.',telegraphLineTester:'The line repairer releases a retired tester after showing its limits; the station keeps its working instrument.',foldingTrailMarker:'The route rider gives you a spare after the clerk confirms the public-road detour.',signalFlagSet:'The post office transfers surplus flags after the recovery work is closed.',conductorWhistle:'The station master transfers a personally owned spare after the private handoff.',lockableMapCase:'The county clerk releases an old case after the copy is filed and records returned.',travelRope:'The coach driver transfers a personal spare once the gate owner confirms the public handoff.'};
const knowledgeCallbackTargets:Partial<Record<keyof typeof KNOWLEDGE_FACTS,string[]>>={
 telegraphRepeatConvention:['the-wire-that-sang-twice','station-mark-in-margin','bell-before-the-wire'],
 reheatedSealSigns:['seal-that-cooled-wrong','letter-from-ash-lot','envelope-returned-five-times'],
 senderReceiverCopyDifference:['copy-that-came-back','copyists-pencil','morning-the-warning-arrived'],
 relayDelayMarks:['rain-on-the-relay','flooded-relay-book','postal-road-after-the-flood','morning-the-warning-arrived'],
 telegraphPayerNotAuthority:['initials-on-the-wire','copy-that-came-back'],
 undeliverableForwardingMarks:['town-name-that-moved','no-forwarding-address-for-the-founder','envelope-returned-five-times','blue-chalk-milepost'],
 telegraphOfficeBellConvention:['station-without-a-clock','bell-before-the-wire','the-wire-that-sang-twice'],
 courierHorseChangeNotation:['horse-change-ledger','the-last-mile-pouch','postal-road-after-the-flood'],
 lateMessageMayRetainOtherValue:['morning-the-warning-arrived','rain-on-the-relay','mailbag-at-milepost-nine'],
 senderCopyDoesNotProveReceipt:['first-words-over-the-wire','flooded-relay-book','copy-that-came-back'],
 courierRouteEndMark:['last-station-keepers-route','postal-road-after-the-flood'],
 signsOfRecopiedMessage:['blue-room-dispatch','mailbag-at-milepost-nine','seal-that-cooled-wrong'],
};
const loreCallbackTargets:Record<string,string[]>={
 'Bellweather’s post road moved uphill after a bridge washout; faded blue marks still point along the abandoned lane.':['postal-road-after-the-flood'],
 'County road notices were copied by hand during the 1864 flood when the telegraph line failed for three days.':['morning-the-warning-arrived','flooded-relay-book'],
 'Bellweather kept paired freight copies after an 1872 grain dispute.':['initials-on-the-wire'],
 'The store’s founding brothers shared initials on early freight orders.':['town-name-that-moved'],
 'Old Ford moved uphill after the creek changed course; the former post mark remains in the route book.':['blue-chalk-milepost'],
 'Alder Crossing’s first telegraph message arrived on opening day; the family named in its missing address never claimed the original.':['station-without-a-clock'],
 'The postal road shifted to the ridge after the 1864 flood buried the valley bridge; maps kept the lower route for a generation.':['blue-chalk-milepost'],
 'A Bracken Cooperative evacuation notice preceded the last dated letter from Ash Lot; the record never established who stayed behind.':['envelope-returned-five-times'],
 'The bridge warning was written before dawn but entered after the crew departed; the town later blamed the ferry keeper for the relay delay.':['last-station-keepers-route'],
 'The town founder left no forwarding address when the old settlement closed; later notices used its vanished name as civic shorthand.':['first-words-over-the-wire'],
 'The Blue Room press office closed after a mill-fire account was disputed; its surviving unsigned dispatch may be a draft, not a correction.':['copyists-pencil'],
 'The last foothill relay log records a route to an upper post but no return; the station closed without confirming whether its keeper left or was lost.':['postal-road-after-the-flood'],
 'A sealed family letter followed the rail expansion through three towns but never reached its intended recipient.':['town-name-that-moved'],
};
const s=(id:string,title:string,text:string,choices:Scene['choices'],variants?:Scene['textVariants'])=>largeScene(id,title,text,choices,undefined,variants);
const e=(id:string,title:string,text:string)=>largeEnd(id,title,text);

function make(w:Story,index:number):Scenario{
 const routeVariants:NonNullable<Scene['textVariants']>=[{requirements:{historyFlags:['opened_private_courier_letter']},text:'The clerk remembers that you once opened private correspondence; they keep the duplicate behind the counter until the recipient arrives.'},{requirements:{historyFlags:['courier_seen_by_message_interceptor']},text:'The operator checks the street before handing over the route slip; someone who watched an earlier exchange may recognize you.'}];
 for(const [key,targets] of Object.entries(knowledgeCallbackTargets)) if(targets?.includes(w.id)) routeVariants.push({requirements:{knowledgeKeys:[KNOWLEDGE_FACTS[key as keyof typeof KNOWLEDGE_FACTS].id]},text:`You recognize a useful convention: ${KNOWLEDGE_FACTS[key as keyof typeof KNOWLEDGE_FACTS].text} It informs your question but does not prove this message was received.`});
 for(const [lore,targets] of Object.entries(loreCallbackTargets)) if(targets.includes(w.id)) routeVariants.push({requirements:{lore:[lore]},text:`You remember the history attached to this route: ${lore} The old account adds context, not proof about this dispatch.`});
 const choices:Scene['choices']=[
  {id:'deliverAsKnown',label:w.deliver,next:'delivered',effects:{historyFlags:[w.positive]}},
  {id:'holdOrReturn',label:w.delay,next:'delayed',effects:{historyFlags:[w.negative]}},
  {id:'warnAndQualify',label:'Warn the recipient or office and state what remains uncertain',next:'warned',effects:{historyFlags:[w.positive,'courier_stated_uncertainty_before_action']}},
  ...(w.expedite?[{id:'payForDuplicate',label:'Spend one coin to send a duplicate by the staffed route',requirements:{minMoney:1},hint:'The second copy may preserve the warning, but it costs a coin and does not guarantee a reply.',next:'delivered',effects:{money:-1,historyFlags:[w.positive,'courier_paid_to_duplicate_message']}}]:[]),
  ...(w.injuryRisk?[{id:'takeHazard',label:'Take the signposted hazardous shortcut to save time',hint:w.warning,next:'injured',effects:{health:-1,historyFlags:[w.negative,'courier_took_signposted_hazard']}}]:[]),
  ...(w.threatRisk?[{id:'confrontWatcher',label:'Confront the watcher who has noticed the handoff',hint:'Withdrawing avoids exposing yourself or the message further.',next:'threatened',effects:{historyFlags:[w.negative,'courier_seen_by_message_interceptor']}}]:[]),
 ];
 const handlingChoices:Scene['choices']=[{id:'verifyOutside',label:'Verify the address or route without opening the message',next:'decision',effects:{setFlags:['courier_verified_outside']}},{id:'carryNow',label:'Carry it on the stated route now',next:'decision',effects:{setFlags:['courier_chose_speed']}},...(w.sealed?[{id:'keepSealedMessage',label:'Keep the correspondence sealed and let the recipient decide whether to read it',next:'decision',effects:{setFlags:['courier_kept_message_sealed'],historyFlags:['courier_kept_message_sealed']}},{id:'openSealedMessage',label:'Open it despite the visible seal and confidentiality warning',next:'opened',effects:{setFlags:['courier_opened_message'],historyFlags:['opened_private_courier_letter',w.negative]}}]:[]),...(w.damageCase?[{id:'floodedShortcut',label:'Take the flooded shortcut with your Waterproof Ledger Tube',requirements:{items:['waterproofLedgerTube']},hint:'The tube is not watertight if submerged; water covers the ford.',next:'decision',effects:{damageItems:['waterproofLedgerTube'],historyFlags:[w.negative]}}]:[])];
 const handling:Scene['choices']=handlingChoices.map((choice)=>({...choice,effects:{...(w.knowledge?{knowledgeEntries:[KNOWLEDGE_FACTS[w.knowledge]]}:{}),...choice.effects}}));
 const rewardChoices:Scene['choices']=[...(w.lane==='GEAR'&&w.gear?[{id:'takeGear',label:`Accept the released ${w.gearName} as part of your pay`,requirements:{notOwnedItems:[w.gear]},next:'gearEnding',effects:{gainItems:[w.gear],gainItemProvenance:{[w.gear]:itemSources[w.gear]}}}]:[]),...(w.secondaryKnowledge?[{id:'recordProcedure',label:'Study and record the additional handling convention',next:'knowledgeEnding',effects:{knowledgeEntries:[KNOWLEDGE_FACTS[w.secondaryKnowledge]]}}]:[]),...(w.lore?[{id:'recordLore',label:'Preserve the route or correspondence history',next:'loreEnding',effects:{lore:[w.lore]}}]:[]),...(w.secondaryLore?[{id:'recordRelatedLore',label:'Record the connected local history',next:'loreEnding',effects:{lore:[w.secondaryLore]}}]:[]),{id:'takeFee',label:`Take the ${w.coins}-coin delivery fee`,next:'paid',effects:{money:w.coins}},{id:'declineFee',label:'Decline payment and leave the record with the office',next:'unpaid'}];
 const scenes:Record<string,Scene>={
  start:s('start','A Message with Consequences',w.opening,[{id:'acceptDelivery',label:'Accept the message and confirm its named route',next:'handling',effects:{setFlags:['courier_accepted_delivery']}},{id:'declineDelivery',label:'Decline and leave it with the responsible office',next:'declined',effects:{historyFlags:[w.negative]}}],routeVariants),
  handling:s('handling',w.lane==='KNOWLEDGE'?'Reading the Office Convention':w.lane==='LORE'?'The Record behind the Message':'At the Handoff',`${w.complication} ${w.warning}`,handling),
  decision:s('decision','Before the Message Moves',`${w.decision} ${w.complication} The office can record whether it arrived intact, late, opened, or with uncertainty stated.`,choices),
  ...(w.sealed?{opened:s('opened','The Seal Is Broken',`You open the correspondence. ${w.revelation??w.complication} The seal cannot be restored without a trace; these words do not establish the sender’s motive.`,[{id:'deliverAfterOpening',label:'Tell the recipient you opened it and hand over the full message',next:'delivered',effects:{historyFlags:['courier_disclosed_opening_to_recipient',w.positive]}},{id:'reportOpening',label:'Report the broken seal and let the recipient decide',next:'warned',effects:{historyFlags:['courier_reported_confidentiality_breach',w.positive]}},{id:'concealOpening',label:'Reseal it and say nothing about opening it',next:'delayed',effects:{historyFlags:['courier_concealed_confidentiality_breach',w.negative]}}])}:{}),
  delivered:s('delivered','Delivered with the Record Intact',`${w.positive.replaceAll('_',' ')}. You state what you know without adding words the sender did not send.`,[{id:'settleDelivered',label:'Close the delivery record',next:'settle'}],[{requirements:{historyFlags:['courier_kept_message_sealed']},text:'You deliver the correspondence sealed, leaving its contents and next decision with the named recipient.'},{requirements:{historyFlags:['opened_private_courier_letter']},text:'You deliver the message after opening it and disclose what you did; the broken seal remains part of the record.'}]),
  delayed:s('delayed','A Delay Entered in the Book',`${w.delay} The office records the cause. The opportunity may not return, but the message remains accounted for.`,[{id:'settleDelayed',label:'Close the delayed record',next:'settle'}]),
  warned:s('warned','Uncertainty Delivered Honestly',`${w.warning} You state the limit of the evidence before the recipient acts.`,[{id:'settleWarned',label:'Close the warning record',next:'settle'}]),
  declined:s('declined','The Message Stays with the Office',`You decline the route. The office keeps responsibility; the sender may need another courier and the refusal is entered in the dispatch book.`,[{id:'settleDeclined',label:'Leave the message with its office',next:'settle'}]),
  ...(w.injuryRisk?{injured:s('injured','A Costly Shortcut',`The signposted hazard catches you: a painful knock delays the delivery. You are treated before continuing; the record notes the risk you chose.`,[{id:'settleInjured',label:'Finish the delivery record',next:'settle'}])}:{}),
  ...(w.threatRisk?{threatened:s('threatened','A Witness Made',`The watcher leaves before the clerk can identify them. You withdraw rather than turn a delivery into a fight; the office records that the message may have been intercepted.`,[{id:'settleThreatened',label:'Report the watcher and close the record',next:'settle'}])}:{}),
  settle:s('settle','The Dispatch Account',`The office records the outcome: ${w.consequence}. Payment and continuity remain your choice.`,rewardChoices),
  ...(w.lane==='GEAR'&&w.gear?{gearEnding:e('gearEnding','Equipment Released to You',`${itemSources[w.gear]} The message and office property remain behind.`)}:{}),
  ...(w.knowledge||w.secondaryKnowledge?{knowledgeEnding:e('knowledgeEnding','A Convention Worth Keeping',w.secondaryKnowledge?'You add the additional handling convention to your notes; the office keeps its separate dispatch record.':'The office files its convention beside the dispatch record; the lesson stays with you.')}:{}),
  ...(w.lore||w.secondaryLore?{loreEnding:e('loreEnding','A Route Remembered',`You preserve the history attached to this message: ${w.lore??w.secondaryLore}`)}:{}),
  paid:e('paid','A Recorded Delivery Fee',`You take ${w.coins} coins; the clerk records whether the message was timely, delayed, or returned.`),unpaid:e('unpaid','No Fee Taken','You leave without payment; the office retains the recipient, seal, and delivery status.'),
 };
 const tags=largeTags({hook:`${w.opening} ${w.complication}`,role:'messenger',activity:'communication/witness',tone:w.risk==='LOW'?'quiet':'tense/dangerous',risk:w.risk,setting:w.site,combat:w.threatRisk?'AVOIDABLE':'NONE',structures:['message handling','privacy vs urgency','stateful delivery outcome','imperfect records'],entry:['hired/posted work','accidental encounter'],rewards:[w.lane,w.gear?'Gear':'coins',w.knowledge?'Knowledge':'Lore'],outcomes:['on-time/late delivery','privacy kept/breached','uncertainty preserved','reward/refusal']});
 return largeAdventure(w.id,w.title,`Information travels through people, roads, offices, and imperfect records. ${w.title} makes delivery itself consequential.`,tags,'start',scenes);
}

export const COURIER_MAIL_TELEGRAPH_GENRE_BATCH:Scenario[]=stories.map(make);
export const COURIER_BATCH_PRIMARY_LANES=stories.reduce((n,w)=>({...n,[w.lane]:n[w.lane]+1}),{GEAR:0,KNOWLEDGE:0,LORE:0});
export const COURIER_CONSEQUENCE_MATRIX=stories.map(({id,consequence,warning,positive,negative})=>({id,consequence,warning,positive,negative}));
