import type { Scenario, Scene, ScenarioDiversity } from '../types';
import { largeAdventure, largeEnd, largeScene, largeTags } from './largeContentTools';

const choice = (id: string, label: string, next: string, effects?: Scene['choices'][number]['effects'], requirements?: Scene['choices'][number]['requirements']): Scene['choices'][number] => ({ id, label, next, ...(effects ? { effects } : {}), ...(requirements ? { requirements: { ...requirements, ...(requirements.items?.length ? { usableItems: [...new Set([...(requirements.usableItems ?? []), ...requirements.items])] } : {}) } } : {}) });
const tags = (id: string, title: string, hook: string, setting: string, risk: ScenarioDiversity['riskTier'], activity = 'rescue/care'): ScenarioDiversity => largeTags({ hook, activity, role: 'traveler/passenger', tone: 'tense/dangerous', risk, setting, fantasy: 'NONE', combat: ['the-pay-carriage-at-dusk', 'the-witness-under-escort', 'the-fence-at-crow-road', 'the-courier-relay-box', 'the-silent-warehouse-shift', 'the-bridge-pins', 'the-glass-plate-box', 'the-night-mail-train'].includes(id) ? 'POSSIBLE' : 'NONE', structures: ['escort responsibility', 'divided protection', 'partial outcome'], entry: ['hired/posted work'], rewards: ['Gear', 'coins', 'reusable Knowledge'], outcomes: ['success/partial success', 'escape/survival', 'walk-away/refusal'] });
const story = (id: string, title: string, subtitle: string, risk: ScenarioDiversity['riskTier'], setting: string, hook: string, startScene: string, scenes: Record<string, Scene>, activity?: string): Scenario => largeAdventure(id, title, subtitle, tags(id, title, hook, setting, risk, activity), startScene, scenes);
const end = (id: string, title: string, text: string) => largeEnd(id, title, text);

// These stories use different graph shapes: preparation then travel, in-motion
// emergencies, split responsibilities, night watch, disputed obligations, and
// relay handoffs. Employer equipment is temporary unless a transfer is explicit.
export const ESCORT_PROTECTION_GENRE_BATCH: Scenario[] = [
  story('the-doctor-before-the-ford', 'The Doctor Before the Ford', 'A doctor and a medicine case must cross before the river rises.', 'HIGH', 'flooded ford and river road', 'A medical escort becomes a choice between the patient’s medicine and the doctor’s safety.', 'departure', {
    departure: largeScene('departure', 'A Rising Ford', 'Dr. Mara Venn has a sealed medicine case and a patient waiting across the river. The stepping stones are visible, but the current is already carrying branches. She asks you to carry the case while she tests the first stones.', [choice('case', 'Keep the medicine case above the water and cross together', 'crossing', { setFlags: ['doctor_case_protected'] }), choice('rope', 'Use your Travel Rope to make a handline first', 'crossing', { setFlags: ['doctor_rope_line'] }, { items: ['travelRope'] }), choice('wait', 'Wait for the ferryman, though the medicine will arrive late', 'late')]),
    crossing: largeScene('crossing', 'The Middle Stones', 'Halfway across, a submerged stone shifts beneath the doctor. The case is still dry, but she is losing her footing.', [choice('support', 'Turn back with the doctor, leaving the case on the high stone', 'support', { setFlags: ['case_left_high'] }), choice('casefirst', 'Push the case to the far bank before helping her', 'caseFirst', { setFlags: ['doctor_slipped'] }), choice('withdraw', 'Retreat together before the current takes either of you', 'late')]),
    support: largeScene('support', 'A Hand at the Sleeve', 'You brace the doctor until both of you regain the near bank. The case remains visible on a stone beyond the fastest water; no patient can be reached from here.', [choice('retrieve', 'Ask the ferryman to retrieve the case by boat', 'delivered', { setFlags: ['case_retrieved_by_ferryman'] }), choice('leave', 'Leave the case and carry the doctor to shelter', 'doctorSafe')]),
    caseFirst: largeScene('caseFirst', 'The Case on the Far Bank', 'The case reaches dry ground, but the doctor is now clinging to the handline. The patient is still waiting.', [choice('pullDoctor', 'Pull the doctor toward the near bank', 'doctorSafe'), choice('callHelp', 'Call the ferryman before moving either of you', 'delivered', { setFlags: ['ferryman_rescue'] })]),
    delivered: end('delivered', 'Medicine Arrives', 'The ferryman brings the doctor and case across on the next safe trip. The patient receives the medicine later than planned, but it remains usable.'),
    doctorSafe: end('doctorSafe', 'The Doctor Is Safe', 'You get the doctor to shelter. The case is left beyond the current and the patient must wait for another supply.'),
    late: end('late', 'A Necessary Delay', 'You refuse to gamble with a rising river. The doctor sends word ahead; the patient waits, and no one is swept away.'),
  }),

  story('the-pay-carriage-at-dusk', 'The Pay Carriage at Dusk', 'A payroll box must reach the mill office before the crew leaves.', 'HIGH', 'mill road and covered carriage', 'A protection job tests whether the Traveler protects the money, driver, or route when a false stop becomes a real threat.', 'load', {
    load: largeScene('load', 'One Seat Within Reach', 'The mill owner puts the locked payroll box under the seat and gives you a lantern and a short length of chain. The driver says the east road is watched; the longer ridge road is rough but open.', [choice('chain', 'Keep the chain ready to secure the box', 'stop', { setFlags: ['payroll_chain'] }), choice('lantern', 'Keep the lantern ready to signal the mill', 'stop', { setFlags: ['payroll_lantern'] }), choice('ridge', 'Take the ridge road before dark', 'ridge')]),
    stop: largeScene('stop', 'A Man with a Receipt', 'A man steps into the road holding a receipt for a toll. The paper has no mill seal. Behind him, another figure watches the driver rather than the box.', [choice('question', 'Ask the man to read the toll clause aloud', 'clause'), choice('signal', 'Signal the mill with the lantern and keep the driver moving', 'arrival', { setFlags: ['mill_signaled'], money: 3 }), choice('fight', 'Stand between the figures and the carriage', 'fight', { combat: { enemy: 'payroll road attackers', winChance: 0.52, damageOnWin: 1, damageOnLoss: 5, winNext: 'arrival', lossNext: 'withdraw' } })]),
    clause: largeScene('clause', 'No Such Toll', 'The man cannot name the mill contract. His companion moves toward the carriage door; the driver has room to turn onto a farm track.', [choice('turn', 'Tell the driver to take the farm track now', 'arrival', { money: 3 }), choice('hold', 'Hold the road while the driver turns', 'fight', { combat: { enemy: 'payroll road attackers', winChance: 0.50, damageOnWin: 1, damageOnLoss: 5, winNext: 'arrival', lossNext: 'withdraw' } })]),
    ridge: end('ridge', 'A Rough but Open Road', 'The carriage reaches the mill late with its payroll box untouched. The longer route costs daylight but avoids the false toll.'),
    arrival: end('arrival', 'The Wages Arrive', 'The driver reaches the mill office with the payroll box. The owner counts the wages before the workers are sent home.'),
    withdraw: end('withdraw', 'The Driver Gets Clear', 'The driver leaves by the farm track. You are bruised, but the payroll box and driver reach the mill; the owner withholds the danger bonus.'),
    fight: end('fight', 'The Driver Gets Clear', 'The driver reaches the mill with the payroll box. The owner pays the base wage but withholds the danger bonus.'),
  }, 'travel/exploration'),

  story('the-crate-of-window-glass', 'The Crate of Window Glass', 'A fragile load must cross a road being repaired before rain.', 'MODERATE', 'county road repair site', 'Protecting delicate cargo is about load balance and timing, not attackers.', 'load', {
    load: largeScene('load', 'A Narrow Bed', 'A glazier’s crate is packed with window panes. The wagon bed tilts slightly left; the road crew has closed the straight track and marked a dry but longer detour.', [choice('strap', 'Use the Freightman’s Strap to brace the crate', 'detour', { setFlags: ['crate_braced'] }, { items: ['freightmansStrap'] }), choice('blanket', 'Wrap the corners in the employer’s spare blanket', 'detour', { setFlags: ['crate_wrapped'] }), choice('detour', 'Take the longer dry detour without repacking', 'delayed')]),
    detour: largeScene('detour', 'A Rut at the Drain', 'A fresh rut runs across the detour. The wagon can cross slowly, but a wheel will dip; the glazier wants the panes delivered before the crew leaves.', [choice('unload', 'Unload the crate and carry it across in smaller pieces', 'carried'), choice('jack', 'Use your Folding Carriage Jack to level the wagon first', 'leveled', undefined, { items: ['foldingCarriageJack'] }), choice('cross', 'Cross slowly and accept that a pane may crack', 'cracked')]),
    carried: end('carried', 'Every Pane Accounted For', 'The glazier and driver carry the crate across by hand. The panes arrive intact, though the crew waits and the delivery wage is reduced.'),
    leveled: end('leveled', 'A Level Bed', 'The jack steadies the wagon on firm ground; the crate crosses without shifting. The tool is yours and remains with you.'),
    cracked: end('cracked', 'A Costly Rattle', 'The wagon crosses, but one pane cracks in the rut. The glazier accepts the remaining glass and pays only the partial wage.'),
    delayed: end('delayed', 'Rain Before Arrival', 'You wait for the repair crew to reopen the straight road. The glass arrives dry, but the shop has closed for the day.'),
  }, 'labor/repair'),

  story('the-witness-under-escort', 'The Witness under Escort', 'A sawmill worker asks for safe passage to give an account in town.', 'HIGH', 'sawmill road and town approach', 'The escort must protect a person while honoring their choice about what to disclose.', 'yard', {
    yard: largeScene('yard', 'A Worker at the Back Gate', 'Nell Armit says a foreman threatened her after she saw a brace removed from a mill lift. She wants to reach the town clerk, but asks you not to read the folded statement she carries.', [choice('respect', 'Leave the statement sealed and choose the public road', 'road', { setFlags: ['statement_sealed'] }), choice('case', 'Offer your Lockable Map Case for the sealed statement', 'road', { setFlags: ['statement_in_case'] }, { items: ['lockableMapCase'] }), choice('question', 'Ask what help she wants if the foreman appears', 'plan')]),
    plan: largeScene('plan', 'Her Terms', 'Nell wants a witness, not a fight. She will speak for herself if you stay beside her; if the road is blocked, she prefers to wait at the church rather than turn back alone.', [choice('agree', 'Agree to stay beside her and use the church as a refuge', 'road', { setFlags: ['nells_plan'] }), choice('refuse', 'Decline the escort rather than promise protection you cannot give', 'refused')]),
    road: largeScene('road', 'The Mill Cart', 'A cart comes up behind you and slows when Nell looks back. The driver is the foreman’s brother. He steers across the lane and says she must return to the mill; one hand has left the reins.', [choice('continue', 'Keep Nell moving toward the staffed clerk’s office', 'arrived'), choice('church', 'Take the marked lane to the church refuge', 'refuge'), choice('confront', 'Stand between the cart and Nell and demand he move', 'confronted'), choice('fight', 'Defend Nell if he steps down and grabs her', 'fight', { combat: { enemy: 'mill foreman’s brother', winChance: 0.53, damageOnWin: 1, damageOnLoss: 5, winNext: 'arrived', lossNext: 'refuge' } })]),
    arrived: end('arrived', 'A Witness Reaches Town', 'Nell reaches the clerk’s office with her statement sealed. She gives her account herself; your presence is noted without claiming what you did not hear.'),
    refuge: end('refuge', 'A Safe Pause', 'Nell waits inside the church while the cart passes. She chooses to continue with a town constable after the road is clear.'),
    confronted: end('confronted', 'The Cart Turns Away', 'The driver says he was sent to collect a mill ledger, not Nell. The explanation is awkward but not proof of a threat; he turns back when she asks him to leave.'),
    refused: end('refused', 'An Honest Limit', 'You do not promise safety you cannot ensure. Nell waits for the clerk to send another escort.'),
    fight: end('fight', 'Nell Reaches the Clerk', 'The driver leaves when the clerk calls for witnesses. Nell reaches the office and gives her account herself.'),
  }, 'communication/witness'),

  story('the-shepherds-return', 'The Shepherd’s Return', 'A flock must be moved before smoke from a distant grass fire shifts west.', 'MODERATE', 'sheep pasture and windbreak', 'Protecting livestock means managing panic and firebreaks rather than fighting a predator.', 'pasture', {
    pasture: largeScene('pasture', 'Smoke beyond the Ridge', 'Shepherd Ada Wynn has thirty sheep near a dry creek. Smoke rises beyond the ridge and the wind is turning. Her dog knows the flock but is limping; the gate to the stone lane is jammed.', [choice('gate', 'Use your Pocket Toolkit to free the gate hinge', 'lane', { setFlags: ['gate_freed'] }, { items: ['pocketToolkit'] }), choice('dog', 'Help Ada move the flock slowly with the limping dog', 'creek', { setFlags: ['slow_flock'] }), choice('warning', 'Use your Farm Whistle to alert the neighboring pasture', 'neighbors', undefined, { items: ['farmWhistle'] })]),
    lane: largeScene('lane', 'The Stone Lane', 'The gate opens onto a narrow lane with a stone wall on one side. The flock can pass safely, but Ada’s cart cannot follow it.', [choice('flock', 'Walk with the flock and leave the cart for later', 'safeFlock'), choice('cart', 'Move the cart first, risking a slower flock', 'split')]),
    creek: largeScene('creek', 'A Split in the Flock', 'Two sheep break toward the dry creek while the others follow Ada. Smoke is still distant, but the breeze is carrying ash.', [choice('two', 'Stay with the two sheep and call Ada to keep the main flock moving', 'partial'), choice('main', 'Stay with the main flock and let the neighbors retrieve the pair', 'safeFlock')]),
    neighbors: end('neighbors', 'Help from the Next Pasture', 'The neighbor answers and opens a second lane. The flock reaches the lower field together; Ada pays the agreed wage and keeps her cart behind.'),
    safeFlock: end('safeFlock', 'The Flock Reaches Stone Ground', 'The sheep reach the bare stone field before the wind carries the smoke down. The cart remains by the gate, but every animal is accounted for.'),
    split: end('split', 'Two Duties, One Delay', 'The cart reaches the lane, but the main flock loses time and two sheep need to be gathered by the neighbors. Ada pays a reduced wage for the delay.'),
    partial: end('partial', 'No Perfect Gathering', 'You keep the pair from entering the creek while Ada drives the others to stone ground. The flock is safe, though the move takes longer and the dog must rest.'),
  }, 'animals'),

  story('the-ferry-for-the-midwife', 'The Ferry for the Midwife', 'A midwife must cross before a household’s labor becomes urgent.', 'MODERATE', 'ferry landing and riverside lane', 'The Traveler must decide whether to risk a damaged ferry or use a slower relay route.', 'landing', {
    landing: largeScene('landing', 'A Frayed Hauling Line', 'Midwife Elsie Ward waits with a small medical bag. The ferry’s hauling line is frayed near the bank; the ferryman says it will hold once, but not twice.', [choice('inspect', 'Inspect the line with your Heavy Leather Gloves', 'line', undefined, { items: ['heavyLeatherGloves'] }), choice('alternate', 'Send a runner to the upper bridge for a relay crossing', 'relay'), choice('replace', 'Ask the ferryman to replace the line before crossing', 'delay')]),
    line: largeScene('line', 'Fibers under the Splice', 'The line has a weak splice hidden under fresh tar. It may carry the empty ferry, but the midwife and ferryman should not both stand aboard.', [choice('one', 'Send the empty ferry across, then take the midwife by skiff', 'relay'), choice('risk', 'Cross together on the hauling line', 'crossing')]),
    relay: end('relay', 'A Longer Safe Passage', 'The midwife reaches the upper bridge by cart and is met by a neighbor on the far bank. The household receives her later, but the crossing remains safe.'),
    crossing: end('crossing', 'A Line Gives Way', 'The line parts as the ferry reaches midstream. The ferryman cuts it free and rows to the near bank; the midwife is unhurt but must wait for a repair.'),
    delay: end('delay', 'A Repaired Crossing', 'The ferryman replaces the line before taking passengers. The midwife reaches the household after dark and pays you the agreed modest escort fee.'),
  }, 'rescue/care'),

  story('the-lanterns-at-camp-four', 'The Lanterns at Camp Four', 'A rail crew repairs a signal while the Traveler watches their tools and the dark track.', 'HIGH', 'rail siding and repair camp', 'Protecting a working crew means balancing lookout duty against keeping the signal lamp lit.', 'camp', {
    camp: largeScene('camp', 'Tools beside the Track', 'Forewoman Inez Vale has a crew working on a signal arm. A second lamp is theirs, and a Lantern Guard would keep its glass safe in the brush. You are asked to watch the tool board while she climbs.', [choice('lamp', 'Fit your Lantern Guard to the spare lamp', 'dark', { setFlags: ['guarded_lamp'] }, { items: ['lanternGuard'] }), choice('board', 'Keep the tool board within sight and leave the lamp bare', 'dark', { setFlags: ['watched_tools'] }), choice('signal', 'Use your Conductor’s Whistle to set a warning signal', 'signal', undefined, { items: ['conductorWhistle'] })]),
    dark: largeScene('dark', 'A Hand at the Board', 'A figure approaches the tool board from the far side of the siding. The crew is still on the signal arm; the track is quiet, and the figure has not touched anything yet.', [choice('call', 'Call out and identify yourself before approaching', 'identified'), choice('protectCrew', 'Warn the crew and stay by the lit work area', 'safe'), choice('rush', 'Rush across the track to block the figure', 'hurt')]),
    signal: end('signal', 'A Clear Work Signal', 'The whistle brings the forewoman down before anyone approaches the board. The stranger is a relief worker from the next siding, and the crew finishes with both lamps intact.'),
    identified: end('identified', 'A Worker, Not a Thief', 'The figure is the night brakeman looking for a replacement wrench. The crew lends one and finishes the signal; the watched tools remain accounted for.'),
    safe: end('safe', 'Work Ends before Trouble', 'The stranger turns out to be a night brakeman, but your warning gets the crew down safely before he reaches the board. The repair resumes in daylight.'),
    hurt: end('hurt', 'A Bad Crossing', 'You reach the far side as the figure backs away. A passing handcar forces you to jump clear; nobody is hurt, but the crew stops work until morning.'),
  }, 'labor/repair'),

  story('the-courier-relay-box', 'The Courier Relay Box', 'A locked box must pass through three hands without opening.', 'LOW', 'post road and relay station', 'An escort relay tests chain-of-custody without inviting the Traveler to read private papers.', 'handoff', {
    handoff: largeScene('handoff', 'A Sealed Box', 'Courier Amos Beck carries a small locked box with a wax seal and a county route mark. The next rider is late. Amos asks you to guard the box at the relay stable, not carry it onward.', [choice('guard', 'Keep the box in view while Amos finds the station keeper', 'stable'), choice('case', 'Offer your Lockable Map Case for temporary weather cover', 'stable', { setFlags: ['case_offered'] }, { items: ['lockableMapCase'] }), choice('decline', 'Refuse custody without a written handoff', 'refused')]),
    stable: largeScene('stable', 'A Second Receipt', 'A rider arrives with a receipt bearing the right route but the wrong date. Amos recognizes the rider’s horse, not the signature. The rider reaches for the sealed box when Amos refuses the handoff.', [choice('wait', 'Wait for the station keeper to verify both receipts', 'verified'), choice('handoff', 'Let Amos decide whether to transfer the box', 'transfer'), choice('open', 'Ask Amos to break the seal and check the contents', 'breach'), choice('defend', 'Keep the box back and defend Amos if grabbed', 'fight', { combat: { enemy: 'false courier', winChance: 0.5, damageOnWin: 1, damageOnLoss: 4, winNext: 'verified', lossNext: 'refused' } })]),
    verified: end('verified', 'The Seal Remains Whole', 'The keeper confirms the rider is assigned to the next leg, but the date was copied from yesterday’s sheet. The box travels onward unopened.'),
    transfer: end('transfer', 'A Handoff on the Courier’s Word', 'Amos accepts responsibility for the transfer and signs the rider’s receipt. You neither read nor claim the contents.'),
    breach: end('breach', 'Trust Broken', 'Amos refuses to break the county seal. The next rider takes the box after the keeper arrives, but the clerk records your suggestion as a breach of confidence.'),
    refused: end('refused', 'No Custody Without a Record', 'You decline the responsibility until the station keeper can witness it. Amos waits with the box and later records the delay himself.'),
    fight: end('fight', 'The Handoff Is Stopped', 'The rider lets go when the station keeper calls for help. The box stays sealed; the clerk verifies its route before sending it onward.'),
  }, 'communication/witness'),

  story('the-wagon-with-the-lame-wheel', 'The Wagon with the Lame Wheel', 'A family’s wagon must reach the doctor before a child’s fever worsens.', 'MODERATE', 'muddy farm road', 'A repair under time pressure becomes a choice between speed and a controlled load.', 'road', {
    road: largeScene('road', 'A Wheel Running Crooked', 'The left wheel leans under the wagon. The family has medicine inside, and the road slopes toward a drainage ditch. The hub is cracked but the axle is sound.', [choice('jack', 'Use your Folding Carriage Jack on the firm shoulder', 'repair', undefined, { items: ['foldingCarriageJack'] }), choice('unload', 'Move the medicine and child before touching the wheel', 'unload'), choice('wrench', 'Use your Compact Wheel Wrench to check the nuts', 'repair', undefined, { items: ['compactWheelWrench'] })]),
    repair: largeScene('repair', 'A Hub under Strain', 'The wheel can be held long enough to reach the smith if the load is shifted. The family asks you to choose who rides and who walks beside the wagon.', [choice('child', 'Keep the child and medicine in the wagon; walk beside the wheel', 'arrive'), choice('medicine', 'Carry the medicine yourself and send the wagon slowly', 'split'), choice('stop', 'Wait for the smith rather than move a cracked hub', 'wait')]),
    unload: largeScene('unload', 'A Safer Load', 'The child is carried to level ground and the medicine is safe. The wagon now weighs less, but the family must decide whether to leave household goods beside the road.', [choice('goods', 'Leave the goods under a neighbor’s watch and move the family', 'arrive'), choice('all', 'Wait until help can move the goods too', 'wait')]),
    arrive: end('arrive', 'The Doctor Is Reached', 'The child and medicine reach the doctor. The wagon remains with the smith for a new hub; the family pays a reduced fee for the delay.'),
    split: end('split', 'Two Arrivals', 'You carry the medicine ahead while the family keeps the wagon on the shoulder. The doctor sees the child later, but the treatment is ready.'),
    wait: end('wait', 'The Wheel Stays Put', 'You prevent the cracked hub from failing on the slope. The doctor is delayed, and the family pays no escort wage, but no one is injured.'),
  }, 'rescue/care'),

  story('the-quiet-cattle-drive', 'The Quiet Cattle Drive', 'A small herd must pass a telegraph crew without scattering.', 'LOW', 'open range and telegraph line', 'Protecting a work crew and livestock at once requires coordination, not force.', 'range', {
    range: largeScene('range', 'Wire across the Drive', 'Cattle are moving toward a telegraph line where two workers have a pole raised. A young steer shies at the wire’s shadow. The crew cannot lower the pole until the herd passes.', [choice('whistle', 'Use your Farm Whistle from the downwind side', 'herd', undefined, { items: ['farmWhistle'] }), choice('rope', 'Use a Travel Rope to guide the steer away from the post', 'guide', undefined, { items: ['travelRope'] }), choice('wait', 'Hold the herd at the fence until the pole is lowered', 'delay')]),
    herd: largeScene('herd', 'A Split at the Post', 'The cattle slow, but the steer veers toward a shallow ditch. The telegraph crew has a clear way down if the herd remains behind the fence.', [choice('steer', 'Stay with the steer while the crew lowers the pole', 'safe'), choice('crew', 'Keep the herd back and send the drover to the steer', 'split')]),
    guide: end('guide', 'The Line Clears', 'The rope gives the drover a visible guide without pulling the animal. The crew lowers the pole and the herd passes with the steer calm.'),
    delay: end('delay', 'A Patient Delay', 'The herd waits until the crew lowers the pole. The drive loses an hour but no animal reaches the wire.'),
    safe: end('safe', 'The Steer Turns Back', 'The steer follows the familiar herd call away from the ditch. The crew lowers the pole once the cattle are past.'),
    split: end('split', 'Two Safe Tasks', 'The drover brings the steer around while you keep the rest of the herd back. One animal is late to the pen, but neither crew nor cattle are harmed.'),
  }, 'animals'),

  story('the-archive-through-the-rain', 'The Archive through the Rain', 'A town archive must be moved before a roof leak reaches its shelves.', 'MODERATE', 'town archive and flooded lane', 'The protected object is information; moving it safely matters more than retaining custody.', 'archive', {
    archive: largeScene('archive', 'Water at the Ceiling', 'A clerk has two dry carts and one hour before rain reaches the upper shelves. The deed box is locked; the bound ledger is already swelling at the edges.', [choice('ledger', 'Carry the ledger first in your Weatherproof Blanket', 'carryLedger', { setFlags: ['ledger_first'] }, { items: ['weatherproofBlanket'], usableItems: ['weatherproofBlanket'] }), choice('box', 'Move the deed box first using a Travel Rope sling', 'carryBox', { setFlags: ['box_first'] }, { items: ['travelRope'], usableItems: ['travelRope'] }), choice('help', 'Ask the clerk to choose which record must not be lost', 'choice')]),
    choice: largeScene('choice', 'A Clerk Names the Priority', 'The clerk says the deed box can be reconstructed from county copies, but the ledger contains the only record of a boundary dispute. She asks you to save that first.', [choice('follow', 'Follow the clerk’s priority and take the ledger', 'carryLedger'), choice('disagree', 'Move the deed box because it is already locked', 'carryBox')]),
     carryLedger: largeScene('carryLedger', 'The Lane Runs with Water', 'The cart reaches a flooded rut. The ledger must stay above the wheel line; the deed box can be set on the dry sill while you cross.', [choice('case', 'Secure the ledger inside your Lockable Map Case', 'saved', undefined, { items: ['lockableMapCase'], usableItems: ['lockableMapCase'] }), choice('blanket', 'Wrap it tightly and carry it across by hand', 'saved'), choice('turn', 'Wait for the water to fall', 'partial')]),
    carryBox: end('carryBox', 'The Deeds Stay Dry', 'The deed box reaches the church hall intact. Rain damages several ledger pages before the archive crew can return.'),
    saved: end('saved', 'A Record Preserved', 'The ledger arrives dry enough to read and the clerk keeps the deed box on the sill. You protected the record the town could not replace.'),
    partial: end('partial', 'Some Pages Run', 'The wait protects the box, but several ledger pages blur before the rain stops. The clerk saves the remaining volume and pays a smaller moving fee.'),
  }, 'labor/repair'),

  story('the-night-guard-at-the-icehouse', 'The Night Guard at the Icehouse', 'A night watch protects a shipment of ice and the workers loading it.', 'MODERATE', 'icehouse loading yard', 'Watch duty is about detecting a structural hazard rather than assuming every sound is a thief.', 'yard', {
    yard: largeScene('yard', 'A Shift in the Floor', 'The icehouse floor creaks under a loaded sled. Two workers are inside stacking blocks, and a lantern hangs above the exit. The owner asks you to watch the door while the floor is checked.', [choice('guard', 'Keep the exit clear and call if the boards shift again', 'creak'), choice('lamp', 'Use your Lantern Guard to move the lamp near the floor seam', 'seam', undefined, { items: ['lanternGuard'] }), choice('enter', 'Go inside and help the workers unload the sled', 'inside')]),
    creak: largeScene('creak', 'Another Creak', 'A board cracks and the sled tilts. The workers are near the back wall; the exit is clear if the sled is not pulled against the door.', [choice('call', 'Call the workers to the back wall', 'safe'), choice('pull', 'Pull the sled toward the exit before the floor gives', 'spill')]),
    seam: largeScene('seam', 'A Damp Line', 'The lamp shows water seeping beneath the boards. The icehouse is not being entered; thaw water has undermined the floor supports.', [choice('evacuate', 'Evacuate the workers and leave the ice', 'safe'), choice('brace', 'Brace the sled while the owner clears the workers', 'spill')]),
    inside: end('inside', 'The Sled Moves', 'You help lift the sled clear before the floor splits. The workers leave with you; several ice blocks are lost but no one is trapped.'),
    safe: end('safe', 'The Yard Is Cleared', 'The workers get outside before a floor section drops. The owner loses the ice shipment but pays the agreed watch wage.'),
    spill: end('spill', 'Lost Ice, Safe Workers', 'The sled breaks through a plank and the ice spills. The workers escape the yard; the owner accepts the loss rather than risk a second collapse.'),
  }, 'survival'),

  story('the-horse-for-the-farrier', 'The Horse for the Farrier', 'A valuable mare must be led through town without worsening a hoof injury.', 'LOW', 'town street and farrier yard', 'A calm lead and informed pacing matter more than forcing a frightened animal forward.', 'street', {
    street: largeScene('street', 'A Tender Step', 'The mare favors her near forehoof. Her owner, Mrs. Bell, wants the farrier before the shop closes; a wagon crowd has gathered at the main street.', [choice('lead', 'Use a quiet lead and take the stable lane', 'lane'), choice('gloves', 'Use Heavy Leather Gloves to check the hoof before moving', 'hoof', undefined, { items: ['heavyLeatherGloves'] }), choice('crowd', 'Ask the crowd to open the main street', 'crowd')]),
    hoof: largeScene('hoof', 'A Stone under the Shoe', 'A small stone is wedged beside the shoe, not through the hoof. The mare still needs a farrier, but she can walk slowly if the stone is eased free.', [choice('ease', 'Ease the stone out and let her rest between blocks', 'arrived'), choice('wait', 'Keep her still until the farrier comes to the street', 'late')]),
    lane: largeScene('lane', 'The Narrow Stable Lane', 'A delivery cart blocks half the lane. The mare has space to pass if the driver backs toward the wall, but a sudden turn could strain the hoof.', [choice('ask', 'Ask the cart driver to back slowly', 'arrived'), choice('return', 'Turn back to the quieter stable yard', 'late')]),
    crowd: end('crowd', 'A Clear Street', 'The crowd steps aside when the owner explains the injury. The mare reaches the farrier without being hurried.'),
    arrived: end('arrived', 'At the Farrier’s Door', 'The farrier removes the stone and confirms the shoe needs resetting. Mrs. Bell pays the agreed escort fee; the mare rests in the yard.'),
    late: end('late', 'A Sounder Choice', 'The farrier comes to the stable yard after closing. The mare arrives later but is not forced through the crowd.'),
  }, 'animals'),

  story('the-missing-survey-case', 'The Missing Survey Case', 'A survey crew needs its instruments carried away from a threatened cut.', 'HIGH', 'rail cut and survey camp', 'The Traveler must protect people first while accounting for costly instruments.', 'cut', {
    cut: largeScene('cut', 'A Crack above the Stakes', 'Surveyor Penn sees a fresh crack above the cut where his crew is measuring a rail grade. The instrument case is on a plank table below it; the workers are scattered along the line.', [choice('workers', 'Call the crew out before touching the instrument case', 'evacuate'), choice('case', 'Use your Freightman’s Strap to secure the case to the handcart', 'cart', undefined, { items: ['freightmansStrap'] }), choice('marker', 'Use a Folding Trail Marker to flag the unstable edge', 'evacuate', undefined, { items: ['foldingTrailMarker'] })]),
    evacuate: largeScene('evacuate', 'The Cut Gives a Warning', 'A stone slides down the face. The crew is moving, but one chainman is on the far end with no clear path except the lower track.', [choice('go', 'Cross the lower track to bring the chainman out', 'crewSafe'), choice('call', 'Call him to wait while the others circle around', 'partial')]),
    cart: largeScene('cart', 'The Case on Wheels', 'The instrument case is secured, but the crack widens. The handcart can roll to the open track; the far chainman still needs warning.', [choice('roll', 'Roll the case out and shout for the chainman', 'partial'), choice('leave', 'Leave the case and bring the chainman out first', 'crewSafe')]),
    crewSafe: end('crewSafe', 'People before Instruments', 'The crew reaches open ground. The instrument case remains below the crack and is lost when a section slumps; Penn records that you chose the workers first.'),
    partial: end('partial', 'Crew and Case Accounted For', 'The crew gets clear and the case reaches the track, scratched but usable. Survey work stops until the cut is inspected.'),
  }, 'labor/repair'),

  story('the-smallpox-letter', 'The Smallpox Letter', 'A sealed warning must reach a doctor without alarming a crowded town.', 'MODERATE', 'country post route and town clinic', 'Protecting a confidential medical notice is a relay and trust problem.', 'post', {
    post: largeScene('post', 'A Sealed Notice', 'The postmaster asks you to ride with a sealed letter to Dr. Senn. He says it contains an urgent illness warning, but the seal must remain intact until the doctor opens it.', [choice('case', 'Keep the notice dry inside your Lockable Map Case', 'gate', undefined, { items: ['lockableMapCase'], usableItems: ['lockableMapCase'] }), choice('cloak', 'Keep it beneath your Weatherproof Cloak', 'gate', undefined, { items: ['weatherproofCloak'], usableItems: ['weatherproofCloak'] }), choice('ask', 'Ask the postmaster to provide a written custody receipt', 'receipt')]),
    receipt: largeScene('receipt', 'A Name in the Margin', 'The receipt names the doctor and a clinic address. A parent at the post office asks whether the letter means their child is ill; you have not read it.', [choice('privacy', 'Tell the parent only that the doctor will receive it', 'gate'), choice('decline', 'Return the letter to the postmaster rather than discuss it', 'returned')]),
    gate: largeScene('gate', 'The Clinic Gate', 'A crowd is waiting outside the clinic. The doctor is inside with a patient; a stablehand offers to take the letter through the back door.', [choice('wait', 'Wait until the doctor can receive the sealed letter', 'delivered'), choice('stable', 'Give it to the stablehand for the back entrance', 'handoff'), choice('crowd', 'Ask the crowd to make a clear path without naming the letter', 'delivered')]),
    delivered: end('delivered', 'A Private Delivery', 'The doctor receives the sealed notice and opens it inside. You do not learn who is ill; the postmaster pays the agreed delivery fee.'),
    handoff: end('handoff', 'A Witnessed Handoff', 'The stablehand signs for the sealed letter and carries it through the back entrance. The seal remains whole.'),
    returned: end('returned', 'The Letter Stays Sealed', 'The postmaster keeps the notice and sends it with a clerk. Your caution delays the warning but protects its privacy.'),
  }, 'communication/witness'),

  story('the-winter-feed-sled', 'The Winter Feed Sled', 'A feed sled must cross a frozen pond before the animals run short.', 'HIGH', 'frozen pond and farm lane', 'Protecting animals and cargo requires choosing when not to cross.', 'pond', {
    pond: largeScene('pond', 'A Dark Seam in the Ice', 'A farmer has one sled of feed for cattle across the pond. A dark seam runs beneath the snow near the shortest path; the long road adds two hours.', [choice('road', 'Take the long road around the pond', 'arrived'), choice('sound', 'Use your Collapsible Sounding Rod at the near edge', 'test', undefined, { items: ['collapsibleSoundingRod'] }), choice('cross', 'Cross the marked shallow inlet on foot first', 'inlet')]),
    test: largeScene('test', 'A Hollow Note', 'The rod finds solid ice near shore and a hollow answer toward the middle. The sled team can turn back without unloading, but the feed will arrive late.', [choice('turn', 'Turn back and use the long road', 'arrived'), choice('unload', 'Unload feed for a hand-carried crossing at the inlet', 'partial')]),
    inlet: largeScene('inlet', 'The Team Stops', 'The lead horse plants its feet at the inlet. The farmer says it has crossed here before, but the ice makes a low sound under the sled.', [choice('listen', 'Listen to the ice and turn the team away', 'arrived'), choice('urge', 'Urge the team across before the light fades', 'lost')]),
    arrived: end('arrived', 'Feed Reaches the Barn', 'The feed reaches the cattle by the long road after dark. The farmer pays for the haul and thanks you for not testing the middle ice with the team.'),
    partial: end('partial', 'Some Feed, Safely Carried', 'The animals receive enough feed for the night, carried in smaller loads over the firm inlet. The sled remains on the near bank.'),
    lost: end('lost', 'A Sled in the Water', 'The ice gives under the empty edge of the sled. The horse is led to firm ground and no person is lost, but the feed must be replaced.'),
  }, 'survival'),

  story('the-fence-at-crow-road', 'The Fence at Crow Road', 'A hired crew repairs a roadside fence while a landowner’s men approach.', 'HIGH', 'county road and fenced pasture', 'Protecting a work crew means verifying authority before choosing whether to stand ground.', 'fence', {
    fence: largeScene('fence', 'A Crew at the Gap', 'A road commissioner hired three workers to close a washed-out gap in a pasture fence. Two armed men arrive claiming the fence blocks their cattle drive; the crew has no copy of the order.', [choice('order', 'Ask the men to show their land or work order', 'claim'), choice('crew', 'Move the workers and tools behind the stone wall', 'withdraw'), choice('stand', 'Stand between the men and the crew', 'stand')]),
    claim: largeScene('claim', 'Two Different Claims', 'The men own the pasture but not the county verge. Their cattle are still a mile away; the workers can finish the gap if the men agree to wait for the commissioner.', [choice('wait', 'Ask both sides to wait for the commissioner', 'settled'), choice('finish', 'Help the crew finish the public fence section', 'fight')]),
    stand: largeScene('stand', 'A Hand Moves to a Belt', 'The nearer man reaches toward his belt when you step forward. The crew has an open path behind the wall; the men have not yet drawn.', [choice('withdraw', 'Back toward the wall and signal the crew to leave', 'withdraw'), choice('fight', 'Hold position while the crew clears the tools', 'fight', { combat: { enemy: 'armed fence claimants', winChance: 0.45, damageOnWin: 1, damageOnLoss: 6, winNext: 'settled', lossNext: 'hurt' } })]),
    settled: end('settled', 'The Commissioner Arrives', 'The commissioner confirms the public verge and asks the men to move their cattle route. The fence crew finishes with its tools and workers safe.'),
    withdraw: end('withdraw', 'Crew before Fence', 'The workers leave with their tools. The gap stays open until the commissioner arrives; no one is hurt and you receive only the agreed travel allowance.'),
    fight: end('fight', 'Work Resumes under Witness', 'The men back away when the crew and a passing teamster gather at the wall. The commissioner later verifies the order and pays the crew.'),
    hurt: end('hurt', 'A Costly Withdrawal', 'You are struck as you retreat, but the workers reach the wall and keep their tools. The commissioner pays the base wage without a protection bonus.'),
  }, 'labor/repair'),

  story('the-glass-plate-box', 'The Glass-Plate Box', 'A photographer needs a fragile plate box carried over a washed-out hill road.', 'MODERATE', 'hill road and photographic camp', 'The cargo is fragile and time-sensitive; the Traveler must choose between speed, protection, and an honest delay.', 'camp', {
    camp: largeScene('camp', 'A Box of Negatives', 'Photographer Lyle Senn carries glass plates from a survey camp. A storm has cut the hill road, and a lower track is open but muddy. The plates are irreplaceable; his camera is not.', [choice('wrap', 'Wrap the plate box in your Weatherproof Blanket', 'track', undefined, { items: ['weatherproofBlanket'], usableItems: ['weatherproofBlanket'] }), choice('case', 'Secure it in your Lockable Map Case', 'track', undefined, { items: ['lockableMapCase'], usableItems: ['lockableMapCase'] }), choice('wait', 'Wait for the hill road to be inspected', 'delay')]),
    track: largeScene('track', 'Mud above the Culvert', 'The lower track crosses a narrow culvert. It can carry one person at a time; the photographer can walk beside the box or carry the camera first. A stranger reaches for the camera strap from the brush.', [choice('box', 'Carry the plate box across before the camera', 'safe'), choice('camera', 'Carry the camera first and let Lyle move the box', 'cracked'), choice('return', 'Turn back before the culvert', 'delay'), choice('defend', 'Protect Lyle if the stranger grabs the camera', 'fight', { combat: { enemy: 'camera thief', winChance: 0.48, damageOnWin: 1, damageOnLoss: 4, winNext: 'safe', lossNext: 'cracked' } })]),
    safe: end('safe', 'The Plates Arrive', 'The plates cross dry and the camera follows. Lyle pays the agreed fee and records your care in the town studio ledger.'),
    cracked: end('cracked', 'A Plate Lost', 'The camera arrives safely, but one glass plate cracks when the box shifts. Lyle pays a reduced fee; the surviving images are still usable.'),
    delay: end('delay', 'A Day for the Road Crew', 'You wait for a proper inspection rather than risk the box on a soft culvert. The plates arrive the next day, intact but late.'),
    fight: end('fight', 'The Camera Stays with Its Owner', 'The stranger lets go of the strap and runs when the driver calls for help. The plate box remains the priority; the photographer decides whether to replace the camera later.'),
  }, 'travel/exploration'),

  story('the-night-mail-train', 'The Night Mail Train', 'A station agent asks you to guard mail sacks during a storm delay.', 'MODERATE', 'rail station platform', 'The task is to protect the transfer without assuming every waiting traveler is a thief.', 'platform', {
    platform: largeScene('platform', 'Sacks beneath the Awning', 'A storm delays the mail train. The agent has two sacks under the platform awning and must inspect a signal lamp down the track. Passengers wait in the station room; one man tries to drag a sack toward the dark siding.', [choice('stay', 'Stay with the sacks where passengers can see you', 'rain'), choice('move', 'Move the sacks into the locked parcel room with the agent’s key', 'room'), choice('signal', 'Use your Conductor’s Whistle to call the porter before leaving', 'porter', undefined, { items: ['conductorWhistle'] }), choice('stop', 'Stop the man only if he takes the sack', 'fight', { combat: { enemy: 'mail thief', winChance: 0.54, damageOnWin: 1, damageOnLoss: 4, winNext: 'room', lossNext: 'delay' } })]),
    rain: largeScene('rain', 'A Passenger Takes Shelter', 'A soaked passenger asks to sit beneath the awning. The sacks are dry but narrow the space; the station room is open and warm.', [choice('room', 'Move the passenger to the station room, leaving sacks in view', 'room'), choice('share', 'Make room for the passenger beside the sacks', 'shared'), choice('agent', 'Wait for the agent before changing the arrangement', 'delay')]),
    room: end('room', 'A Recorded Transfer', 'The agent returns and records both sacks in the parcel room. The passenger stays in the warm station; nothing is opened or lost.'),
    porter: end('porter', 'A Shared Watch', 'The porter arrives and takes the platform watch while the agent checks the lamp. The mail remains sealed through the delay.'),
    shared: end('shared', 'Dry People, Dry Mail', 'The passenger shelters under the awning until the porter comes. The sacks remain dry, and the station agent pays the watch fee.'),
    delay: end('delay', 'A Slow, Accountable Shift', 'You leave the sacks where they are and keep watch until the agent returns. The train is late, but the transfer is properly logged.'),
    fight: end('fight', 'The Parcel Room Is Locked', 'The porter helps the agent secure the sacks. The man leaves before the train arrives; no mail is opened.'),
  }, 'communication/witness'),

  story('the-bridge-pins', 'The Bridge Pins', 'A bridge crew needs its pin chest protected while a damaged span is inspected.', 'HIGH', 'covered bridge and work bank', 'Protecting expensive parts must not take priority over keeping workers clear of an unsafe span.', 'bank', {
    bank: largeScene('bank', 'A Pin Chest at the Abutment', 'The bridge crew leaves a chest of iron pins on the near bank while the foreman checks a split beam. A boy from the nearby farm says he saw someone watching the chest from the far bank.', [choice('watch', 'Watch the chest from the dry abutment', 'watch'), choice('secure', 'Use your Travel Rope to secure the chest to the work cart', 'beam', undefined, { items: ['travelRope'] }), choice('crew', 'Ask the foreman to move the crew off the span first', 'clear')]),
    watch: largeScene('watch', 'A Beam Settles', 'The beam shifts before anyone approaches the chest. The crew is still on the span; the far-bank watcher crosses toward the pin chest while the foreman shouts for everyone to clear the bridge.', [choice('warn', 'Warn the crew and leave the chest where it is', 'clear'), choice('chest', 'Move the chest before the beam shifts further', 'beam'), choice('stop', 'Stop the watcher if they reach for the chest', 'fight', { combat: { enemy: 'bridge-parts thief', winChance: 0.46, damageOnWin: 1, damageOnLoss: 5, winNext: 'clear', lossNext: 'partial' } })]),
    beam: largeScene('beam', 'The Chest Can Wait', 'The chest is secure, but the bridge is not. A second creak comes from the center span; the foreman orders everyone off.', [choice('leave', 'Leave the chest and help clear the span', 'clear'), choice('stay', 'Stay with the chest while the workers cross to safety', 'partial')]),
    clear: end('clear', 'People off the Bridge', 'The crew reaches the bank before a beam drops. The pin chest remains on the abutment and is recovered after the span is shored.'),
    partial: end('partial', 'A Chest and a Close Call', 'The chest stays tied to the cart, but the workers cross without your help. One is bruised by a falling plank; the foreman records the near miss.'),
    fight: end('fight', 'The Crew Clears the Span', 'The watcher flees without the pin chest when the bridge crew reaches the bank. The foreman closes the bridge; its condition, not the missing parts, is the remaining danger.'),
  }, 'labor/repair'),

  story('the-lost-childs-lantern', 'The Lost Child’s Lantern', 'A child and an older sibling must be brought home through a foggy orchard.', 'LOW', 'orchard lane and farmstead', 'A quiet family escort uses clear signaling and staying together instead of a supernatural or criminal threat.', 'orchard', {
    orchard: largeScene('orchard', 'A Light between the Trees', 'You find eight-year-old Ruth beside an orchard wall, holding a dim lantern. Her older brother is on the far side of the trees, calling but not moving closer because the fog hides the ditch.', [choice('answer', 'Use your Trail Whistle so both children can follow one sound', 'signal', undefined, { items: ['trailWhistle'] }), choice('light', 'Keep Ruth beside you and walk toward the brother’s voice', 'ditch'), choice('wait', 'Stay at the wall and ask the brother to call from one place', 'signal')]),
    signal: largeScene('signal', 'One Call at a Time', 'The brother answers from a fence post. Ruth knows the gate but not the safe path through the ditch; the lantern is low on oil.', [choice('gate', 'Walk Ruth to the gate, then bring her brother back', 'home'), choice('brother', 'Ask the brother to stay put while you fetch the farm lantern', 'farm')]),
    ditch: largeScene('ditch', 'A Hidden Drop', 'The path slopes sharply where the orchard ditch crosses it. Ruth stops when she sees the edge; her brother’s voice is close but still hidden by the fog.', [choice('back', 'Return to the wall and use the known gate route', 'home'), choice('call', 'Call the brother to stay still while you find the gate', 'farm')]),
    home: end('home', 'Both Children Home', 'You bring the children through the gate together. Their mother thanks you with a hot meal and a small lamp wick for your own lantern.'),
    farm: end('farm', 'A Lantern from the House', 'You fetch the farm lantern and guide both children along the fence. Their mother records your help in the parish book and pays the agreed coin.'),
  }, 'rescue/care'),

  story('the-telegraph-repair-car', 'The Telegraph Repair Car', 'A line crew must reach a storm-damaged pole before messages stop.', 'MODERATE', 'telegraph line and handcar', 'Protection means keeping the workers, repair parts, and the handcar safe while the line is inspected.', 'line', {
    line: largeScene('line', 'A Wire across the Track', 'A telegraph wire hangs low over the handcar track. The repair crew is waiting with a spare insulator and a ladder; the pole leans toward the road.', [choice('block', 'Use your Folding Trail Marker to stop carts before the wire', 'blocked', undefined, { items: ['foldingTrailMarker'] }), choice('gloves', 'Keep the crew back while checking the wire with gloves', 'inspect', undefined, { items: ['heavyLeatherGloves'] }), choice('send', 'Send a rider to the next station for a line closure', 'closed')]),
    blocked: largeScene('blocked', 'A Cart Approaches', 'A farm cart appears beyond the bend before the rider returns. The driver cannot see the wire; the crew is still clear of the pole.', [choice('signal', 'Signal the driver with your Roadside Signal Mirror', 'safe', undefined, { items: ['roadsideSignalMirror'] }), choice('wave', 'Wave from the track and keep the crew behind the bank', 'safe'), choice('move', 'Move the handcar across the track to block passage', 'damage')]),
    inspect: largeScene('inspect', 'A Live but Sagging Line', 'The wire is not broken, but the leaning pole could bring it down if the crew climbs now. The handcar can carry the parts to a second pole on firm ground.', [choice('second', 'Repair the line from the sound second pole', 'partial'), choice('tester', 'Use your Telegraph Line Tester from firm ground, then repair from the second pole', 'partial', { setFlags: ['telegraph_tester_confirmed_continuity'] }, { items: ['telegraphLineTester'] }), choice('pole', 'Brace the leaning pole and climb together', 'repair')]),
    closed: end('closed', 'The Line Is Closed', 'The next station closes the track and sends a second crew. The repair takes longer, but nobody passes beneath the sagging wire.'),
    safe: end('safe', 'A Clear Work Zone', 'The cart stops before the wire and the crew moves the handcar behind the bank. The pole is inspected after the road is closed.'),
    damage: end('damage', 'A Bent Handcar', 'The cart stops, but the handcar takes a wheel strike as it crosses the track. No one is hurt; the crew repairs the pole from the ground.'),
    partial: { ...end('partial', 'Messages Travel by Relay', 'The crew repairs the line from the firm pole and sends messages by handcar relay past the damaged section.'), textVariants: [{ requirements: { flags: ['telegraph_tester_confirmed_continuity'] }, text: 'Your Telegraph Line Tester confirms continuity from the sound pole, so the crew knows the circuit still reaches the next station. It does not make the leaning pole safe to climb. They repair from firm ground and relay messages past the damaged section.' }] },
    repair: end('repair', 'A Temporary Line', 'The crew braces the pole and replaces the insulator. The line works at reduced speed until a new pole arrives.'),
  }, 'labor/repair'),

  story('the-supper-wagon', 'The Supper Wagon', 'A relief kitchen’s supper must reach a work camp before the pass closes.', 'MODERATE', 'mountain pass and work camp', 'The Traveler must choose between keeping hot food, keeping the team rested, and reaching workers before weather closes the pass.', 'kitchen', {
    kitchen: largeScene('kitchen', 'A Covered Pot', 'The innkeeper loads supper into a covered wagon for a road crew trapped near the pass. One horse has a rubbed shoulder; the weather is turning, and the cook has a Weatherproof Blanket.', [choice('cover', 'Use the cook’s Weatherproof Blanket to cover the food and spare horse', 'pass'), choice('rest', 'Change the team and leave the food under the cook’s cover', 'delay'), choice('signal', 'Use your Farm Whistle to warn the camp before arrival', 'pass', undefined, { items: ['farmWhistle'] })]),
    pass: largeScene('pass', 'A Fallen Branch', 'A branch blocks the narrow pass. The wagon can be unloaded and carried through in baskets, but the spare horse is tiring.', [choice('food', 'Carry the food through first while the team rests', 'delivered'), choice('horse', 'Lead the tired horse back and ask the camp to collect supper', 'partial'), choice('clear', 'Use a Bridgewright’s Hammer to shift the branch', 'cleared', undefined, { items: ['bridgewrightHammer'], usableItems: ['bridgewrightHammer'] })]),
    delay: end('delay', 'A Rested Team', 'The team rests and the camp sends two workers with a handcart. Supper arrives cold but the horse is not made to pull through the pass.'),
    delivered: end('delivered', 'A Hot Meal, Late', 'The crew receives supper before the pass closes. The horse rests at the inn, and the innkeeper pays the agreed delivery fee.'),
    partial: end('partial', 'The Camp Comes Down', 'The workers meet the wagon at the lower road. The meal is shared there; the crew loses a little work time but the horse is spared.'),
    cleared: end('cleared', 'A Branch Shifted Safely', 'The hammer lets the crew move the branch without cutting it. The wagon passes slowly and reaches camp before the weather closes the route.'),
  }, 'labor/repair'),

  story('the-fence-at-the-fog-line', 'The Fence at the Fog Line', 'A traveling naturalist and two porters must carry a specimen jar through fog.', 'LOW', 'marsh path and field station', 'A fragile sample and a disoriented team make clear communication more valuable than speed.', 'marsh', {
    marsh: largeScene('marsh', 'A Jar in the Pack', 'Naturalist Dr. Kersey carries a sealed jar from a marsh station. The porters know the boardwalk, but fog has hidden the split where the path divides. The jar must stay upright.', [choice('mark', 'Use a Folding Trail Marker at the fork', 'fork', undefined, { items: ['foldingTrailMarker'] }), choice('rope', 'Keep the porters linked with a Travel Rope', 'linked', undefined, { items: ['travelRope'] }), choice('wait', 'Wait for the fog to thin before moving', 'wait')]),
    fork: largeScene('fork', 'Two Boardwalks', 'One boardwalk is dry but has a missing plank; the other is intact and longer. The specimen jar is still sealed, and the porters are steady.', [choice('long', 'Take the intact boardwalk and arrive late', 'safe'), choice('short', 'Cross the missing plank one at a time', 'partial')]),
    linked: largeScene('linked', 'A Porter Slips', 'One porter slips beside the boardwalk but catches the rail. The jar remains with Dr. Kersey; the safe path back is still visible.', [choice('help', 'Help the porter stand before moving the jar', 'safe'), choice('jar', 'Have Kersey move the jar while you help the porter', 'partial')]),
    wait: end('wait', 'The Fog Lifts', 'The party waits until the split is visible. The specimen arrives intact, and the naturalist records the marsh route for the next survey.'),
    safe: end('safe', 'The Jar Arrives Upright', 'The porters reach the field station without opening the jar. Dr. Kersey pays the agreed fee and explains the route marks to the next crew.'),
    partial: end('partial', 'A Slower, Careful Arrival', 'The group reaches the station with the porter shaken and the specimen intact. The naturalist delays the next survey until the boardwalk is repaired.'),
  }, 'travel/exploration'),

  story('the-lumber-crew-at-the-gully', 'The Lumber Crew at the Gully', 'A logging crew must move a saw and two workers across a washed-out gully.', 'HIGH', 'logging road and washed-out gully', 'A split rescue choice asks whether the Traveler protects people or expensive equipment first.', 'gully', {
    gully: largeScene('gully', 'A Broken Footbridge', 'A plank bridge has dropped into the gully. One worker is across with a leg injury; the crew’s two-person saw is on the near side. Water is rising but still shallow. The crew’s older folding stretcher is in their wagon; they offer it to you if you can bring their worker across safely.', [choice('worker', 'Use your Folding Field Stretcher to bring the worker across', 'rescue', undefined, { items: ['foldingFieldStretcher'] }), choice('crewStretcher', 'Borrow the crew’s stretcher to bring the worker across', 'rescue', { setFlags: ['borrowed_crew_stretcher'] }, { notItems: ['foldingFieldStretcher'] }), choice('rope', 'Rig your Travel Rope as a guide line before crossing', 'line', undefined, { items: ['travelRope'] }), choice('saw', 'Move the saw to high ground before the water rises', 'saw')]),
    rescue: largeScene('rescue', 'A Difficult Lift', 'The stretcher keeps the worker level, but the gully lip is narrow. The crew can pull from the far side if you keep the frame clear of the broken planks.', [choice('slow', 'Move slowly with the crew on both ends', 'workerSafe'), choice('acceptCrewStretcher', 'Use the crew’s stretcher, then accept it as their retired spare', 'workerSafe', { gainItems: ['foldingFieldStretcher'], historyFlags: ['received_folding_field_stretcher_from_lumber_crew'] }, { notItems: ['foldingFieldStretcher'] }), choice('alone', 'Lift the stretcher alone before water reaches it', 'strain')]),
    line: largeScene('line', 'A Line across the Cut', 'The rope holds on a sound tree, though one end is near the saw. The worker can cross if the crew keeps the line taut.', [choice('cross', 'Bring the injured worker across first', 'workerSafe'), choice('saw', 'Secure the saw before the water carries its case', 'saw')]),
    saw: end('saw', 'The Saw Is Saved', 'The saw reaches high ground, but the injured worker must wait for a second rope and more hands. The crew records the delay and your choice plainly.'),
    workerSafe: end('workerSafe', 'A Worker Reaches the Bank', 'The worker reaches the near bank and receives care. The saw is left on the far side until the water falls; the crew pays a reduced wage. If you accepted their retired stretcher, they mark it as yours before packing the wagon.'),
    strain: end('strain', 'A Painful Lift', 'The worker gets across, but you strain your back attempting the lift alone. The saw remains behind and the crew takes over the carry.'),
  }, 'rescue/care'),

  story('the-quiet-coffin-cart', 'The Quiet Coffin Cart', 'A family asks for help bringing a coffin through a steep lane before the funeral.', 'MODERATE', 'village lane and hillside chapel', 'A solemn escort protects dignity and a fragile load without adding a threat for excitement.', 'lane', {
    lane: largeScene('lane', 'A Wheel on the Slope', 'The hearse cart’s brake slips on the chapel lane. The family walks behind it; the coffin is secured but the road drops toward a stone wall.', [choice('rope', 'Use a Travel Rope as a second restraint line', 'brake', undefined, { items: ['travelRope'] }), choice('wedge', 'Use your Steel Wedge to hold the wheel at each pause', 'brake', undefined, { items: ['steelWedge'] }), choice('turn', 'Turn back to the level road and ask the chapel to delay', 'delay')]),
    brake: largeScene('brake', 'A Pause at the Wall', 'The cart stops at the wall. The family can walk the rest of the way beside it if the load is steadied; the chapel bell has not yet rung.', [choice('steady', 'Ask two family members to steady the cart while you guide it', 'arrived'), choice('unload', 'Unload the coffin and carry it up the final slope', 'carry')]),
    delay: end('delay', 'A Funeral Delayed', 'The family waits for a second cart with a sound brake. The service begins later, but the coffin is never put at risk.'),
    arrived: end('arrived', 'A Careful Arrival', 'The cart reaches the chapel at walking pace. The family thanks you quietly and gives you the agreed two-coin fee.'),
    carry: end('carry', 'Many Hands on the Hill', 'The family carries the coffin the last stretch together. It arrives safely, though the service starts late.'),
  }, 'social interaction'),

  story('the-silent-warehouse-shift', 'The Silent Warehouse Shift', 'A warehouse owner asks you to protect a night inventory until the clerk returns.', 'MODERATE', 'river warehouse and loading apron', 'A suspected theft becomes a fire and evacuation decision rather than a fight.', 'warehouse', {
    warehouse: largeScene('warehouse', 'A Smell of Hot Rope', 'The owner has left you with a lantern, a list, and three crates of lamp oil. A hot-rope smell comes from the loading apron; a watchman says he heard footsteps but saw no one.', [choice('list', 'Check the inventory list before moving anything', 'apron'), choice('lantern', 'Use your Lantern Guard while checking the loading apron', 'apron', undefined, { items: ['lanternGuard'] }), choice('watch', 'Ask the watchman to stay with the crates while you fetch help', 'help')]),
    apron: largeScene('apron', 'Smoke beneath the Canvas', 'A rope has smoldered against a crate corner. The oil remains sealed; the watchman is outside and the river door is open. A figure tries to leave with the inventory book.', [choice('water', 'Move the crates away from the ember before fetching water', 'evacuated'), choice('people', 'Get the watchman and clerk clear before touching the crates', 'evacuated'), choice('fight', 'Stop the figure only if they threaten the watchman', 'fight', { combat: { enemy: 'warehouse thief', winChance: 0.48, damageOnWin: 1, damageOnLoss: 4, winNext: 'evacuated', lossNext: 'pursuit' } })]),
    help: end('help', 'A Watch with Another Person', 'The clerk returns with the fire bucket. No crate is moved until the smell is traced; the owner pays you for the watch and the inventory remains sealed.'),
    evacuated: end('evacuated', 'No Fire Takes Hold', 'The ember is put out before the oil crates are endangered. The inventory clerk finds no missing goods and records the damaged canvas rope.'),
    pursuit: end('pursuit', 'The Figure Escapes', 'The figure leaves by the river door. You return to the crates before the fire spreads; the owner pays no pursuit bonus but keeps the goods safe.'),
    fight: end('fight', 'The Watchman Is Safe', 'The thief drops the inventory book and escapes through the river door. You keep the watchman clear while the clerk puts out the ember.'),
  }, 'labor/repair'),

  story('the-last-mile-of-the-medicine-wagon', 'The Last Mile of the Medicine Wagon', 'A medicine wagon reaches a washed bridge with a patient waiting beyond it.', 'HIGH', 'washed bridge and county road', 'The Traveler must choose whether to protect the medicine, the driver, or a stranded worker when the bridge fails.', 'bridge', {
    bridge: largeScene('bridge', 'A Missing Middle Plank', 'The medicine wagon stops before a bridge with one missing middle plank. A road worker is on the far side with a sprained ankle; the patient’s home is beyond the bridge.', [choice('worker', 'Call the worker to stay still while you find the side path', 'side'), choice('wagon', 'Keep the wagon and medicine on firm ground', 'load'), choice('cross', 'Use your Collapsible Sounding Rod to test the near span', 'test', undefined, { items: ['collapsibleSoundingRod'] })]),
    side: largeScene('side', 'The Side Path', 'The path is narrow but firm. It reaches the worker first, then joins the road below the bridge; the wagon cannot follow it.', [choice('help', 'Bring the worker down and send the medicine by another cart', 'split'), choice('leave', 'Leave the worker with a blanket and go for a cart', 'delayed')]),
    load: largeScene('load', 'The Medicine Can Travel', 'A farm cart can carry the medicine around the bridge, but the driver must stay with the original wagon. The patient may wait an hour.', [choice('transfer', 'Transfer the medicine to the farm cart', 'delivered'), choice('wait', 'Wait for the bridge crew to repair the span', 'delayed')]),
    test: end('test', 'A Span Not to Trust', 'The rod sounds hollow at the missing plank. You keep the wagon back; a farm cart takes the medicine by the lower road.'),
    split: end('split', 'Worker First, Medicine Next', 'The worker reaches the road and the medicine is sent in a second cart. Both arrive, though the patient waits and the escort wage is reduced.'),
    delayed: end('delayed', 'A Longer Route', 'The worker is kept warm while another cart is fetched. The medicine arrives late but the bridge is not used.'),
    delivered: end('delivered', 'The Medicine Gets Through', 'The farm cart takes the medicine to the patient. The driver stays with the wagon and road crew; the owner pays the agreed delivery fee.'),
  }, 'rescue/care'),

  story('the-watch-at-the-sheepfold', 'The Watch at the Sheepfold', 'A shepherd asks for help guarding a lambing fold during a night of strange calls.', 'MODERATE', 'stone sheepfold and ridge pasture', 'The tension is grounded in animal behavior and uncertain sounds; protection means not opening the fold in panic.', 'fold', {
    fold: largeScene('fold', 'A Call beyond the Wall', 'The ewes are quiet inside the stone fold. A call comes from the ridge, then repeats nearer. The shepherd’s dog refuses to leave the gate; there are no tracks in the damp soil.', [choice('stay', 'Keep the gate shut and watch for a real approach', 'approach'), choice('lamp', 'Use your Lantern Guard to shield the fold lamp from wind', 'approach', undefined, { items: ['lanternGuard'] }), choice('answer', 'Answer the call with your Farm Whistle', 'response', undefined, { items: ['farmWhistle'] })]),
    approach: largeScene('approach', 'A Shape at the Wall', 'A lamb presses against the far stones. The call comes again, but the dog’s ears turn toward the creek rather than the ridge.', [choice('lamb', 'Check the lamb from inside the fold', 'safe'), choice('creek', 'Stay with the flock while the shepherd checks the creek', 'creek')]),
    response: largeScene('response', 'The Whistle Answers Back', 'A second whistle answers from the lower pasture. The neighboring shepherd is checking a loose ewe; the call was a signal, not a threat.', [choice('open', 'Open the gate only when the neighbor reaches it', 'safe'), choice('wait', 'Keep the flock enclosed until daylight', 'dawn')]),
    safe: end('safe', 'The Fold Holds', 'The lamb is returned to its mother and the neighbor secures the loose ewe. The shepherd pays the watch wage and leaves the flock enclosed for the night.'),
    creek: end('creek', 'An Animal at the Water', 'The call came from the neighbor’s ewe at the creek. The flock stays behind the wall while the animal is brought back.'),
    dawn: end('dawn', 'No One Opens the Gate in Fear', 'The flock stays enclosed until daylight. The shepherd loses sleep but no animal wanders into the dark.'),
  }, 'animals'),

  story('the-broken-axle-relay', 'The Broken Axle Relay', 'A road crew must move a replacement axle and keep its injured driver warm.', 'HIGH', 'winter road and repair shed', 'A split priority forces the Traveler to delegate or choose between equipment delivery and immediate care.', 'shed', {
    shed: largeScene('shed', 'A Driver beside the Axle', 'A replacement axle is ready at the shed. The driver has fallen and may have a broken wrist; the repair crew waits two miles away with a wagon that cannot move without the part.', [choice('driver', 'Stabilize the driver and send a runner with the axle news', 'care'), choice('axle', 'Use your Folding Carriage Jack to load the axle onto the cart', 'load', undefined, { items: ['foldingCarriageJack'] }), choice('ask', 'Ask the driver which task he wants handled first', 'delegated')]),
    care: largeScene('care', 'Warmth before the Road', 'The driver is conscious and can walk with support. The axle cart can still leave if another worker takes the reins.', [choice('stay', 'Stay with the driver until the doctor arrives', 'careDone'), choice('send', 'Send the axle cart while you walk with the driver', 'both')]),
    load: largeScene('load', 'The Cart Is Ready', 'The axle is secured, but the driver is alone beside the cold shed. A passing teamster offers to take him to the doctor.', [choice('teamster', 'Accept the teamster’s help and escort the axle', 'both'), choice('stay', 'Leave the axle for a second cart and stay with the driver', 'careDone')]),
    delegated: end('delegated', 'The Driver Chooses', 'The driver asks you to send the axle and accept the teamster’s help for his wrist. Both needs are met, though neither arrives first.'),
    careDone: end('careDone', 'A Warm Room', 'The driver reaches the repair shed’s warm room. The crew waits for another axle cart and you receive no delivery wage.'),
    both: end('both', 'Two Useful Arrivals', 'The driver reaches the doctor and the axle reaches the crew. The repair starts late; the foreman pays a smaller wage for the divided delay.'),
  }, 'rescue/care'),
];
