import type { Scenario } from '../types';

export const THE_FALLEN_TREE: Scenario = {
  id: 'the-fallen-tree', title: 'The Fallen Tree', subtitle: 'A road obstruction hides a more urgent problem.', startScene: 'roadBlocked',
  timePhases: [{ id: 'afternoon', label: 'Late Afternoon', atMinutes: 0 }, { id: 'dusk', label: 'Dusk', atMinutes: 15 }, { id: 'dark', label: 'Dark Road', atMinutes: 30 }],
  runRandomSelections: [{ id: 'driver', values: ['Osmia', 'Harlan', 'Dov', 'Pruett', 'Nella'].map((value) => ({ value })) }],
  scenes: {
    roadBlocked: { id: 'roadBlocked', title: 'A Tree Across the Road', tone: 'warning', text: 'A broad tree has fallen across the road. Its trunk rests on the uphill bank; branches cover the downhill ditch. No wagon or person is visible beyond it. As you approach from firm ground, you hear a faint call from under the lower branches.', choices: [
      { id: 'lookUnderBranches', label: 'Call out and inspect the branches', hint: 'Stay clear of the trunk until you know what is beneath it.', timeCost: 2, next: 'driverPinned', effects: { knowledge: ['A cart driver is pinned by a branch below the fallen tree.'] } },
      { id: 'goForHelp', label: 'Walk to the farm for help', hint: 'The road remains blocked, but you stay clear of the trunk.', timeCost: 12, next: 'farmHelp' },
      { id: 'turnBack', label: 'Turn back and use the east road', hint: 'The detour is long but avoids the unstable tree.', timeCost: 25, next: 'detourEnding' },
    ] },
    driverPinned: { id: 'driverPinned', title: 'A Driver Beneath a Limb', tone: 'danger', text: 'The trapped driver answers to the name {{driver}}. They are pinned at the lower ditch edge by a heavy branch across one leg. The cart is beyond the tree, and its horse stands loose on the far shoulder. The trunk is still settling against the uphill bank; lifting beneath it could make the whole tree roll.', choices: [
      { id: 'callToDriver', label: 'Keep {{driver}} still and call for help', hint: 'You stay outside the branches while someone goes for a team.', timeCost: 8, next: 'farmHelp', effects: { historyFlags: ['called_help_for_pinned_driver'] } },
      { id: 'useWedgeAndLever', label: 'Raise the branch with a wedge and lever', hint: 'A wedge or hammer may steady the small limb; the trunk itself is too large to move.', requirements: { anyItems: ['steelWedge', 'bridgewrightHammer', 'foldingPryTool'] }, timeCost: 3, chance: { probability: 0.67, lateProbability: 0.49, lateAfterMinutes: 15, bonusItems: ['steelWedge', 'bridgewrightHammer', 'foldingPryTool'], bonusProbability: 0.14, successNext: 'driverFree', failureNext: 'treeShifts', successMessage: 'The small limb rises enough for {{driver}} to pull free.', failureMessage: 'The branch rolls toward the trunk. You spring clear, but {{driver}} remains pinned.' } },
      { id: 'liftByHand', label: 'Try to lift the branch by hand', hint: 'It is heavy, and the trunk above is still settling. You could be crushed.', timeCost: 2, chance: { probability: 0.38, lateProbability: 0.24, lateAfterMinutes: 15, bonusItems: ['heavyLeatherGloves', 'freightmansStrap'], bonusProbability: 0.1, successNext: 'driverFree', failureNext: 'treeShifts', successMessage: 'The branch rises briefly; {{driver}} slides free.', failureMessage: 'The limb shifts back while you are beneath it.', failureEffects: { health: -5, historyFlags: ['risked_life_under_fallen_tree'] } } },
      { id: 'leavePinnedDriver', label: 'Back away and leave for help', next: 'detourEnding', effects: { historyFlags: ['left_pinned_driver_for_help'] } },
    ] },
    treeShifts: { id: 'treeShifts', title: 'The Trunk Settles', tone: 'danger', text: 'The branch has dropped lower and the trunk groans against the uphill bank. You are on firm road, clear of its fall path. {{driver}} is still trapped but answering. More force from directly beneath the tree may kill you.', choices: [
      { id: 'getTeamHelp', label: 'Run for the farm team and lifting gear', timeCost: 10, next: 'farmHelp' },
      { id: 'tryWedgeNow', label: 'Set a wedge from the ditch edge', requirements: { anyItems: ['steelWedge', 'bridgewrightHammer', 'foldingPryTool'] }, hint: 'Work from outside the trunk’s fall path; if it rolls, get clear.', timeCost: 2, chance: { probability: 0.56, lateProbability: 0.37, lateAfterMinutes: 20, bonusItems: ['steelWedge', 'bridgewrightHammer'], bonusProbability: 0.12, successNext: 'driverFree', failureNext: 'driverLost', successMessage: 'The wedge holds the branch long enough for {{driver}} to crawl out.', failureMessage: 'The branch settles across the ditch before {{driver}} can move.' } },
      { id: 'workUnderTrunk', label: 'Try to lift the settling trunk yourself', hint: 'The trunk is rolling toward you; it could crush you outright.', timeCost: 1, chance: { probability: 0.18, lateProbability: 0.08, lateAfterMinutes: 15, successNext: 'driverFree', failureNext: 'playerDies', successMessage: 'You lift the trunk just long enough for {{driver}} to roll clear.', failureMessage: 'The trunk rolls down the bank before you can escape.' } },
      { id: 'retreatTree', label: 'Retreat to the east road', next: 'detourEnding', effects: { historyFlags: ['retreated_from_fallen_tree'] } },
    ] },
    farmHelp: { id: 'farmHelp', title: 'Help from the Farm', tone: 'warning', text: 'Two farmhands arrive with a fence rail and a small lifting jack. They keep everyone outside the trunk’s fall path. {{driver}} is still conscious, but the pinned leg is swelling.', choices: [
      { id: 'jackBranch', label: 'Use the jack on the branch, not the trunk', hint: 'The farmhands brace the rail while you guide {{driver}} clear.', timeCost: 4, chance: { probability: 0.78, lateProbability: 0.59, lateAfterMinutes: 20, successNext: 'driverFree', failureNext: 'driverLost', successMessage: 'The branch rises and {{driver}} crawls to the clear road.', failureMessage: 'The jack slips from the muddy ground; the limb settles before anyone is hurt.' } },
      { id: 'waitForSaw', label: 'Wait for a saw team from the village', timeCost: 12, next: 'driverLost' },
      { id: 'chooseDetour', label: 'Leave the work to the farmhands', next: 'detourEnding' },
    ] },
    driverFree: { id: 'driverFree', title: 'Clear of the Branch', tone: 'safe', ending: 'success', choices: [], text: '{{driver}} is clear and the farmhands splint the injured leg. The tree remains across the road; no one tries to move its trunk without a proper team.' },
    driverLost: { id: 'driverLost', title: 'The Branch Settles', tone: 'warning', ending: 'success', choices: [], text: 'The branch settles across the ditch before {{driver}} can be freed. The farmhands stay with them and send for the village saw team. You remain clear of the trunk.' },
    detourEnding: { id: 'detourEnding', title: 'The East Road', tone: 'safe', ending: 'success', choices: [], text: 'You take the east road around the obstruction. The fallen tree remains dangerous, and the driver’s outcome is left to the people already seeking help.' },
    playerDies: { id: 'playerDies', title: 'Under the Trunk', tone: 'danger', ending: 'death', choices: [], text: 'The trunk rolls from the bank while you work below it. The farmhands reach {{driver}}, but cannot pull you clear.' },
  },
};
