import type { FrontierCard } from './frontierDiscoveryTools';
import { frontierAdventure } from './frontierDiscoveryTools';
import { largeScene } from './largeContentTools';
import type { Scenario, Scene } from '../types';

const cards: FrontierCard[] = [
  { id: 'roof-through-the-trees', title: 'The Roof Through the Trees', subtitle: 'A repaired cabin may not be as empty as it looks.', shape: 'occupant', risk: 'LOW', setting: 'remote forest cabin', hook: 'A newer window repair and undisturbed dust make an apparently abandoned cabin uncertain.', opening: 'From the old timber road you see a roof deep between the pines. The cabin looks neglected, but one window has a fresh board and the track to its door is hard to read.', clue: 'Inside, most surfaces wear a grey film. One chair is clean, a cup has a dry ring beneath it, and the newer window board is nailed from outside. Nothing proves who last used the cabin.', turn: 'You can watch the cabin from the tree line or enter no farther than the common room.', cautious: 'Watch from the tree line for a while', bold: 'Look through the repaired window', leave: 'Return to the timber road', insight: 'A cabin in disrepair had a recently repaired window and signs of limited use.' },
  { id: 'camp-with-fresh-ashes', title: 'The Camp with Fresh Ashes', subtitle: 'The fire is cold, but the camp does not feel finished.', shape: 'occupant', risk: 'MODERATE', setting: 'remote prospecting camp', hook: 'Fresh ash and fresh food contradict the camp’s weathered tools.', opening: 'A prospecting camp stands below the trail. Its canvas is down and its tools are rusted, but a fire pit holds pale ash with one charcoal edge still black; a wrapped heel of bread lies under a tin.', clue: 'Bootprints leave the camp toward the creek, but none return. The bread is yesterday’s at most, and the cold fire has been covered carefully rather than abandoned in haste.', turn: 'Someone may be nearby or may mean to return. The trail down to the road remains open.', cautious: 'Wait where the camp can be watched', bold: 'Follow the prints toward the creek', leave: 'Leave the camp undisturbed', insight: 'A weathered prospecting camp had recently tended ashes and food set aside.' },
  { id: 'floorboard-that-was-replaced', title: 'The Floorboard That Was Replaced', subtitle: 'One repair in a derelict cabin is newer than the rest.', shape: 'salvage', risk: 'LOW', setting: 'remote cabin', hook: 'A newer floorboard signals a hidden object but does not settle ownership.', opening: 'An old cabin stands open beside the trail. One floorboard is pale and square-edged among warped dark planks; the roof leaks over the far wall, not over it.', clue: 'The board is fastened with newer nails, but it is not loose. A narrow seam shows a paper edge below. The cabin has no name or claim mark, and its empty appearance is not proof that the compartment is yours.', turn: 'The board can be lifted slowly, left intact, or marked for someone with a clearer claim.', cautious: 'Read the paper edge without lifting the board', bold: 'Pry up the replaced board', leave: 'Leave the floor untouched', insight: 'A newer floorboard concealed papers in an unmarked cabin; ownership remained unclear.' },
  { id: 'forgotten-sluice', title: 'The Forgotten Sluice', subtitle: 'An old channel still carries water through a placer camp.', shape: 'trace', risk: 'MODERATE', setting: 'creekside placer workings', hook: 'A working-looking water diversion reveals how an old claim used the creek.', opening: 'A shallow ditch leaves the creek and bends behind alder trees. Beyond it stands a weathered sluice box. The main trail stays on firm ground beside the water.', clue: 'The ditch stones are old, but one gate board is newer and the channel has been cleared of leaves. There is no paper claim marker; someone may still use the water.', turn: 'The small gate can be examined without blocking the creek. Changing it would affect the channel downstream.', cautious: 'Inspect the gate and water marks', bold: 'Open the sluice and test its flow', leave: 'Leave the watercourse as it is', insight: 'An old placer sluice had a recently cleared channel and a newer gate board.' },
  { id: 'the-mule-trail', title: 'The Mule Trail', subtitle: 'Old pack marks leave the road and climb toward a hidden shelf.', shape: 'trace', risk: 'MODERATE', setting: 'mountain pack trail', hook: 'Pack-animal signs lead to a route and the history of a failed supply run.', opening: 'A narrow track leaves the road and climbs between two rock shoulders. Old mule shoes mark the dirt; a broken strap lies near the fork, while the broad road remains in sight behind you.', clue: 'Farther up, the track passes a dropped tin cup and a split crate. The load was set down rather than scattered by a fall; from here a narrow return path descends to the road.', turn: 'A shelf above the trail may explain the abandoned load, but the climb is loose.', cautious: 'Study the load marks from the trail', bold: 'Climb to the shelf above the crates', leave: 'Mark the fork and return to the road', insight: 'An old mule trail carried a supply load to a shelf above the main road.' },
  { id: 'the-prospectors-map', title: 'The Prospector’s Map', subtitle: 'A working map marks water and hazards, not promised treasure.', shape: 'trace', risk: 'MODERATE', setting: 'mountain trail', hook: 'A map’s practical annotations let the traveler choose whether to follow an unexplained mark.', opening: 'A map case lies open under a trail marker, weighted by a stone. The hand-drawn sheet shows a spring, two camps, loose ground, and a circle without a label. No name appears on the case.', clue: 'The spring and camp marks match the country around you. A penciled note warns that the eastern slope sheds rock after rain; the unexplained circle lies beyond it.', turn: 'The circle may be a work site, a boundary, or nothing useful. The safer route returns to the road.', cautious: 'Copy the useful water and hazard marks', bold: 'Follow the map toward the circle', leave: 'Leave the map where you found it', insight: 'A prospector’s map marked a spring and rockfall slope; its unlabelled circle was unverified.' },
  { id: 'empty-assay-office', title: 'The Empty Assay Office', subtitle: 'A ledger and an arriving claimant complicate an empty office.', shape: 'claim', risk: 'MODERATE', setting: 'remote assay shack', hook: 'An office ledger and a stranger’s uncertain claim put custody of records at stake.', opening: 'The assay shack door stands open. Scales, sample jars, and a ledger remain on the desk; a locked drawer is set into the wall. A traveler arrives behind you and says the office belonged to her late employer.', clue: 'The ledger names two partners, but the last page is torn. The stranger knows the drawer’s keyhole is new and says she came to collect samples, not the book. Neither fact proves who may take the records.', turn: 'The desk is dry and the door can be left open. You can compare marks, let the stranger look, or keep out of the drawer.', cautious: 'Read the partnership entries aloud', bold: 'Ask the stranger to identify a sample mark', leave: 'Step outside and leave custody unsettled', insight: 'An assay ledger listed two partners; a visitor claimed authority to collect samples but not the book.' },
  { id: 'cabin-with-two-locks', title: 'The Cabin with Two Locks', subtitle: 'A broken old lock and a new one tell different stories.', shape: 'occupant', risk: 'MODERATE', setting: 'remote cabin', hook: 'Two generations of locks complicate whether a cabin is abandoned or occupied.', opening: 'A cabin at the end of a faint trail has a rusted hasp hanging open and a newer padlock through a second staple. Split wood is stacked beneath the eave, but no smoke rises.', clue: 'The new lock bears fresh scratches around its keyway. Behind the cabin, one narrow set of bootprints approaches and then turns back toward the ridge.', turn: 'Someone may be keeping others out, or may have lost the key. You can wait, examine the tracks, or leave.', cautious: 'Follow the bootprints only to the ridge', bold: 'Wait nearby for the lock’s user', leave: 'Turn back without touching either lock', insight: 'A remote cabin had an old broken hasp, a newer lock, stacked wood, and a recent visitor.' },
  { id: 'gold-dust-in-the-floorboards', title: 'The Gold Dust in the Floorboards', subtitle: 'A glittering trace is evidence, not a promise.', shape: 'salvage', risk: 'MODERATE', setting: 'old mining cabin', hook: 'Gold dust may indicate recent work, hidden storage, or careless handling.', opening: 'A cabin floor catches light in a thin line of yellow grit. The dust is concentrated beside a stove leg; the rest of the room is bare, and the nearest creek is a long walk downhill.', clue: 'A pan-shaped stain marks the boards, but there is no loose seam or visible cache. The dust could have fallen from a pocket, a sample, or repeated work at the stove-side table.', turn: 'Opening the floor would damage the cabin and may reveal nothing. You can record the trace or search carefully around the stove.', cautious: 'Brush the grit into a paper fold as evidence', bold: 'Lift the board beside the stove', leave: 'Leave the floor undisturbed', insight: 'Gold dust on a cabin floor traced to a work stain, not a confirmed cache.' },
  { id: 'the-old-hoist', title: 'The Old Hoist', subtitle: 'A rusted platform still hangs above a mine shaft.', shape: 'hazard', risk: 'HIGH', setting: 'abandoned mine shaft', hook: 'A working hoist is not necessarily safe enough to carry a person.', opening: 'A rusted hoist stands over a timbered shaft. Its platform hangs several feet below the rim; one cable strand is broken and the brake lever does not catch on its first test. A stone stair descends along the wall.', clue: 'The cable is frayed where it bends over the pulley. The stair has fallen in at the bottom, but the upper steps are firm and a marked route back to daylight remains behind you.', turn: 'The hoist could move equipment, but trusting it with a person would put the broken cable under full weight.', cautious: 'Mark the shaft and inspect from the rim', bold: 'Test the hoist with a loose timber', leave: 'Withdraw before the rim crumbles', insight: 'The old mine hoist had a frayed cable and unreliable brake; the stair was partly collapsed.' , danger: 0.54 },
  { id: 'camp-below-the-slide', title: 'The Camp Below the Slide', subtitle: 'A buried camp remains reachable while the slope keeps shifting.', shape: 'hazard', risk: 'HIGH', setting: 'landslide gulch', hook: 'The player must limit salvage beneath a visibly unstable slope.', opening: 'A landslide has buried half a work camp. The exposed cookhouse and tool shed sit below a cracked slope; a fresh pebble run crosses the old path. You stand on firm ground above the slide.', clue: 'A tent pole and a locked chest remain visible near the buried wall. Small stones keep ticking down the face. There is a broad route back to the ridge, but no safe way to hold the slope in place.', turn: 'Each trip below the crack crosses the same moving ground. The visible tools may be worth less than a clean retreat.', cautious: 'Take only the loose tool at the edge', bold: 'Reach for the chest near the buried wall', leave: 'Return to the ridge now', insight: 'A landslide-buried camp still shed stones; its exposed edge was safer than the buried wall.' , danger: 0.49 },
  { id: 'the-hidden-tailings-pile', title: 'The Hidden Tailings Pile', subtitle: 'Brush covers discarded rock beside an old claim.', shape: 'claim', risk: 'MODERATE', setting: 'old placer claim', hook: 'Covered tailings could hide ore, evidence, or a reason someone concealed the work.', opening: 'Brush has been laid in neat layers over a low pile beside an abandoned claim. The main workings are open to view; a narrow track skirts the covered mound and returns to the road.', clue: 'Under one branch lie pale crushed stones and a broken assay bottle. The brush is fresh enough to bend, but no tracks show whether it was placed to hide ore or keep rain off the samples.', turn: 'Uncovering the pile may disturb another worker’s evidence. You can compare a few stones, replace the brush, or expose more.', cautious: 'Inspect one exposed stone and replace the brush', bold: 'Clear the whole pile', leave: 'Leave the covering in place', insight: 'A brushed-over tailings pile held assay fragments; its purpose and ownership were uncertain.' },
  { id: 'the-old-claim-cabin', title: 'The Old Claim Cabin', subtitle: 'Worn tools and careful repairs tell a life without explaining its end.', shape: 'trace', risk: 'LOW', setting: 'remote claim cabin', hook: 'A quiet cabin visit reconstructs a working life from repairs and tool wear, not a mystery twist.', opening: 'A small claim cabin stands open on a shelf above the creek. The stove is cold, the door swings freely, and no tracks are fresh. You see a repaired boot, a tool sharpened down almost to its handle, and a table worn smooth on one side.', clue: 'A line of notches on the doorframe marks seasons, not height. The repaired boot is child-sized; the table has one place set close to the window that faces the old trail.', turn: 'The room suggests someone kept working and expected a smaller visitor. No letter explains who they were.', cautious: 'Record the marks and leave the room intact', bold: 'Search the drawers for a name', leave: 'Close the door and continue', insight: 'The old claim cabin showed years of work and a child’s visits, but no certain account of the family.', boldEndingTitle: 'A Family Still Unnamed', boldEndingText: 'Your search leaves the family unnamed. The repaired boot and worn tools suggest a life remembered through its work, but not who made them.' },
  { id: 'the-claim-with-no-name', title: 'The Claim with No Name', subtitle: 'Fresh work sits where no marker or paperwork can be found.', shape: 'claim', risk: 'MODERATE', setting: 'remote creek claim', hook: 'Recent labor without markers creates an ownership question without a simple verdict.', opening: 'A creek cut shows recent shovel work, but there is no claim stake, sign, or cabin. A narrow boot track leaves the cut upstream; the public trail remains visible below.', clue: 'The gravel is washed into neat ridges, and a new plank spans a small runnel. No name or ownership mark appears on the tools left beside it.', turn: 'The work is too recent to call forgotten, but the site offers no clear claimant. You can note the location, wait, or take a loose pan left on the bank.', cautious: 'Mark the site and wait at a distance', bold: 'Try the loose pan in the shallows', leave: 'Leave without disturbing the work', insight: 'A recently worked creek cut had no visible claim markers or owner’s name.' },
  { id: 'the-broken-rocker-box', title: 'The Broken Rocker Box', subtitle: 'A creekside machine can be repaired, salvaged, or left for its owner.', shape: 'salvage', risk: 'LOW', setting: 'placer creek', hook: 'A damaged rocker box shows tool wear and recent use, making its ownership uncertain.', opening: 'A wooden rocker box rests beside a creek. One handle is split; the riffle tray is clean of mud, and fresh bootprints end at the water. A small repair patch lies nearby.', clue: 'The patch fits the broken handle but was never nailed on. The machine is not valuable enough to explain a claim by itself, yet someone likely meant to return.', turn: 'You can study the repair and leave a note-like marker, try the box briefly, or carry off the loose iron plate.', cautious: 'Fit the patch to see what failed', bold: 'Rock the box with the split handle', leave: 'Leave the repair pieces together', insight: 'A creekside rocker box had a recent unfinished repair and signs of intended return.' },
  { id: 'the-rusted-safe', title: 'The Rusted Safe', subtitle: 'A heavy safe sits where the floor is giving way.', shape: 'hazard', risk: 'HIGH', setting: 'collapsing claim office', hook: 'The prize is unknown and the floor visibly fails beneath the safe.', opening: 'A small office has slumped toward the creek. A rusted safe sits over a bowed floor joist; cracks run from its feet toward a hole beneath the wall. The doorway and solid ground are behind you.', clue: 'The safe door is shut, but the lock plate is pitted and no handle remains. Dust has fallen through the floor gap; shifting the safe would load the weakest part of the room.', turn: 'No record says what the safe holds. You can inspect the joists from the doorway, try the lock without moving it, or retreat.', cautious: 'Check the joist from solid ground', bold: 'Try the lock without shifting the safe', leave: 'Back out of the office', insight: 'A rusted safe stood over a failing floor; its contents were unknown.' , danger: 0.52 },
  { id: 'the-cache-under-the-stove', title: 'The Cache Under the Stove', subtitle: 'A hidden compartment looks stored, not forgotten.', shape: 'salvage', risk: 'MODERATE', setting: 'remote cabin', hook: 'A deliberate cache makes taking useful supplies a real ownership choice.', opening: 'A cabin’s stove has been moved just enough to expose a fitted tin beneath it. The tin is dry, the stove legs leave an older dust outline, and no one is visible along the trail.', clue: 'Inside are two coins, two sealed papers, and a small tool wrapped in oilcloth. The wrapper bears initials; the coins are counted in a column on the top paper.', turn: 'This is stored property, not random debris. You can put it back, carry the papers to a nearby settlement, or take what you can use.', cautious: 'Read the top paper and restore the tin', bold: 'Take the two coins and leave the papers', leave: 'Close the compartment untouched', insight: 'A cabin cache was deliberately stored and included initials and a written coin count.', boldRisk: false, cautiousEndingTitle: 'The Cache Marked for Return', cautiousEndingText: 'You read the count, restore the tin beneath the stove, and mark where it was found. The coins, papers, and wrapped tool remain together for whoever stored them.', boldEndingTitle: 'The Coins Leave with You', boldEndingText: 'You take the two counted coins and leave the papers and tool wrapped as you found them. The cache was deliberately stored, and its initials may still identify an owner.', boldEffects: { money: 2, historyFlags: ['took two coins from an identified cache beneath a cabin stove'] } },
  { id: 'the-washed-out-claim', title: 'The Washed-Out Claim', subtitle: 'Floodwater has exposed a worksite beneath unstable ground.', shape: 'hazard', risk: 'HIGH', setting: 'flooded creek claim', hook: 'A retreat window narrows as floodwater reveals old workings.', opening: 'The creek has cut away a bank and exposed old timbers, a shovel, and a dark opening. Water is still rising against the lower stones; the path back follows the higher bank behind you.', clue: 'A waterline climbs the exposed timber. One tool is caught above it, while the lower boards shift whenever the current surges. Nothing shows whether the mine is safe beyond the entrance.', turn: 'The higher path remains dry for now. Going below the fresh cut risks being trapped by the same water that revealed it.', cautious: 'Take the loose shovel from high ground', bold: 'Step down to inspect the exposed opening', leave: 'Use the high bank to retreat', insight: 'Floodwater exposed old workings at a claim while the waterline continued to rise.' , danger: 0.46 },
  { id: 'the-old-dredge', title: 'The Old Dredge', subtitle: 'A half-submerged machine shifts against its moorings.', shape: 'hazard', risk: 'HIGH', setting: 'remote river bend', hook: 'Salvage from a partly submerged dredge competes with current and shifting iron.', opening: 'A small dredge sits half underwater at a river bend, tied to the bank by two chains. The upstream chain is taut; the downstream one knocks against a timber post. A gravel path returns to the road.', clue: 'The deck tilts whenever the current catches the bucket chain. A tool locker is open and empty; a ledger box remains bolted near the cabin door, above the water for the moment.', turn: 'The river is rising and the deck is not level. The ledger box can be read from the bank only if the machine holds still.', cautious: 'Read the box markings from the bank', bold: 'Step aboard and reach the ledger box', leave: 'Leave the dredge to the river', insight: 'A half-submerged dredge held a bolted ledger box above a rising river.' , danger: 0.51 },
  { id: 'the-derelict-stamp-mill', title: 'The Derelict Stamp Mill', subtitle: 'One stripped room and one untouched mechanism tell different stories.', shape: 'hazard', risk: 'HIGH', setting: 'abandoned stamp mill', hook: 'Heavy machinery and selective stripping reveal recent salvage without requiring combat.', opening: 'The stamp mill stands silent beside a cut bank. The near room is stripped to bolt holes; behind it, a narrow plank floor leads to a bank of heavy stamps still hanging above the ore trough.', clue: 'Fresh wrench marks shine on two empty mounts. The remaining machine is held by old pins, and the plank floor creaks in the same place each time you shift your weight.', turn: 'You could learn how the mill was laid out from the doorway. Removing a part would mean standing beneath the suspended stamps.', cautious: 'Sketch the mill from the doorway', bold: 'Inspect the hanging pins up close', leave: 'Step back onto solid ground', insight: 'The stamp mill had been selectively stripped; its remaining pins and floor were unsafe to approach.' , danger: 0.49 },
  { id: 'survey-stakes-are-wrong', title: 'The Survey Stakes Are Wrong', subtitle: 'Two lines of stakes disagree, and the creek has moved.', shape: 'claim', risk: 'LOW', setting: 'creekside property boundary', hook: 'Survey evidence is complicated by changed terrain rather than an automatic fraud reveal.', opening: 'Two rows of survey stakes cross a creek meadow. The older stakes follow a dry channel; the newer row cuts through it. The creek now runs between the two lines.', clue: 'The older stakes carry faded cuts; the newer ones have a uniform notch but no date. A washed-out bank shows the creek moved since the first line was set.', turn: 'Both surveys describe ground that no longer looks the same. One row may be wrong without being dishonest.', cautious: 'Copy both stake lines onto a rough sketch', bold: 'Follow the old channel to its source', leave: 'Leave the boundary question to the neighbors', insight: 'Two survey lines followed different courses, and creek erosion could explain part of the change.' },
  { id: 'the-forgotten-powder-shed', title: 'The Forgotten Powder Shed', subtitle: 'An old warning sign is easier to read than the corroded latch.', shape: 'hazard', risk: 'HIGH', setting: 'remote mine site', hook: 'The danger is recognizing old blasting materials and refusing unsafe handling.', opening: 'A low stone shed stands apart from the mine. A faded warning mark remains over the door; through a gap you can see corroded tins and dry straw. A clear path leads back to the open hillside.', clue: 'The tins are swollen and rusted, and the straw is packed around them. You cannot tell what remains inside; moving or opening them would be unsafe.', turn: 'No salvage is worth testing the contents. You can mark the shed for an experienced crew or leave without disturbing it.', cautious: 'Mark the shed and warn the nearest camp', bold: 'Look for a label through the wall gap', leave: 'Withdraw without touching the latch', insight: 'A remote powder shed still held corroded containers that should not be handled.' , danger: 0.47 },
  { id: 'the-creek-diversion', title: 'The Creek Diversion', subtitle: 'A small channel bends uphill where no natural water would go.', shape: 'trace', risk: 'MODERATE', setting: 'wooded creek diversion', hook: 'Simple water engineering reveals a hidden worksite and its purpose.', opening: 'A narrow channel leaves the creek and runs uphill through the woods. Stone edges keep it straight across the slope; the main trail crosses below and remains easy to find.', clue: 'The channel ends at a dry settling pond behind a ridge. There are fresh shovel cuts in one bank and old sluice boards at the other, but no camp or current worker is visible.', turn: 'The diversion may have served a claim or a mill. Following the stone line is safer than walking the cut bank.', cautious: 'Trace the channel from its upper edge', bold: 'Climb over the ridge to the pond', leave: 'Mark where it leaves the creek and go', insight: 'A stone-lined diversion carried creek water to a dry settling pond behind the ridge.' },
  { id: 'locked-strongbox-in-the-ruins', title: 'The Locked Strongbox in the Ruins', subtitle: 'A lock does not say who owns what is inside.', shape: 'salvage', risk: 'MODERATE', setting: 'remote stone ruin', hook: 'A locked box in a ruin creates a choice about ownership before contents are known.', opening: 'A stone storehouse has collapsed on one side. A small strongbox remains beneath a shelf, still locked; a name is scratched under its handle, and the doorway is clear.', clue: 'The name matches no marker nearby. The box has not been forced, and dry dust lies unbroken around it. It could belong to the former storekeeper or to someone who placed it here later.', turn: 'Opening it would destroy the lock and leave no way to return it sealed. You may record the name, pry it, or walk away.', cautious: 'Copy the name and leave the box sealed', bold: 'Pry the strongbox open', leave: 'Leave the ruins as they stand', insight: 'A sealed strongbox in a ruin bore a name but no proof of present ownership.' },
  { id: 'the-broken-gate', title: 'The Broken Gate', subtitle: 'A remote claim gate was forced, but the marks do not say why.', shape: 'claim', risk: 'MODERATE', setting: 'remote claim entrance', hook: 'Fresh damage at a gate could be sabotage, emergency entry, or an owner’s return.', opening: 'A timber gate blocks a claim road. One hinge is split outward; the latch is bent inward. Beyond it, the track divides toward the cabin and the creek cut.', clue: 'A wheel rut crosses the gate line, but there are bootprints in both directions. A broken medicine bottle lies near the hinge, while a fresh repair wedge rests on the cabin side.', turn: 'The gate was forced and then partly repaired. The marks do not identify who did either, or why.', cautious: 'Follow the wheel rut only as far as the fork', bold: 'Check the cabin for someone needing help', leave: 'Do not cross the damaged gate', insight: 'A claim gate was forced, partly repaired, and crossed by a wheel; the cause remained uncertain.' },
  { id: 'the-missing-assayer', title: 'The Missing Assayer', subtitle: 'A meal sits untouched beside an open assay book.', shape: 'occupant', risk: 'MODERATE', setting: 'remote assay station', hook: 'An abandoned meal and open records distinguish accident, rescue, and voluntary departure.', opening: 'An assay station door stands open. A bowl of stew is cold on the table, a book is open to a fresh entry, and the assayer is nowhere in sight. A stream path and a ridge trail leave the building.', clue: 'One chair has fallen sideways, but the floor shows no struggle. The latest assay sample is capped and dated; a coat and walking stick are missing from the peg.', turn: 'The assayer may have stepped out, taken a route, or needed help. The stream is shallow near the building; the ridge trail disappears around a blind shoulder.', cautious: 'Call from the doorway and wait', bold: 'Follow the ridge trail to the shoulder', leave: 'Leave word at the nearest settlement', insight: 'The missing assayer left with a coat and walking stick; no clear evidence of a struggle remained.' },
  { id: 'the-claim-jumpers-story', title: 'The Claim Jumper’s Story', subtitle: 'The occupant has a map; the absent owner has improvements.', shape: 'claim', risk: 'MODERATE', setting: 'remote mining claim', hook: 'Two sides offer evidence of partial legitimacy rather than a simple owner/criminal split.', opening: 'A worker occupies a claim cabin and says the first owner left years ago. The cabin contains a hand-drawn boundary map; outside, the old sluice has been repaired with new boards.', clue: 'The map shows a water right shared with a neighboring claim. A letter from the absent owner asks the worker to keep the sluice clear, but never grants the cabin or claim.', turn: 'The worker has a real task and the owner has not clearly surrendered title. Both accounts leave something out.', cautious: 'Compare the letter with the map', bold: 'Ask the worker what was promised aloud', leave: 'Refuse to take sides and leave', insight: 'The claim occupant had been asked to maintain a shared sluice, but no document transferred ownership.' },
  { id: 'the-forgotten-supply-cache', title: 'The Forgotten Supply Cache', subtitle: 'A dry cache sits beside fresh footprints.', shape: 'salvage', risk: 'LOW', setting: 'remote trail cache', hook: 'Useful supplies are deliberately hidden and may be expected back.', opening: 'Under a shelf of rock beside the trail, a waxed bundle holds rope, food, and a folded blanket. Fresh bootprints approach it and leave; a small stone has been set on top of the wrapping.', clue: 'The bundle is dry and orderly. A stitched mark on the blanket matches no owner you know. The prints are recent enough that someone may still be nearby.', turn: 'This looks stored, not discarded. You may leave it, mark the location, or take one useful thing and accept that it could be missed.', cautious: 'Mark the cache for its owner', bold: 'Take one useful supply', leave: 'Leave the bundle untouched', insight: 'A trail cache held dry supplies and bore signs its owner might return.' },
  { id: 'the-old-hydraulic-cut', title: 'The Old Hydraulic Cut', subtitle: 'A wide hillside trench still sheds loose earth.', shape: 'hazard', risk: 'HIGH', setting: 'eroded mining cut', hook: 'A large excavation is visually striking but offers meaningful exploration from a safe rim.', opening: 'A broad cut gouges the hillside above a creek. Wooden pipes lie along its rim; the inner face is steep and scalloped by old water work. You stand on a firm spur with a clear path back.', clue: 'A narrow ledge descends toward an iron fitting, but fresh soil has fallen across its lower end. The pipe line can be followed along the rim without entering the cut.', turn: 'The fitting may explain how water was brought here. Descending adds no certainty about what lies below and risks the loose face.', cautious: 'Follow the pipe line along the rim', bold: 'Descend to the iron fitting', leave: 'Return by the firm spur', insight: 'An old hydraulic cut was fed by a rim-side wooden pipeline; its lower face remained unstable.' , danger: 0.50 },
  { id: 'claim-at-dry-creek', title: 'The Claim at Dry Creek', subtitle: 'Two groups point to moved markers and incomplete papers.', shape: 'claim', risk: 'MODERATE', setting: 'dry creek claim', hook: 'Competing claimants each hold a physical clue and neither has complete papers.', opening: 'Two groups meet at a dry creek cut. One points to stakes beside the wash; the other holds a receipt for timber used on the opposite bank. The creek bed is dry, and both groups say the boundary moved.', clue: 'The stake line follows an old channel. A survey sketch shows a bend that no longer exists, and the receipt proves timber was bought but not where it was set.', turn: 'Neither marker nor paper settles the present line. You can lay the evidence together, carry one account away, or refuse to judge.', cautious: 'Let both groups compare the sketch and receipt', bold: 'Walk the old creek line with one claimant', leave: 'Leave before the argument hardens', insight: 'At Dry Creek, old stakes followed a vanished channel and the timber receipt did not establish a boundary.' },
  { id: 'claim-jumpers-at-sundown', title: 'Claim Jumpers at Sundown', subtitle: 'You were hired to watch a claim, not to decide who owns it.', shape: 'claim', risk: 'LOW', setting: 'remote mining claim at dusk', hook: 'A guard job becomes a legitimacy test when the supposed intruders present older evidence.', opening: 'You were paid to watch a remote claim until the owner returns. At sundown, two travelers arrive with an older deed copy and say the present cabin was built over their family’s boundary stake.', clue: 'The employer’s posted map excludes the old stake; the visitors’ copy includes it, but has no witness seal. The visitors remain outside the fence and have no weapons in hand.', turn: 'Your job is to prevent removal of equipment, not to enforce an uncertain title. Darkness is falling and the road back remains open.', cautious: 'Keep the gate closed and read both papers', bold: 'Let them point out the old stake from the road', leave: 'End the watch and return to the settlement', insight: 'The hired claim watch faced an older, unverified boundary document and a newer incomplete map.' },
  { id: 'the-man-in-the-abandoned-camp', title: 'The Man in the Abandoned Camp', subtitle: 'A camp called empty has a tended stove and a resident.', shape: 'occupant', risk: 'MODERATE', setting: 'remote work camp', hook: 'A resident’s presence complicates the word abandoned without proving his claim.', opening: 'An old work camp stands quiet except for a thin line of smoke. One man sits outside the cookhouse repairing a strap. He says the crew left, but he stayed to watch the tools.', clue: 'His name is absent from the camp ledger, though a recent entry records food for one. The tool shed is locked, and he has a key but no written appointment.', turn: 'He may be caretaker, worker, heir, or simply someone sheltering there. The nearest settlement is a day’s walk.', cautious: 'Ask what he was told to protect', bold: 'Compare his key with the shed lock', leave: 'Take the public trail past camp', insight: 'A man remained in a deserted work camp with a shed key and a ledger entry for one ration.' },
  { id: 'the-timber-claim', title: 'The Timber Claim', subtitle: 'Fresh cuts appear inside a boundary no one has checked lately.', shape: 'claim', risk: 'MODERATE', setting: 'remote timber tract', hook: 'New cutting may be theft, a returning owner, or a boundary misunderstanding.', opening: 'Fresh stumps line one side of an old timber road. A faded claim post stands beyond them, leaning toward the track; the cut logs are stacked neatly rather than hauled away.', clue: 'The cuts are clean and recent. A matching axe mark appears on a log at the far end of the tract, but the mark is a maker’s stamp, not an owner’s sign.', turn: 'Someone worked here and may return for the timber. The boundary post is too faded to show which side of the road it governs.', cautious: 'Measure the cuts against the leaning post', bold: 'Follow the log drag marks to the far end', leave: 'Keep to the public timber road', insight: 'Fresh timber had been cut inside a tract with a leaning, unreadable boundary post.' },
  { id: 'the-second-claim-marker', title: 'The Second Claim Marker', subtitle: 'A new stake stands inside an older line.', shape: 'claim', risk: 'LOW', setting: 'mining boundary', hook: 'A second marker may be fraud, correction, or an old boundary followed anew.', opening: 'A new stake stands inside a line of weathered claim markers. Its paint is fresh, but the hole is shallow and the ground around it has not settled.', clue: 'The old stakes bear the same notch used on a nearby survey stone. The new one has a claimant’s initials but no date or witness mark.', turn: 'Someone has marked an interior boundary; whether it is a correction or an attempt to shift ground is not yet clear.', cautious: 'Copy the marks without moving either stake', bold: 'Find where the new line meets the creek', leave: 'Leave the boundary as you found it', insight: 'A freshly placed claim stake sat inside an older marked line without a date or witness.' },
  { id: 'the-claim-that-pays-too-well', title: 'The Claim That Pays Too Well', subtitle: 'A generous guard wage comes with a request not to ask questions.', shape: 'claim', risk: 'LOW', setting: 'remote claim camp', hook: 'A suspiciously high wage is tested against what the employer is actually guarding.', opening: 'A prospector offers unusually high pay to keep watch at a remote claim overnight. He points to the cabin, but not the locked shed behind it; he asks you to turn away anyone who approaches.', clue: 'The claim map shows no special value. The shed has fresh iron bands, and you hear movement inside though the prospector says it is empty. The road and camp gate are both visible.', turn: 'The job may protect property, evidence, or a person. The employer has not told you what is behind the shed.', cautious: 'Ask to inspect what you are hired to guard', bold: 'Check the shed door from the lit side', leave: 'Decline the watch and take the road', insight: 'A high-paying claim watch included a locked shed with unexplained movement.' },
  { id: 'camp-with-fresh-cut-wood', title: 'The Camp with Fresh-Cut Wood', subtitle: 'An empty camp has prepared for someone to return.', shape: 'trace', risk: 'MODERATE', setting: 'remote forest camp', hook: 'Fresh prepared firewood and maintained bedding imply a planned return without a visible occupant.', opening: 'A camp appears deserted: the fire is cold, the canvas folded, and the tools stacked. Beneath a lean-to sits a neat pile of fresh-cut wood, dry under an oilcloth.', clue: 'The wood has clean hatchet faces, and a cup is turned upside down beside it. A narrow path has been swept clear through the brush; no recent tracks approach from the road.', turn: 'The place is prepared, not necessarily abandoned. You can wait, leave a sign, or use the shelter and accept that you may meet its keeper.', cautious: 'Leave a visible note-like marker from the road', bold: 'Wait near the cleared path', leave: 'Continue without using the camp', insight: 'A folded camp had dry fresh-cut wood and a cleared path prepared for a return.' },
  { id: 'the-shaft-behind-the-trees', title: 'The Shaft Behind the Trees', subtitle: 'A hidden mine opening has no safe ladder and no marked owner.', shape: 'hazard', risk: 'HIGH', setting: 'wooded mine shaft', hook: 'Surface evidence rewards discovery while making descent an informed choice.', opening: 'Brush conceals a square mine opening beyond the trail. The rim is timbered, but one support has split; no ladder reaches the bottom. A path around the shaft returns to the road.', clue: 'A tin tag nailed to the sound post lists a crew and year. The split support has old rot, while the trail around the rim is firm enough to stand on.', turn: 'The tag identifies a work crew, not ownership or what remains below. Descending without a ladder would be a blind drop.', cautious: 'Copy the crew tag and mark the shaft', bold: 'Inspect the opening from the firm side', leave: 'Return to the road without approaching', insight: 'A wooded shaft was worked by a named crew, but its broken support made descent unsafe.' , danger: 0.55 },
  { id: 'the-old-ferry-landing', title: 'The Old Ferry Landing', subtitle: 'A disused landing shows fresh rope wear across the river.', shape: 'trace', risk: 'MODERATE', setting: 'remote river landing', hook: 'Fresh wear at a forgotten landing hints at an active crossing and route beyond.', opening: 'An old ferry landing is overgrown at the river bend. The timber platform is grey, but a rope groove is pale and smooth; a trail climbs the opposite bank through willows.', clue: 'A new knot is tied around the landing post, and one set of bootprints leads down from the public trail. The river is too broad to wade, and no boat is tied here.', turn: 'Someone may be crossing privately or maintaining a route. The far-bank trail cannot be reached safely from this side.', cautious: 'Record the rope mark and search the near-bank trail', bold: 'Call across toward the far-bank trail', leave: 'Stay on the public road', insight: 'The old ferry landing had fresh rope wear and a new knot but no boat.' },
  { id: 'the-collapsed-storehouse', title: 'The Collapsed Storehouse', subtitle: 'A beam pins one corner while useful goods remain visible inside.', shape: 'hazard', risk: 'HIGH', setting: 'remote storehouse ruin', hook: 'The traveler chooses a limit for salvage under a visibly unstable beam.', opening: 'A remote storehouse has collapsed along its back wall. A sound doorway remains; from it you can see a crate under a tilted beam and dry shelves along the near wall.', clue: 'The beam rests on a cracked post, and dust falls when wind moves the roof. The near shelf can be reached from the doorway; the crate cannot.', turn: 'The visible dry goods are close enough to take without crossing the cracked floor. Reaching the crate would put you under the beam.', cautious: 'Take only what rests on the near shelf', bold: 'Reach beneath the tilted beam for the crate', leave: 'Leave the storehouse undisturbed', insight: 'The collapsed storehouse still held goods on a near shelf, but its back corner was unstable.' , danger: 0.53 },
  { id: 'the-trail-that-ends-at-stone', title: 'The Trail That Ends at Stone', subtitle: 'A path stops at bare rock where old cut marks continue.', shape: 'trace', risk: 'MODERATE', setting: 'remote rock face', hook: 'Chisel marks and displaced stones distinguish a removed route from a natural dead end.', opening: 'A narrow trail ends at a smooth stone face. Old chisel marks run upward for several feet, then vanish under lichen. A line of foundation stones turns behind a cedar at the trail’s edge.', clue: 'The foundation line reaches a shallow notch in the rock. One stone has been lifted and set back; beyond it is a narrow dry ledge, not a doorway.', turn: 'The trail may have served a quarry or a removed store shed. The ledge continues to a wider shelf, while the path back is clear.', cautious: 'Follow the foundation stones to the wider shelf', bold: 'Test the lichen-covered notch', leave: 'Turn back from the rock face', insight: 'An old trail ended at a worked stone face beside foundations and a narrow ledge.' },
];

const decisionCopyOverrides: Record<string, Partial<FrontierCard>> = {
  'roof-through-the-trees': {
    turn: 'From the common room, you can watch the approach through the repaired window, inspect its newer board from inside, or return to the timber road.',
    cautious: 'Watch the approach from the common room',
    bold: 'Inspect the repaired window from inside',
  },
  'empty-assay-office': {
    turn: 'You can give both sides the same account of the evidence, keep your finding private, or leave the claim unsettled.',
  },
  'the-broken-rocker-box': {
    turn: 'The patch fits the split handle but has not been fastened. You can compare it with the break, rock the box briefly using the damaged handle, or leave both parts for whoever returns.',
    cautious: 'Compare the patch with the split handle',
  },
  'the-cache-under-the-stove': {
    turn: 'This is stored property, not random debris: the initials and written count show the cache was deliberately kept. You can read the top paper and restore the tin, take the two coins while leaving the papers and tool, or close the compartment untouched.',
  },
};
for (const card of cards) Object.assign(card, decisionCopyOverrides[card.id]);

const closures: Record<string, string> = {
  'roof-through-the-trees': 'The repaired board and clean chair suggest a shelter still used in passing; you leave it ready for whoever returns.',
  'camp-with-fresh-ashes': 'You do not disturb the food or fire pit. The camp remains ready for its absent worker, and your tracks are the only new ones.',
  'floorboard-that-was-replaced': 'The paper is put back beneath the board. You preserve the cabin, but now know its repair was meant to hide something.',
  'forgotten-sluice': 'The gate stays where you found it, so water continues along the channel without an unrecorded change to anyone’s work.',
  'the-mule-trail': 'The dropped load marks an older route to the shelf. You return by the visible descent rather than carrying an unknown burden.',
  'the-prospectors-map': 'The map becomes useful as a route record, not a promise of riches; the unmarked circle remains unverified.',
  'empty-assay-office': 'The ledger remains in the office. The visitor leaves with no sample until the partnership record can be checked.',
  'cabin-with-two-locks': 'The second lock remains intact. Whatever it protects, you do not mistake an empty trail for permission to break it.',
  'gold-dust-in-the-floorboards': 'The dust points to repeated handling at the stove-side table, but no hidden fortune is established.',
  'the-old-hoist': 'You leave the hoist untouched and mark its broken cable; anyone returning will see the danger before trusting it.',
  'camp-below-the-slide': 'You stop before the moving slope takes more ground. The visible edge is recorded; the buried wall is left alone.',
  'the-hidden-tailings-pile': 'The brush is laid back over the assay fragments. You preserve evidence without deciding why the pile was covered.',
  'the-old-claim-cabin': 'The cabin offers no final explanation, but its worn tools and small boot repair turn an empty room into a remembered life.',
  'the-claim-with-no-name': 'You leave the tools where the worker can find them. Recent labor is clear; title is not.',
  'the-broken-rocker-box': 'The loose repair patch stays with the machine. Whoever returns can finish the repair without wondering who moved the parts.',
  'the-rusted-safe': 'The safe stays on the failing joist. Its contents remain unknown, and no one has traded a sound floor for a guess.',
  'the-cache-under-the-stove': 'The tin is restored beneath the stove; the initials and written count give a future owner a way to recognize it.',
  'the-washed-out-claim': 'The flood-cut bank keeps changing. You leave before rising water closes the high route and record what the current exposed.',
  'the-old-dredge': 'The ledger box stays above the waterline, and the river keeps shifting the empty dredge against its chains.',
  'the-derelict-stamp-mill': 'The remaining pins stay in place. You have learned why the stripped room was safer to inspect than the hanging stamps.',
  'survey-stakes-are-wrong': 'The sketch preserves both lines and the moved creek; it records uncertainty instead of accusing a surveyor without proof.',
  'the-forgotten-powder-shed': 'The corroded tins remain sealed. The warning is passed on without turning dangerous old supplies into a prize.',
  'the-creek-diversion': 'The stone channel leads to a dry settling pond, evidence of old work rather than a secret spring or guaranteed deposit.',
  'locked-strongbox-in-the-ruins': 'The scratched name is copied while the strongbox stays sealed. Its contents do not become yours merely because the roof fell.',
  'the-broken-gate': 'The gate’s damage and repair wedge are left for the claimant to inspect; the marks do not prove sabotage or theft.',
  'the-missing-assayer': 'The missing worker’s coat and walking stick point to a chosen departure as readily as an emergency; no fate is invented.',
  'the-claim-jumpers-story': 'The sluice keeps its shared use while neither the worker nor the absent owner receives a title the evidence cannot grant.',
  'the-forgotten-supply-cache': 'The cache’s placement and fresh prints are recorded. You leave the owner a chance to return rather than treating storage as refuse.',
  'the-old-hydraulic-cut': 'The rim-side pipe explains how water reached the excavation; the unstable lower face is not worth testing for ore.',
  'claim-at-dry-creek': 'Both groups leave with the old-channel sketch and the limits of the timber receipt; the boundary remains for better records.',
  'claim-jumpers-at-sundown': 'You end the watch without seizing anyone’s tools. The employer’s incomplete map and the older copy remain competing evidence.',
  'the-man-in-the-abandoned-camp': 'The camp ledger and shed key support a caretaker’s story, but do not prove ownership; you leave the lock undamaged.',
  'the-timber-claim': 'The fresh cuts are marked without accusing anyone. The leaning post cannot establish which side of the road was claimed.',
  'the-second-claim-marker': 'Both lines remain in place. The new stake is evidence of a claim, not proof that the older boundary was false.',
  'the-claim-that-pays-too-well': 'You refuse to guard an unexplained locked shed blindly. The wage offer does not answer what the employer is protecting.',
  'camp-with-fresh-cut-wood': 'The covered wood and cleared path remain ready for a return. You neither use the shelter nor assume its keeper is gone.',
  'the-shaft-behind-the-trees': 'The crew tag records who worked the shaft; the broken support keeps the discovery on the surface.',
  'the-old-ferry-landing': 'The fresh knot suggests someone still uses the crossing, but without a boat you keep to the public road.',
  'the-collapsed-storehouse': 'You leave the cracked rear corner untouched. The near shelf was enough; the crate beneath the beam was not worth a collapse.',
  'the-trail-that-ends-at-stone': 'The foundation line shows a route once continued around the rock. The ledge is recorded, not mistaken for a safe doorway.',
};

const fatalHazards: Record<string, Pick<FrontierCard, 'fatalFailure' | 'failureMessage' | 'fatalText'>> = {
  'camp-below-the-slide': { fatalFailure: true, failureMessage: 'The cracked slope releases a full sheet of earth across the chest and your way uphill.', fatalText: 'The slope breaks loose above you. There is no time to reach the ridge before the buried wall and earth close over the lower shelf.' },
  'the-washed-out-claim': { fatalFailure: true, failureMessage: 'The rising current breaks the lower boards away as you step down.', fatalText: 'The bank collapses into the swollen creek. The high path was visible, but you stepped below it as the water rose.' },
  'the-old-dredge': { fatalFailure: true, failureMessage: 'The dredge rolls under the current and throws you into the fast channel.', fatalText: 'The loosened dredge turns beneath you. The river carries you under before anyone on the distant road can reach the bend.' },
  'the-derelict-stamp-mill': { fatalFailure: true, failureMessage: 'The plank gives way beneath the suspended stamps; the old pins tear loose.', fatalText: 'The hanging stamps drop through the failing floor. You are crushed beneath the machine whose weight and loose pins were visible.' },
  'the-old-hydraulic-cut': { fatalFailure: true, failureMessage: 'The narrow ledge shears away beneath your weight and slides into the cut.', fatalText: 'The ledge breaks loose above the deep excavation. The firm rim was the safe route, but you descended onto ground already shedding soil.' },
  'the-collapsed-storehouse': { fatalFailure: true, failureMessage: 'The cracked post splits as you reach beneath the tilted beam.', fatalText: 'The beam falls into the back corner as you reach under it. The sound doorway and near shelf were safe; the warned corner was not.' },
};
const moderateRisk = new Set(['the-old-hoist', 'the-rusted-safe', 'the-shaft-behind-the-trees']);
const frontierAdventures = cards.map((card) => frontierAdventure({
  ...card,
  closure: closures[card.id],
  ...(moderateRisk.has(card.id) ? { risk: 'MODERATE' as const } : {}),
  ...(card.id === 'the-forgotten-powder-shed' ? { risk: 'LOW' as const, boldRisk: false } : {}),
  ...(fatalHazards[card.id] ?? {}),
}));

/** The assayer story needs observed results for each promised action, not the generic short-form endings. */
function completeMissingAssayerInvestigation(scenario: Scenario): Scenario {
  const { scenes } = scenario;
  scenes['the-missing-assayerEvidence'] = {
    ...scenes['the-missing-assayerEvidence'],
    choices: [
      { id: 'callFromDoor', label: 'Call from the doorway and wait for an answer', next: 'the-missing-assayerWait', effects: { knowledge: ['The missing assayer left with a coat and walking stick; no clear evidence of a struggle remained.'] } },
      { id: 'followRidgeTrail', label: 'Follow the ridge trail to the blind shoulder', next: 'the-missing-assayerDecision', effects: { historyFlags: ['followed the ridge trail from the missing assayer’s station'] } },
      { id: 'leaveWord', label: 'Take the description to the nearest settlement', next: 'the-missing-assayerReport', effects: { historyFlags: ['reported the missing assayer at the nearest settlement'] } },
    ],
  };
  scenes['the-missing-assayerDecision'] = largeScene(
    'the-missing-assayerDecision',
    'Where the Ridge Trail Goes',
    'You follow the trail to the blind shoulder. The path narrows across loose shale; boot marks cross one another and fade where bare stone begins. Beyond the shoulder, a lower track bends toward the old assay road, but neither the prints nor the route establish that the assayer came this way. You find no sign of an injured person.',
    [
      { id: 'traceToSaddle', label: 'Follow the lower track as far as the ridge saddle', next: 'the-missing-assayerBold', effects: { knowledge: ['The ridge trail from the assay station reaches a lower track toward the old assay road, but the prints cannot identify who used it.'] } },
      { id: 'callAndReturn', label: 'Call once, then return to leave a note at the station', next: 'the-missing-assayerCautious', effects: { historyFlags: ['recorded the ridge trail and unanswered call at the assay station'] } },
    ],
    'warning',
  );
  scenes['the-missing-assayerWait'] = largeScene(
    'the-missing-assayerWait',
    'No Answer at the Station',
    'You call from the doorway, step outside, and wait. No one answers from the stream path or the ridge. The book remains open to its dated entry, and nothing in the quiet around the station tells you whether the assayer meant to be away only briefly.',
    [
      { id: 'leaveStationNote', label: 'Leave a note with the time and return to the road', next: 'the-missing-assayerCautious', effects: { historyFlags: ['left a time-stamped note after no answer at the assay station'] } },
      { id: 'reportAfterWaiting', label: 'Report the absence at the nearest settlement', next: 'the-missing-assayerReport', effects: { historyFlags: ['reported the missing assayer at the nearest settlement'] } },
    ],
    'safe',
  );
  scenes['the-missing-assayerReport'] = largeScene(
    'the-missing-assayerReport',
    'A Description Left Behind',
    'At the nearest settlement, you give the clerk the assayer’s description, the dated open book, and the two routes from the station. No one there has news of the worker. The clerk records the details and agrees to ask people returning along the assay road; there is still no evidence to say whether the assayer left by choice or needs help.',
    [{ id: 'leaveReport', label: 'Leave the report recorded and continue your journey', next: 'the-missing-assayerEvidenceLeft' }],
    'safe',
  );
  scenes['the-missing-assayerCautious'] = {
    ...scenes['the-missing-assayerCautious'],
    text: 'You leave a note at the station with the route you checked and the time of your unanswered call. The ridge trail remains passable, and the dated assay entry is undisturbed. You have made it easier for the next visitor to compare accounts, but the assayer’s whereabouts remain unknown.',
  };
  scenes['the-missing-assayerBold'] = {
    ...scenes['the-missing-assayerBold'],
    text: 'At the ridge saddle, the lower track continues toward the old assay road, then disappears over bare stone. You find no one and no sign of a fall. The route is now clearer, but the prints cannot be dated or identified; the assayer may have taken it, or someone else may have.',
  };
  scenes['the-missing-assayerEvidenceLeft'] = {
    ...scenes['the-missing-assayerEvidenceLeft'],
    text: 'You leave the description and last-known details with the settlement clerk. No one has seen the assayer, but the report is recorded for people returning along the assay road. The coat and walking stick suggest a departure; they do not settle whether it was voluntary or an emergency.',
  };
  return scenario;
}

export const FRONTIER_DISCOVERY_ADVENTURES = frontierAdventures.map((scenario) =>
  specializeSurveyStakes(scenario.id === 'the-missing-assayer' ? completeMissingAssayerInvestigation(scenario) : scenario),
);

function specializeSurveyStakes(scenario: Scenario): Scenario {
  if (scenario.id !== 'survey-stakes-are-wrong') return scenario;
  const startId = `${scenario.id}Start`;
  const evidenceId = `${scenario.id}Evidence`;
  const decisionId = `${scenario.id}Decision`;
  const creekCheckId = `${scenario.id}CreekCheck`;
  const recordId = `${scenario.id}FieldRecord`;
  const deferredId = `${scenario.id}Deferred`;
  const notesId = `${scenario.id}NotesOnly`;
  const insight = 'Two survey lines followed different courses, and creek erosion could explain part of the change.';
  // Keep prior terminal/decision IDs addressable for saves created before this route was specialized.
  const scenes: Record<string, Scene> = { ...scenario.scenes };

  scenes[startId] = { ...scenes[startId], title: 'A Surveyor’s Errand', text: 'A county surveyor has asked you to note two stake rows where the creek changed course. One row follows an old dry channel; the other crosses the present meadow. You are to record what the ground shows, not decide who owns it.', choices: [
    { id: 'inspectStakeRows', label: 'Walk both rows and read their marks', next: evidenceId },
    { id: 'markAndLeave', label: 'Mark the site for the surveyor and move on', next: `${scenario.id}Left` },
    { id: 'turnAway', label: 'Leave without taking the assignment', next: `${scenario.id}Left` },
  ] };
  scenes[evidenceId] = { ...scenes[evidenceId], title: 'Two Lines on Changed Ground', text: 'The older stakes carry faded cuts. The newer row has uniform notches but no date. A washed bank shows the creek has moved since the first line was set; neither line alone establishes the present boundary.', choices: [
    { id: 'copyBothRows', label: 'Copy both rows and their marks', next: decisionId, effects: { knowledge: [insight] } },
    { id: 'traceNewRow', label: 'Follow the newer row to the current creek', next: creekCheckId, effects: { historyFlags: [`investigated ${scenario.title.toLowerCase()} beyond the first clues`] } },
    { id: 'leaveSurveyEvidence', label: 'Leave the markers untouched and return', next: `${scenario.id}EvidenceLeft`, effects: { knowledge: [insight], historyFlags: [`left ${scenario.title.toLowerCase()} after recording its visible evidence`] } },
  ] };
  scenes[decisionId] = { id: decisionId, title: 'What the Field Book Should Say', tone: 'safe', text: 'Your notes can preserve the two rows without turning a changed creek into a verdict. The surveyor can compare them with the fixed stone when the watercourse is checked again.', choices: [
    { id: 'recordBothRows', label: 'Enter both rows and the old channel separately', next: recordId, effects: { knowledge: [insight] } },
    { id: 'requestRemeasure', label: 'Ask the surveyor to remeasure before drawing a line', next: deferredId },
    { id: 'submitNotesOnly', label: 'Return the observations without a boundary reading', next: notesId },
  ] };
  scenes[creekCheckId] = { id: creekCheckId, title: 'Where the Creek Runs Now', tone: 'safe', text: 'The newer stakes turn toward the present creek; the old row tracks a channel that is now dry. That explains why the lines differ, but not when either was meant to govern the land.', choices: [
    { id: 'recordCreekShift', label: 'Add the present creek bend as a separate note', next: recordId, effects: { knowledge: [insight] } },
    { id: 'requestCreekRemeasure', label: 'Ask for a fresh survey after the water settles', next: deferredId },
    { id: 'submitCreekNotes', label: 'Return without drawing a boundary', next: notesId },
  ] };
  scenes[recordId] = { id: recordId, title: 'A Record, Not a Ruling', text: 'The field book keeps the older row, newer row, and changed creek as separate observations. The surveyor has something useful to compare; no one has been named right or wrong on incomplete ground.', ending: 'success', choices: [] };
  scenes[deferredId] = { id: deferredId, title: 'A Line Left for Later', text: 'No boundary is drawn and neither stake row is moved. The surveyor will return with the fixed-stone reference when the creek’s present course can be measured again.', ending: 'success', choices: [] };
  scenes[notesId] = { id: notesId, title: 'Observations Without a Boundary', text: 'You return only what you saw: two stake rows, a vanished channel, and a creek that moved. The surveyor can decide whether more measurements are worth the trip; your notes make no claim of ownership.', ending: 'success', choices: [] };
  return { ...scenario, subtitle: 'A field record must separate moved water from a boundary ruling.', scenes };
}
