import { ITEMS } from '../items';
import type { Scenario } from '../types';

const CARRYABLE_ITEMS = Object.values(ITEMS).filter((item) => item.carryable).map((item) => item.id);

export const GIVE_ME_WHATCHA_GOT: Scenario = {
  id: 'give-me-whatcha-got', title: 'Give Me Whatcha Got', subtitle: 'A robbery is already underway. Getting out alive may be enough.', startScene: 'bankRobbery',
  timePhases: [{ id: 'firstDemand', label: 'The First Demand', atMinutes: 0 }, { id: 'robberyStretches', label: 'The Room Tightens', atMinutes: 4 }],
  runRandomSelections: [
    { id: 'robber', values: ['Mirek', 'Zorren', 'Dario', 'Aldwyn', 'Veska'].map((value) => ({ value })) },
    { id: 'crewStyle', values: ['controlled', 'nervous', 'disorganized'].map((value) => ({ value })) },
    { id: 'patron', values: ['Jory', 'Teleri', 'Lucan', 'Tavi'].map((value) => ({ value })) },
    { id: 'patronMove', values: ['holds', 'panics', 'bolts'].map((value) => ({ value })) },
    { id: 'gunOutcome', values: ['warningShot', 'patronWounded', 'patronKilled', 'clerkKilled'].map((value) => ({ value })) },
  ],
  scenes: {
    bankRobbery: { id: 'bankRobbery', title: 'Inside the Bank', tone: 'danger',
      text: 'You came to the town bank for ordinary business. Two armed robbers have entered: {{robber}} stands by the teller counter with a revolver, and a second watches the front door. You and three patrons are in the public line; the clerk is behind the counter. The staff door is beyond the robbers. They demand the cash drawer and tell everyone to keep still. One patron glances toward the exit.',
      textVariants: [
        { requirements: { selections: { crewStyle: 'controlled' } }, text: 'You came to the town bank for ordinary business. Two armed robbers have entered: {{robber}} stands by the teller counter with a revolver, and a second watches the front door. The clerk is behind the counter; you and three patrons are in the public line. The staff door lies beyond the robbers. Their orders are brisk and controlled: cash from the drawer, no sudden movement.' },
        { requirements: { selections: { crewStyle: 'nervous' } }, text: 'You came to the town bank for ordinary business. Two armed robbers have entered. {{robber}} holds a revolver too tightly and keeps glancing at the patrons; the second watches the front door. You are in the public line with three patrons, while the clerk is behind the counter. The staff door is beyond the robbers. They demand the drawer’s cash.' },
        { requirements: { selections: { crewStyle: 'disorganized' } }, text: 'You came to the town bank for ordinary business. Two armed robbers have entered: {{robber}} points a revolver toward the counter while the second argues about the cash drawer. You and three patrons are in the public line; the clerk is behind the counter. The front door is watched, and the staff door is beyond the robbers. Their movements are hurried and uncertain.' },
      ],
      choices: [
        { id: 'complyWithRobbers', label: 'Keep still and obey their orders', timeCost: 1, effects: { historyFlags: ['complied_during_bank_robbery'] }, next: 'cashTaken' },
        { id: 'steadyPatron', label: 'Quietly steady the nearby patron', timeCost: 1, hint: 'Calming someone may help; a sudden movement may draw notice.', chance: { probability: 0.62, bonusSelections: { crewStyle: 'controlled', patronMove: 'holds' }, bonusProbability: 0.1, penaltySelections: { crewStyle: 'nervous', patronMove: 'bolts' }, penaltyProbability: 0.15, successNext: 'patronsSteady', failureNext: 'patronPanics', successMessage: '{{patron}} stays low and quiet. The robbers keep their attention on the counter.', failureMessage: '{{patron}} flinches toward the door, and a robber turns the revolver toward the line.', successEffects: { historyFlags: ['calmed_patrons_during_bank_robbery'] }, failureEffects: { historyFlags: ['tried_to_calm_patron_during_bank_robbery'] } } },
        { id: 'observeRobbery', label: 'Stay still and watch the room', timeCost: 1, effects: { historyFlags: ['observed_bank_robbery'] }, next: 'cashTaken' },
      ] },
    cashTaken: { id: 'cashTaken', title: 'The Cash Drawer', tone: 'danger',
      text: '{{robber}} orders everyone to hand over any money they have. The revolver remains visible, and the front door is watched. If you try to hide something and are noticed, the robber may think you are resisting.',
      textVariants: [{ requirements: { historyFlags: ['survived_armed_crisis'] }, text: 'You have faced an armed crisis before, but this is a crowded bank with two robbers and no safe calculation. {{robber}} orders everyone to hand over money; the front door is watched.' }],
      choices: [
        { id: 'handOverMoney', label: 'Hand over the money you carry', requirements: { minMoney: 1 }, timeCost: 1, effects: { loseMoney: true, historyFlags: ['complied_during_bank_robbery', 'survived_bank_robbery', 'lost_property_to_robbers'] }, next: 'afterCashDemand' },
        { id: 'noMoneyToHandOver', label: 'Keep your hands visible; you carry no cash', requirements: { maxMoney: 0 }, timeCost: 1, effects: { historyFlags: ['complied_during_bank_robbery', 'survived_bank_robbery'] }, next: 'afterCashDemand' },
        { id: 'hideMoney', label: 'Try to conceal your money', requirements: { minMoney: 1 }, hint: 'If noticed, they may seize it and turn their weapon on you.', timeCost: 1, chance: { probability: 0.5, bonusSelections: { crewStyle: 'disorganized' }, bonusProbability: 0.12, penaltySelections: { crewStyle: 'nervous' }, penaltyProbability: 0.16, successNext: 'moneyConcealed', failureNext: 'caughtHidingMoney', successMessage: 'You hide your purse before the robber looks your way.', failureMessage: '{{robber}} sees the movement and snatches the purse from you.', successEffects: { setFlags: ['concealed_property_during_robbery'], historyFlags: ['concealed_property_during_robbery', 'survived_bank_robbery'] }, failureEffects: { loseMoney: true, health: -1, historyFlags: ['lost_property_to_robbers'] } } },
        { id: 'hideCarriedItem', label: 'Try to hide your carried item', requirements: { anyItems: CARRYABLE_ITEMS }, hint: 'If noticed, they may take the item and treat the movement as resistance.', timeCost: 1, chance: { probability: 0.48, bonusSelections: { crewStyle: 'disorganized' }, bonusProbability: 0.12, penaltySelections: { crewStyle: 'nervous' }, penaltyProbability: 0.16, successNext: 'itemConcealed', failureNext: 'caughtHidingItem', successMessage: 'You slip the item out of sight, then hand over your purse; the robbers do not notice the movement.', failureMessage: '{{robber}} catches the movement, takes the item, and seizes your purse.', successEffects: { loseMoney: true, setFlags: ['concealed_property_during_robbery'], historyFlags: ['concealed_property_during_robbery', 'lost_property_to_robbers', 'survived_bank_robbery'] }, failureEffects: { loseMoney: true, loseCarriedItem: true, health: -2, historyFlags: ['lost_property_to_robbers', 'was_injured_in_bank_robbery'] } } },
      ] },
    patronsSteady: { id: 'patronsSteady', title: 'A Little Calm', tone: 'warning',
      text: '{{patron}} keeps their head down. Nobody rushes the robbers, and the clerk can fill the drawer sack without a sudden movement. The robbers leave without searching the line. Your quiet words may have helped, though the robbery still succeeds.',
      choices: [
        { id: 'stayLowAsCashTaken', label: 'Stay low while they take the money', effects: { historyFlags: ['complied_during_bank_robbery', 'survived_bank_robbery', 'calmed_patrons_during_bank_robbery'] }, next: 'robbersLeave' },
        { id: 'watchForClerk', label: 'Keep others calm and watch the clerk', effects: { historyFlags: ['calmed_patrons_during_bank_robbery', 'survived_bank_robbery'] }, next: 'robbersLeave' },
      ] },
    patronPanics: { id: 'patronPanics', title: 'A Sudden Movement', tone: 'danger',
      text: '{{patron}} rises and starts toward the front of the line. {{robber}} turns, revolver raised, and demands purses from the people in the line. You are close enough to pull {{patron}} down, but crossing the aisle puts you in the line of fire.',
      choices: [
        { id: 'stayLowDuringPanic', label: 'Hand over your money and stay low', effects: { loseMoney: true, historyFlags: ['complied_during_bank_robbery', 'survived_bank_robbery'] }, next: 'robbersLeave' },
        { id: 'callPatronBack', label: 'Call for {{patron}} to stop', hint: 'A calm warning may reach them; the robber is already watching.', chance: { probability: 0.54, successNext: 'patronStops', failureNext: 'gunshotInBank', successMessage: '{{patron}} stops before reaching the aisle.', failureMessage: 'The shout and movement bring a shot from the teller counter.', successEffects: { historyFlags: ['calmed_patrons_during_bank_robbery'] }, failureEffects: { health: -2, historyFlags: ['witnessed_shooting_during_bank_robbery'] } } },
        { id: 'pullPatronDown', label: 'Pull {{patron}} down beside you', hint: 'The robber has a raised revolver; you may be shot crossing the aisle.', chance: { probability: 0.44, successNext: 'briefOpening', failureNext: 'gunshotInBank', successMessage: 'You pull {{patron}} below the counter edge as the robber looks away.', failureMessage: 'You reach for {{patron}} as a shot breaks across the bank.', successEffects: { health: -1, historyFlags: ['intervened_in_bank_robbery', 'calmed_patrons_during_bank_robbery'] }, failureEffects: { health: -6, historyFlags: ['intervened_in_bank_robbery', 'was_injured_in_bank_robbery'] } } },
      ] },
    briefOpening: { id: 'briefOpening', title: 'A Moment of Distraction', tone: 'danger',
      text: '{{patron}} is down beside you. {{robber}} has turned toward the teller and the second robber is looking at the door. The nearest revolver is still in reach, and you have only a moment. If you wait, they may search the line next. Rushing an armed robber might keep the crew from escaping with the bank’s cash, but it could get you killed.',
      choices: [
        { id: 'keepPatronDown', label: 'Stay low as they search the line', effects: { loseMoney: true, historyFlags: ['survived_bank_robbery', 'calmed_patrons_during_bank_robbery'] }, next: 'robbersLeave' },
        { id: 'rushArmedRobber', label: 'Rush the nearest robber', hint: 'A revolver is still in reach; failure could be fatal.', chance: { probability: 0.2, successNext: 'robberStopped', failureNext: 'shotPlayer', successMessage: 'You knock the robber down, but take a hard blow in the struggle.', failureMessage: 'The robber turns and fires before you reach them.', successEffects: { health: -3, historyFlags: ['intervened_in_bank_robbery', 'survived_bank_robbery'] }, failureEffects: { health: -10, historyFlags: ['intervened_in_bank_robbery', 'was_injured_in_bank_robbery'] } } },
      ] },
    afterCashDemand: { id: 'afterCashDemand', title: 'One More Demand', tone: 'warning',
      text: 'Any money you handed over is gone. The robbers prepare to leave.',
      textVariants: [
        { requirements: { selections: { crewStyle: 'controlled' } }, text: 'The controlled robber takes the cash and motions the room to stay still. They do not search anyone as they move toward the door.' },
        { requirements: { selections: { crewStyle: 'nervous' }, anyItems: CARRYABLE_ITEMS }, text: 'The nervous robber notices the item you carried in and demands it too. The banked items are not with you; only the one item on this character is at risk.' },
        { requirements: { selections: { crewStyle: 'disorganized' }, anyItems: CARRYABLE_ITEMS }, text: 'As the crew jostles toward the watched front door, one robber spots the item you carried in and points the revolver at it. Your banked property is safe elsewhere; this carried item is not.' },
        { requirements: { selections: { crewStyle: 'nervous' }, notItems: CARRYABLE_ITEMS }, text: 'The nervous robber scans the line but finds no more money on you. They tell you to keep your hands where they can see them.' },
        { requirements: { selections: { crewStyle: 'disorganized' }, notItems: CARRYABLE_ITEMS }, text: 'The disorganized crew searches no further once the cash is handed over. Their attention is on the door and the teller.' },
      ],
      choices: [
        { id: 'giveItemToNervousCrew', label: 'Hand over your carried item', requirements: { selections: { crewStyle: 'nervous' }, anyItems: CARRYABLE_ITEMS }, effects: { loseCarriedItem: true, historyFlags: ['lost_property_to_robbers', 'survived_bank_robbery'] }, next: 'robbersLeave' },
        { id: 'refuseNervousSearch', label: 'Keep still and refuse the search', requirements: { selections: { crewStyle: 'nervous' }, anyItems: CARRYABLE_ITEMS }, hint: 'They have a revolver pointed at your property; refusal may provoke a shot.', chance: { probability: 0.35, successNext: 'robbersLeave', failureNext: 'shotPlayer', successMessage: 'The robber hesitates, then turns toward the door without taking the item.', failureMessage: 'The robber fires when you refuse to hand it over.', successEffects: { historyFlags: ['survived_bank_robbery'] }, failureEffects: { health: -10, historyFlags: ['was_injured_in_bank_robbery'] } } },
        { id: 'giveItemToDisorganizedCrew', label: 'Hand over your carried item', requirements: { selections: { crewStyle: 'disorganized' }, anyItems: CARRYABLE_ITEMS }, effects: { loseCarriedItem: true, historyFlags: ['lost_property_to_robbers', 'survived_bank_robbery'] }, next: 'robbersLeave' },
        { id: 'refuseDisorganizedSearch', label: 'Keep still and refuse the search', requirements: { selections: { crewStyle: 'disorganized' }, anyItems: CARRYABLE_ITEMS }, hint: 'The revolver is close. Refusal may make the confused crew panic.', chance: { probability: 0.29, successNext: 'robbersLeave', failureNext: 'shotPlayer', successMessage: 'The robber curses but does not fire; the crew retreats toward the door.', failureMessage: 'A robber fires in the confusion.', successEffects: { historyFlags: ['survived_bank_robbery'] }, failureEffects: { health: -10, historyFlags: ['was_injured_in_bank_robbery'] } } },
        { id: 'stayVisibleToRobbers', label: 'Keep your hands visible and wait', requirements: { selections: { crewStyle: 'controlled' } }, effects: { historyFlags: ['survived_bank_robbery'] }, next: 'robbersLeave' },
        { id: 'stayVisibleNoItem', label: 'Keep your hands visible and wait', requirements: { notItems: CARRYABLE_ITEMS, selections: { crewStyle: 'nervous' } }, effects: { historyFlags: ['survived_bank_robbery'] }, next: 'robbersLeave' },
        { id: 'stayVisibleDisorganizedNoItem', label: 'Keep your hands visible and wait', requirements: { notItems: CARRYABLE_ITEMS, selections: { crewStyle: 'disorganized' } }, effects: { historyFlags: ['survived_bank_robbery'] }, next: 'robbersLeave' },
      ] },
    moneyConcealed: { id: 'moneyConcealed', title: 'The Purse Stays Hidden', tone: 'warning', text: 'Your purse remains hidden as the robbers gather the bank’s cash. Nobody is certain whether they saw your movement. The next moments may still be dangerous, but your money is not yet in their hands.',
      choices: [{ id: 'stayStillWithMoney', label: 'Stay still until they leave', effects: { historyFlags: ['survived_bank_robbery'] }, next: 'robbersLeave' }] },
    itemConcealed: { id: 'itemConcealed', title: 'The Item Stays Hidden', tone: 'warning', text: 'Your carried item remains out of sight. The robbers take the money from the room, but do not search you again. Banked property was never at risk.',
      choices: [{ id: 'stayStillWithItem', label: 'Stay still until they leave', effects: { historyFlags: ['survived_bank_robbery'] }, next: 'robbersLeave' }] },
    caughtHidingMoney: { id: 'caughtHidingMoney', title: 'The Movement Is Seen', tone: 'danger', text: '{{robber}} sees you hiding the purse and takes it. The revolver stays trained on the line until the crew is ready to leave.',
      choices: [{ id: 'showEmptyHandsAfterMoney', label: 'Show your empty hands and wait', effects: { historyFlags: ['survived_bank_robbery'] }, next: 'robbersLeave' }] },
    caughtHidingItem: { id: 'caughtHidingItem', title: 'The Item Is Taken', tone: 'danger', text: '{{robber}} sees your attempt to hide the carried item, takes it from you, and seizes your purse. The loss is immediate and explicit; nothing banked is touched.',
      choices: [{ id: 'showEmptyHandsAfterItem', label: 'Show your empty hands and wait', effects: { historyFlags: ['survived_bank_robbery'] }, next: 'robbersLeave' }] },
    patronStops: { id: 'patronStops', title: 'The Patron Stops', tone: 'warning', text: '{{patron}} stops when you call. The robber turns back to the teller; nobody rushes the door. After taking the drawer’s cash, they order the line to hand over any purses too. Your warning may have prevented a worse movement, but the robbery continues.',
      choices: [{ id: 'stayLowAfterWarning', label: 'Hand over your money and stay low', effects: { loseMoney: true, historyFlags: ['survived_bank_robbery', 'calmed_patrons_during_bank_robbery'] }, next: 'robbersLeave' }] },
    gunshotInBank: { id: 'gunshotInBank', title: 'A Shot in the Bank', tone: 'danger',
      text: 'A shot cracks across the room. The robber’s attention returns to the line and they demand any remaining purses. You are hurt, but the crew has not yet left.',
      textVariants: [
        { requirements: { selections: { gunOutcome: 'warningShot' } }, text: 'A shot cracks into the wood above the teller counter. Nobody is visibly struck. The robber’s attention returns to the line; the room is still in danger.' },
        { requirements: { selections: { gunOutcome: 'patronWounded' } }, text: 'A shot wounds {{patron}}, who falls behind the counter but is still moving. The robbers shout for everyone to stay down.' },
        { requirements: { selections: { gunOutcome: 'patronKilled' } }, text: 'A shot strikes {{patron}}. They fall and do not move. The robbers shout for everyone to stay down; you cannot reach the patron safely while the crew still holds the room.' },
        { requirements: { selections: { gunOutcome: 'clerkKilled' } }, text: 'A shot strikes the clerk behind the counter. They fall and do not move. You cannot reach them safely while the robbers still hold the room.' },
      ],
      choices: [
        { id: 'stayDownAfterShot', label: 'Hand over your money and stay down', effects: { loseMoney: true, historyFlags: ['survived_bank_robbery', 'witnessed_shooting_during_bank_robbery'] }, next: 'robbersLeave' },
        { id: 'bandageWoundedPatron', label: 'Treat {{patron}} after the search', requirements: { selections: { gunOutcome: 'patronWounded' }, items: ['fieldBandageRoll'] }, effects: { loseItems: ['fieldBandageRoll'], loseMoney: true, historyFlags: ['survived_bank_robbery', 'witnessed_shooting_during_bank_robbery'] }, next: 'patronTreated' },
      ] },
    robberStopped: { id: 'robberStopped', title: 'The Robber Goes Down', tone: 'danger', text: 'You knock {{robber}} off balance. The second robber backs toward the door, then runs. The clerk is alive behind the counter; several patrons are shaken, and nobody mistakes the struggle for a clean victory.',
      choices: [{ id: 'checkRoomAfterStop', label: 'Check on the people in the room', effects: { historyFlags: ['survived_bank_robbery', 'intervened_in_bank_robbery'] }, next: 'safeAfterRobbery' }] },
    patronTreated: { id: 'patronTreated', title: 'After the Shot', tone: 'warning', text: 'When the robbers flee, you use your bandage on {{patron}}’s wound while the clerk sends for a doctor. Your help buys time, not a cure.', ending: 'success', choices: [] },
    robbersLeave: { id: 'robbersLeave', title: 'The Door Closes', tone: 'warning',
      text: 'The robbers leave with the money from the drawer. The front door shuts behind them. The room is shaken; nobody calls you a hero for staying alive.',
      textVariants: [
        { requirements: { historyFlags: ['concealed_property_during_robbery'] }, text: 'The robbers leave with the money from the drawer. What you concealed remains yours. The front door shuts behind them; the room is shaken, and survival is enough.' },
        { requirements: { historyFlags: ['intervened_in_bank_robbery'] }, text: 'The robbers flee after your sudden move. The clerk and patrons are shaken, and the bank’s cash is still gone. You survived, but the room did not escape without cost.' },
      ],
      ending: 'success', choices: [] },
    safeAfterRobbery: { id: 'safeAfterRobbery', title: 'When the Room Settles', tone: 'safe', text: 'The clerk checks the patrons while a neighbor runs for the local constable. You helped some people stay upright, but the robbers escaped with the bank’s cash. Nobody offers you a special reward.',
      textVariants: [{ requirements: { historyFlags: ['survived_armed_crisis'] }, text: 'The clerk checks the patrons while a neighbor runs for the local constable. You survived an armed crisis before, but this was a crowded room with no safe answer. The robbers escaped with the cash.' }],
      ending: 'success', choices: [] },
    shotPlayer: { id: 'shotPlayer', title: 'The Cost of Resistance', tone: 'danger', text: 'The robber fires before you reach them. You knowingly crossed the line of a raised revolver, and the attempt ends here.', ending: 'death', choices: [] },
  },
};
