import type { Scenario, Scene } from '../types';
import { KNOWLEDGE_FACTS } from '../knowledgeFacts';
import { largeAdventure, largeEnd, largeScene, largeTags } from './largeContentTools';

type Work = { id:string; title:string; site:string; machine:string; risk:'LOW'|'MODERATE'|'HIGH'; problem:string; clue:string; tool?:string; toolName?:string; toolAction?:string; extraTool?:{id:string;label:string}; diagnosis:string; repair:string; restart:string; complication:string; lesson:string; reward:string; rewardName:string; custodian:string; coins:number; pressure?:boolean; knowledgeFact?:keyof typeof KNOWLEDGE_FACTS };
const work: Work[] = [
  {id:'the-belt-that-slapped-back',title:'The Belt That Slapped Back',site:'water-powered grain mill',machine:'main drive belt',risk:'HIGH',problem:'The mill’s leather belt has begun to walk off its crown. The miller has stopped the wheel, but the grain crew is pressing to finish a flour order before rain.',clue:'One belt edge is polished and the other is frayed; a loose bearing bracket may have pulled the drive out of line.',tool:'foremanMultiTool',toolName:'Foreman’s Multi-tool',toolAction:'Check the bracket fasteners with your Foreman’s Multi-tool',diagnosis:'The bracket has shifted a finger’s width. Tightening it under belt tension would pull the belt harder against the frame.',repair:'Slack the belt and square the bracket before anyone touches the drive.',restart:'Turn the wheel by hand first, then let it run unloaded for one minute.',complication:'At the first slow turn the belt tracks true, but a grain sack has slipped toward the open run of the wheel.',lesson:'A belt that walks to one edge often points to alignment or bearing movement; never tighten it while the drive is under load.',reward:'pocketToolkit',rewardName:'Pocket Toolkit',custodian:'Miller Ansel Venn releases his personally owned spare Pocket Toolkit after the safe restart; the mill’s working tools remain in the shop.',coins:2},
  {id:'one-tooth-on-the-sawmill',title:'One Tooth on the Sawmill',site:'lumber camp sawmill',machine:'carriage feed rack',risk:'HIGH',problem:'A timber carriage jolts at the same point on each pass. The saw is stopped with the log clamped and the crew standing clear.',clue:'One feed tooth is bright at its tip while the next two show older dark wear.',tool:'heavyLeatherGloves',toolName:'Heavy Leather Gloves',toolAction:'Handle the exposed feed cover with Heavy Leather Gloves after the drive is isolated',diagnosis:'A splinter is wedged behind the tooth; forcing the carriage could bend the rack and send the clamped timber sideways.',repair:'Keep the saw isolated and have the sawyer secure the log before clearing the splinter with the shop hook.',restart:'Move the carriage by hand through one full pass before powering it.',complication:'The hand pass catches once at the return; the crew finds a second loose chip in the guide.',lesson:'A repeated catch at one point can come from debris in a guide; prove a free hand movement before powering a saw.',reward:'bridgewrightHammer',rewardName:'Bridgewright’s Hammer',custodian:'Sawyer Edda Marr releases a spare hammer from her own repair roll after the carriage is checked by hand.',coins:2},
  {id:'the-east-siding-points',title:'The East Siding Points',site:'rail yard east siding',machine:'hand-operated switch points',risk:'MODERATE',problem:'The points will not lie flush for the waiting freight car. The signal is at stop and no engine is approaching.',clue:'Packed gravel sits beneath the outer point; the connecting rod is dry but not bent.',tool:'pocketToolkit',toolName:'Pocket Toolkit',toolAction:'Use the Pocket Toolkit to inspect the exposed rod pin without removing it',diagnosis:'The obstruction is gravel, not a broken linkage. The switch must remain protected while the points are cleared.',repair:'Have the yard hand keep the signal at stop while you clear the loose gravel with the issued wooden scraper.',restart:'Move the lever through both positions and check the locking pin before the signal changes.',complication:'The points seat, but the lock pin catches halfway on the second throw.',lesson:'A switch lever can move while its points remain obstructed; verify the rail faces and lock before authorizing movement.',reward:'conductorWhistle',rewardName:'Conductor’s Whistle',custodian:'Yard foreman Olan Reed signs over his personally owned spare Conductor’s Whistle after the safe switch test.',coins:2},
  {id:'the-load-under-the-warehouse-hoist',title:'The Load under the Warehouse Hoist',site:'river warehouse loading bay',machine:'hand hoist and cargo sling',risk:'HIGH',problem:'A crate hangs a foot above the floor while a hoist line hums under tension. Workers are clear of the suspended load.',clue:'The brake pawl rests on only the outer edge of its ratchet tooth.',tool:'compactBlockAndTackle',toolName:'Compact Block-and-Tackle',toolAction:'Rig the Compact Block-and-Tackle to a rated floor ring before easing the load',diagnosis:'The pawl is not seated deeply enough to trust. The hoist cannot be inspected while the crate is hanging over the crew.',repair:'Clear the bay and lower the crate onto timber blocks using the hand brake in short, checked movements.',restart:'Test the empty hoist through a short lift before loading again.',complication:'The empty hook rises cleanly, but the crate’s sling has a hidden split at one seam.',lesson:'A hoist brake must hold on a fully seated tooth; a clean empty test does not certify a damaged sling.',reward:'ironRopeClamp',rewardName:'Iron Rope Clamp',custodian:'Warehouse rigger Pella Dorn gives you her separately owned spare Iron Rope Clamp after the crate is safely blocked.',coins:2},
  {id:'the-pump-below-number-three',title:'The Pump below Number Three',site:'mine pump house',machine:'reciprocating water pump',risk:'HIGH',problem:'Water is rising slowly in the lower sump. Pump Three knocks once per stroke, and the mine captain has stopped the drive before sending anyone below.',clue:'A connecting pin is dry and bright on one side; the rod has not left its guide.',tool:'fieldCalipers',toolName:'Field Calipers',toolAction:'Compare the pin’s exposed diameter with its spare using Field Calipers',diagnosis:'The pin is wearing unevenly. It may finish a short run, but a break would stop the pump and drop the rod into the pit.',repair:'Keep the pump isolated and fit the shop’s spare pin with the mine mechanic present.',restart:'Run the pump against the shallow test channel while the mechanic watches the rod.',complication:'The knock is gone, but the discharge weakens when the sump gate is opened.',lesson:'A repaired pump linkage should be tested against its working load; quiet motion alone does not prove full flow.',reward:'foldingBenchClamp',rewardName:'Folding Bench Clamp',custodian:'Mine mechanic Jori Pell releases a personal spare Folding Bench Clamp after the pin is fitted and tested.',coins:3},
  {id:'the-warm-bearing-at-noon',title:'The Warm Bearing at Noon',site:'steam-driven flour works',machine:'line-shaft bearing',risk:'MODERATE',problem:'A bearing grows warmer than the others and gives a dry rasp. The belt is stopped; flour production can wait, though the mill owner asks for a quick answer.',clue:'The oil cup is empty and the bearing cap has a dark streak at its lower edge.',tool:'pocketToolkit',toolName:'Pocket Toolkit',toolAction:'Use the Pocket Toolkit’s small oil cup to compare the bearing’s feed with the next shaft',diagnosis:'The dry cup is a likely cause, but the dark streak may mean the bearing surface is scored. Oil will not repair scoring.',repair:'Let the shaft cool, inspect the cap, then replenish the cup only if the mechanic finds no deep scoring.',restart:'Turn the shaft by hand and run it unloaded while checking temperature by touch at a safe distance.',complication:'The rasp lessens but returns under belt load, so the owner must keep this line shut until the bearing is opened.',lesson:'A dry bearing may quiet after oiling, but recurring heat or rasp under load calls for inspection, not more lubricant.',reward:'heavyLeatherGloves',rewardName:'Heavy Leather Gloves',custodian:'The millwright transfers his separately owned spare Heavy Leather Gloves for your careful shutdown and inspection.',coins:2},
  {id:'the-rivet-at-car-seven',title:'The Rivet at Car Seven',site:'freight yard repair track',machine:'freight-car drawbar keeper',risk:'MODERATE',problem:'A freight car’s keeper plate has shifted. The car is chocked on a repair track and uncoupled from the moving yard.',clue:'One rivet head is flattened while the neighboring heads remain round.',tool:'bridgewrightHammer',toolName:'Bridgewright’s Hammer',toolAction:'Check the plate seating with the Bridgewright’s Hammer without striking the rivets',extraTool:{id:'machinistFileSet',label:'Smooth a small burr on the replacement keeper edge with your Machinist’s File Set; leave the cracked hole to the fitter'},diagnosis:'The plate has worked loose around one rivet; hammering it in place could hide a cracked hole.',repair:'Keep the car chocked and ask the rail fitter to inspect the plate before replacing its fastener.',restart:'Move the empty car a few feet under a yard hand’s watch, then recheck the keeper.',complication:'The plate stays aligned in the short move, but the neighboring rivet hole shows a hairline crack.',lesson:'A flattened rivet can indicate movement around its hole; inspect the plate before tightening or covering the mark.',reward:'compactWheelWrench',rewardName:'Compact Wheel Wrench',custodian:'The fitter releases a separately owned Compact Wheel Wrench after the damaged car is tagged for shop repair.',coins:2},
  {id:'the-semaphore-in-the-rain',title:'The Semaphore in the Rain',site:'rail junction signal post',machine:'counterweighted semaphore linkage',risk:'MODERATE',problem:'The arm moves slowly and stops short of its danger position. The dispatcher has held trains outside the junction.',clue:'Water has entered the lower linkage cover; the counterweight wire is slack but intact.',tool:'foldingCardMirror',toolName:'Folding Card Mirror',toolAction:'Use a Folding Card Mirror to see the lower rod joint without putting a hand inside',diagnosis:'The joint is binding at the cover edge. The arm’s position cannot be trusted until the full travel is checked.',repair:'Keep the signal at stop and have the signalman clear the cover drain with the issued brush.',restart:'Move the arm by hand through its full arc and verify both stops with the dispatcher.',complication:'The arm now travels freely, but rain obscures the far approach; the dispatcher keeps the junction closed until visibility improves.',lesson:'A free-moving signal is not enough; its full travel and the sight line must both be verified before traffic resumes.',reward:'roadmansLantern',rewardName:'Roadman’s Lantern',custodian:'Signalman Vey Orlo gives you his personally owned spare Roadman’s Lantern for the careful inspection.',coins:2},
  {id:'the-grain-under-the-guard',title:'The Grain under the Guard',site:'county grain mill',machine:'bucket elevator lower shoe',risk:'HIGH',problem:'Grain has spilled beneath the elevator guard and the belt slows each turn. The miller has stopped the drive; no one is reaching into the moving machinery.',clue:'The guard is bowed outward where damp grain has packed behind it.',tool:'heavyLeatherGloves',toolName:'Heavy Leather Gloves',toolAction:'Use Heavy Leather Gloves to handle the guard only after the belt is isolated',diagnosis:'The belt may be intact; the packed grain is loading the lower shoe and could catch the buckets if restarted.',repair:'Lock the drive out, remove the guard, and clear the packed grain with the miller’s wooden paddle.',restart:'Turn the elevator by hand before starting it empty.',complication:'The empty run clears, but the lower shoe leaks grain again when the feed gate opens.',lesson:'A belt slowing under a packed shoe should be isolated and cleared; restarting against the blockage can damage the buckets.',reward:'lanternGuard',rewardName:'Lantern Guard',custodian:'Miller Halda Voss releases a spare Lantern Guard from her personal kit after you prevent a loaded restart.',coins:2},
  {id:'the-hoist-that-would-not-set-down',title:'The Hoist That Would Not Set Down',site:'quarry loading platform',machine:'stone-block hoist brake',risk:'HIGH',problem:'A stone block hangs above the loading platform. The hand brake slips a fraction each time the crew tries to lower it.',clue:'The brake band is shiny at one end and its adjusting nut has backed away from the witness mark.',tool:'lineTensionGauge',toolName:'Line Tension Gauge',toolAction:'Compare the hoist line pull from outside the exclusion zone with the Line Tension Gauge',diagnosis:'The brake adjustment has shifted, but the line’s uneven pull means the load may also be off-center.',repair:'Clear the platform and lower the block onto cribbing with the quarry rigger controlling the brake.',restart:'Test the empty drum and brake through several turns before lifting any stone.',complication:'The brake holds empty, while the block’s lifting eye is found bent and must be replaced before another lift.',lesson:'A brake test without load confirms its motion, not its holding strength; keep people clear until the rig is inspected under controlled load.',reward:'compactBlockAndTackle',rewardName:'Compact Block-and-Tackle',custodian:'Quarry rigger Senn gives you a separately owned spare Compact Block-and-Tackle after the block is safely grounded.',coins:3},
  {id:'the-lathe-chip',title:'The Lathe Chip',site:'machine shop',machine:'belt-driven lathe',risk:'MODERATE',problem:'A lathe leaves a rough spiral on a shaft. The operator has stopped the spindle, but the foreman wants the order finished before the rail crew returns.',clue:'The tool rest is loose and a thin curl of metal is caught beneath its clamp.',tool:'machinistFileSet',toolName:'Machinist’s File Set',toolAction:'Use your Machinist’s File Set to compare the burr after the spindle is isolated',diagnosis:'The loose rest can chatter against the work. Filing the shaft now would remove material without correcting the movement.',repair:'Re-seat the tool rest and have the machinist check the blank before taking another cut.',restart:'Run a shallow test cut on scrap stock and inspect the surface before returning to the order.',complication:'The scrap cut is smooth, but the ordered shaft is already undersize from earlier cuts and must be replaced.',lesson:'A rough cut can come from a loose rest; finishing the surface before fixing the support only hides the cause.',reward:'machinistFileSet',rewardName:'Machinist’s File Set',custodian:'Machinist Orren Pike transfers his personally owned spare Machinist’s File Set after your test identifies the loose rest.',coins:2},
  {id:'the-winches-uneven-pull',title:'The Winch’s Uneven Pull',site:'ore tram incline',machine:'hand winch and haul line',risk:'HIGH',problem:'A loaded ore tub climbs crookedly and one side of the drum winds faster. The crew has stopped the tub on a clear stretch of track.',clue:'The line coils overlap on one drum cheek; the anchor bolts remain seated.',tool:'lineTensionGauge',toolName:'Line Tension Gauge',toolAction:'Compare the two line legs with a Line Tension Gauge from behind the barrier',diagnosis:'The winding is uneven and may side-load the drum. The tub must not be pulled farther until the line is paid out safely.',repair:'Set the brake, clear the track, and re-spool the line with the mine winch operator.',restart:'Run the empty tub a short distance and inspect the drum before loading ore.',complication:'The empty run tracks evenly, but the loaded tub reveals a flat spot in one wheel.',lesson:'Even line tension cannot correct a damaged wheel; test the whole haul system before returning a load to service.',reward:'ironRopeClamp',rewardName:'Iron Rope Clamp',custodian:'The mine operator gives you a personally owned spare Iron Rope Clamp after the winch line is re-spooled.',coins:2},
  {id:'the-steam-pipe-behind-the-washroom',title:'The Steam Pipe behind the Washroom',site:'rail depot washroom annex',machine:'low-pressure steam heating line',risk:'HIGH',problem:'A pipe joint hisses behind a screen and warm water beads along the floor. Workers have already moved away from the leak.',clue:'The joint’s paint is blistered, but the pressure needle is still within its marked working band.',tool:'heavyLeatherGloves',toolName:'Heavy Leather Gloves',toolAction:'Use Heavy Leather Gloves to move the screen only after the steam valve is shut',diagnosis:'The leak is at a threaded joint. The gauge does not show an emergency overpressure, but escaping steam can still scald.',repair:'Close the branch valve and call the depot fitter; do not tighten a hot, pressurized fitting.',restart:'Let the fitter cool and reseal the joint, then reopen the valve gradually while watching the gauge.',complication:'The joint stays dry, but condensation reveals a second weak seam farther down the line.',lesson:'A normal gauge reading does not make a leaking steam joint safe to handle; isolate, cool, and inspect the full branch.',reward:'smokeHood',rewardName:'Smoke Hood',custodian:'Depot keeper Lysa Pell releases a separately owned Smoke Hood after the leak is isolated and the fitter takes over.',coins:2},
  {id:'the-tool-peg-on-night-shift',title:'The Tool Peg on Night Shift',site:'rail engine shed',machine:'shared tool board and wheel-drop table',risk:'LOW',problem:'A wheel-drop table is ready for a repair, but the box spanner listed on the board is missing. The engine is secured and the crew can wait.',clue:'The board’s chalk count is fresh, while the sign-out slate ends before the previous shift change.',tool:'foldingCardMirror',toolName:'Folding Card Mirror',toolAction:'Use a Folding Card Mirror to check the dark gap below the tool bench without reaching in',diagnosis:'The tool is absent from the board but its whereabouts remain unknown. The missing sign-out line is a record gap, not proof of theft.',repair:'Check the tool crib and ask both shifts before opening personal kits.',restart:'Resume only after the proper box spanner is found and the wheel-drop table is checked empty.',complication:'The spanner is found in the fitter’s locked drawer, put away after a late repair but not entered on the slate.',lesson:'A missing shared tool and an incomplete sign-out record do not establish theft; reconcile custody before blaming a worker.',reward:'foldingPryTool',rewardName:'Folding Pry Tool',custodian:'Fitter Ren Davi releases a retired Folding Pry Tool from his own kit after the missing spanner is found and returned.',coins:1},
  {id:'the-misfed-grain-gate',title:'The Misfed Grain Gate',site:'river grain elevator',machine:'gravity feed gate',risk:'MODERATE',problem:'Grain continues to trickle after the receiving bin is full. The gate wheel turns, but the flow does not stop cleanly.',clue:'A wooden stop is split and the gate stem has a polished band near its closed position.',tool:'foremanMultiTool',toolName:'Foreman’s Multi-tool',toolAction:'Inspect the stop and stem with the Foreman’s Multi-tool without forcing the wheel',diagnosis:'The split stop lets the gate drift back open. The bin is not yet overflowing, but a hard turn could shear the stem.',repair:'Close the upstream chute and replace the stop with the mill’s spare hardwood block.',restart:'Feed a small measure first and watch the gate hold before restoring the full flow.',complication:'The gate holds at low flow, but a second bin is found damp from an earlier leak.',lesson:'A gate that drifts near closed may have a failed stop; isolate the feed before adjusting the stem.',reward:'carpenterSquare',rewardName:'Carpenter’s Square',custodian:'The grain master transfers an unused Carpenter’s Square from his personal toolbox after the stop is replaced.',coins:2},
  {id:'the-dragging-brake-at-bell-yard',title:'The Dragging Brake at Bell Yard',site:'rail freight inspection track',machine:'freight car brake shoe',risk:'MODERATE',problem:'One car rolls slowly after the brake is released. It is chocked on a level inspection track with the crew clear.',clue:'The left shoe remains close to the wheel while the right linkage returns fully.',tool:'compactWheelWrench',toolName:'Compact Wheel Wrench',toolAction:'Compare the linkage nut positions with your Compact Wheel Wrench as a gauge, without turning them',extraTool:{id:'machinistFileSet',label:'Remove only the confirmed burr from a detached brake-shoe edge with your Machinist’s File Set'},diagnosis:'A return spring is stretched. Tightening the nut could make the shoe bind harder against the wheel.',repair:'Keep the car chocked and have the rail fitter replace the spring before movement.',restart:'Roll the empty car a short distance and confirm both shoes clear before reconnecting it.',complication:'Both shoes clear, but the car’s loaded test is postponed until the track crew checks the whole consist.',lesson:'A brake that drags after release may have a weak return spring; do not adjust a linkage before identifying which part fails.',reward:'compactWheelWrench',rewardName:'Compact Wheel Wrench',custodian:'Rail fitter Sal Meeks releases a duplicate Compact Wheel Wrench from his personal roll after the brake is repaired.',coins:2},
  {id:'the-shaft-marks-at-ash-mill',title:'The Shaft Marks at Ash Mill',site:'old watermill workshop',machine:'mill shaft and wooden bearing blocks',risk:'MODERATE',problem:'A shaft scrapes once each turn after the mill wheel is brought back into service. The water gate is closed and the wheel is stationary.',clue:'A fresh bright arc appears on one side of the shaft; the bearing block shows old compression marks on the opposite side.',tool:'fieldCalipers',toolName:'Field Calipers',toolAction:'Compare shaft diameter at the bright arc and an unworn section with Field Calipers',diagnosis:'The shaft may be out of round or the block misaligned. The marks do not show which changed first.',repair:'Keep the wheel gated while the millwright checks the block seat and shaft at several points.',restart:'Turn the wheel by hand with the belt removed before restoring the drive.',complication:'The hand turn clears, but the millwright finds the old block has compressed unevenly and needs replacement.',lesson:'A wear arc can locate rubbing but not prove its cause; compare the shaft and bearing seat before realigning.',reward:'brassPlumbBob',rewardName:'Brass Plumb Bob',custodian:'Millwright Sora Vale releases her personally owned spare Brass Plumb Bob after the bearing alignment is recorded.',coins:2},
  {id:'the-sorting-table-jam',title:'The Jam at the Sorting Table',site:'rail parcel depot',machine:'hand-fed sorting table rollers',risk:'LOW',problem:'Parcels bunch before a roller and the table stops. No powered conveyor is present; workers turn the rollers by hand.',clue:'A torn paper label is wound around one roller and the bearing cap is still cool.',tool:'pocketToolkit',toolName:'Pocket Toolkit',toolAction:'Use the Pocket Toolkit’s pliers to lift the label after the table is blocked from movement',diagnosis:'The jam is paper at the roller, not a seized bearing. Pulling against the roller could tear a parcel or cut a hand.',repair:'Block the roller and unwind the label with the depot clerk holding the parcel queue.',restart:'Turn the empty roller by hand and feed one parcel at a time.',complication:'The table runs, but one parcel has no destination label and must be held for the sender.',lesson:'A cool bearing and visible wrapped material point to a feed jam; isolate the roller before removing it.',reward:'foldingBenchClamp',rewardName:'Folding Bench Clamp',custodian:'Depot clerk Mal Orr gives you his personally owned spare Folding Bench Clamp after the sorting table is cleared.',coins:1,knowledgeFact:'sortingTableFeedJam'},
  {id:'the-cable-over-foundry-road',title:'The Cable over Foundry Road',site:'foundry yard crossing',machine:'manual overhead transfer cable',risk:'MODERATE',problem:'A suspended ladle carrier waits above a marked clear lane. A worker has stepped past the line to retrieve a dropped hook.',clue:'The cable sags more than the chalk mark on its support post; the load is still locked at the near stop.',tool:'lineTensionGauge',toolName:'Line Tension Gauge',toolAction:'Compare the two visible cable spans with the Line Tension Gauge from behind the barrier',diagnosis:'The line has stretched or the load has shifted. The carrier must not travel above anyone until the rigger inspects the anchor.',repair:'Warn the worker back, lock the carrier at the stop, and have the rigger check both anchors.',restart:'Run the empty carrier along the near section only after the rigger signs off the line.',complication:'The empty carrier moves freely, but a cracked anchor plate keeps the loaded route closed.',lesson:'A tension reading compares spans but cannot certify an anchor; inspect the full load path and keep people out from beneath it.',reward:'ironRopeClamp',rewardName:'Iron Rope Clamp',custodian:'Rigger Toma Pell gifts a separately owned Iron Rope Clamp after the crew secures the crossing and tags the cracked plate.',coins:2},
  {id:'the-ore-cart-on-the-incline',title:'The Ore Cart on the Incline',site:'mine tram incline',machine:'gravity tram brake and wheel chock',risk:'HIGH',problem:'An ore cart stands on a shallow incline with its brake lever down. The wheel chock has shifted but the cart has not moved.',clue:'The brake handle reaches its stop before the shoe touches the wheel.',tool:'compactWheelWrench',toolName:'Compact Wheel Wrench',toolAction:'Inspect the brake shoe gap with a Compact Wheel Wrench held as a spacer, not a lever',diagnosis:'The linkage is worn and the chock is the only reliable restraint. No one should work downhill of the cart.',repair:'Add a second timber chock from uphill and unload the cart before the mechanic adjusts the linkage.',restart:'Test the empty cart against the chocks while the crew stays outside its downhill path.',complication:'The brake catches empty, but one wheel has a cracked rim and the cart remains out of service.',lesson:'A brake handle at its stop does not prove the shoe is engaged; secure a vehicle independently before repair.',reward:'steelWedge',rewardName:'Steel Wedge',custodian:'Mine mechanic Rell Voss releases a spare Steel Wedge from his personal tool chest after the cart is chocked.',coins:2},
  {id:'the-bell-before-the-restart',title:'The Bell before the Restart',site:'textile mill night shift',machine:'belt drive and hand warning bell',risk:'MODERATE',problem:'A repaired belt is ready for a trial, but the warning bell gives no sound from the far end of the room.',clue:'The clapper moves freely; a folded rag has been placed inside the bell mouth to quiet it.',tool:'conductorWhistle',toolName:'Conductor’s Whistle',toolAction:'Use the Conductor’s Whistle to test whether the crew can hear a signal from the far platform',diagnosis:'The bell is deliberately muffled, though no one knows by whom. Restarting without a clear warning would leave workers unaware.',repair:'Keep the belt stopped, remove the rag in view of the crew, and agree on a whistle-and-hand signal.',restart:'Sound the agreed warning, wait for each station’s response, then run the belt empty.',complication:'The crew answers the whistle, but the shift foreman admits the rag was used to spare a sleeping neighbor; the practice has to change.',lesson:'A warning device only protects workers if its signal is audible, agreed, and answered before motion starts.',reward:'conductorWhistle',rewardName:'Conductor’s Whistle',custodian:'Foreman Elsi Marr releases a second, personally owned Conductor’s Whistle after the crew adopts the tested restart signal.',coins:2},
  {id:'the-oil-on-the-switch-rod',title:'The Oil on the Switch Rod',site:'rail repair shed',machine:'siding switch linkage',risk:'LOW',problem:'A switch rod moves stiffly after a rainstorm. The crew has protected the siding and traffic is held outside the yard.',clue:'Oil darkens the near joint, but grit has collected at the far pin.',tool:'pocketToolkit',toolName:'Pocket Toolkit',toolAction:'Use the Pocket Toolkit’s driver to remove the accessible cover screw after the rod is secured',diagnosis:'Adding more oil would trap grit at the far pin. The rod needs cleaning before lubrication.',repair:'Keep the switch protected, brush the pin clean with the fitter’s rag, then apply a small amount of oil.',restart:'Throw the switch twice and check that the locking pin seats each time.',complication:'The rod moves freely, but the lock hole is oval from wear and the switch stays tagged for replacement.',lesson:'Lubrication cannot correct a worn joint; clean grit first and check that the lock still seats under movement.',reward:'pocketToolkit',rewardName:'Pocket Toolkit',custodian:'Rail fitter Pavin Holt signs over a personally owned spare Pocket Toolkit after the linkage is cleaned and tagged for repair.',coins:1},
  {id:'the-sparks-at-the-belt-house',title:'The Sparks at the Belt House',site:'ore crusher belt house',machine:'leather drive belt and iron pulley',risk:'HIGH',problem:'A brief spark appears near the belt splice. The crusher has stopped, and workers are gathering outside the belt room.',clue:'The pulley rim is scraped and the belt splice has a frayed edge; no fire has started.',tool:'heavyLeatherGloves',toolName:'Heavy Leather Gloves',toolAction:'Use Heavy Leather Gloves only after the drive is isolated to inspect the splice edge',diagnosis:'A metal buckle may be striking the pulley. Restarting could throw the belt or ignite oil-soaked dust nearby.',repair:'Keep the room clear, remove loose oil rags, and have the mechanic replace the damaged splice.',restart:'Turn the pulley by hand and inspect the full belt path before a short unloaded run.',complication:'The new splice clears the rim, but the crew finds oil-soaked waste beneath the bearing and removes it before restart.',lesson:'Sparks near a belt demand shutdown and a check for both mechanical contact and combustible residue.',reward:'smokeHood',rewardName:'Smoke Hood',custodian:'Crusher foreman Nera Vale releases her personally owned spare Smoke Hood after the belt room is cleared and inspected.',coins:3},
  {id:'the-slow-wheel-at-copper-mill',title:'The Slow Wheel at Copper Mill',site:'copper stamping works',machine:'steam-driven flywheel linkage',risk:'MODERATE',problem:'The flywheel slows once each turn under a light test. The operator has disengaged the press and the crew is behind the painted line.',clue:'A linkage pin shines on one side and the counterweight chain clicks against its guard.',tool:'fieldCalipers',toolName:'Field Calipers',toolAction:'Compare the pin diameter at its worn and unworn sides with Field Calipers',diagnosis:'The pin is worn and the chain guard loose; either can cause the repeating sound, and neither is safe to ignore.',repair:'Keep the press disengaged while the operator replaces the pin and fastens the guard.',restart:'Turn the wheel by hand, then run one unloaded cycle with the crew behind the line.',complication:'The click is gone, but the press still slows under a blank, so the operator schedules a full drive inspection.',lesson:'A repeating sound can have more than one source; isolate each moving part and test under load only after a safe unloaded cycle.',reward:'fieldCalipers',rewardName:'Field Calipers',custodian:'The operator gives you a separately owned spare pair of Field Calipers after you help isolate both sources of the noise.',coins:2},
];

const s = (id:string,title:string,text:string,choices:Scene['choices'],textVariants?:Scene['textVariants']) => largeScene(id,title,text,choices,undefined,textVariants);
const e = (id:string,title:string,text:string) => largeEnd(id,title,text);
const pay = (item:string,source:string,flag:string) => ({gainItems:[item],gainItemProvenance:{[item]:source},historyFlags:[flag]});
const learnedLesson = (w:Work) => w.knowledgeFact ? {knowledgeEntries:[KNOWLEDGE_FACTS[w.knowledgeFact]]} : {knowledge:[w.lesson]};
const make = (w:Work):Scenario => {
  const inspection:Scene['choices'] = [
    {id:'inspect',label:w.toolAction ?? 'Inspect the moving parts from outside the marked work zone',next:'diagnose',...(w.tool?{requirements:{items:[w.tool]}}:{}),effects:{setFlags:['usedIndustrialGear']}},
    {id:'observe',label:'Watch one stopped cycle and compare the wear marks',next:'diagnose'},
    {id:'warn',label:'Keep the machine isolated and clear the nearby crew',next:'shutdown',effects:{setFlags:['choseShutdown']}},
  ];
  // A tool callback is optional; keep a no-Gear inspection route available.
  if (w.tool) inspection[0] = {id:'inspect',label:w.toolAction!,next:'diagnose',requirements:{items:[w.tool]},effects:{setFlags:['usedIndustrialGear']}};
  const scenes:Record<string,Scene> = {
    inspect:s('inspect','Stopped Before the Fault',`${w.problem} ${w.clue} The equipment is stopped or isolated before you approach; the foreman asks for practical help, not a guess about the machine.`,inspection),
    diagnose:s('diagnose','A Cause, Not Yet a Repair',`${w.diagnosis} ${w.complication}`,[
      {id:'repair',label:w.repair,next:'test',effects:{setFlags:['choseRepair']}},
      {id:'hold',label:'Leave the machine stopped and ask the responsible fitter to take over',next:'shutdown',effects:{...learnedLesson(w),setFlags:['choseShutdown']}},
      {id:'rush',label:'Tell the foreman to resume the full job without a test',next:'unsafe',effects:{setFlags:['choseRush']}},
      ...(w.extraTool?[{id:'useSpecialistFile',label:w.extraTool.label,next:'test',requirements:{items:[w.extraTool.id]},effects:{setFlags:['usedSpecialistFile']}}]:[]),
    ]),
    test:s('test','A Test Is Another Decision',`${w.restart} ${w.complication} A safe short test can reveal a remaining fault; it cannot certify every part of the machine.`,[
      {id:'slow',label:'Run the controlled test described by the operator',next:'settle',effects:{...learnedLesson(w),setFlags:['testedCarefully']}},
      {id:'stopAgain',label:'Stop at the first irregular movement and call the fitter',next:'shutdown',effects:{...learnedLesson(w),setFlags:['choseShutdown']}},
      {id:'fullLoad',label:'Put the machine straight back to its full work load',next:'unsafe',effects:{...learnedLesson(w),setFlags:['choseRush']}},
    ]),
    shutdown:s('shutdown','Work Held for a Reason',`You keep the ${w.machine} out of service. The crew moves clear, and the responsible operator takes over the repair or inspection. The delay costs production, but the unresolved condition is not passed to the next shift.`,[
      {id:'closeOut',label:'Record the fault and accept the partial work payment',next:'partial',effects:{...learnedLesson(w),setFlags:['partialWork']}},
      {id:'stay',label:'Wait for the fitter and help verify the hand test',next:'settle',effects:{...learnedLesson(w),setFlags:['testedCarefully']}},
    ]),
    unsafe:s('unsafe','The Full Load Finds the Weak Point',`The untested ${w.machine} jolts under load. The crew hits the stop and steps clear; a small part is damaged, but the clear work zone prevents an injury. The production order is delayed while the fitter checks the machine.`,[
      {id:'secure',label:'Keep the drive isolated and help account for the damaged parts',next:'settle',effects:{...learnedLesson(w),setFlags:['choseRush','partialWork']}},
      {id:'withdraw',label:'Leave the repair to the fitter and report what moved',next:'partial',effects:{...learnedLesson(w),setFlags:['partialWork']}},
    ]),
    settle:{...s('settle','The Work and Its Limits',`${w.machine} is either safely tested, left isolated for the fitter, or stopped after an irregular full-load attempt. The foreman confirms the fault report before discussing your compensation.`,[
      {id:'wage',label:`Take the ${w.coins}-coin work fee`,next:'paid',effects:{...learnedLesson(w),money:w.coins}},
      {id:'declineFee',label:'Decline the fee',next:'unpaid',effects:learnedLesson(w)},
      {id:'gear',label:`Accept the released ${w.rewardName} as wages`,next:'kept',requirements:{notOwnedItems:[w.reward]},effects:{...learnedLesson(w),...pay(w.reward,`${w.custodian} The operational machine and employer-owned tools remain with the worksite.`,`earned_industrial_${w.id}`)}},
    ]),textVariants:[
      {requirements:{flags:['testedCarefully']},text:`The controlled test gives the crew a result without promising more than it checked. ${w.complication}`},
      {requirements:{flags:['choseShutdown']},text:'The work stays stopped for the fitter. Your decision prevents an unresolved machine state from being treated as a safe restart.'},
      {requirements:{flags:['choseRush']},text:'The rushed restart damages a small part and costs the shift time. No one is injured, but the fitter must complete the inspection before work resumes.'},
    ]},
    partial:e('partial','A Responsible Hold',`You leave the ${w.machine} isolated and take one coin for the inspection already completed. The fault report identifies what remains for the fitter.`),
    paid:e('paid','Work Accounted For',`You take ${w.coins} coins for the inspection and work. ${w.lesson}`),
    unpaid:e('unpaid','No Fee Taken',`You decline payment. The ${w.machine} remains in the state agreed with the foreman, and the practical lesson stays with you: ${w.lesson}`),
    learned:e('learned','A Method Worth Keeping',`You retain the practical rule: ${w.lesson}`),
    kept:e('kept','A Tool from the Work Roll',`${w.custodian} You take the ${w.rewardName}; it supports practical work but does not make an unsafe machine safe.`),
  };
  const tags = largeTags({hook:`${w.machine} creates a worksite problem: ${w.problem}`,role:'worker',activity:'labor/repair',tone:w.risk==='LOW'?'adventurous':'tense/dangerous',risk:w.risk,setting:w.site,fantasy:'NONE',combat:'NONE',structures:['worksite inspection','diagnosis before repair','restart or shutdown consequence','performance-based compensation'],entry:['hired/posted work','accidental encounter'],rewards:['Gear','coins','Knowledge'],outcomes:['success/partial success','walk-away/refusal','costly success/no-perfect-outcome possible']});
  return largeAdventure(w.id,w.title,`A practical failure in the ${w.machine} turns a shift into a safety decision.`,tags,'inspect',scenes);
};
export const INDUSTRIAL_MILL_RAIL_GEAR_BATCH:Scenario[] = work.map(make);
