import type { Scenario } from '../types';

export const THE_LOOSE_TEAM: Scenario = {
  id: 'the-loose-team', title: 'The Loose Team', subtitle: 'A runaway wagon is bearing down on a road junction.', startScene: 'roadJunction',
  timePhases: [{ id: 'clear', label: 'Clear Road', atMinutes: 0 }, { id: 'closing', label: 'Wagon Closing', atMinutes: 3 }, { id: 'lastSeconds', label: 'Moments to Act', atMinutes: 6 }],
  runRandomSelections: [{ id: 'handler', values: ['Irena', 'Joric', 'Solvi', 'Edric', 'Nomi'].map((value) => ({ value })) }],
  scenes: {
    roadJunction: { id: 'roadJunction', title: 'Wheels Without a Driver', tone: 'warning', text: 'You stand on the uphill shoulder above the fork. Two horses pull an empty wagon downhill toward you; their handler, {{handler}}, is running behind the wagon, farther up the road. Two workers are crossing the fork beside a stone marker. An openable gate on your left leads into an empty pasture beside the road.', choices: [
      { id: 'warnWorkers', label: 'Shout for the road workers to clear the fork', hint: 'They can step behind the stone marker if they hear you in time.', timeCost: 1, chance: { probability: 0.82, lateProbability: 0.61, lateAfterMinutes: 3, successNext: 'workersClear', failureNext: 'wagonAtFork', successMessage: 'The workers hear you and scramble behind the marker.', failureMessage: 'The wheels drown your warning. The workers are still in the wagon’s path.', successEffects: { setFlags: ['workersWarned'], historyFlags: ['warned_road_workers'] }, failureEffects: { setFlags: ['workerWarningFailed'] } } },
      { id: 'openPastureGate', label: 'Open the pasture gate ahead of the wagon', hint: 'The gate swings away from the road into an empty field.', timeCost: 1, chance: { probability: 0.66, lateProbability: 0.43, lateAfterMinutes: 3, bonusItems: ['gateHook', 'foldingPryTool'], bonusProbability: 0.14, successNext: 'horsesTurned', failureNext: 'wagonAtFork', successMessage: 'The gate catches the wagon’s eye line; the horses veer into the empty pasture.', failureMessage: 'The latch sticks. The team is almost at the fork.' } },
      { id: 'throwRopeAcrossRoad', label: 'Secure a rope across the safe approach', requirements: { items: ['travelRope'] }, hint: 'An anchored line may slow the wagon, but standing in its path could pull you under it.', timeCost: 1, chance: { probability: 0.57, lateProbability: 0.36, lateAfterMinutes: 3, bonusItems: ['ironRopeClamp', 'freightmansStrap'], bonusProbability: 0.1, successNext: 'wagonTurned', failureNext: 'wagonAtFork', successMessage: 'The line catches the wagon rail and turns its front wheels toward the pasture gate.', failureMessage: 'The line snaps taut and tears free before the wagon reaches it.', failureEffects: { health: -2, historyFlags: ['rope_failed_against_runaway_wagon'] } } },
      { id: 'runAlongside', label: 'Try to reach the horses from the shoulder', hint: 'The downhill pace is dangerous; a fall could put you beneath the wheels.', timeCost: 1, chance: { probability: 0.36, lateProbability: 0.22, lateAfterMinutes: 3, bonusItems: ['heavyLeatherGloves'], bonusProbability: 0.08, successNext: 'teamStopped', failureNext: 'wagonAtFork', successMessage: 'You catch the lead rein from the shoulder and pull the team toward the pasture.', failureMessage: 'A hoof knocks you into the road edge. The team keeps going.', failureEffects: { health: -4, historyFlags: ['injured_near_runaway_team'] } } },
    ] },
    workersClear: { id: 'workersClear', title: 'The Fork Is Clear', tone: 'warning', text: 'The workers are behind the stone marker. {{handler}} is still running behind the wagon, and the open pasture gate lies ahead on the left. The team can still strike the fence or overturn if nothing changes.', choices: [
      { id: 'openGateNow', label: 'Open the pasture gate for the horses', timeCost: 1, chance: { probability: 0.75, lateProbability: 0.51, lateAfterMinutes: 3, bonusItems: ['gateHook', 'foldingPryTool'], bonusProbability: 0.12, successNext: 'horsesTurned', failureNext: 'wagonAtForkAfterWarning', successMessage: 'The horses turn through the gate, and the wagon rolls into the empty pasture.', failureMessage: 'The gate catches on its post as the wagon reaches the fork.' } },
      { id: 'helpHandler', label: 'Call to guide {{handler}} to the marker', hint: 'You remain on the safe shoulder; crossing the road to reach them would put you in front of the team.', timeCost: 1, chance: { probability: 0.75, lateProbability: 0.54, lateAfterMinutes: 3, successNext: 'handlerSafe', failureNext: 'wagonAtForkAfterWarning', successMessage: '{{handler}} hears you and runs to the marker without crossing in front of the horses.', failureMessage: 'The wagon drowns your call. {{handler}} is still behind the team.', successEffects: { historyFlags: ['guided_team_handler_to_safety'] } } },
      { id: 'signalTeam', label: 'Use a whistle to turn the horses', requirements: { anyItems: ['farmWhistle', 'conductorWhistle', 'trailWhistle'] }, timeCost: 1, chance: { probability: 0.68, lateProbability: 0.48, lateAfterMinutes: 3, successNext: 'horsesTurned', failureNext: 'wagonAtForkAfterWarning', successMessage: 'The familiar sharp call makes the horses turn toward the open pasture.', failureMessage: 'The team is too panicked to respond to the whistle.' } },
    ] },
    handlerSafe: { id: 'handlerSafe', title: 'Clear of the Wheels', tone: 'warning', text: '{{handler}} reaches the stone marker beside the workers. No one is in the wagon’s path now. The pasture gate remains open, but the wagon is nearly at the fork.', choices: [
      { id: 'guideIntoPasture', label: 'Guide the wagon through the open gate', timeCost: 1, chance: { probability: 0.64, lateProbability: 0.42, lateAfterMinutes: 3, successNext: 'horsesTurned', failureNext: 'wagonLost', successMessage: 'The horses angle into the field and the wagon slows in soft ground.', failureMessage: 'The wagon misses the gate and rattles through the fork.' } },
      { id: 'stayBehindMarker', label: 'Stay safe and let the wagon pass', hint: 'The workers and handler are out of the road; the wagon may be damaged.', next: 'wagonLost' },
    ] },
    wagonAtFork: { id: 'wagonAtFork', title: 'The Fork Arrives', tone: 'danger', text: 'The wagon reaches the fork, wheels bouncing over the junction stones. You remain on the uphill shoulder, in front of the team; {{handler}} is still running behind it. The workers are beside the marker unless your warning reached them. The pasture gate is beside the road.', textVariants: [{ requirements: { flags: ['workerWarningFailed'] }, text: 'The wagon reaches the fork, wheels bouncing over the junction stones. You remain on the uphill shoulder, in front of the team; {{handler}} is behind it. Your warning failed, and the workers are still in the wagon’s path beside the marker.' }], choices: [
      { id: 'callHandlerToMarker', label: 'Shout for {{handler}} to reach the marker', hint: 'You cannot reach them without crossing in front of the horses. A clear call may guide them out.', timeCost: 1, chance: { probability: 0.65, lateProbability: 0.44, lateAfterMinutes: 3, successNext: 'handlerSafe', failureNext: 'wagonLost', successMessage: '{{handler}} hears you, veers clear of the wagon, and reaches the marker.', failureMessage: 'Your call is lost in the wheel noise; the wagon swings past the marker.', successEffects: { historyFlags: ['guided_team_handler_to_safety'] } } },
      { id: 'openGateLate', label: 'Throw open the pasture gate', timeCost: 1, chance: { probability: 0.43, lateProbability: 0.28, lateAfterMinutes: 3, successNext: 'horsesTurned', failureNext: 'wagonLost', successMessage: 'The horses take the opening and the wagon overturns harmlessly in soft grass.', failureMessage: 'The wagon clips the gatepost and overturns on the verge.' } },
      { id: 'grabLeadRein', label: 'Grab the lead rein beside the wheel', hint: 'The wagon is already bouncing over stones; one slip could put you beneath it.', timeCost: 1, chance: { probability: 0.2, lateProbability: 0.1, lateAfterMinutes: 3, successNext: 'teamStopped', failureNext: 'playerDies', successMessage: 'You catch the rein and pull the team toward the pasture before the wagon passes.', failureMessage: 'The rein yanks you under the wagon’s wheel.' } },
      { id: 'takeCover', label: 'Get behind the stone marker', hint: 'The marker protects you; the wagon and team may be lost.', next: 'wagonLost' },
    ] },
    wagonAtForkAfterWarning: { id: 'wagonAtForkAfterWarning', title: 'The Fork Arrives', tone: 'danger', text: 'The workers are behind the stone marker, but the wagon reaches the fork before the gate opens. You remain on the uphill shoulder ahead of the team; {{handler}} is still running behind it. The wheels bounce over the junction stones.', choices: [
      { id: 'callHandlerClearAfterWarning', label: 'Shout for {{handler}} to reach the marker', hint: 'The workers are safe, but you cannot cross in front of the horses to reach the handler.', timeCost: 1, chance: { probability: 0.65, lateProbability: 0.44, lateAfterMinutes: 3, successNext: 'handlerSafe', failureNext: 'wagonLost', successMessage: '{{handler}} hears you and reaches the marker behind the workers.', failureMessage: 'The wagon drowns your call and swings past the marker.' } },
      { id: 'takeCoverAfterWarning', label: 'Stay behind the marker', next: 'wagonLost' },
    ] },
    horsesTurned: { id: 'horsesTurned', title: 'The Team Leaves the Road', tone: 'safe', ending: 'success', choices: [], text: 'The horses enter the empty pasture and the wagon slows in the soft field. {{handler}} catches up and checks their legs. The workers get clear once the team turns off the road. The wagon needs repair, but no one is run down.', textVariants: [{ requirements: { flags: ['workersWarned'] }, text: 'The horses enter the empty pasture and the wagon slows in the soft field. {{handler}} catches up and checks their legs. The workers remain safely behind the marker, where your warning sent them. The wagon needs repair, but no one is run down.' }, { requirements: { flags: ['workerWarningFailed'] }, text: 'The horses turn into the empty pasture. The wagon swings away from the workers, who scatter behind the marker only after the road clears. {{handler}} catches up to check the horses. The wagon needs repair, but no one is run down.' }] },
    wagonTurned: { id: 'wagonTurned', title: 'A Hard Turn, a Safe Field', tone: 'safe', ending: 'success', choices: [], text: 'The rope turns the wagon into the pasture, where it tips onto soft ground. The horses stop without injury, and {{handler}} reaches them after the turn. The workers get clear as the wagon leaves the road; its sideboard is broken.', textVariants: [{ requirements: { flags: ['workersWarned'] }, text: 'The rope turns the wagon into the pasture, where it tips onto soft ground. The horses stop without injury, and {{handler}} reaches them after the turn. The workers stay safely behind the marker, warned in time. The sideboard is broken.' }, { requirements: { flags: ['workerWarningFailed'] }, text: 'The rope turns the wagon into the pasture, where it tips onto soft ground. The workers scramble clear only when its wheels swing away; your earlier warning did not reach them. {{handler}} catches up to the unharmed horses. The sideboard is broken.' }] },
    teamStopped: { id: 'teamStopped', title: 'The Horses Stop', tone: 'safe', ending: 'success', choices: [], text: 'You guide the lead horses onto the shoulder and {{handler}} catches up to take their reins. The wagon stops before the fork. The workers wait until the team is calm, then cross the road.', textVariants: [{ requirements: { flags: ['workerWarningFailed'] }, text: 'You guide the lead horses onto the shoulder and {{handler}} catches up to take their reins. The workers were not warned, but the stopped wagon gives them time to move clear before they cross.' }] },
    wagonLost: { id: 'wagonLost', title: 'After the Runaway', tone: 'warning', ending: 'success', choices: [], text: 'The wagon overturns at the fork and breaks a wheel. The team veers downhill; {{handler}} catches the horses farther along. The workers get clear as the wagon leaves the junction. The load is scattered, but no one is killed.', textVariants: [{ requirements: { flags: ['workersWarned'] }, text: 'The wagon overturns at the fork and breaks a wheel. The workers stay behind the marker, where your warning sent them. The team veers downhill; {{handler}} catches the horses farther along. The load is scattered, but no one is killed.' }, { requirements: { flags: ['workerWarningFailed'] }, text: 'The wagon overturns at the fork and breaks a wheel. Your warning failed; as the team veers away, the workers scramble off the road. {{handler}} catches the horses farther downhill. The load is scattered, but no one is killed.' }, { requirements: { historyFlags: ['injured_near_runaway_team'] }, text: 'The wagon overturns at the fork and breaks a wheel. You nurse the bruising from the hoof that knocked you aside. The team is caught farther downhill; the workers get clear as the wagon leaves the junction, but the load is scattered.' }] },
    playerDies: { id: 'playerDies', title: 'Beneath the Wheel', tone: 'danger', ending: 'death', choices: [], text: 'You miss the rein and fall into the wagon’s path. The team is caught farther down the hill, but the wheel reaches you first.' },
  },
};
