import type { Scenario } from '../types';

export const THE_LOOSE_TEAM: Scenario = {
  id: 'the-loose-team', title: 'The Loose Team', subtitle: 'A runaway wagon is bearing down on a road junction.', startScene: 'roadJunction',
  timePhases: [{ id: 'clear', label: 'Clear Road', atMinutes: 0 }, { id: 'closing', label: 'Wagon Closing', atMinutes: 3 }, { id: 'lastSeconds', label: 'Moments to Act', atMinutes: 6 }],
  runRandomSelections: [{ id: 'handler', values: ['Irena', 'Joric', 'Solvi', 'Edric', 'Nomi'].map((value) => ({ value })) }],
  scenes: {
    roadJunction: { id: 'roadJunction', title: 'Wheels Without a Driver', tone: 'warning', text: 'From the safe uphill shoulder, you see two horses pulling an empty wagon downhill toward a fork in the road. Their handler, {{handler}}, runs behind them. Two road workers are crossing the fork; an open gate on your left leads into an empty fenced pasture. The horses are frightened, and the wagon is gaining speed.', choices: [
      { id: 'warnWorkers', label: 'Shout for the road workers to clear the fork', hint: 'They can step behind the stone marker if they hear you in time.', timeCost: 1, chance: { probability: 0.82, lateProbability: 0.61, lateAfterMinutes: 3, successNext: 'workersClear', failureNext: 'wagonAtFork', successMessage: 'The workers hear you and scramble behind the marker.', failureMessage: 'The wheels drown your warning. The workers are still in the wagon’s path.', successEffects: { historyFlags: ['warned_road_workers'] } } },
      { id: 'openPastureGate', label: 'Open the pasture gate ahead of the wagon', hint: 'The gate swings away from the road into an empty field.', timeCost: 1, chance: { probability: 0.66, lateProbability: 0.43, lateAfterMinutes: 3, bonusItems: ['gateHook', 'foldingPryTool'], bonusProbability: 0.14, successNext: 'horsesTurned', failureNext: 'wagonAtFork', successMessage: 'The gate catches the wagon’s eye line; the horses veer into the empty pasture.', failureMessage: 'The latch sticks. The team is almost at the fork.' } },
      { id: 'throwRopeAcrossRoad', label: 'Secure a rope across the safe approach', requirements: { items: ['travelRope'] }, hint: 'An anchored line may slow the wagon, but standing in its path could pull you under it.', timeCost: 1, chance: { probability: 0.57, lateProbability: 0.36, lateAfterMinutes: 3, bonusItems: ['ironRopeClamp', 'freightmansStrap'], bonusProbability: 0.1, successNext: 'wagonTurned', failureNext: 'wagonAtFork', successMessage: 'The line catches the wagon rail and turns its front wheels toward the pasture gate.', failureMessage: 'The line snaps taut and tears free before the wagon reaches it.', failureEffects: { health: -2, historyFlags: ['rope_failed_against_runaway_wagon'] } } },
      { id: 'runAlongside', label: 'Try to reach the horses from the shoulder', hint: 'The downhill pace is dangerous; a fall could put you beneath the wheels.', timeCost: 1, chance: { probability: 0.36, lateProbability: 0.22, lateAfterMinutes: 3, bonusItems: ['heavyLeatherGloves'], bonusProbability: 0.08, successNext: 'teamStopped', failureNext: 'wagonAtFork', successMessage: 'You catch the lead rein from the shoulder and pull the team toward the pasture.', failureMessage: 'A hoof knocks you into the road edge. The team keeps going.', failureEffects: { health: -4, historyFlags: ['injured_near_runaway_team'] } } },
    ] },
    workersClear: { id: 'workersClear', title: 'The Fork Is Clear', tone: 'warning', text: 'The workers are behind the stone marker. {{handler}} is still running behind the wagon, and the open pasture gate lies ahead on the left. The team can still strike the fence or overturn if nothing changes.', choices: [
      { id: 'openGateNow', label: 'Open the pasture gate for the horses', timeCost: 1, chance: { probability: 0.75, lateProbability: 0.51, lateAfterMinutes: 3, bonusItems: ['gateHook', 'foldingPryTool'], bonusProbability: 0.12, successNext: 'horsesTurned', failureNext: 'wagonAtForkAfterWarning', successMessage: 'The horses turn through the gate, and the wagon rolls into the empty pasture.', failureMessage: 'The gate catches on its post as the wagon reaches the fork.' } },
      { id: 'helpHandler', label: 'Guide {{handler}} to the stone marker', hint: 'They can escape the road before trying to stop the team.', next: 'handlerSafe', effects: { historyFlags: ['guided_team_handler_to_safety'] } },
      { id: 'signalTeam', label: 'Use a whistle to turn the horses', requirements: { anyItems: ['farmWhistle', 'conductorWhistle', 'trailWhistle'] }, timeCost: 1, chance: { probability: 0.68, lateProbability: 0.48, lateAfterMinutes: 3, successNext: 'horsesTurned', failureNext: 'wagonAtForkAfterWarning', successMessage: 'The familiar sharp call makes the horses turn toward the open pasture.', failureMessage: 'The team is too panicked to respond to the whistle.' } },
    ] },
    handlerSafe: { id: 'handlerSafe', title: 'Clear of the Wheels', tone: 'warning', text: '{{handler}} reaches the stone marker beside the workers. No one is in the wagon’s path now. The pasture gate remains open, but the wagon is nearly at the fork.', choices: [
      { id: 'guideIntoPasture', label: 'Guide the wagon through the open gate', timeCost: 1, chance: { probability: 0.64, lateProbability: 0.42, lateAfterMinutes: 3, successNext: 'horsesTurned', failureNext: 'wagonLost', successMessage: 'The horses angle into the field and the wagon slows in soft ground.', failureMessage: 'The wagon misses the gate and rattles through the fork.' } },
      { id: 'stayBehindMarker', label: 'Stay safe and let the wagon pass', hint: 'The workers and handler are out of the road; the wagon may be damaged.', next: 'wagonLost' },
    ] },
    wagonAtFork: { id: 'wagonAtFork', title: 'The Fork Arrives', tone: 'danger', text: 'The wagon reaches the fork. The workers are still near the marker if you have not warned them; {{handler}} is behind the team. The pasture gate is beside the road, but the wheels are already bouncing over the junction stones.', choices: [
      { id: 'pullHandlerClear', label: 'Pull {{handler}} behind the marker', hint: 'This gets one person out of the road; do not grab the moving wagon.', timeCost: 1, chance: { probability: 0.68, lateProbability: 0.48, lateAfterMinutes: 3, successNext: 'handlerSafe', failureNext: 'wagonLost', successMessage: 'You reach {{handler}} from the shoulder and pull them behind the marker.', failureMessage: 'The wagon swings wide, and you retreat before it reaches you.', failureEffects: { health: -2 } } },
      { id: 'openGateLate', label: 'Throw open the pasture gate', timeCost: 1, chance: { probability: 0.43, lateProbability: 0.28, lateAfterMinutes: 3, successNext: 'horsesTurned', failureNext: 'wagonLost', successMessage: 'The horses take the opening and the wagon overturns harmlessly in soft grass.', failureMessage: 'The wagon clips the gatepost and overturns on the verge.' } },
      { id: 'grabLeadRein', label: 'Grab the lead rein beside the wheel', hint: 'The wagon is already bouncing over stones; one slip could put you beneath it.', timeCost: 1, chance: { probability: 0.2, lateProbability: 0.1, lateAfterMinutes: 3, successNext: 'teamStopped', failureNext: 'playerDies', successMessage: 'You catch the rein and pull the team toward the pasture before the wagon passes.', failureMessage: 'The rein yanks you under the wagon’s wheel.' } },
      { id: 'takeCover', label: 'Get behind the stone marker', hint: 'The marker protects you; the wagon and team may be lost.', next: 'wagonLost' },
    ] },
    wagonAtForkAfterWarning: { id: 'wagonAtForkAfterWarning', title: 'The Fork Arrives', tone: 'danger', text: 'The workers are behind the stone marker, but the wagon reaches the fork before the gate opens. {{handler}} is still behind the team. The wheels bounce over the junction stones, and the empty pasture is beside the road.', choices: [
      { id: 'pullHandlerClearAfterWarning', label: 'Pull {{handler}} behind the marker', hint: 'The workers are already safe; the handler is still near the team.', timeCost: 1, chance: { probability: 0.68, lateProbability: 0.48, lateAfterMinutes: 3, successNext: 'handlerSafe', failureNext: 'wagonLost', successMessage: 'You reach {{handler}} from the shoulder and pull them clear.', failureMessage: 'The wagon swings wide, and you retreat behind the marker.', failureEffects: { health: -2 } } },
      { id: 'takeCoverAfterWarning', label: 'Stay behind the marker', next: 'wagonLost' },
    ] },
    horsesTurned: { id: 'horsesTurned', title: 'The Team Leaves the Road', tone: 'safe', ending: 'success', choices: [], text: 'The horses enter the empty pasture and the wagon slows in the soft field. {{handler}} checks their legs while the road workers stay safely behind the marker. The wagon needs repair, but no one is run down.' },
    wagonTurned: { id: 'wagonTurned', title: 'A Hard Turn, a Safe Field', tone: 'safe', ending: 'success', choices: [], text: 'The rope turns the wagon into the pasture, where it tips onto soft ground. The horses stop without injury. {{handler}} and the road workers are safe, though the wagon’s sideboard is broken.' },
    teamStopped: { id: 'teamStopped', title: 'The Horses Stop', tone: 'safe', ending: 'success', choices: [], text: 'You guide the lead horses onto the shoulder and {{handler}} takes their reins. The wagon stops before the fork. The road workers cross once the team is calm.' },
    wagonLost: { id: 'wagonLost', title: 'After the Runaway', tone: 'warning', ending: 'success', choices: [], text: 'The wagon overturns at the fork and breaks a wheel. You and the people on the shoulder remain clear. The horses are caught farther downhill; the load is scattered, but no one is killed.' },
    playerDies: { id: 'playerDies', title: 'Beneath the Wheel', tone: 'danger', ending: 'death', choices: [], text: 'You miss the rein and fall into the wagon’s path. The team is caught farther down the hill, but the wheel reaches you first.' },
  },
};
