import type { Scenario } from '../types';

export const THE_MISSING_BOAT: Scenario = {
  id: 'the-missing-boat', title: 'The Missing Boat', subtitle: 'A boat has drifted, and its owner is stranded downstream.', startScene: 'emptyLanding',
  timePhases: [{ id: 'lateDay', label: 'Late Daylight', atMinutes: 0 }, { id: 'risingWater', label: 'Water Rising', atMinutes: 10 }, { id: 'dusk', label: 'Dusk', atMinutes: 20 }],
  runRandomSelections: [{ id: 'boatOwner', values: ['Myrna', 'Jasper', 'Lowen', 'Clemence', 'Rollo'].map((value) => ({ value })) }],
  scenes: {
    emptyLanding: { id: 'emptyLanding', title: 'An Empty Mooring', tone: 'warning', text: 'At a quiet landing, a shallow punt is missing from its ring. Its mooring rope is freshly snapped, and a fishing basket sits on the bank. Downstream, the boat owner {{boatOwner}} stands on a low gravel shelf beside the grounded boat, waving. The river between you is fast but narrow; you are on firm shore.', choices: [
      { id: 'callBoatOwner', label: 'Call to {{boatOwner}} from the bank', hint: 'They answer that the boat drifted while they checked a net.', timeCost: 1, next: 'downstreamBank', effects: { knowledge: ['The missing punt grounded downstream while its owner checked a net.'] } },
      { id: 'signalBoatOwner', label: 'Signal with a whistle or mirror', hint: 'A signal carries to the downstream bend without entering the water.', requirements: { anyItems: ['trailWhistle', 'conductorWhistle', 'roadsideSignalMirror', 'farmWhistle'] }, timeCost: 1, next: 'signalAnswered', effects: { historyFlags: ['signaled_stranded_boat_owner'] } },
      { id: 'goForFerry', label: 'Walk to the ferry landing for help', hint: 'You stay on land; the walk takes several minutes.', timeCost: 8, next: 'ferryHelp' },
      { id: 'enterCurrent', label: 'Wade straight toward the gravel shelf', hint: 'The current is fast enough to sweep you downstream.', timeCost: 1, chance: { probability: 0.43, lateProbability: 0.25, lateAfterMinutes: 10, bonusItems: ['travelRope', 'heavyLeatherGloves'], bonusProbability: 0.12, successNext: 'downstreamBank', failureNext: 'riverRescue', successMessage: 'You find footing in the shallows and reach the bank beside {{boatOwner}}.', failureMessage: 'The current takes your legs. You catch a root below the landing.', failureEffects: { health: -3, historyFlags: ['risked_rising_river_for_stranger'] } } },
    ] },
    downstreamBank: { id: 'downstreamBank', title: 'The Boat on the Shelf', tone: 'warning', text: '{{boatOwner}} is on the far side, stranded on a gravel shelf about fifteen feet from firm ground. The punt is wedged beside them, too heavy to shove against the current alone. Water is climbing over the shelf’s lower edge.', choices: [
      { id: 'throwRopeToShelf', label: 'Throw a line to {{boatOwner}}', hint: 'A rope and clamp can steady the pull from solid ground.', requirements: { items: ['travelRope'] }, timeCost: 2, chance: { probability: 0.75, lateProbability: 0.51, lateAfterMinutes: 10, bonusItems: ['ironRopeClamp', 'freightmansStrap'], bonusProbability: 0.12, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'The rope reaches the shelf. {{boatOwner}} secures the punt while you pull toward shore.', failureMessage: 'The hook misses the post on the shelf and falls into the current.' } },
      { id: 'walkBankToShelf', label: 'Follow the bank to the gravel shelf', hint: 'The path stays above the water but narrows near the bend.', timeCost: 4, chance: { probability: 0.64, lateProbability: 0.42, lateAfterMinutes: 10, bonusItems: ['trailCompass', 'weatherproofCloak'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'You find a firm path around the bend and guide {{boatOwner}} back.', failureMessage: 'The bank trail has slumped into water. You turn back before it gives way.' } },
      { id: 'waitForFerryAtShelf', label: 'Wait for the ferry crew to arrive', timeCost: 6, next: 'ferryHelp' },
      { id: 'leaveBoatOwner', label: 'Stay on firm ground and leave for help', next: 'boatOwnerLost', effects: { historyFlags: ['left_stranded_boat_owner_for_help'] } },
    ] },
    signalAnswered: { id: 'signalAnswered', title: 'A Signal from the Bend', tone: 'warning', text: '{{boatOwner}} answers from the shelf and points to the punt wedged beside them. They can stand, but the water is rising over the gravel. The signal has also reached the ferry crew downstream.', choices: [
      { id: 'waitFerryCrew', label: 'Wait on shore for the ferry crew', hint: 'The crew has a shallow workboat, but the shelf is shrinking.', timeCost: 5, next: 'ferryHelp' },
      { id: 'followToShelf', label: 'Follow the bank to {{boatOwner}}', timeCost: 4, chance: { probability: 0.64, lateProbability: 0.42, lateAfterMinutes: 10, bonusItems: ['trailCompass', 'weatherproofCloak'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'You find a firm path to the shelf and guide {{boatOwner}} back.', failureMessage: 'The bank path has slumped into the river.' } },
      { id: 'leaveAfterSignal', label: 'Leave the rescue to the ferry crew', next: 'boatOwnerLost' },
    ] },
    ferryHelp: { id: 'ferryHelp', title: 'A Workboat from the Landing', tone: 'warning', text: 'The ferry crew arrives with a shallow workboat and a second hand on the oars. They keep the bow against the bank; {{boatOwner}} is still on the gravel shelf beside the punt.', choices: [
      { id: 'guideBoatIn', label: 'Help guide the workboat to the shelf', hint: 'The crew rows from upstream so the current carries them toward the shelf.', timeCost: 2, chance: { probability: 0.8, lateProbability: 0.61, lateAfterMinutes: 15, bonusItems: ['travelRope', 'ironRopeClamp'], bonusProbability: 0.08, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'The workboat reaches the shelf, and {{boatOwner}} climbs aboard.', failureMessage: 'A cross-current turns the bow aside. The crew backs away safely.' } },
      { id: 'stayBackFerry', label: 'Stay on shore and let the crew work', next: 'boatOwnerLost' },
    ] },
    riverRescue: { id: 'riverRescue', title: 'Caught by the Current', tone: 'danger', text: 'You catch a root below the landing. The shore is several feet above your hands, and the current keeps pulling at your legs. {{boatOwner}} is still on the gravel shelf. Reaching for them now could cost your grip.', choices: [
      { id: 'climbRoot', label: 'Climb the root back to shore', hint: 'You may get clear while {{boatOwner}} remains stranded.', timeCost: 1, chance: { probability: 0.68, lateProbability: 0.46, lateAfterMinutes: 12, successNext: 'boatOwnerLost', failureNext: 'playerLost', successMessage: 'You pull yourself onto the bank, wet and bruised.', failureMessage: 'The root tears free in your hands.' } },
      { id: 'reachBoatOwnerFromWater', label: 'Reach for {{boatOwner}} from the current', hint: 'This is a desperate move; both of you may be swept away.', timeCost: 1, chance: { probability: 0.28, lateProbability: 0.15, lateAfterMinutes: 12, successNext: 'playerDiesBoatOwnerLives', failureNext: 'bothLost', successMessage: 'You push {{boatOwner}} toward the shelf before the current takes you.', failureMessage: 'The current pulls both of you below the bend.' } },
    ] },
    waterOverShelf: { id: 'waterOverShelf', title: 'The Shelf Is Going Under', tone: 'danger', text: 'The gravel shelf is nearly covered. {{boatOwner}} has climbed onto the grounded punt, which shifts against the bank. You remain on dry ground; the ferry crew is still on the way if called.', choices: [
      { id: 'lastLineToBoat', label: 'Throw one last line from the bank', requirements: { items: ['travelRope'] }, hint: 'The current is pushing the punt away from the shelf.', timeCost: 1, chance: { probability: 0.54, lateProbability: 0.32, lateAfterMinutes: 15, bonusItems: ['ironRopeClamp'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'boatOwnerLost', successMessage: 'The line catches the punt and pulls it within reach.', failureMessage: 'The punt turns downstream. {{boatOwner}} reaches the firm bank by the higher gravel bar.' } },
      { id: 'waitBoatCrew', label: 'Stay on shore and wave the crew in', next: 'lastCrewAttempt' },
      { id: 'leaveShelf', label: 'Back away and leave the landing clear', next: 'boatOwnerLost' },
    ] },
    lastCrewAttempt: { id: 'lastCrewAttempt', title: 'The Crew at the Shelf', tone: 'danger', text: 'The shelf is under water now. {{boatOwner}} has climbed onto the punt, and the ferry crew holds its bow from the bank. They have one chance to draw the boat to shore before the current turns it.', choices: [
      { id: 'steadyLastPull', label: 'Help the crew steady the last pull', timeCost: 1, chance: { probability: 0.67, lateProbability: 0.48, lateAfterMinutes: 15, bonusItems: ['travelRope', 'ironRopeClamp'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'boatOwnerLost', successMessage: 'The punt reaches the bank, and {{boatOwner}} steps onto firm ground.', failureMessage: 'The punt slips away, but {{boatOwner}} reaches the higher bank.' } },
      { id: 'letCrewPull', label: 'Give the crew room to pull alone', next: 'boatOwnerLost' },
    ] },
    safeLanding: { id: 'safeLanding', title: 'Back on the Bank', tone: 'safe', ending: 'success', choices: [], text: '{{boatOwner}} is on firm ground. The punt is hauled above the waterline, where its owner can repair the broken mooring. The river keeps running; no one had to swim it.' },
    boatOwnerLost: { id: 'boatOwnerLost', title: 'The Boat Drifts Away', tone: 'warning', ending: 'success', choices: [], text: 'You remain on firm land. The punt drifts beyond the bend; {{boatOwner}} reaches the higher bank but cannot recover it before dark. The boat is lost, but its owner is safe.' },
    playerLost: { id: 'playerLost', title: 'Under the Current', tone: 'danger', ending: 'death', choices: [], text: 'The root tears away and the current carries you beneath the bend. {{boatOwner}} remains on the gravel shelf until the ferry crew reaches the landing.' },
    playerDiesBoatOwnerLives: { id: 'playerDiesBoatOwnerLives', title: 'One Reaches the Bank', tone: 'danger', ending: 'death', choices: [], text: 'You push {{boatOwner}} onto the higher bank. The current takes you downstream before the ferry crew can pull you clear.' },
    bothLost: { id: 'bothLost', title: 'Below the Bend', tone: 'danger', ending: 'death', choices: [], text: 'The current carries both of you past the bend. The ferry crew reaches the empty shelf too late.' },
  },
};
