import type { Scenario } from '../types';

export const THE_MISSING_BOAT: Scenario = {
  id: 'the-missing-boat', title: 'The Missing Boat', subtitle: 'A boat has drifted, and its owner is stranded downstream.', startScene: 'emptyLanding',
  timePhases: [{ id: 'lateDay', label: 'Late Daylight', atMinutes: 0 }, { id: 'risingWater', label: 'Water Rising', atMinutes: 10 }, { id: 'dusk', label: 'Dusk', atMinutes: 20 }],
  runRandomSelections: [{ id: 'boatOwner', values: ['Myrna', 'Jasper', 'Lowen', 'Clemence', 'Rollo'].map((value) => ({ value })) }],
  scenes: {
    emptyLanding: { id: 'emptyLanding', title: 'An Empty Mooring', tone: 'warning', text: 'From the near bank, a fast, narrow channel separates you from a midstream gravel bar; the far bank is beyond. {{boatOwner}} stands beside a small punt there. Its bow is buried, and current shoves its loaded stern sideways. The mooring snapped while they checked a net; wet catch makes the punt too heavy to free alone. A higher gravel lip leads downstream to the near bank; water covers the lower tongue.', choices: [
      { id: 'callBoatOwner', label: 'Call to {{boatOwner}} from the bank', hint: 'They answer that the boat drifted while they checked a net.', timeCost: 1, next: 'downstreamBank', effects: { knowledge: ['The missing punt grounded downstream while its owner checked a net.'] } },
      { id: 'signalBoatOwner', label: 'Signal with a whistle or mirror', hint: 'A signal carries to the downstream bend without entering the water.', requirements: { anyItems: ['trailWhistle', 'conductorWhistle', 'roadsideSignalMirror', 'farmWhistle'] }, timeCost: 1, next: 'signalAnswered', effects: { historyFlags: ['signaled_stranded_boat_owner'] } },
      { id: 'goForFerry', label: 'Walk to the ferry landing for help', hint: 'You stay on land; the walk takes several minutes.', timeCost: 8, next: 'ferryHelp' },
      { id: 'enterCurrent', label: 'Wade across the narrow channel', hint: 'The current can sweep you off the submerged gravel; the far bank is beyond the bar.', timeCost: 1, chance: { probability: 0.43, lateProbability: 0.25, lateAfterMinutes: 10, bonusItems: ['travelRope', 'heavyLeatherGloves'], bonusProbability: 0.12, successNext: 'barWithMyrna', failureNext: 'riverRescue', successMessage: 'You cross the narrow channel and climb onto the gravel bar beside {{boatOwner}}.', failureMessage: 'The current takes your legs. You catch a root below the landing.', failureEffects: { health: -3, historyFlags: ['risked_rising_river_for_stranger'] } } },
    ] },
    downstreamBank: { id: 'downstreamBank', title: 'The Boat on the Bar', tone: 'warning', text: 'You remain on the near bank. Across the narrow channel, {{boatOwner}} stands on the midstream gravel bar beside the punt. The far bank is beyond a second, deeper channel. The boat’s bow is buried in gravel and the current presses its loaded stern sideways; alone, {{boatOwner}} cannot lift it free. Water is climbing over the bar’s lower edge.', choices: [
      { id: 'throwRopeToShelf', label: 'Throw a line to {{boatOwner}}', hint: 'A rope and clamp can steady the pull from solid ground.', requirements: { items: ['travelRope'] }, timeCost: 2, chance: { probability: 0.75, lateProbability: 0.51, lateAfterMinutes: 10, bonusItems: ['ironRopeClamp', 'freightmansStrap'], bonusProbability: 0.12, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'The rope reaches the shelf. {{boatOwner}} secures the punt while you pull toward shore.', failureMessage: 'The hook misses the post on the shelf and falls into the current.' } },
      { id: 'walkBankToShelf', label: 'Follow the near-bank path to the gravel tongue', hint: 'At the downstream bend, the low gravel tongue may still connect the bar to this bank.', timeCost: 4, chance: { probability: 0.64, lateProbability: 0.42, lateAfterMinutes: 10, bonusItems: ['trailCompass', 'weatherproofCloak'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'You reach the gravel tongue from the near bank. Together, you free the punt and guide it and its owner back across the shallows.', failureMessage: 'The near-bank path has slumped into water. You turn back before it gives way.' } },
      { id: 'waitForFerryAtShelf', label: 'Wait for the ferry crew to arrive', timeCost: 6, next: 'ferryHelp' },
      { id: 'leaveBoatOwner', label: 'Stay on firm ground and leave for help', next: 'boatOwnerLost', effects: { historyFlags: ['left_stranded_boat_owner_for_help'] } },
    ] },
    signalAnswered: { id: 'signalAnswered', title: 'A Signal from the Bend', tone: 'warning', text: '{{boatOwner}} answers from the midstream gravel bar and points to the punt wedged beside them. They can stand, but the rising water is washing over the low gravel tongue that connects the bar to the near bank. The signal has also reached the ferry crew downstream.', choices: [
      { id: 'waitFerryCrew', label: 'Wait on shore for the ferry crew', hint: 'The crew has a shallow workboat, but the shelf is shrinking.', timeCost: 5, next: 'ferryHelp' },
      { id: 'followToShelf', label: 'Follow the near-bank path to the gravel tongue', timeCost: 4, chance: { probability: 0.64, lateProbability: 0.42, lateAfterMinutes: 10, bonusItems: ['trailCompass', 'weatherproofCloak'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'You reach the gravel tongue from the near bank. Together, you free the punt and guide it and its owner back across the shallows.', failureMessage: 'The near-bank path has slumped into the river.' } },
      { id: 'leaveAfterSignal', label: 'Leave the rescue to the ferry crew', next: 'boatOwnerLost' },
    ] },
    ferryHelp: { id: 'ferryHelp', title: 'A Workboat from the Landing', tone: 'warning', text: 'The ferry crew arrives in a shallow workboat. They row from upstream and hold its bow against the near bank, facing {{boatOwner}} on the midstream gravel bar. The current has nearly covered the low gravel tongue; the crew has one careful approach before it disappears.', choices: [
      { id: 'guideBoatIn', label: 'Help guide the workboat to the gravel bar', hint: 'The crew rows from upstream so the current carries them toward the bar.', timeCost: 2, chance: { probability: 0.8, lateProbability: 0.61, lateAfterMinutes: 15, bonusItems: ['travelRope', 'ironRopeClamp'], bonusProbability: 0.08, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'The workboat reaches the gravel bar. {{boatOwner}} climbs aboard, and the crew brings them and the freed punt to the near bank.', failureMessage: 'A cross-current turns the bow aside. The crew backs away safely.' } },
      { id: 'catchPuntLineWithHook', label: 'Catch the punt’s bow line with your Boat Hook', hint: 'Only after the workboat is in the shallow lee; the pole cannot span the channel.', requirements: { items: ['boatHook'], usableItems: ['boatHook'] }, timeCost: 2, next: 'safeLanding', effects: { historyFlags: ['used_boat_hook_to_recover_punt_line'] } },
      { id: 'stayBackFerry', label: 'Stay on shore and let the crew work', next: 'boatOwnerLost' },
    ] },
    riverRescue: { id: 'riverRescue', title: 'Caught by the Current', tone: 'danger', text: 'You catch a root below the near-bank landing. The shore is several feet above your hands, and the current keeps pulling at your legs. {{boatOwner}} is still on the midstream gravel bar beside the punt. Reaching for them now could cost your grip.', choices: [
      { id: 'climbRoot', label: 'Climb the root back to shore', hint: 'You may get clear while {{boatOwner}} remains stranded.', timeCost: 1, chance: { probability: 0.68, lateProbability: 0.46, lateAfterMinutes: 12, successNext: 'boatOwnerLost', failureNext: 'playerLost', successMessage: 'You pull yourself onto the bank, wet and bruised.', failureMessage: 'The root tears free in your hands.' } },
      { id: 'reachBoatOwnerFromWater', label: 'Reach for {{boatOwner}} from the current', hint: 'This is a desperate move; both of you may be swept away.', timeCost: 1, chance: { probability: 0.28, lateProbability: 0.15, lateAfterMinutes: 12, successNext: 'playerDiesBoatOwnerLives', failureNext: 'bothLost', successMessage: 'You shove {{boatOwner}} toward the gravel bar. They catch the punt as the current takes you.', failureMessage: 'The current pulls both of you below the bend.' } },
    ] },
    waterOverShelf: { id: 'waterOverShelf', title: 'The Bar Is Going Under', tone: 'danger', text: 'Water covers most of the midstream gravel bar. {{boatOwner}} has climbed onto the punt, which shifts against the current; the narrow higher lip is the only footpath left toward the near bank. You remain on shore, and the ferry crew is still on the way if called.', choices: [
      { id: 'lastLineToBoat', label: 'Throw one last line from the near bank', requirements: { items: ['travelRope'] }, hint: 'The current is pushing the punt away from the gravel bar.', timeCost: 1, chance: { probability: 0.54, lateProbability: 0.32, lateAfterMinutes: 15, bonusItems: ['ironRopeClamp'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'boatOwnerLost', successMessage: 'The line catches the punt. The ferry crew reaches the bar and brings {{boatOwner}} and the boat to the near bank.', failureMessage: 'The punt turns downstream. {{boatOwner}} steps onto the higher gravel lip and makes for the near bank; the boat is gone.' } },
      { id: 'waitBoatCrew', label: 'Stay on shore and wave the crew in', next: 'lastCrewAttempt' },
      { id: 'leaveShelf', label: 'Back away and leave the landing clear', next: 'boatOwnerLost' },
    ] },
    lastCrewAttempt: { id: 'lastCrewAttempt', title: 'The Crew at the Shelf', tone: 'danger', text: 'The shelf is under water now. {{boatOwner}} has climbed onto the punt, and the ferry crew holds its bow from the bank. They have one chance to draw the boat to shore before the current turns it.', choices: [
      { id: 'steadyLastPull', label: 'Help the crew steady the last pull', timeCost: 1, chance: { probability: 0.67, lateProbability: 0.48, lateAfterMinutes: 15, bonusItems: ['travelRope', 'ironRopeClamp'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'boatOwnerLost', successMessage: 'The punt reaches the bank, and {{boatOwner}} steps onto firm ground.', failureMessage: 'The punt slips away, but {{boatOwner}} reaches the higher bank.' } },
      { id: 'letCrewPull', label: 'Give the crew room to pull alone', next: 'boatOwnerLost' },
    ] },
    barWithMyrna: { id: 'barWithMyrna', title: 'On the Gravel Bar', tone: 'warning', text: 'You are now on the midstream gravel bar with {{boatOwner}}. The near bank is across the narrow channel; the far bank lies beyond a deeper channel on the other side. The punt is still wedged bow-first, too heavy for one person to free. The submerged gravel tongue downstream is the safest route back if you can keep your footing.', choices: [
      { id: 'walkTongueTogether', label: 'Guide the punt along the shallow gravel tongue', hint: 'With two people lifting the bow together, the boat may slide free; the submerged path is slippery.', timeCost: 2, chance: { probability: 0.71, lateProbability: 0.48, lateAfterMinutes: 10, bonusItems: ['travelRope', 'freightmansStrap'], bonusProbability: 0.1, successNext: 'safeLanding', failureNext: 'waterOverShelf', successMessage: 'Together you free the bow and guide the punt down the gravel tongue to the near bank.', failureMessage: 'The punt shifts, but a wave covers the tongue. You retreat to the higher middle of the bar.' } },
      { id: 'signalFromBar', label: 'Signal the ferry crew from the bar', hint: 'A whistle, mirror, or daylight flag can reach the crew if they are watching upstream.', requirements: { anyItems: ['trailWhistle', 'conductorWhistle', 'roadsideSignalMirror', 'farmWhistle', 'signalFlagSet'] }, timeCost: 1, next: 'ferryHelp' },
      { id: 'waitForCrewOnBar', label: 'Wait for the ferry crew', timeCost: 4, next: 'ferryHelp' },
      { id: 'retreatTongueAlone', label: 'Return to the near bank alone', hint: 'The shallow tongue is slick and partly submerged.', timeCost: 2, chance: { probability: 0.75, lateProbability: 0.53, lateAfterMinutes: 10, successNext: 'downstreamBank', failureNext: 'riverRescue', successMessage: 'You cross the gravel tongue and climb onto the near bank.', failureMessage: 'The current catches your foot before you reach shore.', failureEffects: { health: -2 } } },
    ] },
    safeLanding: { id: 'safeLanding', title: 'Back on the Bank', tone: 'safe', text: '{{boatOwner}} reaches the near bank, shivering but unhurt. The punt is hauled above the waterline, where its owner can mend the snapped mooring. The ferry crew checks the line while the river covers the gravel bar. You have time to catch your breath before parting.', choices: [{ id: 'partAfterRescue', label: 'Part ways at the landing', next: 'rescueEnding' }] },
    rescueEnding: { id: 'rescueEnding', title: 'A Safe Landing', tone: 'safe', ending: 'success', choices: [], text: '{{boatOwner}} secures the punt on dry ground. The rescue is over, the channel is behind you, and the late light settles across the landing.' },
    boatOwnerLost: { id: 'boatOwnerLost', title: 'The Boat Drifts Away', tone: 'warning', ending: 'success', choices: [], text: 'You remain on the near bank. The punt drifts beyond the bend; {{boatOwner}} follows the higher gravel lip to the same bank, safe but unable to recover the boat before dark.' },
    playerLost: { id: 'playerLost', title: 'Under the Current', tone: 'danger', ending: 'death', choices: [], text: 'The root tears away and the current carries you beneath the bend. {{boatOwner}} remains on the gravel shelf until the ferry crew reaches the landing.' },
    playerDiesBoatOwnerLives: { id: 'playerDiesBoatOwnerLives', title: 'One Reaches the Bank', tone: 'danger', ending: 'death', choices: [], text: '{{boatOwner}} catches the punt at the gravel bar and clings there until the ferry crew reaches them. The current takes you downstream before anyone can pull you clear.' },
    bothLost: { id: 'bothLost', title: 'Below the Bend', tone: 'danger', ending: 'death', choices: [], text: 'The current carries both of you past the bend. The ferry crew reaches the empty shelf too late.' },
  },
};
