import type { Scenario, ScenarioDiversity, Scene } from '../types';

const d = (hook: string, activity: string, setting: string, risk: ScenarioDiversity['riskTier'], fantasy: ScenarioDiversity['fantasyDensity'], season: 'LOCKED' | 'AFFINITY', role = 'accidental participant'): Partial<ScenarioDiversity> => ({
  distinctiveHook: hook,
  playerRoles: [role], activities: [activity], structures: ['branching narrative'], tones: [risk === 'LOW' ? 'humorous/absurd' : 'mysterious/eerie'], settings: [setting], riskTier: risk,
  fantasyDensity: fantasy, supernaturalThreats: fantasy === 'NONE' ? ['none specified'] : ['unexplained phenomenon'], combat: 'NONE', length: 'STANDARD',
  entryShapes: ['accidental encounter'], outcomeShapes: risk === 'SEVERE' ? ['success/partial success', 'death', 'escape/survival'] : ['success/partial success', 'walk-away/refusal'],
  rewardShapes: ['money/item/knowledge/history possible', 'relationship/referral'], consequenceShapes: risk === 'SEVERE' ? ['health/injury', 'death', 'time/opportunity'] : ['relationship', 'time/opportunity'],
  availability: season === 'LOCKED' ? { season: 'OCTOBER', weightBoost: 1.6 } : { season: 'ALL_YEAR', months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], affinityMonths: [10], weightBoost: 1.35 },
});
const done = (id: string, title: string, text: string): Scene => ({ id, title, text, ending: 'success', choices: [] });
const dead = (id: string, title: string, text: string): Scene => ({ id, title, text, ending: 'death', choices: [] });

export const OCTOBER_AFFINITY_ADVENTURES: Scenario[] = [
  {
    id: 'jack-o-lantern-contest', title: 'The Jack-o’-Lantern Contest', subtitle: 'A local carving contest turns into a test of nerve and good humor.', startScene: 'contestYard',
    diversity: d('A locally announced Halloween carving contest becomes a repair-and-judgment problem when rain threatens the entries.', 'competition/game', 'town/market/inn', 'LOW', 'NONE', 'LOCKED', 'guest'),
    scenes: {
      contestYard: { id: 'contestYard', title: 'The Carving Table', text: 'Each Halloween, the village gathers beside the meeting hall to display carved pumpkins and turnips. A neighbor invites you to join the friendly contest with a spare gourd and borrowed blunt knife. Entrants who stay for the results receive a coin from the small participation purse and a place at supper. Rain is gathering, and one rival insists their design has already been copied.', choices: [
        { id: 'enterCarve', label: 'Enter with the spare gourd', next: 'carvingChoice', effects: { setFlags: ['contestCarver'] } }, { id: 'helpDisplay', label: 'Help keep the entries dry', next: 'rainProblem', effects: { setFlags: ['contestHelper'] } },
        { id: 'judge', label: 'Help the judge settle the copying claim', next: 'copyingClaim', effects: { setFlags: ['contestJudge'] } }, { id: 'leaveContest', label: 'Thank them and move on', next: 'contestDeclined' },
      ] },
      carvingChoice: { id: 'carvingChoice', title: 'A Design of Your Own', text: 'The borrowed knife is serviceable, but the gourd’s skin is thin near its stem. A simple lantern face can be finished quickly; a fine scene may look better if it survives the cut.', choices: [
        { id: 'simpleFace', label: 'Carve a clear, sturdy face', next: 'contestJudging', effects: { setFlags: ['contestSimple'] } }, { id: 'fineScene', label: 'Attempt a detailed scene', next: 'fineCarving', effects: { setFlags: ['contestFine'] } },
      ] },
      fineCarving: { id: 'fineCarving', title: 'The Thin Wall Gives', text: 'A narrow panel splits while you cut. A basket of leaf scraps and twine used to decorate the entries sits on the table; you can mend the design or enter it honestly as a damaged piece.', choices: [
        { id: 'mendGourd', label: 'Mend it with leaf and twine', next: 'contestJudging', effects: { setFlags: ['contestMended'] } }, { id: 'showCrack', label: 'Show the crack as part of it', next: 'contestJudging', effects: { setFlags: ['contestHonest'] } },
      ] },
      rainProblem: { id: 'rainProblem', title: 'Canvas and Wind', text: 'The rain starts before the judge calls the entries. A canvas cover is at hand, but wind keeps lifting one side; moving every carving indoors would take longer than the shower may last.', choices: [
        { id: 'holdCover', label: 'Hold the canvas with the children', next: 'contestJudging', effects: { setFlags: ['contestHelped'] } }, { id: 'moveBest', label: 'Move the most fragile carvings first', next: 'contestJudging', effects: { setFlags: ['contestPrioritized'] } },
      ] },
      copyingClaim: { id: 'copyingClaim', title: 'Two Similar Faces', text: 'The rival points to two triangular eyes and calls it copying. The older carving has a crooked mouth and a twig stem; the newer one shares the eyes but little else. The judge asks you to say only what you actually saw.', choices: [
        { id: 'describeEvidence', label: 'Describe the differences plainly', next: 'contestJudging', effects: { knowledge: ['At a village carving contest, two similar eye-shapes were not enough to establish copying; the judge considered the full design.'], setFlags: ['contestFairWitness'] } }, { id: 'avoidClaim', label: 'Leave the judgment to the carvers', next: 'contestJudging', effects: { setFlags: ['contestStayedOut'] } },
      ] },
      contestJudging: { id: 'contestJudging', title: 'The Judge’s Lantern', text: 'The judge lights each entry in turn. The crowd sees which carvings held together, which were protected from rain, and whether anyone made a claim they could support. No one is disqualified on resemblance alone.', textVariants: [
        { requirements: { flags: ['contestSimple'] }, text: 'Your sturdy face catches the lantern light cleanly. The judge praises its expression, while a more elaborate entry wins the craft prize.' },
        { requirements: { flags: ['contestMended'] }, text: 'The leaf patch makes your cracked gourd the evening’s cleverest repair. The judge awards a small craft ribbon for the recovery, not the original cut.' },
        { requirements: { flags: ['contestHelped'] }, text: 'The canvas stays over most of the table because you and the children keep its edge down. The judge thanks the helpers before announcing the winners.' },
        { requirements: { flags: ['contestFairWitness'] }, text: 'The judge hears your careful account and lets both carvings remain. The rival grumbles, then admits the mouth and stem differ.' },
      ], choices: [
        { id: 'shareAfterContest', label: 'Stay for your coin and supper', requirements: { flags: ['contestCarver'] }, next: 'contestAftermath', effects: { money: 1, historyFlags: ['Entered the village Halloween carving contest'] } },
        { id: 'contestThanks', label: 'Stay for supper with the villagers', next: 'contestSocialAftermath', effects: { historyFlags: ['Helped steady the village Halloween carving contest'] } },
        { id: 'leaveAfterContest', label: 'Leave after the judging', next: 'contestDeparture', effects: { historyFlags: ['Took part in a village Halloween carving contest'] } },
      ] },
      contestAftermath: { id: 'contestAftermath', title: 'A Place at the Table', text: 'The keeper gives you one coin from the participation purse promised to entrants. The winning carver receives the craft prize; you receive supper and the pleasure of seeing your own work under the lanterns as the rain eases.', choices: [{ id: 'contestComplete', label: 'Thank the company and take the road', next: 'contestComplete', effects: { lore: ['A small village marks its Halloween carving contest with a shared supper.'] } }] },
      contestSocialAftermath: { id: 'contestSocialAftermath', title: 'A Place at the Table', text: 'The village invites you to supper after the judging. You leave with thanks for the part you played, not a share of the entrants’ purse.', textVariants: [
        { requirements: { flags: ['contestJudge'] }, text: 'The judge thanks you for separating what you saw from what the rival feared. You receive a place at supper, not a share of the entrants’ purse; by the time you leave, both carvers are discussing the rain instead of accusing one another.' },
        { requirements: { flags: ['contestHelper'] }, text: 'The children remember you holding the canvas while the rain passed. The keeper offers supper with the helpers; the prize belongs to the carvers, but the carvings stayed dry enough for everyone to see them.' },
      ], ending: 'success', choices: [] },
      contestDeparture: done('contestDeparture', 'Lanterns in the Yard', 'You leave after the judging. Behind you, the entries glow along the meeting-hall wall while the villagers debate which one looked most like the farmer who grew it.'),
      contestComplete: done('contestComplete', 'The Gourd Holds', 'The rain passes, the prize is settled, and your part in the contest is remembered more for sound judgment than for the knife-work.'),
      contestDeclined: { ...done('contestDeclined', 'No Entry Tonight', 'You decline the invitation and leave the yard to the villagers’ Halloween custom. Their lanterns and laughter follow you only as far as the road bend.'), completionQualification: 'nonSubstantive' },
    },
  },
  {
    id: 'all-hallows-boarding-house', title: 'All Hallows at the Boarding House', subtitle: 'A harmless evening tale contains a detail nobody admits knowing.', startScene: 'boardingStories',
    diversity: d('A shared ghost-story evening shifts into a provenance puzzle when a newcomer repeats a private detail from the house ledger.', 'social interaction', 'domestic interior', 'MODERATE', 'AMBIGUOUS', 'LOCKED', 'guest'),
    scenes: {
      boardingStories: { id: 'boardingStories', title: 'Stories by the Lamp', text: 'On Halloween night, the boarding-house keeper sets out cider and asks the residents to trade ghost stories. One new lodger, Mr. Venn, describes a brass key hidden beneath the third stair—though the keeper says no such key has been mentioned tonight.', choices: [
        { id: 'askKeySource', label: 'Ask Venn where he learned that', next: 'vennQuestion' }, { id: 'askKeeper', label: 'Ask the keeper about the stair', next: 'keeperAccount' },
        { id: 'inspectStair', label: 'Look beneath the third stair', next: 'stairClue' }, { id: 'leaveStories', label: 'Leave the gathering alone', next: 'boardingDeclined' },
      ] },
      vennQuestion: { id: 'vennQuestion', title: 'An Uncomfortable Pause', text: 'Venn says he heard it from a former resident. The keeper says only the house carpenter and the late Mrs. Vale knew of the loose board. Venn looks more embarrassed than threatening.', choices: [
        { id: 'checkLedger', label: 'Ask to compare the old house ledger', next: 'ledgerRevealed' }, { id: 'checkBoard', label: 'Check the stair with the keeper', next: 'stairClue' },
      ] },
      keeperAccount: { id: 'keeperAccount', title: 'A Loose Board', text: 'The keeper confirms there is a loose stair board, but says the key was removed years ago. They will not pry it up in front of the whole room without a reason.', choices: [
        { id: 'askLedger', label: 'Compare the old ledger quietly', next: 'ledgerRevealed' }, { id: 'leaveKeyAlone', label: 'Let the story remain a story', next: 'boardingAfter' },
      ] },
      stairClue: { id: 'stairClue', title: 'The Dust Line', text: 'The board’s edge has a fresh pale scrape. The keeper lifts it carefully: a brass key is gone, but a strip of old paper remains tucked in the gap.', choices: [
        { id: 'readPaper', label: 'Read the paper with the keeper', next: 'ledgerRevealed', effects: { setFlags: ['foundStairPaper'] } }, { id: 'askVennNow', label: 'Ask Venn about the missing key', next: 'vennConfronted' },
      ] },
      ledgerRevealed: { id: 'ledgerRevealed', title: 'A Familiar Hand', text: 'The house ledger contains an old note about the brass key and the third stair. Venn admits he copied the tale from a page he found while helping carry trunks upstairs. He had mistaken a private note for a ghost story.', choices: [
        { id: 'helpKeeperSettle', label: 'Help the keeper search the upstairs room', next: 'boardingAfter', effects: { knowledge: ['The brass stair key belonged to the boarding house; an old ledger note, not a haunting, explained the hidden detail.'], setFlags: ['keyStorySolved'] } }, { id: 'protectVenn', label: 'Keep the source private and end the tale', next: 'boardingAfter', effects: { historyFlags: ['Kept a boarding-house Halloween story from turning into a public accusation'], setFlags: ['vennProtected'] } },
      ] },
      vennConfronted: { id: 'vennConfronted', title: 'A Story Too Close to Home', text: 'Venn says he saw a key-shaped outline under the board while carrying trunks. He had not taken the key, but the empty place is now plain to everyone in the room.', choices: [{ id: 'bringKeeperIn', label: 'Let the keeper decide what to do', next: 'boardingAfter', effects: { setFlags: ['keyStorySolved'] } }, { id: 'endAccusation', label: 'Stop the questions before they turn cruel', next: 'boardingAfter', effects: { setFlags: ['vennProtected'] } }] },
      boardingAfter: { id: 'boardingAfter', title: 'The Story Changes Hands', text: 'The keeper checks the upstairs room after the guests settle. No key is found, but the paper note is returned to the ledger and Venn offers to help mend the loose stair. The ghost story becomes a small house mystery, and no one is asked to confess to more than they know.', choices: [{ id: 'boardingEnd', label: 'Share the last cup and say goodnight', next: 'boardingEnd', effects: { money: 1, lore: ['At All Hallows, one boarding house traded ghost stories over cider.'] } }] },
      boardingEnd: done('boardingEnd', 'The Third Stair', 'The keeper gives you a coin for the quiet help. Venn stays to repair the board; the key’s fate remains uncertain, but the house has its ordinary explanation for the story.'),
      boardingDeclined: done('boardingDeclined', 'A Story Left Untold', 'You leave the Halloween gathering before the stories turn into questions. The house keeps its small mystery to itself.'),
    },
  },
  {
    id: 'the-masked-visitor', title: 'The Masked Visitor', subtitle: 'At a Halloween gathering, one guest leaves with the wrong parcel.', startScene: 'maskedGathering',
    diversity: d('The traveler uses timing, a repeated phrase, and shoe mud to separate a mistaken parcel swap from a deliberate theft.', 'investigation/mystery', 'town/market/inn', 'MODERATE', 'NONE', 'LOCKED'),
    scenes: {
      maskedGathering: { id: 'maskedGathering', title: 'The Wrong Parcel', text: 'At a Halloween supper in the inn’s common room, guests wear simple masks for the first hour. A small parcel containing the host’s rent papers is missing, and an empty parcel of folded cloth sits in its place. Coats hang in the narrow side room; four guests have already stepped into the yard.', choices: [
        { id: 'checkTiming', label: 'Ask who left just before the toast', next: 'timingClue' }, { id: 'checkParcel', label: 'Compare both parcels carefully', next: 'parcelClue' },
        { id: 'callEveryoneBack', label: 'Ask the host to call the guests back', next: 'guestsReturn' }, { id: 'leaveMaskMystery', label: 'Leave the host to handle it', next: 'maskedDeclined' },
      ] },
      timingClue: { id: 'timingClue', title: 'A Phrase Remembered', text: 'A serving woman recalls one masked guest asking for “the west room,” although this inn has no west room. Another guest had used the phrase as a joke before supper.', choices: [{ id: 'compareFootwear', label: 'Check who wore wet yard shoes', next: 'shoeClue' }, { id: 'compareParcelMarks', label: 'Ask the host about the wrapping', next: 'parcelClue' }] },
      parcelClue: { id: 'parcelClue', title: 'Two Similar Wrappings', text: 'Both parcels use the same brown paper, but the missing one was tied with blue thread. The cloth parcel has a torn end of blue thread caught under its knot.', choices: [{ id: 'traceThread', label: 'Ask who handled the blue thread', next: 'guestsReturn', effects: { setFlags: ['threadClue'] } }, { id: 'checkYard', label: 'Look for matching footprints outside', next: 'shoeClue' }] },
      shoeClue: { id: 'shoeClue', title: 'Mud at the Back Step', text: 'A pair of narrow boots left the common room, stepped into the wet yard, then returned by the kitchen door. The tracks do not prove theft, but they narrow the question to two guests.', choices: [{ id: 'speakPrivately', label: 'Speak to the two guests apart', next: 'privateAccounts' }, { id: 'askHost', label: 'Let the host ask everyone together', next: 'guestsReturn' }] },
      guestsReturn: { id: 'guestsReturn', title: 'Masks Set Aside', text: 'The guests come back and remove their masks. One admits carrying the wrong parcel out to fetch a coat; the other says they saw the exchange but feared being blamed. The rent papers are still missing.', choices: [{ id: 'checkPrivateAccounts', label: 'Compare their accounts quietly', next: 'privateAccounts' }, { id: 'searchCoatRoom', label: 'Search the coat room with permission', next: 'papersFound' }] },
      privateAccounts: { id: 'privateAccounts', title: 'A Deliberate Exchange?', text: 'One guest remembers a low voice saying, “Not this one.” The host recognizes the phrase as something a clerk says when sorting parcels. No one can say whether it was a warning or part of the confusion.', choices: [{ id: 'searchCoats', label: 'Search the coat room with permission', next: 'papersFound' }, { id: 'leaveUncertain', label: 'Return the empty parcel and stop there', next: 'maskedAfter', effects: { setFlags: ['papersUnfound'] } }] },
      papersFound: { id: 'papersFound', title: 'The Clerk’s Coat', text: 'The rent papers are in the inn clerk’s coat pocket. The clerk had carried them outside to keep them dry and forgot where they were put. The masked guests made the mistake look more deliberate than it was.', choices: [{ id: 'returnPapers', label: 'Return the papers and let the clerk explain', next: 'maskedAfter', effects: { setFlags: ['papersRecovered'], knowledge: ['The Halloween parcel scare at the inn came from a clerk keeping papers dry, not a masked thief.'] } }] },
      maskedAfter: { id: 'maskedAfter', title: 'The Supper Resumes', text: 'The host decides what to tell the guests. If the papers were found, the clerk apologizes and the delayed rent can be paid in the morning; if not, the household must wait another day. Either way, the host thanks you for not naming a culprit on a guess.', textVariants: [{ requirements: { flags: ['papersRecovered'] }, text: 'With the papers back, the host accepts the clerk’s apology and postpones the rent payment until morning. No guest is blamed for a swap that the clerk caused.' }, { requirements: { flags: ['papersUnfound'] }, text: 'The papers remain missing, so the household postpones the rent payment and the host will speak with the clerk at daylight. You leave the theft question open rather than accuse a masked guest.' }], choices: [{ id: 'maskedClose', label: 'Take your leave after supper', next: 'maskedClose', effects: { historyFlags: ['Helped prevent a Halloween gathering from becoming a false accusation'] } }] },
      maskedClose: done('maskedClose', 'Masks on the Peg', 'The gathering resumes with masks hung by the door. Your restraint is remembered; whether the papers were found or not, the evening ends without a stranger being condemned on costume and suspicion alone.'),
      maskedDeclined: done('maskedDeclined', 'A Supper Left Behind', 'You decline to investigate and leave the host to speak with the guests. The Halloween supper continues behind you.'),
    },
  },
  {
    id: 'the-halloween-dare', title: 'The Halloween Dare', subtitle: 'A foolish overnight challenge is made more dangerous by an old building.', startScene: 'dareInvitation',
    diversity: d('A voluntary overnight dare in a visibly unsound toll house offers safe refusal, cautious supervision, or a genuinely dangerous entry.', 'survival', 'road/bridge', 'HIGH', 'AMBIGUOUS', 'LOCKED', 'helper/rescuer'),
    scenes: {
      dareInvitation: { id: 'dareInvitation', title: 'The Old Toll House', tone: 'warning', text: 'On Halloween evening, you pass the abandoned toll house and find three local youths gathered outside. One has gone in while the others watch from the road; a cracked stone lintel hangs over loose doorway boards, and a voice calls from the back room. They ask you to help decide what to do.', choices: [
        { id: 'declineDare', label: 'Decline and leave the dare to them', next: 'dareDeclined' }, { id: 'callYouthOut', label: 'Call the youth back to the doorway', next: 'dareCall' },
        { id: 'enterDareHouse', label: 'Enter by the standing side wall', hint: 'The lintel is cracked; loose stones may fall if you go beneath it.', next: 'dareInside' },
      ] },
      dareCall: { id: 'dareCall', title: 'A Voice from the Rear Room', text: 'The youth answers that the floor has dropped behind them. A low opening in the outer side wall reaches the sound strip of solid floor, but not the front doorway. You can call directions from outside; crossing the narrow boards yourself would be faster and far riskier.', choices: [{ id: 'guideYouth', label: 'Guide them toward the side opening', next: 'dareOutsideRescue' }, { id: 'fetchRope', label: 'Fetch help and a rope', next: 'dareHelp' }, { id: 'refuseEntry', label: 'Keep everyone outside and wait for help', next: 'dareHelp' }] },
      dareOutsideRescue: { id: 'dareOutsideRescue', title: 'A Voice from the Wall', text: 'You call directions through the low opening. The youth follows the solid strip along the side wall and crawls out without crossing the dropped floor. A few loose stones fall from the cracked lintel, but nobody enters beneath it.', choices: [{ id: 'stayOutsideRescue', label: 'Wait with them for the owner', next: 'dareAfter', effects: { historyFlags: ['Guided a youth out of the unsafe toll house without entering'] } }, { id: 'leaveOutsideRescue', label: 'Leave once everyone is clear', next: 'dareAfter' }] },
      dareInside: { id: 'dareInside', title: 'The Floor Gives Way', tone: 'danger', text: 'From the side wall, you see the youth on a sound strip of floor beyond a dropped section. The cracked lintel shifts behind you. A dusty shape crosses the rear doorway, but the real danger is the broken floor and falling stone.', choices: [{ id: 'crossGap', label: 'Cross the narrow boards to reach them', hint: 'The boards flex and the roof is shedding grit; a fall could be fatal.', chance: { probability: 0.72, successNext: 'dareRescue', failureNext: 'dareInjured', successMessage: 'The boards hold long enough for you to reach the youth.', failureMessage: 'A board breaks under your weight and you strike the floor below.', failureEffects: { health: -5 } } }, { id: 'backOut', label: 'Back out and call for help', next: 'dareHelp' }] },
      dareRescue: { id: 'dareRescue', title: 'Out before the Dust Falls', text: 'You lead the youth along the sound strip and out beside the wall. A moment later, a section of the cracked lintel sloughs into the doorway. The shadow at the rear is only a hanging coat moving in the draft.', choices: [{ id: 'stayForReaction', label: 'Wait with the youths for the owner', next: 'dareAfter', effects: { historyFlags: ['Stopped a Halloween dare before the unsafe toll house collapsed'] } }, { id: 'leaveAfterRescue', label: 'Leave once everyone is clear', next: 'dareAfter', effects: { knowledge: ['The old toll house floor had a hidden drop, while its moving shadow came from a coat in the draft.'] } }] },
      dareHelp: { id: 'dareHelp', title: 'A Safer Rescue', text: 'You keep the youths clear while a nearby road worker brings a rope and two neighbors. Together they anchor it to a sound post and help the trapped youth across. Nobody enters beneath the cracked lintel.', choices: [{ id: 'dareThank', label: 'Stay until the youth is checked', next: 'dareAfter', effects: { historyFlags: ['Chose a careful rescue during a Halloween dare'] } }, { id: 'dareDepart', label: 'Leave after the safe crossing', next: 'dareAfter' }] },
      dareInjured: { id: 'dareInjured', title: 'A Costly Crossing', tone: 'danger', text: 'You reach the youth but take a hard blow as a board and loose stone fall. The youth is able to follow you out. The toll house is now too unstable for another entry.', choices: [{ id: 'dareRecover', label: 'Let the neighbors take over', next: 'dareAfter', effects: { historyFlags: ['Was hurt while getting a youth out of the old toll house'] } }] },
      dareAfter: { id: 'dareAfter', title: 'No More Dares Tonight', text: 'The youths abandon the challenge. The owner agrees to mark the building closed until it can be braced; the one who went inside admits the dare had stopped being funny once the floor gave way. The shadow has no mystery left in it.', choices: [{ id: 'dareFinish', label: 'Leave the toll house behind', next: 'dareFinish', effects: { money: 2, knowledge: ['At the old toll house, a cracked lintel and dropped floor—not a ghost—made the Halloween dare dangerous.'] } }] },
      dareFinish: done('dareFinish', 'A Dare Ended Safely', 'The owner gives you two coins for keeping the youths clear until help arrived. You leave with the building marked unsafe and the dare finished for a better reason than bravado.'),
      dareDeclined: { ...done('dareDeclined', 'A Dare Not Taken', 'You decline the Halloween challenge and continue down the road. The youths may choose what to do, but you do not enter the visibly unsafe toll house.'), completionQualification: 'nonSubstantive' },
    },
  },
  {
    id: 'the-scarecrow-changes-fields', title: 'The Scarecrow Changes Fields', subtitle: 'A farmer’s scarecrow appears in the wrong field each morning.', startScene: 'scarecrowYard',
    diversity: d('A farm’s scarecrow moves between fields, but its loose sleeve and the farmer’s own work pattern complicate an apparent prank.', 'investigation/mystery', 'farm/homestead', 'MODERATE', 'AMBIGUOUS', 'AFFINITY'),
    scenes: {
      scarecrowYard: { id: 'scarecrowYard', title: 'Facing the Wrong Rows', text: 'A farmer asks for a second pair of eyes: the scarecrow stood by the north corn yesterday and is now at the south bean rows, facing the barn. A drag groove runs between fields, but one end disappears under a cart track. The farmer is certain no one moved it.', choices: [{ id: 'followGroove', label: 'Follow the drag groove', next: 'scarecrowTrack' }, { id: 'askWorkers', label: 'Ask who worked each field', next: 'scarecrowAccounts' }, { id: 'watchAfterDark', label: 'Watch the scarecrow after dusk', next: 'scarecrowWatch' }, { id: 'leaveFarm', label: 'Leave the matter to the farmer', next: 'scarecrowDeclined' }] },
      scarecrowTrack: { id: 'scarecrowTrack', title: 'A Trail under the Wagon', text: 'The groove leads to a wagon parked between the rows. Its wheel rut crosses the drag line, and a scrap of faded blue cloth is caught on the hub.', choices: [{ id: 'askWagonOwner', label: 'Ask the farmhand about the wagon', next: 'scarecrowAccounts' }, { id: 'checkCloth', label: 'Show the cloth to the farmer', next: 'scarecrowChoice' }] },
      scarecrowAccounts: { id: 'scarecrowAccounts', title: 'Two Different Mornings', text: 'A farmhand says they moved the scarecrow once to keep crows from a seed patch, then forgot to tell the farmer. The farmer insists it changed position a second night too. Neither account explains why it faces the barn.', choices: [{ id: 'compareCloth', label: 'Check the scarecrow’s loose sleeve', next: 'scarecrowChoice' }, { id: 'setWatch', label: 'Agree to watch from the barn porch', next: 'scarecrowWatch' }] },
      scarecrowWatch: { id: 'scarecrowWatch', title: 'The Shape at Dusk', text: 'From the porch you see no one cross the field. At dusk a gust turns the scarecrow’s loose sleeve toward the barn, and the head pivots slightly on its peg. A moment later, a crow lands on the crossbar.', choices: [{ id: 'inspectPeg', label: 'Inspect the head and sleeve by daylight', next: 'scarecrowChoice' }, { id: 'keepWatching', label: 'Watch until the fields go dark', next: 'scarecrowAfter', effects: { knowledge: ['A loose peg and wind could turn the scarecrow toward the barn; a farmhand had also moved it between fields once.'] } }] },
      scarecrowChoice: { id: 'scarecrowChoice', title: 'A Turned Peg', text: 'The head is tied with blue cloth and mounted on a loose peg. The farmer asks whether to anchor it in one field or leave it free to turn with the wind. The farmhand admits moving it once, but not on the night the drag groove appeared.', choices: [{ id: 'anchorScarecrow', label: 'Set it firmly in the seed field', next: 'scarecrowAfter', effects: { setFlags: ['scarecrowAnchored'] } }, { id: 'leaveScarecrowLoose', label: 'Leave it to turn with the wind', next: 'scarecrowAfter', effects: { setFlags: ['scarecrowLoose'] } }, { id: 'askFarmhandOwnIt', label: 'Ask the farmhand to explain the move', next: 'scarecrowAfter', effects: { setFlags: ['scarecrowAdmitted'] } }] },
      scarecrowAfter: { id: 'scarecrowAfter', title: 'The Field at First Light', text: 'At first light the scarecrow remains where the farmer left it. The farmhand agrees to tell the farmer before moving it; the unexplained drag groove may have come from a night cart, but nobody claims certainty.', textVariants: [{ requirements: { flags: ['scarecrowAnchored'] }, text: 'At first light the anchored scarecrow remains fixed in the seed field. The farmhand agrees to tell the farmer before moving it; the unexplained drag groove may have come from a night cart, but nobody claims certainty.' }, { requirements: { flags: ['scarecrowLoose'] }, text: 'At first light the scarecrow remains in the field, its loose head turned toward the barn by the wind. The farmhand agrees to tell the farmer before moving it; nobody claims certainty about the drag groove.' }], choices: [{ id: 'scarecrowPayoff', label: 'Accept breakfast and continue on', next: 'scarecrowPayoff', effects: { money: 1, historyFlags: ['Helped a farm settle a scarecrow dispute without accusing the workers'] } }] },
      scarecrowPayoff: done('scarecrowPayoff', 'A Face Toward the Barn', 'The farmer pays you one coin for careful help. The scarecrow stays in the seed field, its sleeve moving whenever the wind turns.'),
      scarecrowDeclined: done('scarecrowDeclined', 'A Farm Matter Left Alone', 'You decline to investigate. The farmer and farmhand continue their own conversation beside the fields.'),
    },
  },
  {
    id: 'the-harvest-mask', title: 'The Harvest Mask', subtitle: 'Several wearers describe the same impossible field.', startScene: 'maskLot',
    diversity: d('A carved mask creates matching visions in multiple wearers; the traveler must distinguish suggestion, fraud, and a persistent uncanny experience.', 'investigation/mystery', 'town/market/inn', 'HIGH', 'EERIE', 'AFFINITY'),
    scenes: {
      maskLot: { id: 'maskLot', title: 'The Estate Lot', text: 'At a farm-sale table sits a wearable wooden harvest mask, dark with age. Its narrow, oddly cut eye slits frame a field in a way that seems to unsettle the two people who tried it: both describe a black sun. The auctioneer says it belonged to the late owner and will not press anyone to wear it.', choices: [{ id: 'declineMask', label: 'Leave the mask untouched', next: 'maskDeclined' }, { id: 'inspectCarving', label: 'Inspect the mask without wearing it', next: 'maskCarving' }, { id: 'askWearers', label: 'Compare the wearers’ accounts', next: 'maskAccounts' }] },
      maskCarving: { id: 'maskCarving', title: 'A Narrow Eye-Line', text: 'The eye slits are cut unevenly. Held to the light, each frames a different slice of the real field beyond the barn door. A faint bitter smell clings to the inner rim, but you cannot identify it.', choices: [{ id: 'askAuctioneer', label: 'Ask who prepared the mask', next: 'maskAccounts' }, { id: 'testBriefly', label: 'Try it for one breath outdoors', next: 'maskVision' }] },
      maskAccounts: { id: 'maskAccounts', title: 'A Shared Description', text: 'Both wearers describe the same lone tree and ditch, although one has never visited this farm. The auctioneer says the old owner used the mask for a harvest play, and the inner rim was recently rubbed with oil to preserve it.', choices: [{ id: 'openWindows', label: 'Air the room and examine the oil', next: 'maskAir' }, { id: 'testBriefly', label: 'Try it for one breath outdoors', next: 'maskVision' }] },
      maskAir: { id: 'maskAir', title: 'Oil on the Inner Rim', text: 'With the room aired, the bitter smell fades. The auctioneer identifies the oil as a strong preservative. It cannot explain why two people described the same field, but no one else tries the mask.', choices: [{ id: 'leaveMaskToAuctioneer', label: 'Leave the mask for further study', next: 'maskAfter' }, { id: 'askWearersAgain', label: 'Ask the wearers what changed', next: 'maskAfter', effects: { knowledge: ['The mask’s bitter preservative oil may have affected its wearers; airing the room reduced the smell but did not explain their shared vision.'] } }] },
      maskVision: { id: 'maskVision', title: 'The Field behind the Eyes', tone: 'warning', text: 'For a breath, the mask frames a field under a dark sun. You remove it at once. The smell is stronger inside; the vision may come from suggestion, the strange eye-line, the oil, or something the sale cannot explain.', choices: [{ id: 'removeMask', label: 'Set it down and air the room', next: 'maskAfter', effects: { knowledge: ['The harvest mask’s repeated vision may be tied to its narrow eye-line and bitter preservation oil; its cause remains uncertain.'] } }, { id: 'keepMaskOn', label: 'Keep it on and follow the field image', hint: 'The smell is strongest inside the mask and the image is disorienting.', next: 'maskDanger' }] },
      maskDanger: { id: 'maskDanger', title: 'The Floor Is Not a Field', tone: 'danger', text: 'The room seems to lengthen. Your foot catches a bench and you fall hard before the auctioneer pulls the mask away. The injury is real even if the vision was not.', choices: [{ id: 'recoverMask', label: 'Sit outside until your balance returns', next: 'maskAfter', effects: { health: -3, setFlags: ['maskFall'] } }] },
      maskAfter: { id: 'maskAfter', title: 'The Sale Is Paused', text: 'The auctioneer ends the demonstration and locks the wearable mask in the estate office until its oily lining can be examined. No one will try it again today. The shared field remains an honest uncertainty, not proof of a curse.', textVariants: [{ requirements: { flags: ['maskFall'] }, text: 'After your fall, the auctioneer ends the demonstration and locks the wearable mask in the estate office until its oily lining can be examined. No one will try it again today. The shared field remains an honest uncertainty, not proof of a curse.' }], choices: [{ id: 'maskFinish', label: 'Leave the sale in the auctioneer’s care', next: 'maskFinish', effects: { historyFlags: ['Stopped an unsafe demonstration of the harvest mask'], lore: ['A harvest mask at a farm sale framed the same impossible field for several wearers.'] } }] },
      maskFinish: { ...done('maskFinish', 'A Field in Common', 'The auctioneer locks the mask away at the farm sale until its lining can be examined. You leave knowing several people saw the same image, but not why.'), textVariants: [{ requirements: { flags: ['maskFall'] }, text: 'The auctioneer locks away the mask after it disorients you and leaves you bruised. You leave knowing several people saw the same image, but not why.' }] },
      maskDeclined: { ...done('maskDeclined', 'No Mask Tried', 'You leave the mask untouched. The auctioneer continues the sale without pressing anyone to wear it.'), completionQualification: 'nonSubstantive' },
    },
  },
  {
    id: 'the-witch-at-millers-ford', title: 'The Witch at Miller’s Ford', subtitle: 'A frightened crowd calls a healer a witch after a child’s fever breaks.', startScene: 'fordCrowd',
    diversity: d('A crowd threatens an isolated folk healer; evidence about a spoiled remedy competes with rumor, and the traveler can reduce danger without deciding whether magic exists.', 'social interaction', 'river/ferry/lake', 'HIGH', 'AMBIGUOUS', 'AFFINITY'),
    scenes: {
      fordCrowd: { id: 'fordCrowd', title: 'At the Ford Gate', tone: 'warning', text: 'At Miller’s Ford, several neighbors gather outside a healer’s cottage. A child’s fever has eased after she refused a bitter draught, and some now call the healer a witch. No one is inside the cottage with her; a broken jar lies in the road, and the ford runs too swiftly to leave the children near it.', choices: [{ id: 'calmNeighbors', label: 'Ask the crowd to step back from the door', next: 'crowdTalk' }, { id: 'speakHealer', label: 'Ask to hear the healer’s account', next: 'healerTalk' }, { id: 'inspectJar', label: 'Inspect the broken jar from the road', next: 'jarClue' }, { id: 'leaveFord', label: 'Leave before the argument grows', next: 'witchDeclined' }] },
      crowdTalk: { id: 'crowdTalk', title: 'The Jar in the Road', text: 'The crowd gives you room, but one neighbor says the draught smelled of spoiled roots. Another insists the child improved only after the healer spoke an old charm. No one saw what was mixed into the jar.', choices: [{ id: 'hearHealer', label: 'Ask the healer what was in the draught', next: 'healerTalk' }, { id: 'checkJar', label: 'Compare the jar with the herb shelf', next: 'jarClue' }] },
      healerTalk: { id: 'healerTalk', title: 'A Practitioner’s Answer', text: 'The healer says the child had a fever and was given willow-bark tea, but the jar had been stored beside a spoiled root preparation. She cannot prove which caused the sickness. She asks only that the crowd stop throwing stones at her shutters.', choices: [{ id: 'askForEvidence', label: 'Ask to inspect the stored remedies', next: 'jarClue' }, { id: 'keepPeace', label: 'Ask them to wait for the family', next: 'witchAfter', effects: { setFlags: ['witchPeaceFirst'] } }] },
      jarClue: { id: 'jarClue', title: 'The Bitter Root', text: 'The jar’s smell matches a spoiled root bundle on the shelf. The healer says she had meant to discard it. The child’s aunt confirms the child refused the draught, but cannot say whether the brief taste caused the illness.', choices: [{ id: 'showRoot', label: 'Show the spoiled bundle to the neighbors', next: 'witchAfter', effects: { knowledge: ['At Miller’s Ford, a spoiled root preparation was found beside the healer’s remedies; the child’s illness had no certain cause.'], setFlags: ['witchEvidence'] } }, { id: 'removeRoot', label: 'Help the healer discard the spoiled root', next: 'witchAfter', effects: { setFlags: ['witchRootRemoved'] } }] },
      witchAfter: { id: 'witchAfter', title: 'The Crowd at a Distance', text: 'The neighbors step away from the cottage. If they saw the spoiled root, they agree to wait for the family’s account; if not, the healer leaves by the back path before the crowd can return. Nobody settles whether her practices are ordinary or otherwise.', textVariants: [{ requirements: { flags: ['witchEvidence'] }, text: 'The neighbors see the spoiled root and agree to wait for the child’s family rather than accuse the healer. The family will decide whether to ask her for help again.' }, { requirements: { flags: ['witchPeaceFirst'] }, text: 'The crowd agrees to wait for the child’s family. The healer leaves by the back path before anyone can turn the argument into a trial.' }], choices: [{ id: 'witchReward', label: 'Accept her written tea instructions', next: 'witchReward', effects: { knowledge: ['Miller’s Ford healer’s willow-bark tea must be made only from sound bark with clean water.'], historyFlags: ['Helped keep a frightened crowd from driving a healer from Miller’s Ford'] } }, { id: 'witchLeave', label: 'Leave without taking anything', next: 'witchLeave', effects: { historyFlags: ['Helped keep a frightened crowd from driving a healer from Miller’s Ford'] } }] },
      witchReward: done('witchReward', 'An Earned Account', 'The healer gives you a written account of how she prepares willow-bark tea, with the warning to use only sound bark and clean water. The crowd disperses, still uncertain but no longer gathered at her door.'),
      witchLeave: done('witchLeave', 'The Ford Grows Quiet', 'You leave the ford after the crowd disperses. The healer’s reputation remains unsettled, but nobody is forced to decide it by rumor.'),
      witchDeclined: done('witchDeclined', 'No Part in the Accusation', 'You leave before taking sides. The crowd remains at a distance from the door, and you do not learn what the family decides.'),
    },
  },
  {
    id: 'the-man-in-the-corn', title: 'The Man in the Corn', subtitle: 'A moving shape crosses the rows without following them.', startScene: 'cornfieldEdge',
    diversity: d('A moving figure seems to cross a cornfield against the rows; a missing farmhand, a wild animal, or a hostile intruder remain plausible until the traveler commits.', 'survival', 'farm/homestead', 'SEVERE', 'AMBIGUOUS', 'AFFINITY'),
    scenes: {
      cornfieldEdge: { id: 'cornfieldEdge', title: 'Movement between the Rows', tone: 'warning', text: 'At the cornfield edge, the farmer points to a dark shape moving crosswise through the stalks. The rows are shoulder-high and cut visibility to a few paces. A farmhand is missing, livestock refuse the field, and a loaded shotgun rests with the farmer—not with you.', choices: [{ id: 'stayEdge', label: 'Keep everyone at the field edge', next: 'cornTracks' }, { id: 'callFarmhand', label: 'Call the missing farmhand by name', next: 'cornReply' }, { id: 'enterCorn', label: 'Enter the rows alone', hint: 'The rows hide both ground and movement; something may be close.', next: 'cornDanger' }, { id: 'leaveCorn', label: 'Leave and fetch more help', next: 'cornHelp' }] },
      cornTracks: { id: 'cornTracks', title: 'A Break in the Rows', text: 'At the edge you find a narrow path trampled against the planting direction. There are boot prints going in and none clearly coming out. A pale strip of shirt cloth is caught on a stalk.', choices: [{ id: 'callAcrossRows', label: 'Call once from the path', next: 'cornReply' }, { id: 'waitForHelp', label: 'Wait for the farmer’s neighbor', next: 'cornHelp' }] },
      cornReply: { id: 'cornReply', title: 'A Voice or an Echo', tone: 'warning', text: 'Something answers with two short whistles. The farmer says that is the missing hand’s signal, but livestock have heard it too and are pushing at the fence. You still cannot see who made the sound.', choices: [{ id: 'holdFence', label: 'Help the farmer secure the livestock', next: 'cornHelp' }, { id: 'followWhistle', label: 'Follow the trampled row toward the signal', next: 'cornDanger' }] },
      cornDanger: { id: 'cornDanger', title: 'The Rows Close Behind', tone: 'danger', text: 'The stalks close around you. The shape moves fast across the rows, then stops. You hear a heavy animal snort nearby; a rusted drainage trench runs hidden beneath the plants. Turn back while the edge remains in sight, or press toward the movement.', choices: [{ id: 'retreatCorn', label: 'Retreat toward the field edge', next: 'cornAfter', effects: { setFlags: ['cornRetreated'] } }, { id: 'pressCorn', label: 'Press toward the stopped shape', hint: 'The hidden trench and unseen animal make this a potentially fatal risk.', chance: { probability: 0.55, successNext: 'cornFound', failureNext: 'cornKilled', successMessage: 'You reach the shape without falling into the trench.', failureMessage: 'The ground drops beneath you as something charges through the stalks.', failureEffects: { health: -99 } } }] },
      cornFound: { id: 'cornFound', title: 'A Farmhand and a Boar', text: 'The shape is the missing farmhand, pinned behind a fallen fence rail while a wild boar roots in the crop. The farmer’s shouting draws the animal away. You and the farmhand reach the edge without trying to corner it.', choices: [{ id: 'walkFarmhandBack', label: 'Walk the farmhand back to the house', next: 'cornAfter', effects: { money: 3, knowledge: ['A trampled cross-row path through corn concealed a drainage trench and a wild boar; the missing hand was trapped behind a fallen rail.'], setFlags: ['cornRescued'] } }] },
      cornHelp: { id: 'cornHelp', title: 'More Hands at the Fence', text: 'A neighbor arrives with a long pole and helps the farmer close the pasture gate. From the safe edge, you hear the missing hand answer again. They are trapped behind a fallen rail, not lost in the rows.', choices: [{ id: 'guideHand', label: 'Guide the farmhand along the outer row', next: 'cornFound', effects: { setFlags: ['cornHelped'] } }, { id: 'waitNeighbor', label: 'Let the neighbor draw the boar away', next: 'cornAfter', effects: { setFlags: ['cornRetreated'] } }] },
      cornAfter: { id: 'cornAfter', title: 'The Field Is Closed', text: 'The farmer bars the field until daylight and asks the neighbors to check the drainage trench before anyone enters. The search will continue with more people and a clear route.', textVariants: [{ requirements: { flags: ['cornRetreated'] }, text: 'You leave the field closed and the search to a larger group at daylight. The farmer keeps the livestock behind the sound fence.' }, { requirements: { flags: ['cornRescued'] }, text: 'The missing farmhand sits safely beside the house while the farmer bars the field until daylight. Neighbors will check the drainage trench before anyone enters again.' }], choices: [{ id: 'cornEnd', label: 'Take the road back to the farm', next: 'cornEnd', effects: { historyFlags: ['Helped contain a dangerous search in a cornfield'] } }] },
      cornKilled: dead('cornKilled', 'Lost between the Rows', 'You fall into the hidden drainage trench as the boar charges through the corn. The farmer hears the crash but cannot reach you before the animal and broken ground make the field lethal.'),
      cornEnd: done('cornEnd', 'The Cornfield at Dusk', 'The missing hand is carried home if found; otherwise, the search waits for daylight and more people. The boar leaves the rows on its own, and the farmer keeps the field closed.'),
    },
  },
  {
    id: 'coffin-makers-extra-order', title: 'The Coffin Maker’s Extra Order', subtitle: 'An anonymous coffin order matches a living customer’s measurements.', startScene: 'coffinWorkshop',
    diversity: d('A coffin maker receives a paid, anonymous order measured to a living neighbor, forcing a choice between privacy, warning, and tracing the order.', 'investigation/mystery', 'workshop/mill/quarry/warehouse', 'MODERATE', 'AMBIGUOUS', 'AFFINITY'),
    scenes: {
      coffinWorkshop: { id: 'coffinWorkshop', title: 'The Unclaimed Order', text: 'A coffin maker shows you an order paid in advance and left without a name. Its measurements match Mr. Dace, who is alive and standing across the street. The maker will not build it without understanding the threat, but fears losing the payment.', choices: [{ id: 'askDace', label: 'Warn Dace privately', next: 'daceAccount' }, { id: 'traceOrder', label: 'Ask the maker about the handwriting', next: 'orderClue' }, { id: 'returnPayment', label: 'Advise returning the payment', next: 'coffinAfter', effects: { setFlags: ['orderReturned'] } }, { id: 'leaveOrder', label: 'Leave the maker to decide', next: 'coffinDeclined' }] },
      daceAccount: { id: 'daceAccount', title: 'A Poor Joke', text: 'Dace recognizes the measurements: he gave them to a traveling tailor after a coat fitting. He has no enemy he can name, but a former business partner recently threatened to “put him in a box.”', choices: [{ id: 'compareWriting', label: 'Compare the order with a shop note', next: 'orderClue' }, { id: 'bringMakerTogether', label: 'Ask Dace and the maker to speak together', next: 'coffinAfter', effects: { setFlags: ['daceInformed'] } }] },
      orderClue: { id: 'orderClue', title: 'A Tailor’s Hand', text: 'The order uses the tailor’s distinctive crossed sevens. The maker admits the tailor delivered the paper and said it was a joke, but never said whose joke it was. Dace’s former partner has paid the tailor for work before.', choices: [{ id: 'confrontTailor', label: 'Ask the tailor to explain the order', next: 'tailorAccount' }, { id: 'keepOrderEvidence', label: 'Keep the order and warn Dace', next: 'coffinAfter', effects: { setFlags: ['orderKept'] } }] },
      tailorAccount: { id: 'tailorAccount', title: 'A Threat Made Useful', text: 'The tailor says Dace’s former partner supplied the measurements and meant to frighten him into settling an old debt. The tailor thought it was theater. Dace calls the debt disputed and refuses to meet the partner alone.', choices: [{ id: 'returnOrder', label: 'Return the order and payment', next: 'coffinAfter', effects: { setFlags: ['orderReturned', 'tailorNamed'] } }, { id: 'keepOrder', label: 'Keep the order as evidence', next: 'coffinAfter', effects: { setFlags: ['orderKept', 'tailorNamed'] } }] },
      coffinAfter: { id: 'coffinAfter', title: 'No Coffin Built', text: 'The maker refuses to build the coffin. If the order was returned, the payment goes back to the tailor; if kept as evidence, the paper is sealed with Dace’s consent. The threat is now known, though the debt itself remains disputed.', textVariants: [{ requirements: { flags: ['orderReturned'] }, text: 'The maker returns the payment and refuses the work. Dace asks the town clerk to witness any future discussion of the debt.' }, { requirements: { flags: ['orderKept'] }, text: 'The maker seals the order as evidence and refuses the work. Dace asks the town clerk to witness any future discussion of the debt.' }], choices: [{ id: 'coffinFinish', label: 'Leave the workshop with Dace', next: 'coffinFinish', effects: { knowledge: ['An anonymous coffin order used a living man’s tailor measurements to threaten him over a disputed debt.'], historyFlags: ['Helped expose a threat disguised as a coffin order'] } }] },
      coffinFinish: done('coffinFinish', 'An Order Cancelled', 'No coffin is made. Dace and the maker leave together to speak with the town clerk, and the tailor must answer for turning a disputed debt into a threat.'),
      coffinDeclined: done('coffinDeclined', 'A Decision Unmade', 'You leave the maker with the unsigned order. The measurements remain alarming, but you do not involve yourself in the dispute.'),
    },
  },
  {
    id: 'skeleton-in-the-wagon', title: 'The Skeleton in the Wagon', subtitle: 'A traveling teacher cannot prove where his lesson bones came from.', startScene: 'wagonShed',
    diversity: d('An articulated teaching skeleton prompts a provenance dispute resolved through records and respectful handling rather than a supernatural reveal.', 'investigation/mystery', 'road/bridge', 'MODERATE', 'NONE', 'AFFINITY'),
    scenes: {
      wagonShed: { id: 'wagonShed', title: 'A Cart without a Wheel', text: 'A traveling anatomy teacher’s wagon breaks an axle beside a shed. Its crate has opened, showing an articulated human skeleton tied upright for lessons. The teacher says it came from a medical school; a passerby says the bones resemble a relative buried nearby.', choices: [{ id: 'askTeacher', label: 'Ask the teacher for his papers', next: 'skeletonPapers' }, { id: 'askWitness', label: 'Hear the passerby’s account', next: 'skeletonWitness' }, { id: 'helpAxle', label: 'Help brace the wagon before rain', next: 'skeletonAxle' }, { id: 'leaveBones', label: 'Leave the dispute to the sheriff', next: 'skeletonDeclined' }] },
      skeletonPapers: { id: 'skeletonPapers', title: 'A School Seal', text: 'The teacher produces a receipt bearing a school seal, but it lists only “one teaching specimen.” The passerby says their relative’s grave was opened years ago and never properly closed.', choices: [{ id: 'compareNames', label: 'Compare the tag with the receipt', next: 'skeletonClerk' }, { id: 'protectRemains', label: 'Cover the bones and pause the lesson', next: 'skeletonAfter', effects: { setFlags: ['bonesCovered'] } }] },
      skeletonWitness: { id: 'skeletonWitness', title: 'A Family Marker', text: 'The passerby remembers a brass tag on the relative’s coffin and a crooked finger bone. They cannot identify the bones from across the shed, and they ask that no one handle them roughly.', choices: [{ id: 'checkTag', label: 'Look for a tag without moving the bones', next: 'skeletonClerk' }, { id: 'coverCrate', label: 'Cover the crate and wait before moving it', next: 'skeletonAfter', effects: { setFlags: ['bonesCovered'] } }] },
      skeletonAxle: { id: 'skeletonAxle', title: 'The Crate Must Stay Upright', text: 'The axle can be braced with a fence rail, but shifting the wagon would jostle the open crate. The teacher and passerby both ask that the bones be covered before the wheel is moved.', choices: [{ id: 'coverAndBrace', label: 'Cover the crate, then brace the axle', next: 'skeletonAfter', effects: { setFlags: ['bonesCovered'] } }, { id: 'callClerk', label: 'Wait before moving the wagon', next: 'skeletonClerk' }] },
      skeletonClerk: { id: 'skeletonClerk', title: 'A Record without a Name', text: 'The crate lining holds a brass lot tag that matches the school receipt’s shipment mark. Neither record identifies whose remains they are. The mark narrows the source to a school shipment, not a particular grave.', choices: [{ id: 'recordDispute', label: 'Record the uncertainty and protect the bones', next: 'skeletonAfter', effects: { knowledge: ['A teaching skeleton had a school receipt and matching lot tag, but no record identifying whose remains they were.'] } }, { id: 'askForPause', label: 'Ask the teacher to suspend the lesson', next: 'skeletonAfter', effects: { setFlags: ['bonesCovered'] } }] },
      skeletonAfter: { id: 'skeletonAfter', title: 'A Lesson Delayed', text: 'The teacher covers the crate and agrees to take the lot number back to the school. The passerby receives a written account of the shipment, but no one claims the bones have been identified. The wagon is braced, and the lesson is postponed.', choices: [{ id: 'skeletonPayment', label: 'Accept a meal for helping settle matters', next: 'skeletonPayment', effects: { historyFlags: ['Helped protect human remains during a disputed teaching display'] } }] },
      skeletonPayment: done('skeletonPayment', 'The Crate Travels Covered', 'The teacher gives you supper for helping with the axle and the careful delay. The bones remain covered until the school can trace their record; the family’s question is neither dismissed nor falsely answered.'),
      skeletonDeclined: done('skeletonDeclined', 'A Dispute Left Unsettled', 'You leave the wagon and its disputed cargo to the people already present. The crate is covered before the teacher continues his explanation.'),
    },
  },
  {
    id: 'the-headless-rider', title: 'The Headless Rider', subtitle: 'A rider appears headless only when seen against the ridge lanterns.', startScene: 'ridgeRumor',
    diversity: d('A night rider’s missing head is caused by a hood and lantern alignment, but the rider is concealing an injured passenger and a stolen horse.', 'investigation/mystery', 'road/bridge', 'HIGH', 'EERIE', 'AFFINITY'),
    scenes: {
      ridgeRumor: { id: 'ridgeRumor', title: 'A Shape on the Ridge', text: 'Farmers and coach drivers here know the old Headless Rider tale: a dark shape said to pass the ridge road at dusk. Tonight you see one yourself, its shoulders apparently joined to the horse’s mane. A lantern post stands behind the track; a steep ditch lies between you and the road.', choices: [{ id: 'watchRider', label: 'Watch the next pass from the road', next: 'riderPass' }, { id: 'callRider', label: 'Call out from the safe roadside', next: 'riderAnswer' }, { id: 'approachRider', label: 'Approach across the ditch', hint: 'The ditch is steep and the horse is moving fast.', next: 'riderDanger' }, { id: 'leaveRider', label: 'Leave the ridge before dark', next: 'riderDeclined' }] },
      riderPass: { id: 'riderPass', title: 'The Lantern Line', text: 'The figure passes behind the lantern post. A hood folds low over the rider’s face, hiding it in shadow. The horse is lathered and favors one leg; something pale shifts behind the rider.', choices: [{ id: 'signalStop', label: 'Raise both hands and signal them to stop', next: 'riderAnswer' }, { id: 'followAtDistance', label: 'Follow from the marked road', next: 'riderTrail' }] },
      riderAnswer: { id: 'riderAnswer', title: 'A Voice beneath the Hood', text: 'The rider turns. You hear a woman ask whether the road reaches the mill, then a second voice from behind her says nothing. She does not appear headless from this angle, but she urges the horse onward.', choices: [{ id: 'offerHelp', label: 'Offer help from the road', next: 'riderTruth' }, { id: 'followRoad', label: 'Follow at a respectful distance', next: 'riderTrail' }] },
      riderTrail: { id: 'riderTrail', title: 'A Fresh Track', text: 'The hoofprints turn toward an abandoned stable rather than the mill. The horse leaves a faint blood mark where its shoe has shifted. You can hear the rider trying to quiet it.', choices: [{ id: 'approachStable', label: 'Call out before entering the stable yard', next: 'riderTruth' }, { id: 'fetchHelp', label: 'Fetch the road keeper', next: 'riderTruth', effects: { setFlags: ['riderHelpFetched'] } }] },
      riderDanger: { id: 'riderDanger', title: 'The Horse Shies', tone: 'danger', text: 'The horse shies at the ditch edge. The rider pulls it around and the pale shape behind them cries out. You are close enough to see the horse is hurt, but not close enough to take its reins safely.', choices: [{ id: 'stepBackRider', label: 'Step back and let them turn', next: 'riderTruth', effects: { setFlags: ['riderTurned'] } }, { id: 'grabHorse', label: 'Grab for the bridle', hint: 'A frightened, injured horse can strike or trample.', chance: { probability: 0.55, successNext: 'riderTruth', failureNext: 'riderHurt', successMessage: 'You catch the hanging lead and steady the horse.', failureMessage: 'The horse jerks sideways and knocks you down.', failureEffects: { health: -4 } } }] },
      riderHurt: { id: 'riderHurt', title: 'A Hard Fall', tone: 'warning', text: 'You fall clear of the hooves, bruised but not trapped. The rider stops when the hidden passenger calls out. They will not leave the injured horse behind now.', choices: [{ id: 'riderRecover', label: 'Let them dismount and explain', next: 'riderTruth', effects: { setFlags: ['riderTurned'] } }] },
      riderTruth: { id: 'riderTruth', title: 'Two People, One Horse', text: 'The rider removes the hood: she is a mill worker carrying her injured brother away from an abusive employer. The horse is borrowed without permission and too lame to continue. She had used the ridge silhouette to avoid being recognized. A road keeper’s post stands a short walk down the marked road.', choices: [{ id: 'helpRider', label: 'Help them reach the road keeper', next: 'riderAfter', effects: { setFlags: ['riderHelped'] } }, { id: 'reportRider', label: 'Ask the keeper about the borrowed horse', next: 'riderAfter', effects: { setFlags: ['riderReported'] } }, { id: 'leaveRiderTruth', label: 'Leave them to choose their next step', next: 'riderAfter', effects: { setFlags: ['riderLeft'] } }] },
      riderAfter: { id: 'riderAfter', title: 'The Hood Comes Down', text: 'The road keeper’s post is close, and the brother needs care. The horse’s owner has not yet been told; the rider is no ghost, but the silhouette served its purpose.', textVariants: [{ requirements: { flags: ['riderHelped'] }, text: 'You help the brother reach a nearby cottage for care and tell the road keeper where the borrowed horse stands. The rider is no ghost, but the silhouette served its purpose.' }, { requirements: { flags: ['riderReported'] }, text: 'The road keeper agrees to locate the horse’s owner and arrange care for the brother. The rider is no ghost, but the silhouette served its purpose.' }, { requirements: { flags: ['riderLeft'] }, text: 'You leave the worker and her brother at the stable; the road keeper’s post is nearby, but you do not wait to learn what they decide. The horse is too lame to continue.' }], choices: [{ id: 'riderFinish', label: 'Continue down the road', next: 'riderFinish', effects: { historyFlags: ['Learned why a hooded rider used the ridge road to avoid recognition'] } }] },
      riderFinish: { id: 'riderFinish', title: 'The Road below the Ridge', text: 'A hood and lantern explain how tonight’s rider echoed the district’s old tale, without proving what every past witness saw.', textVariants: [{ requirements: { flags: ['riderHelped'] }, text: 'The road keeper takes responsibility for the borrowed horse while the injured brother reaches shelter. A hood and lantern explain tonight’s headless silhouette; the older ridge tale remains a tale.' }, { requirements: { flags: ['riderReported'] }, text: 'The road keeper now knows about the borrowed horse and injured brother. The hood and lantern explain tonight’s silhouette, though they settle nothing about the older tale.' }, { requirements: { flags: ['riderLeft'] }, text: 'You leave before learning what the pair decide. The hooded silhouette echoes the old story, but you do not learn why it was made.' }], ending: 'success', choices: [] },
      riderDeclined: { ...done('riderDeclined', 'No Pursuit', 'You leave the ridge before dark. You do not follow the rider, and the road remains open.'), completionQualification: 'nonSubstantive' },
    },
  },
  {
    id: 'the-last-house-before-the-woods', title: 'The Last House before the Woods', subtitle: 'A hospitable family asks you not to answer a voice beyond the fence.', startScene: 'lastHouse',
    diversity: d('The traveler must decide whether to trust a family’s practical night rules at an isolated house while an unknown voice tests the boundary.', 'survival', 'domestic interior', 'HIGH', 'EERIE', 'AFFINITY'),
    scenes: {
      lastHouse: { id: 'lastHouse', title: 'A Room before Dark', text: 'Rain catches you at the last house before a broad wood. The family offers supper and a dry room. Their only request: after dark, do not open the north door or answer anyone calling from beyond the fence. They show you the north door and the fence before dusk; no one is outside.', choices: [{ id: 'acceptRoom', label: 'Accept the room and ask why', next: 'houseRules' }, { id: 'refuseStay', label: 'Thank them and continue before dark', next: 'houseDeclined' }, { id: 'inspectFence', label: 'Inspect the north fence in daylight', next: 'houseBoundary' }] },
      houseRules: { id: 'houseRules', title: 'A Rule without a Story', text: 'The family says a loose dog has come to the north fence before, and their youngest child sleepwalks. They do not claim ghosts. A lantern and a sturdy bar are already fitted inside the north door.', choices: [{ id: 'agreeRule', label: 'Agree to leave the door barred', next: 'houseNight', effects: { setFlags: ['northDoorBarred'] } }, { id: 'sleepNearDoor', label: 'Ask for a room away from the north door', next: 'houseNight' }] },
      houseBoundary: { id: 'houseBoundary', title: 'Tracks outside the Fence', text: 'In daylight you find dog tracks along the outside of the fence and small bare footprints on the inside. The family’s explanation is plausible, but the child says they have not left the house at night.', choices: [{ id: 'askChild', label: 'Ask the child about the footprints gently', next: 'houseNight', effects: { setFlags: ['childAsked'] } }, { id: 'stayBoundary', label: 'Accept shelter and watch from indoors', next: 'houseNight' }] },
      houseNight: { id: 'houseNight', title: 'A Voice at the North Door', tone: 'warning', text: 'After dark, a voice calls from beyond the fence using the child’s name. The dog barks once. By the time you reach the north door, a shadow has moved from the fence to the stoop. The bar is still set across the door, and the family is awake in the kitchen. The voice may be a person, the dog owner, or someone who knows the household.', choices: [{ id: 'keepDoorBarred', label: 'Keep the door shut and wake the family', next: 'houseAfter', effects: { setFlags: ['voiceIgnored'] } }, { id: 'lookWindow', label: 'Look through the shutter crack', next: 'houseOutside' }, { id: 'openNorthDoor', label: 'Open the door and call back', hint: 'The caller has reached the stoop; the family warned you and the doorway is exposed.', next: 'houseDanger' }] },
      houseOutside: { id: 'houseOutside', title: 'A Figure at the Gate', text: 'Through the shutter you see a man by the gate holding a small lantern. He is not the child. The dog has gone quiet, and the man steps away when the family lights the kitchen.', choices: [{ id: 'wakeFamily', label: 'Tell the family what you saw', next: 'houseAfter', effects: { setFlags: ['callerSeen'] } }, { id: 'stayShut', label: 'Stay behind the barred door', next: 'houseAfter', effects: { setFlags: ['voiceIgnored'] } }] },
      houseDanger: { id: 'houseDanger', title: 'The Bar Holds', tone: 'danger', text: 'A man is waiting just beyond the threshold, not the child. He reaches for the door as the family pulls you back. The bar holds, but you are struck against the frame.', choices: [{ id: 'barAfter', label: 'Help the family hold the door', next: 'houseAfter', effects: { health: -3, setFlags: ['callerFled'] } }, { id: 'retreatKitchen', label: 'Retreat to the lit kitchen', next: 'houseAfter', effects: { setFlags: ['callerFled'] } }] },
      houseAfter: { id: 'houseAfter', title: 'The North Door at Dawn', text: 'At dawn, the family knows only that someone called from beyond the fence. The child slept in the kitchen. The household keeps the north door barred while they decide whether to ask the road keeper to walk the boundary.', textVariants: [{ requirements: { flags: ['callerSeen'] }, text: 'At dawn, the family reports the boot-printed stranger you saw beyond the fence to the road keeper. The child slept in the kitchen. Their rule kept everyone inside; no haunting is established.' }, { requirements: { flags: ['callerFled'] }, text: 'At dawn, the family finds a boot print beyond the fence and reports the stranger who tested the barred door. The child slept in the kitchen; the unknown caller is gone.' }], choices: [{ id: 'houseFinish', label: 'Share breakfast before setting out', next: 'houseFinish', effects: { historyFlags: ['Respected a household boundary and helped report a stranger at the north fence'], knowledge: ['The last house before the woods barred its north door after dark because a stranger had been calling from beyond the fence.'] } }] },
      houseFinish: done('houseFinish', 'Morning beyond the Fence', 'The family gives you breakfast and a dry place to repack. You leave in daylight with the stranger reported and the house’s caution understood, if not every reason for it.'),
      houseDeclined: done('houseDeclined', 'A Dry Road Chosen', 'You thank the family and continue before dark. You do not learn what the north-door rule was meant to prevent.'),
    },
  },
];
