import type { Scenario } from '../types';

const sourceValues = ['wellRunoff', 'spoiledStew', 'waterBarrel', 'wellDebris'];

export const POISON_THE_WELL: Scenario = {
  id: 'poison-the-well', title: 'Poison the Well', subtitle: 'A shared meal, a shared well, and no simple answer.', startScene: 'arrival',
  runRandomSelections: [
    { id: 'setting', values: ['farm', 'roadsideInn', 'travelerShelter'].map((value) => ({ value })) },
    { id: 'source', values: sourceValues.map((value) => ({ value })) },
    { id: 'host', values: ['Gilda', 'Eamon', 'Dulcie', 'Albin', 'Jocasta'].map((value) => ({ value })) },
  ],
  scenes: {
    arrival: { id: 'arrival', title: 'A Quiet House, Uneasy Guests', tone: 'warning',
      text: 'At a {{setting}}, you find two people resting with stomach cramps. {{host}} says the trouble began before dawn. A covered water barrel, the shared well, and a pot of last night’s stew have all been used today. A clean cup sits by the barrel. Nobody knows the cause; none should be tasted as a test.',
      textVariants: [
        { requirements: { selections: { setting: 'farm' } }, text: 'At a family farm, you find two people resting with stomach cramps. {{host}} says the trouble began before dawn. A covered water barrel, the shared well, and a pot of last night’s stew have all been used today. A clean cup sits by the barrel. Nobody knows the cause; none should be tasted as a test.' },
        { requirements: { selections: { setting: 'roadsideInn' } }, text: 'At a roadside inn, you find two guests resting with stomach cramps. {{host}} says the trouble began before dawn. A covered water barrel, the shared well, and a pot of last night’s stew have all been used today. A clean cup sits by the barrel. Nobody knows the cause; none should be tasted as a test.' },
        { requirements: { selections: { setting: 'travelerShelter' } }, text: 'At a travelers’ shelter, you find two people resting with stomach cramps. {{host}} says the trouble began before dawn. A covered water barrel, the shared well, and a pot of last night’s stew have all been used today. A clean cup sits by the barrel. Nobody knows the cause; none should be tasted as a test.' },
      ],
      choices: [
        { id: 'askTimeline', label: 'Ask who fell ill, and when', timeCost: 8, next: 'timeline' },
        { id: 'inspectWell', label: 'Inspect the well and its edge', timeCost: 12, next: 'wellInspection' },
        { id: 'inspectFood', label: 'Check the shared food', timeCost: 10, next: 'foodInspection' },
        { id: 'leave', label: 'Thank them and move on', effects: { historyFlags: ['left_before_investigating_illness'] }, next: 'leftEarly' },
      ] },
    timeline: { id: 'timeline', title: 'The First Reports', tone: 'safe',
      text: 'One person ate the stew but drank only from the well; another used the water barrel and skipped supper. A third is not sure. The overlap is imperfect, but {{host}} has enough clean water for a short while if the shared sources are set aside.',
      textVariants: [{ requirements: { selections: { source: 'wellRunoff' } }, text: 'The first person to fall ill drank from the well after rain; two others followed. Their meals differed. {{host}} has enough clean water for a short while if the well is set aside.' }, { requirements: { selections: { source: 'spoiledStew' } }, text: 'Everyone sick ate the stew; two healthy people skipped it. Their water came from different places. {{host}} has enough clean food and clean water for a short while.' }, { requirements: { selections: { source: 'waterBarrel' } }, text: 'Everyone sick drank from the covered barrel; two healthy people used the well instead. The barrel’s lid sat crooked this morning. {{host}} has clean water for a short while.' }, { requirements: { selections: { source: 'wellDebris' } }, text: 'The sickness began after someone noticed leaves and a sour smell near the well’s lower channel. Other meals differed. {{host}} has clean water set aside for a short while.' }],
      choices: [
        { id: 'closeWell', label: 'Ask everyone to avoid the well', timeCost: 4, effects: { setFlags: ['wellClosed'] }, next: 'wellSetAside' },
        { id: 'inspectBarrel', label: 'Inspect the covered water barrel', timeCost: 8, next: 'barrelInspection' },
        { id: 'inspectMeal', label: 'Compare the meals served', timeCost: 8, next: 'foodInspection' },
      ] },
    wellInspection: { id: 'wellInspection', title: 'At the Well', tone: 'warning',
      text: 'The stone rim is dry. The opening is narrow, and the water lies below arm’s reach. No one has seen anything fall in. Rain ran across the yard last night, but that alone does not prove the well is at fault.',
      textVariants: [
        { requirements: { selections: { source: 'wellRunoff' } }, text: 'The well rim is wet where last night’s rain ran down the slope. A thin brown line reaches the stonework; the water lies below arm’s reach. The runoff may have entered, but you cannot tell by looking.' },
        { requirements: { selections: { source: 'wellDebris' } }, text: 'Wet leaves and a sour smell collect in the low channel beside the well. The opening is narrow and water lies below arm’s reach; you cannot see what is beneath the surface.' },
      ],
      choices: [
        { id: 'sampleWell', label: 'Lower the clean cup without drinking', hint: 'Your rope keeps you back from the narrow opening.', requirements: { items: ['travelRope'] }, timeCost: 8, effects: { setFlags: ['sampledWell'] }, next: 'wellEvidence' },
        { id: 'useHook', label: 'Check the reachable drain with your hook', requirements: { items: ['drainageHook'], selections: { source: 'wellDebris' } }, timeCost: 8, effects: { setFlags: ['used_drainage_hook'] }, next: 'wellEvidence' },
        { id: 'mirrorWellLip', label: 'Use your mirror beneath the stone lip', requirements: { items: ['foldingCardMirror'] }, timeCost: 6, effects: { setFlags: ['inspected_well_lip'] }, next: 'wellEvidence' },
        { id: 'loupeResidue', label: 'Inspect the damp grit with your loupe', hint: 'Fine detail may raise a concern, not name a poison.', requirements: { items: ['assayersLoupe'], selections: { source: 'wellRunoff' } }, timeCost: 6, effects: { setFlags: ['inspected_well_grit'] }, next: 'wellEvidence' },
        { id: 'glovedDebris', label: 'Lift reachable leaves with your gloves', requirements: { items: ['heavyLeatherGloves'], selections: { source: 'wellDebris' } }, timeCost: 6, effects: { setFlags: ['cleared_reachable_well_debris'] }, next: 'wellEvidence' },
        { id: 'askTimelineFromWell', label: 'Compare who ate and drank what', timeCost: 6, next: 'reportsCollected' },
        { id: 'warnWell', label: 'Set the well aside while you compare sources', timeCost: 4, effects: { setFlags: ['wellClosed'] }, next: 'wellSetAside' },
      ] },
    foodInspection: { id: 'foodInspection', title: 'What Was Shared?', tone: 'safe',
      text: 'The stew pot is covered, but it sat near the warm stove overnight. A clean water cup and a basket of bread are separate. Nobody can identify a source just by looking, and tasting suspect food would tell you little safely.',
      textVariants: [{ requirements: { selections: { source: 'spoiledStew' } }, text: 'A sour smell rises when {{host}} lifts the stew-pot lid. The bread and clean water were kept apart. This is a warning, not proof, and tasting it would be an unsafe test.' }],
      choices: [
        { id: 'compareMeals', label: 'Compare who ate each dish', timeCost: 8, next: 'reportsCollected' },
        { id: 'checkBarrelFromKitchen', label: 'Inspect the covered water barrel', timeCost: 8, next: 'barrelInspection' },
        { id: 'tasteWarning', label: 'Consider tasting the suspect stew', hint: 'The sick ate it; tasting is an avoidable exposure, not a reliable test.', timeCost: 2, next: 'tasteWarning' },
        { id: 'discardStew', label: 'Discard the stew as a precaution', timeCost: 5, effects: { setFlags: ['stewDiscarded'] }, next: 'stewSetAside' },
      ] },
    barrelInspection: { id: 'barrelInspection', title: 'The Water Barrel', tone: 'warning',
      text: 'The wooden barrel stands beside the kitchen door. Its lid is heavy enough to keep out leaves, but the rim is damp and the small tap is used by everyone. You can inspect it without drinking.',
      textVariants: [{ requirements: { selections: { source: 'waterBarrel' } }, text: 'The barrel lid rocks on one chipped edge. A muddy thumbprint marks the rim, and the tap’s inner lip is dark with old grime. The well water looks clear; neither fact alone proves anything.' }],
      choices: [
        { id: 'coverBarrel', label: 'Set the barrel aside and use clean water', timeCost: 4, effects: { setFlags: ['barrelClosed'] }, next: 'barrelSetAside' },
        { id: 'askWhoUsedBarrel', label: 'Compare who ate and drank what', timeCost: 6, next: 'reportsCollected' },
        { id: 'checkDrainage', label: 'Compare the well and meal reports', timeCost: 8, next: 'reportsCollected' },
      ] },
    tasteWarning: { id: 'tasteWarning', title: 'A Poor Test', tone: 'danger',
      text: 'You know the stew was shared by people who fell ill. No taste can identify a cause reliably. If you still choose to eat it, you accept a real chance of feeling sick yourself.',
      choices: [
        { id: 'tasteStewIfSource', label: 'Taste a spoonful anyway', requirements: { selections: { source: 'spoiledStew' } }, timeCost: 45, effects: { health: -2, setFlags: ['ate_suspect_food'] }, next: 'feltIll' },
        { id: 'tasteStewIfOther', label: 'Taste a spoonful anyway', requirements: { selections: { source: 'wellRunoff' } }, timeCost: 45, effects: { setFlags: ['ate_suspect_food'] }, next: 'noImmediateIllness' },
        { id: 'tasteStewIfBarrel', label: 'Taste a spoonful anyway', requirements: { selections: { source: 'waterBarrel' } }, timeCost: 45, effects: { setFlags: ['ate_suspect_food'] }, next: 'noImmediateIllness' },
        { id: 'tasteStewIfDebris', label: 'Taste a spoonful anyway', requirements: { selections: { source: 'wellDebris' } }, timeCost: 45, effects: { setFlags: ['ate_suspect_food'] }, next: 'noImmediateIllness' },
        { id: 'doNotTaste', label: 'Do not eat it; compare the evidence', timeCost: 2, next: 'reportsCollected' },
      ] },
    wellEvidence: { id: 'wellEvidence', title: 'A Careful Inspection', tone: 'warning',
      text: 'A careful look raises concern, but gives no laboratory answer. A smell, color, or speck cannot name a poison or prove what made anyone sick.',
      textVariants: [
        { requirements: { flags: ['sampledWell'] }, text: 'You lower the clean cup and bring up a little water without drinking it. A smell, color, or speck can raise concern, but there is no field test here that can name a poison.' },
        { requirements: { flags: ['used_drainage_hook'] }, text: 'Your hook shifts leaves from the reachable edge of the channel; you keep your hands above the stone rim. Clearing the drain may help, but does not name a cause.' },
        { requirements: { flags: ['inspected_well_lip'] }, text: 'Your folding mirror shows a damp mud line beneath the inner stone lip. It is evidence worth comparing, not a way to identify what made anyone sick.' },
        { requirements: { flags: ['inspected_well_grit'] }, text: 'The loupe makes the grit along the rim visible: soil and a thin film of plant matter. Fine detail can raise concern, not identify a poison.' },
        { requirements: { flags: ['cleared_reachable_well_debris'] }, text: 'With thick gloves, you lift reachable wet leaves from the channel. You do not reach into the well itself. Clearing it may help, but does not prove the cause.' },
        { requirements: { selections: { source: 'wellRunoff' } }, text: 'The cup brings up cloudy water with grit from the rain channel. That supports concern about runoff; it cannot prove the well caused every illness.' },
        { requirements: { selections: { source: 'wellDebris' } }, text: 'A leaf fragment and sour odor cling to the sample cup. The neglected channel needs clearing, though appearance alone cannot prove it caused the sickness.' },
      ],
      choices: [
        { id: 'closeSampledWell', label: 'Keep the well closed while you compare', timeCost: 4, effects: { setFlags: ['wellClosed'] }, next: 'wellSetAside' },
        { id: 'compareSampleMeal', label: 'Compare these findings with meal reports', timeCost: 8, next: 'reportsCollected' },
        { id: 'inspectBarrelAfterSample', label: 'Check the covered barrel too', timeCost: 8, next: 'barrelInspection' },
      ] },
    wellSetAside: { id: 'wellSetAside', title: 'One Source Set Aside', tone: 'warning',
      text: 'The well is marked out of use, and everyone switches to clean water. This is a prudent precaution, but the sick still need watching and the cause is not settled.',
      choices: [
        { id: 'wellWasCause', label: 'Keep the well closed and tell the neighbors', requirements: { selections: { source: 'wellRunoff' } }, effects: { knowledge: ['Rain runoff can foul an unprotected well.'], historyFlags: ['helped_isolate_contaminated_well'] }, next: 'containedWell' },
        { id: 'debrisWasCause', label: 'Have the well channel cleared before reuse', requirements: { selections: { source: 'wellDebris' } }, effects: { knowledge: ['Leaves and stagnant debris can spoil a well channel.'], historyFlags: ['helped_isolate_contaminated_well'] }, next: 'containedWell' },
        { id: 'wrongWellSource', label: 'Continue checking food and stored water', requirements: { selections: { source: 'spoiledStew' } }, next: 'wrongSource' },
        { id: 'wrongWellBarrel', label: 'Continue checking food and stored water', requirements: { selections: { source: 'waterBarrel' } }, next: 'wrongSource' },
      ] },
    stewSetAside: { id: 'stewSetAside', title: 'The Pot Is Emptied', tone: 'safe',
      text: '{{host}} empties the stew pot and keeps it away from the clean food. The guests use fresh water while you compare their reports. Nothing has been proven, but one possible source is no longer being served.',
      choices: [
        { id: 'stewWasCause', label: 'Keep the stew discarded and warn the next guests', requirements: { selections: { source: 'spoiledStew' } }, effects: { knowledge: ['Shared food left warm too long can make several people ill.'], historyFlags: ['helped_isolate_spoiled_food'] }, next: 'containedFood' },
        { id: 'stewWasNotCause', label: 'Inspect the water sources before closing anything else', requirements: { selections: { source: 'wellRunoff' } }, next: 'wrongSource' },
        { id: 'stewWasNotBarrel', label: 'Inspect the water sources before closing anything else', requirements: { selections: { source: 'waterBarrel' } }, next: 'wrongSource' },
        { id: 'stewWasNotDebris', label: 'Inspect the water sources before closing anything else', requirements: { selections: { source: 'wellDebris' } }, next: 'wrongSource' },
      ] },
    barrelSetAside: { id: 'barrelSetAside', title: 'Clean Water for Now', tone: 'safe',
      text: 'The barrel is set aside and clean water is brought out. {{host}} has the tap and lid cleaned before anyone uses it again. You compare who drank from it before calling the matter settled.',
      choices: [
        { id: 'barrelWasCause', label: 'Keep the barrel closed and explain why', requirements: { selections: { source: 'waterBarrel' } }, effects: { knowledge: ['A fouled water barrel can sicken people even when a nearby well is sound.'], historyFlags: ['helped_isolate_contaminated_barrel'] }, next: 'containedBarrel' },
        { id: 'barrelWasNotCauseWell', label: 'Inspect the well before deciding', requirements: { selections: { source: 'wellRunoff' } }, next: 'wrongSource' },
        { id: 'barrelWasNotCauseFood', label: 'Compare the meal reports before deciding', requirements: { selections: { source: 'spoiledStew' } }, next: 'wrongSource' },
        { id: 'barrelWasNotCauseDebris', label: 'Check the well channel before deciding', requirements: { selections: { source: 'wellDebris' } }, next: 'wrongSource' },
      ] },
    wrongSource: { id: 'wrongSource', title: 'The Pattern Does Not Fit', tone: 'warning',
      text: 'The people keep to clean food and water, but the illness pattern does not fit the source you set aside. {{host}} compares who ate and drank what; one source remains shared by the sick and not the healthy.',
      textVariants: [
        { requirements: { selections: { source: 'wellRunoff' } }, text: 'The well was closed, but the first sick guest drank from it before anyone else. The meal and barrel reports do not fit as well. {{host}} keeps the well closed and warns neighboring households.' },
        { requirements: { selections: { source: 'spoiledStew' } }, text: 'The barrel and well were set aside, but the sick all ate the stew. {{host}} keeps the pot empty and warns neighboring guests.' },
        { requirements: { selections: { source: 'waterBarrel' } }, text: 'The well and stew reports do not fit. The sick all drank from the covered barrel; its lid sat crooked and its tap was fouled. {{host}} keeps it closed.' },
        { requirements: { selections: { source: 'wellDebris' } }, text: 'The well’s lower channel is the shared point. With it marked closed, clean water is brought from elsewhere while the channel is cleared.' },
      ],
      choices: [
        { id: 'recoverWell', label: 'Keep the well closed until runoff is cleared', requirements: { selections: { source: 'wellRunoff' } }, effects: { knowledge: ['Rain runoff can foul an unprotected well.'], historyFlags: ['helped_isolate_contaminated_well'] }, next: 'containedWell' },
        { id: 'recoverFood', label: 'Keep the stew discarded and warn the guests', requirements: { selections: { source: 'spoiledStew' } }, effects: { knowledge: ['Shared food left warm too long can make several people ill.'], historyFlags: ['helped_isolate_spoiled_food'] }, next: 'containedFood' },
        { id: 'recoverBarrel', label: 'Keep the barrel closed and clean its tap', requirements: { selections: { source: 'waterBarrel' } }, effects: { knowledge: ['A fouled water barrel can sicken people even when a nearby well is sound.'], historyFlags: ['helped_isolate_contaminated_barrel'] }, next: 'containedBarrel' },
        { id: 'recoverDebris', label: 'Clear the channel and keep the well closed meanwhile', requirements: { selections: { source: 'wellDebris' } }, effects: { knowledge: ['Leaves and stagnant debris can spoil a well channel.'], historyFlags: ['helped_isolate_contaminated_well'] }, next: 'containedWell' },
      ] },
    feltIll: { id: 'feltIll', title: 'Later That Hour', tone: 'warning', text: 'Cramping and a cold sweat make the walk harder. The stew was the source this time; your choice exposed you, though there was no way to diagnose it by taste. {{host}} sets out clean water and a place to rest.', choices: [{ id: 'restAfterExposure', label: 'Rest, then leave when steady', effects: { historyFlags: ['became_ill_after_known_exposure'] }, next: 'sickEnding' }] },
    noImmediateIllness: { id: 'noImmediateIllness', title: 'An Unhelpful Taste', tone: 'safe', text: 'The spoonful gives you no useful answer. The cause lies elsewhere; taste cannot establish what is safe. {{host}} returns to the meal and water reports.', choices: [{ id: 'resumeInvestigation', label: 'Compare the reports', next: 'reportsCollected' }] },
    reportsCollected: { id: 'reportsCollected', title: 'The Shared Source', tone: 'warning',
      text: 'You compare who became ill with what each person ate and drank. The overlap is not perfect, but it points to one shared source. The household can stop using that source and warn the next travelers.',
      textVariants: [
        { requirements: { selections: { source: 'wellRunoff' } }, text: 'The first sick guest drank from the well after rain; the later cases followed, while meals and barrel use differed. The runoff channel reaches the well rim.' },
        { requirements: { selections: { source: 'spoiledStew' } }, text: 'Everyone sick ate the stew, while two healthy people skipped it. Their water came from different sources. The pot stood warm overnight.' },
        { requirements: { selections: { source: 'waterBarrel' } }, text: 'Everyone sick drank from the covered barrel; healthy guests used the well instead. Its lid sat crooked and its tap was fouled.' },
        { requirements: { selections: { source: 'wellDebris' } }, text: 'The sick all drank from the well after leaves and stagnant water collected in its lower channel. Other meals and drinking vessels differed.' },
      ],
      choices: [
        { id: 'reportWellCause', label: 'Keep the well closed and warn the neighbors', requirements: { selections: { source: 'wellRunoff' } }, effects: { setFlags: ['wellClosed'], knowledge: ['Rain runoff can foul an unprotected well.'], historyFlags: ['helped_isolate_contaminated_well'] }, next: 'containedWell' },
        { id: 'reportFoodCause', label: 'Discard the stew and warn the next guests', requirements: { selections: { source: 'spoiledStew' } }, effects: { setFlags: ['stewDiscarded'], knowledge: ['Shared food left warm too long can make several people ill.'], historyFlags: ['helped_isolate_spoiled_food'] }, next: 'containedFood' },
        { id: 'reportBarrelCause', label: 'Close the barrel and clean its tap', requirements: { selections: { source: 'waterBarrel' } }, effects: { setFlags: ['barrelClosed'], knowledge: ['A fouled water barrel can sicken people even when a nearby well is sound.'], historyFlags: ['helped_isolate_contaminated_barrel'] }, next: 'containedBarrel' },
        { id: 'reportDebrisCause', label: 'Clear the well channel; keep it closed for now', requirements: { selections: { source: 'wellDebris' } }, effects: { setFlags: ['wellClosed'], knowledge: ['Leaves and stagnant debris can spoil a well channel.'], historyFlags: ['helped_isolate_contaminated_well'] }, next: 'debrisAftercare' },
      ] },
    containedWell: { id: 'containedWell', title: 'The Well Is Kept Closed', text: 'The suspect source is isolated, clean water is used instead, and neighbors are warned. The guests improve with rest. You cannot know how quickly everyone would have been found without the warning.', ending: 'success', choices: [] },
    debrisAftercare: { id: 'debrisAftercare', title: 'A Clear Channel, Still Closed', text: 'The host clears leaves from the lower channel but keeps the well closed until it is checked. A sound drainage hook in the pump shed was replaced recently; the host offers the older tool if it would help on the road.', choices: [
      { id: 'acceptOldDrainageHook', label: 'Accept the spare drainage hook', requirements: { notItems: ['drainageHook'] }, effects: { gainItems: ['drainageHook'], historyFlags: ['received_old_drainage_hook_after_well_cleanup'] }, next: 'debrisResolved' },
      { id: 'leaveOldDrainageHook', label: 'Leave the tool with the host', next: 'debrisResolved' },
    ] },
    debrisResolved: { id: 'debrisResolved', title: 'Clean Water, No Guesswork', text: 'The well stays closed until someone can confirm it is safe again. The sick guests have clean water and a warning has gone to neighboring households; the cause was contained, not cured by a tool.', ending: 'success', choices: [] },
    containedFood: { id: 'containedFood', title: 'The Meal Is Stopped', text: 'The shared stew is discarded and the remaining food kept separate. No one else eats it. The guests are watched and given clean water; the cause is not a mystery to the house now.', ending: 'success', choices: [] },
    containedBarrel: { id: 'containedBarrel', title: 'The Barrel Is Set Aside', text: 'The fouled barrel is closed, its tap cleaned, and clean water drawn from elsewhere. The well remains usable. The sick are watched while the house avoids the source they shared.', ending: 'success', choices: [] },
    leftEarly: { id: 'leftEarly', title: 'The Road Continues', text: 'You leave before the house learns what caused the illness. The people have clean water set aside, but the cause and what happens next remain with them.', ending: 'success', choices: [] },
    sickEnding: { id: 'sickEnding', title: 'A Slow Recovery', text: 'You spend the night resting. The sickness passes, but the delay costs you a day and leaves the household to finish isolating the source.', ending: 'success', choices: [] },
  },
};
