import type { Scenario } from '../types';

export const SILENT_NIGHT: Scenario = {
  id: 'silent-night', title: 'Silent Night?', subtitle: 'A disturbance through the wall may be nothing—or may not.', startScene: 'wakingInnocently',
  timePhases: [{ id: 'deepNight', label: 'The Small Hours', atMinutes: 0 }, { id: 'nearDawn', label: 'Before Dawn', atMinutes: 12 }],
  runRandomSelections: [
    { id: 'argument', values: ['drunken', 'lodgingDebt', 'propertyDispute', 'threat'].map((value) => ({ value })) },
    { id: 'escalation', values: ['settles', 'damage', 'injury', 'fatality'].map((value) => ({ value })) },
    { id: 'guest', values: ['Cyrilla', 'Dennet', 'Orwin', 'Elsbeth', 'Ygraine'].map((value) => ({ value })) },
    { id: 'innkeeper', values: ['Berit', 'Veyra', 'Corren', 'Jossam'].map((value) => ({ value })) },
  ],
  scenes: {
    wakingInnocently: { id: 'wakingInnocently', title: 'Voices Through the Wall', tone: 'warning',
      text: 'You wake in your inn bed to raised voices somewhere below. A chair scrapes, then someone mutters. You cannot tell who is speaking or what they want. It may be an ordinary late argument that will burn itself out.',
      textVariants: [{ requirements: { selections: { argument: 'threat' } }, text: 'You wake in your inn bed to raised voices below. One voice says, “Let go. I mean it.” Something strikes the wall once. No one calls for help; it may still be a quarrel that will stop on its own.' }],
      choices: [
        { id: 'listenFromBed', label: 'Listen before deciding', timeCost: 2, effects: { historyFlags: ['investigated_midnight_argument'] }, next: 'listeningAtDoor' },
        { id: 'askForQuiet', label: 'Ask them to keep it down', timeCost: 2, next: 'quietRequest' },
        { id: 'goSee', label: 'Go to the common room', timeCost: 3, next: 'commonRoom' },
        { id: 'ignoreArgument', label: 'Roll over and ignore it', timeCost: 2, effects: { historyFlags: ['slept_through_inn_incident', 'stayed_out_of_inn_dispute'] }, next: 'morningAfterSleep' },
      ] },
    listeningAtDoor: { id: 'listeningAtDoor', title: 'A Little More to Hear', tone: 'warning',
      text: 'From your doorway, the voices remain muffled. You catch an argument about a bill, but not whether anyone is in danger. The stairs are at the end of the corridor; the innkeeper sleeps behind the front desk.',
      textVariants: [
        { requirements: { selections: { argument: 'drunken' } }, text: 'The voices belong to two guests arguing over a song and a spilled drink. One laughs between complaints. The stairs are at the end of the corridor; the innkeeper sleeps behind the front desk.' },
        { requirements: { selections: { argument: 'propertyDispute' } }, text: '{{guest}} says a satchel is theirs; another guest says it was left in the common room. No one has mentioned a weapon. The stairs are at the end of the corridor, beside the front desk.' },
        { requirements: { selections: { argument: 'threat' } }, text: 'You hear {{guest}} say, “Please, I gave it back.” A second voice answers, “You’ll be sorry.” Something scrapes across the floor. You still do not know whether anyone is armed, but this sounds more serious than noise.' },
      ],
      choices: [
        { id: 'wakeInnkeeper', label: 'Wake the innkeeper', timeCost: 2, effects: { historyFlags: ['sought_help_in_inn_dispute'] }, next: 'innkeeperArrives' },
        { id: 'goToCommonRoom', label: 'Look from the common-room doorway', timeCost: 2, next: 'commonRoom' },
        { id: 'askAgainQuietly', label: 'Ask them to stop from the hall', timeCost: 2, next: 'quietRequest' },
        { id: 'sleepAfterListening', label: 'Go back to bed', timeCost: 2, effects: { historyFlags: ['stayed_out_of_inn_dispute'] }, next: 'morningAfterHearing' },
      ] },
    quietRequest: { id: 'quietRequest', title: 'A Knock in the Night', tone: 'warning',
      text: 'Your knock carries down the narrow hall. The voices stop for a breath, then one answers from the common room. You are alone on the upper landing; the innkeeper is downstairs.',
      textVariants: [{ requirements: { selections: { argument: 'threat' } }, text: 'Your knock carries down the narrow hall. A chair scrapes hard and a voice snaps, “Mind your own room.” You are alone on the upper landing; the innkeeper is downstairs. If this is more than an argument, a direct challenge could draw anger toward you.' }],
      choices: [
        { id: 'calmRequest', label: 'Speak calmly and ask for quiet', hint: 'They may settle—or take the interruption badly.', timeCost: 2, chance: { probability: 0.66, bonusSelections: { argument: 'drunken' }, bonusProbability: 0.14, penaltySelections: { argument: 'threat' }, penaltyProbability: 0.2, successNext: 'argumentCools', failureNext: 'tempersRise', successMessage: 'The voices soften and the argument begins to ebb.', failureMessage: 'One guest answers with a sharper threat; the noise has not settled.', successEffects: { historyFlags: ['intervened_in_inn_dispute'] }, failureEffects: { historyFlags: ['intervened_in_inn_dispute'] } } },
        { id: 'getInnkeeperAfterKnock', label: 'Wake the innkeeper instead', timeCost: 2, effects: { historyFlags: ['sought_help_in_inn_dispute'] }, next: 'innkeeperArrives' },
        { id: 'retreatAfterKnock', label: 'Return to your room', effects: { historyFlags: ['stayed_out_of_inn_dispute'] }, next: 'morningAfterHearing' },
      ] },
    commonRoom: { id: 'commonRoom', title: 'At the Common-Room Door', tone: 'warning',
      text: 'From the doorway you see {{guest}} facing another guest beside a table. The innkeeper is not there. You can stay in the hall, fetch help, or speak without stepping between them.',
      textVariants: [
        { requirements: { selections: { argument: 'drunken' } }, text: 'Two tired guests argue beside a tipped chair; one still holds a cup. No one appears hurt, and the front door is clear behind you.' },
        { requirements: { selections: { argument: 'propertyDispute' } }, text: 'A guest holds a satchel while {{guest}} reaches for its strap. Neither has drawn anything. You are in the doorway; the front door and stairs are behind you.' },
        { requirements: { selections: { argument: 'threat' } }, text: '{{guest}} is backed against a table. A small knife is visible in the other guest’s hand. You remain in the doorway with the stairs behind you; stepping between them puts you within reach of the blade.' },
      ],
      choices: [
        { id: 'fetchInnkeeperFromRoom', label: 'Fetch the innkeeper', timeCost: 2, effects: { historyFlags: ['sought_help_in_inn_dispute'] }, next: 'innkeeperArrives' },
        { id: 'speakFromDoor', label: 'Ask them to stop from the doorway', timeCost: 2, chance: { probability: 0.58, bonusSelections: { argument: 'drunken' }, bonusProbability: 0.14, penaltySelections: { argument: 'threat' }, penaltyProbability: 0.18, successNext: 'argumentCools', failureNext: 'tempersRise', successMessage: 'Both guests look toward you, and the argument loses its force.', failureMessage: 'The angry guest turns toward you; the argument is now more volatile.', successEffects: { historyFlags: ['intervened_in_inn_dispute'] }, failureEffects: { historyFlags: ['intervened_in_inn_dispute'] } } },
        { id: 'leaveCommonRoom', label: 'Step back and leave them to it', effects: { historyFlags: ['stayed_out_of_inn_dispute'] }, next: 'morningAfterHearing' },
        { id: 'separateThreat', label: 'Step between them', requirements: { selections: { argument: 'threat' } }, hint: 'The knife is already visible; you would be within arm’s reach.', chance: { probability: 0.32, successNext: 'guestsSeparated', failureNext: 'knifeInjury', successMessage: 'You force space between them and shove the table into the way.', failureMessage: 'The knife catches you as you step between the guests.', successEffects: { health: -2, historyFlags: ['intervened_in_inn_dispute', 'prevented_inn_violence'] }, failureEffects: { health: -5, historyFlags: ['was_injured_in_inn_dispute', 'witnessed_inn_violence'] } } },
      ] },
    tempersRise: { id: 'tempersRise', title: 'The Argument Turns', tone: 'danger',
      text: 'A guest steps into the hall and shoves the table aside. The innkeeper is still downstairs. You have time to call for help or back away; touching either guest could make you part of the fight.',
      textVariants: [{ requirements: { selections: { argument: 'threat' } }, text: 'The knife is plainly visible now, and {{guest}} is pressed against the table. You are still by the doorway. Calling the innkeeper or retreating is safer than stepping into reach, though neither guarantees what happens next.' }],
      choices: [
        { id: 'callHostDuringFight', label: 'Call the innkeeper loudly', timeCost: 1, effects: { historyFlags: ['sought_help_in_inn_dispute'] }, next: 'innkeeperArrives' },
        { id: 'backAwayFromFight', label: 'Back away and let them move past', effects: { historyFlags: ['stayed_out_of_inn_dispute'] }, next: 'morningAfterHearing' },
        { id: 'separateEscalated', label: 'Try to separate them now', requirements: { selections: { argument: 'threat' } }, hint: 'The knife is in reach. You could be badly hurt.', chance: { probability: 0.24, successNext: 'guestsSeparated', failureNext: 'knifeInjury', successMessage: 'You wedge a chair between them and pull {{guest}} clear.', failureMessage: 'The knife catches you as you move in.', successEffects: { health: -2, historyFlags: ['intervened_in_inn_dispute', 'prevented_inn_violence'] }, failureEffects: { health: -5, historyFlags: ['was_injured_in_inn_dispute', 'witnessed_inn_violence'] } } },
      ] },
    innkeeperArrives: { id: 'innkeeperArrives', title: 'The Innkeeper Takes the Hall', tone: 'warning',
      text: '{{innkeeper}} comes down in a dressing gown and stands at the foot of the stairs, speaking firmly to both guests. The argument may be ordinary or serious; the innkeeper knows these people better than you do.',
      choices: [
        { id: 'letInnkeeperHandle', label: 'Give the innkeeper room to handle it', effects: { historyFlags: ['sought_help_in_inn_dispute', 'left_innkeeper_to_handle_dispute'] }, next: 'hostSettlesIt' },
        { id: 'stayAsWitness', label: 'Stay in the lit doorway as a witness', effects: { historyFlags: ['sought_help_in_inn_dispute', 'witnessed_innkeeper_separate_guests'] }, next: 'hostSettlesIt' },
      ] },
    argumentCools: { id: 'argumentCools', title: 'The Voices Fade', tone: 'safe', text: 'The guests lower their voices. {{guest}} leaves the common room with the satchel—or without it—and no one asks you to decide whose account was right. You return to bed without knowing whether your words made the difference.', ending: 'success', choices: [] },
    guestsSeparated: { id: 'guestsSeparated', title: 'Space Between Them', tone: 'warning', text: 'The guests move apart. The knife is laid on the floor and stays there while the innkeeper is called. You have prevented an immediate blow, but the dispute itself is not yours to settle.', ending: 'success', choices: [] },
    knifeInjury: { id: 'knifeInjury', title: 'A Costly Step In', tone: 'danger', text: 'The knife wounds you before the innkeeper can reach the room. The guests scatter in opposite directions. Your injury is serious, but you are still able to call for help. A bandage can slow the bleeding; it cannot repair the wound.',
      choices: [
        { id: 'bandageInnWound', label: 'Use your bandage while you wait', requirements: { items: ['fieldBandageRoll'] }, effects: { loseItems: ['fieldBandageRoll'], health: 1 }, next: 'morningAfterInjury' },
        { id: 'callHostForWound', label: 'Call the innkeeper to help', effects: { historyFlags: ['sought_help_in_inn_dispute'] }, next: 'morningAfterInjury' },
        { id: 'reachYourRoom', label: 'Get to your room and bind the wound', next: 'morningAfterInjury' },
      ] },
    morningAfterInjury: { id: 'morningAfterInjury', title: 'A Difficult Morning', tone: 'warning', text: 'The innkeeper brings clean cloth and sends for a doctor. You are alive, though the wound will take time to heal. The guests have been sent to separate rooms, and no one asks you to settle their dispute.', ending: 'success', choices: [] },
    hostSettlesIt: { id: 'hostSettlesIt', title: 'Morning at the Inn', tone: 'safe',
      text: 'The innkeeper sends the guests to separate rooms. At breakfast, the quarrel is already a private matter again. A chair is broken, but no one asks you to take sides.',
      textVariants: [
        { requirements: { historyFlags: ['witnessed_innkeeper_separate_guests'] }, text: 'You stay in the lit doorway until the innkeeper sends the guests to separate rooms. At breakfast, if their accounts differ, you can say what you saw; the quarrel itself remains theirs to settle.' },
        { requirements: { selections: { argument: 'drunken' } }, text: 'By morning the guests are embarrassed about the song and spilled drink. Nothing worse came of it. Whether the innkeeper’s arrival or the cooling night did the work is hard to say.' },
      ],
      ending: 'success', choices: [] },
    morningAfterSleep: { id: 'morningAfterSleep', title: 'Morning Comes', tone: 'safe',
      text: 'You sleep through the rest of the night. At breakfast the common room is much as you left it; the argument appears to have ended without needing you.', ending: 'success', choices: [] },
    morningAfterHearing: { id: 'morningAfterHearing', title: 'What the Night Left Behind', tone: 'safe',
      text: 'You return to your room. In the morning, a chair is broken and a guest is gone. Nobody says whether the argument was settled or merely carried elsewhere.',
      textVariants: [
        { requirements: { selections: { argument: 'drunken' } }, text: 'The guests stopped arguing and slept late. At breakfast one apologizes for the noise. Nothing serious happened.' },
        { requirements: { selections: { argument: 'propertyDispute' } }, text: 'The satchel is gone from the common room. The innkeeper cannot say who took it, and no one asks you to choose whose claim was true.' },
        { requirements: { selections: { argument: 'threat', escalation: 'injury' } }, text: 'At dawn the innkeeper tells you one guest was hurt in the common room. They survived and have gone for a doctor. You did not know exactly what was happening when you left.' },
        { requirements: { selections: { argument: 'threat', escalation: 'fatality' } }, text: 'At dawn you learn that a guest died in the common room. You heard a threat and a blow, but from your room you could not know how the night would end.' },
      ],
      ending: 'success', choices: [] },
  },
};
