import type { Scenario } from '../types';

export const THE_SOUND_IN_THE_WELL: Scenario = {
  id: 'the-sound-in-the-well', title: 'The Sound in the Well', subtitle: 'A worker is alive below the rim, but the stones are shifting.', startScene: 'farmyardWell',
  timePhases: [{ id: 'calling', label: 'A Voice Below', atMinutes: 0 }, { id: 'weak', label: 'The Voice Weakens', atMinutes: 5 }, { id: 'danger', label: 'The Well Shifts', atMinutes: 10 }],
  runRandomSelections: [{ id: 'worker', values: ['Nerys', 'Fenna', 'Ivo', 'Sabine', 'Corwin'].map((value) => ({ value })) }],
  scenes: {
    farmyardWell: { id: 'farmyardWell', title: 'A Voice from the Well', tone: 'danger', text: 'At a farmyard, the owner stands beside you at a stone well. Their farmhand, {{worker}}, fell while clearing its bucket. The hand rope snapped, and no bucket hangs over the opening. You stand on firm ground at the rim. The old stones shed grit when the owner leans too close.', choices: [
      { id: 'callDown', label: 'Call down and listen carefully', hint: 'Learn where {{worker}} is before moving anything.', timeCost: 1, next: 'voiceBelow', effects: { knowledge: ['The worker is conscious on a narrow ledge below the well rim.'] } },
      { id: 'sendForHelp', label: 'Send the owner for the farm rope', hint: 'Safer than climbing down, but the rope is stored several minutes away.', timeCost: 6, next: 'ropeArrives', effects: { setFlags: ['helpForWell'] } },
      { id: 'lowerLantern', label: 'Lower a lantern on the spare line', hint: 'The short line can light the well, not lift anyone.', requirements: { items: ['lantern'] }, timeCost: 1, next: 'litWell', effects: { knowledge: ['The worker is conscious on a narrow ledge below the well rim.'] } },
      { id: 'leaveWell', label: 'Keep clear and continue your journey', hint: 'The owner will call for help; you will not descend.', next: 'leftWellEnding', effects: { historyFlags: ['left_worker_in_well_for_help'] } },
    ] },
    voiceBelow: { id: 'voiceBelow', title: 'A Narrow Ledge', tone: 'danger', text: 'A voice answers from a narrow stone ledge about twelve feet below the rim. {{worker}} is conscious, with one ankle pinned beneath a fallen bucket frame. The owner has gone to the barn for a long rope and pulley. Loose stones fall when anyone leans over the opening.', choices: [
      { id: 'rigRope', label: 'Anchor the farm rope and lower a loop', hint: 'A clamp or block-and-tackle can steady the load. No one needs to enter the well.', timeCost: 2, chance: { probability: 0.72, lateProbability: 0.5, lateAfterMinutes: 5, bonusItems: ['ironRopeClamp', 'compactBlockAndTackle', 'freightmansStrap'], bonusProbability: 0.12, successNext: 'ropeRescue', failureNext: 'ropeSlips', successMessage: 'The rope holds against the far fence post, and {{worker}} gets an arm through the loop.', failureMessage: 'The rope slips on the stone rim. You remain above ground, but {{worker}} is still trapped.' } },
      { id: 'descendWell', label: 'Climb down to free the ankle', hint: 'The stones are shedding grit. If the wall shifts while you are below, you may be killed.', timeCost: 2, chance: { probability: 0.48, lateProbability: 0.3, lateAfterMinutes: 5, bonusItems: ['travelRope', 'heavyLeatherGloves'], bonusProbability: 0.12, successNext: 'belowWell', failureNext: 'wellFall', successMessage: 'You reach the ledge and begin shifting the frame.', failureMessage: 'A section of the lining shifts. You strike the ledge hard on the way down.', failureEffects: { health: -4, historyFlags: ['descended_into_unsafe_well'] } } },
      { id: 'waitForOwner', label: 'Wait for the owner and proper rope', timeCost: 4, next: 'ropeArrives', effects: { setFlags: ['helpForWell'] } },
    ] },
    litWell: { id: 'litWell', title: 'Light on the Ledge', tone: 'warning', text: 'The lantern shows {{worker}} on a ledge below, ankle caught under a light wooden frame. The stone lining is cracked above the ledge. The spare line is too short to lift anyone; the owner is fetching the farm rope.', choices: [
      { id: 'waitLitWell', label: 'Wait for the owner’s rope', timeCost: 4, next: 'ropeArrives', effects: { setFlags: ['helpForWell'] } },
      { id: 'climbLitWell', label: 'Climb down while the ledge holds', hint: 'The wall is cracked; a fall could kill you.', timeCost: 2, chance: { probability: 0.45, lateProbability: 0.26, lateAfterMinutes: 5, bonusItems: ['travelRope', 'heavyLeatherGloves'], bonusProbability: 0.12, successNext: 'belowWell', failureNext: 'wellFall', successMessage: 'You reach the ledge without dislodging the stones.', failureMessage: 'The wall sheds a slab as you climb. You fall against the ledge.', failureEffects: { health: -4, historyFlags: ['descended_into_unsafe_well'] } } },
      { id: 'leaveLitWell', label: 'Stay above and leave for help', next: 'leftWellEnding', effects: { historyFlags: ['left_worker_in_well_for_help'] } },
    ] },
    ropeArrives: { id: 'ropeArrives', title: 'A Sound Rope', tone: 'warning', text: 'The owner returns with a long farm rope and a wooden pulley. {{worker}} answers, but more grit is falling from the wall. The pulley can lower a loop from the rim; no one needs to climb down.', choices: [
      { id: 'lowerFarmLoop', label: 'Lower the loop and haul together', hint: 'Stay away from the rim’s loose stones. A smooth lift can free the trapped ankle.', timeCost: 2, chance: { probability: 0.78, lateProbability: 0.53, lateAfterMinutes: 8, bonusItems: ['ironRopeClamp', 'compactBlockAndTackle', 'travelRope'], bonusProbability: 0.1, successNext: 'rescuedWorker', failureNext: 'ropeSlips', successMessage: 'The loop holds, the owner lifts, and {{worker}} comes up carefully.', failureMessage: 'The line bites against the rim and slides. {{worker}} remains on the ledge.' } },
      { id: 'askOwnerToGetHelp', label: 'Send for two more hands', timeCost: 5, next: 'lateRope', effects: { setFlags: ['extraHands'] } },
      { id: 'leaveRopeRescue', label: 'Keep clear and leave for help', next: 'leftWellEnding', effects: { historyFlags: ['left_worker_in_well_for_help'] } },
    ] },
    ropeSlips: { id: 'ropeSlips', title: 'The Line Slips', tone: 'danger', text: 'The rope is back at the rim, and {{worker}} is still on the ledge. The loose stones are now falling more often. The owner can fetch extra hands, or you can attempt another lift from above.', choices: [
      { id: 'retryWellRope', label: 'Reset the pulley for one more lift', timeCost: 2, chance: { probability: 0.61, lateProbability: 0.35, lateAfterMinutes: 8, bonusItems: ['ironRopeClamp', 'compactBlockAndTackle', 'travelRope'], bonusProbability: 0.12, successNext: 'rescuedWorker', failureNext: 'workerLost', successMessage: 'The line holds on the second lift. {{worker}} clears the ledge.', failureMessage: 'The ledge crumbles before the rope can take the weight.' } },
      { id: 'getWellHelp', label: 'Go for more hands', timeCost: 5, next: 'lateRope', effects: { setFlags: ['extraHands'] } },
      { id: 'leaveSlippedRope', label: 'Back away and leave for help', next: 'workerLost', effects: { historyFlags: ['left_worker_in_well_for_help'] } },
    ] },
    lateRope: { id: 'lateRope', title: 'More Hands at the Rim', tone: 'danger', text: 'Two farmhands arrive and take the far end of the rope. {{worker}} is faint but answering. The extra hands can steady the pulley; the old stones are still shifting.', choices: [
      { id: 'liftWithHands', label: 'Haul together from stable ground', timeCost: 1, chance: { probability: 0.7, lateProbability: 0.48, lateAfterMinutes: 10, bonusItems: ['ironRopeClamp', 'compactBlockAndTackle'], bonusProbability: 0.1, successNext: 'rescuedWorker', failureNext: 'workerLost', successMessage: 'The workers lift evenly and bring {{worker}} over the rim.', failureMessage: 'The ledge breaks away before the lift is complete.' } },
      { id: 'letOwnerContinue', label: 'Let the owner decide whether to continue', next: 'workerLost' },
    ] },
    ropeRescue: { id: 'ropeRescue', title: 'The Loop Holds', tone: 'warning', text: 'The loop is under {{worker}}’s arms, and the owner controls the rope from the far fence post. The frame still pins one ankle. A steady pull can bring {{worker}} up, though the stones keep shedding grit.', choices: [
      { id: 'haulWorkerUp', label: 'Haul {{worker}} up slowly', timeCost: 2, chance: { probability: 0.78, lateProbability: 0.54, lateAfterMinutes: 8, bonusItems: ['ironRopeClamp', 'compactBlockAndTackle'], bonusProbability: 0.1, successNext: 'rescuedWorker', failureNext: 'ropeSlips', successMessage: 'The owner and you lift together until {{worker}} clears the rim.', failureMessage: 'The line slips before the frame can be moved. {{worker}} remains on the ledge.' } },
      { id: 'bringExtraHands', label: 'Call the owner back with extra hands', timeCost: 4, next: 'lateRope' },
      { id: 'leaveRopeHeld', label: 'Keep the line steady while help is fetched', next: 'workerLost' },
    ] },
    belowWell: { id: 'belowWell', title: 'On the Ledge', tone: 'danger', text: 'You reach {{worker}} on the narrow ledge. The bucket frame pins an ankle; the rope from above is the only safe way back. Stones keep tapping down around you. You can shift the light frame, but staying here is dangerous.', choices: [
      { id: 'freeWorkerBelow', label: 'Lift the frame while they take the rope', hint: 'The frame is light, but the wall may shed another stone.', timeCost: 2, chance: { probability: 0.64, lateProbability: 0.42, lateAfterMinutes: 8, bonusItems: ['heavyLeatherGloves', 'bridgewrightHammer'], bonusProbability: 0.1, successNext: 'rescuedWorker', failureNext: 'wellFall', successMessage: 'You shift the frame and guide {{worker}} into the loop.', failureMessage: 'The ledge shifts under your feet and the lining cracks above.', failureEffects: { health: -4 } } },
      { id: 'climbOutAlone', label: 'Climb back before the wall moves', next: 'abandonedWellLedge', effects: { historyFlags: ['retreated_from_unsafe_well'] } },
    ] },
    wellFall: { id: 'wellFall', title: 'The Lining Shifts', tone: 'danger', text: 'A slab breaks loose above you. The rope still hangs from the rim, and {{worker}} is beside the ledge. The next stone could close the only foothold. Reaching for them again may kill you.', choices: [
      { id: 'grabWorkerInFall', label: 'Get {{worker}} into the loop now', hint: 'You are beneath unstable stone. Failure may be fatal.', timeCost: 1, chance: { probability: 0.34, lateProbability: 0.18, lateAfterMinutes: 8, successNext: 'playerDiesWorkerLives', failureNext: 'bothLost', successMessage: 'You get {{worker}} into the loop and push them toward the rope. The next slab strikes you.', failureMessage: 'The wall collapses across the ledge.', successEffects: { setFlags: ['workerOnRope'] } } },
      { id: 'climbFromFall', label: 'Use the rope to climb out alone', hint: 'You may escape, but {{worker}} will remain below.', timeCost: 1, chance: { probability: 0.58, successNext: 'workerLost', failureNext: 'playerDiesWorkerLives', successMessage: 'You reach the rim before the next stones fall.', failureMessage: 'The rope tears free as the wall collapses.' } },
    ] },
    rescuedWorker: { id: 'rescuedWorker', title: 'Back in the Farmyard', tone: 'safe', ending: 'success', choices: [], text: '{{worker}} is on firm ground, shaken and bruised but alive. The owner takes them inside and wraps the ankle. You helped without turning a broken well into a second rescue.' },
    workerLost: { id: 'workerLost', title: 'The Well Is Left to the Farm', tone: 'warning', ending: 'success', choices: [], text: 'You leave the well rim intact and get clear. {{worker}} is not brought up before you go; the owner will send for the village well crew. The outcome is uncertain, but you do not make the shaft more dangerous.' },
    leftWellEnding: { id: 'leftWellEnding', title: 'Help Is on the Way', tone: 'warning', ending: 'success', choices: [], text: 'You keep clear of the rim and continue down the road. The owner is already calling for the village well crew; {{worker}} is still below, answering from the ledge.' },
    abandonedWellLedge: { id: 'abandonedWellLedge', title: 'The Climb Back', tone: 'warning', ending: 'success', choices: [], text: 'You climb out before the wall shifts again. The owner and farmhands remain at the rim with {{worker}} on the ledge, preparing a safer lift. You are bruised, but the shaft has not taken another life.' },
    playerDiesWorkerLives: { id: 'playerDiesWorkerLives', title: 'The Rope Comes Up Once', tone: 'danger', ending: 'death', choices: [], text: '{{worker}} is hauled into the farmyard alive. You do not climb out of the shifting well.' },
    bothLost: { id: 'bothLost', title: 'The Well Collapses', tone: 'danger', ending: 'death', choices: [], text: 'The ledge and old stone lining collapse together. Neither you nor {{worker}} reaches the rim before the farmhands pull the rope clear.' },
  },
};
