import type { Scenario } from '../types';

export const THE_BLUE_HOLE: Scenario = {
  id: 'the-blue-hole', title: 'The Blue Hole', subtitle: 'A warm afternoon, cool water, and no promise of an event.', startScene: 'sunnyBank',
  timePhases: [{ id: 'early', label: 'Early Afternoon', atMinutes: 0 }, { id: 'later', label: 'Late Afternoon', atMinutes: 35 }, { id: 'evening', label: 'Evening Light', atMinutes: 80 }],
  runRandomSelections: [
    { id: 'visitOutcome', values: [{ value: 'quiet', weight: 38 }, { value: 'interestingFind', weight: 22 }, { value: 'minorIncident', weight: 20 }, { value: 'drowningEmergency', weight: 20 }] },
    { id: 'victimState', values: ['tired and responsive', 'panicking', 'cramping', 'briefly submerged'].map((value) => ({ value })) },
    { id: 'swimmer', values: ['Lettice', 'Osric', 'Nadine', 'Torvald', 'Melisande'].map((value) => ({ value })) },
    { id: 'helper', values: ['Garran', 'Eudora', 'Thomlin', 'Ysabel', 'Peregrine'].map((value) => ({ value })) },
  ],
  scenes: {
    sunnyBank: { id: 'sunnyBank', title: 'A Warm Place to Stop', tone: 'safe',
      text: 'A clear pool sits beneath low banks on a warm afternoon. {{swimmer}} and two others are already there; one adult watches a child near the shallows. A bathing raft is tied to the short landing, with a coil of line on a peg. You can see the deeper blue water from shore. Your clothes, pack, and carried gear stay here if you swim.',
      choices: [
        { id: 'wadeIn', label: 'Wade in near the bank', timeCost: 2, effects: { historyFlags: ['spent_afternoon_at_blue_hole'] }, next: 'shallows' },
        { id: 'talkFirst', label: 'Talk with the swimmers first', timeCost: 3, effects: { historyFlags: ['met_local_swimmers'] }, next: 'shoreTalk' },
        { id: 'restOnBank', label: 'Rest in the shade', timeCost: 20, effects: { historyFlags: ['spent_afternoon_at_blue_hole', 'chose_not_to_enter_water'] }, next: 'quietRest' },
        { id: 'leaveBlueHole', label: 'Keep to the road', effects: { historyFlags: ['chose_not_to_enter_water'] }, next: 'leftBank' },
      ] },
    shoreTalk: { id: 'shoreTalk', title: 'A Little Local Knowledge', tone: 'safe',
      text: '{{swimmer}} points out the deep shelf, where the color changes. The child is watched closely; {{helper}} says they can swim well but is staying near the landing. Nobody is worried. The rope coil belongs to the bathing raft, not to anyone’s pack.',
      choices: [
        { id: 'enterAfterTalk', label: 'Wade in by the shallow bank', timeCost: 2, effects: { historyFlags: ['spent_afternoon_at_blue_hole'] }, next: 'shallows' },
        { id: 'stayShoreAfterTalk', label: 'Stay on shore and enjoy the company', timeCost: 15, effects: { historyFlags: ['spent_afternoon_at_blue_hole', 'met_local_swimmers', 'chose_not_to_enter_water'] }, next: 'quietRest' },
        { id: 'leaveAfterTalk', label: 'Thank them and move on', effects: { historyFlags: ['met_local_swimmers', 'chose_not_to_enter_water'] }, next: 'leftBank' },
      ] },
    shallows: { id: 'shallows', title: 'Cool Water', tone: 'safe',
      text: 'You wade in where the bottom is firm. The pool deepens toward the blue shelf; your clothes and bag remain on the bank, out of reach. The others are spread between the landing and the shallows.',
      choices: [
        { id: 'swimOut', label: 'Swim out toward the blue shelf', timeCost: 8, next: 'firstSwim' },
        { id: 'floatNearShore', label: 'Float where you can still stand', timeCost: 8, next: 'quietRest' },
        { id: 'returnFromShallows', label: 'Return to shore', timeCost: 3, effects: { historyFlags: ['chose_not_to_enter_water'] }, next: 'quietRest' },
      ] },
    firstSwim: { id: 'firstSwim', title: 'Out Beyond the Shallows', tone: 'safe',
      text: 'You are in the water, beyond easy standing depth, with the bank behind you and the landing visible to one side. Your gear is still with your clothes on shore; nothing carried can be reached from here.',
      textVariants: [
        { requirements: { selections: { visitOutcome: 'quiet' } }, text: 'You swim into the deep blue and find a comfortable rhythm. The bank is behind you; the landing is off to one side. Your clothes and gear remain on shore. For now, it is simply a swim.' },
        { requirements: { selections: { visitOutcome: 'interestingFind' } }, text: 'You swim into the deep blue and catch a glint beneath a flat stone. The bank is behind you and your gear remains with your clothes on shore. The water is calm around you.' },
        { requirements: { selections: { visitOutcome: 'minorIncident' } }, text: 'You swim into the deep blue. A tightness begins in your calf, but you are not far from the shallows. Your clothes and gear remain on shore, out of reach.' },
        { requirements: { selections: { visitOutcome: 'drowningEmergency' } }, text: 'You swim into the deep blue. {{swimmer}} is farther out than before, but still floating and calling to someone on shore. The landing is behind you; your gear remains with your clothes.' },
      ],
      choices: [
        { id: 'swimFarther', label: 'Swim farther from the bank', hint: 'You will be farther from standing depth and your belongings.', timeCost: 5, next: 'deepWater' },
        { id: 'turnBackEarly', label: 'Turn back while the bank is close', timeCost: 5, effects: { historyFlags: ['chose_not_to_enter_water'] }, next: 'quietRest' },
        { id: 'floatInPlace', label: 'Float and rest for a while', timeCost: 8, next: 'quietRest' },
      ] },
    deepWater: { id: 'deepWater', title: 'The Blue Shelf', tone: 'safe',
      text: 'The water is deeper here, though the bank remains in sight. The others are still near the landing and the shallows. You can turn back whenever you choose.',
      textVariants: [
        { requirements: { selections: { visitOutcome: 'quiet' } }, text: 'The pool is cool and clear beneath the blue shelf. Nothing is wrong; the bank remains in sight and the afternoon is unhurried.' },
        { requirements: { selections: { visitOutcome: 'interestingFind' } }, text: 'A small copper token lies just beneath a flat stone where the shelf begins. It is not valuable, but its worn fish mark may belong to the old ferry crossing.' },
        { requirements: { selections: { visitOutcome: 'minorIncident' } }, text: 'Your calf tightens into a painful cramp. You are above deep water but within a few strokes of the shallows; the bank is still in view.' },
        { requirements: { selections: { visitOutcome: 'drowningEmergency' } }, text: '{{swimmer}} has stopped calling. They are {{victimState}} in the water, about fifteen feet away. You are already swimming, tired only from the short crossing. The bank is behind you; your pack, rope, and other gear are on shore.' },
      ],
      choices: [
        { id: 'quietSwimEnd', label: 'Enjoy the water, then return', requirements: { selections: { visitOutcome: 'quiet' } }, timeCost: 10, effects: { historyFlags: ['spent_afternoon_at_blue_hole'] }, next: 'quietRest' },
        { id: 'retrieveToken', label: 'Retrieve the small copper token', hint: 'A brief dive in clear water, with no great value promised.', requirements: { selections: { visitOutcome: 'interestingFind' } }, timeCost: 3, effects: { money: 1, lore: ['A worn fish token came from the old ferry crossing.'], historyFlags: ['found_object_at_blue_hole', 'spent_afternoon_at_blue_hole'] }, next: 'foundToken' },
        { id: 'returnFromFind', label: 'Leave the token and head back', requirements: { selections: { visitOutcome: 'interestingFind' } }, timeCost: 8, effects: { historyFlags: ['spent_afternoon_at_blue_hole'] }, next: 'quietRest' },
        { id: 'crampToShore', label: 'Turn toward the shallows and float', requirements: { selections: { visitOutcome: 'minorIncident' } }, timeCost: 4, chance: { probability: 0.9, successNext: 'minorRecovered', failureNext: 'minorRecovered', successMessage: 'You keep your breathing steady and the cramp eases.', failureMessage: 'The cramp hurts, but you stay afloat and reach shallow water.', failureEffects: { health: -1 } }, effects: { historyFlags: ['spent_afternoon_at_blue_hole'] } },
        { id: 'drowningDirect', label: 'Swim directly to {{swimmer}}', hint: 'A panicked swimmer may grab you and pull you under.', requirements: { selections: { visitOutcome: 'drowningEmergency' } }, timeCost: 1, chance: { probability: 0.43, bonusSelections: { victimState: 'tired and responsive' }, bonusProbability: 0.18, penaltySelections: { victimState: 'panicking' }, penaltyProbability: 0.2, successNext: 'bothReachBank', failureNext: 'waterStruggle', successMessage: 'You reach {{swimmer}} and keep enough distance to guide them toward the shallows.', failureMessage: '{{swimmer}} grabs at you. You break free, but both of you are in trouble.' , successEffects: { health: -1, historyFlags: ['attempted_water_rescue', 'rescued_drowning_swimmer', 'survived_near_drowning'] }, failureEffects: { health: -4, historyFlags: ['attempted_water_rescue', 'survived_near_drowning'] } } },
        { id: 'drowningCoach', label: 'Stay back and call instructions', hint: 'This may help only while they can hear and respond.', requirements: { selections: { visitOutcome: 'drowningEmergency' } }, timeCost: 2, chance: { probability: 0.48, bonusSelections: { victimState: 'tired and responsive' }, bonusProbability: 0.22, penaltySelections: { victimState: 'briefly submerged' }, penaltyProbability: 0.35, successNext: 'bothReachBank', failureNext: 'victimLost', successMessage: '{{swimmer}} turns toward your voice and reaches the shallows.', failureMessage: '{{swimmer}} slips beneath the surface before your words reach them.', successEffects: { historyFlags: ['attempted_water_rescue', 'rescued_drowning_swimmer', 'survived_near_drowning'] }, failureEffects: { historyFlags: ['attempted_water_rescue'] } } },
        { id: 'callFromWater', label: 'Call to the landing for the rope', hint: 'The coil is on shore; someone else must bring it.', requirements: { selections: { visitOutcome: 'drowningEmergency' } }, timeCost: 2, effects: { historyFlags: ['attempted_water_rescue', 'called_others_for_help'] }, next: 'helpersAtLanding' },
      ] },
    helpersAtLanding: { id: 'helpersAtLanding', title: 'A Line from Shore', tone: 'warning',
      text: 'Your call reaches {{helper}} at the landing. They take the coil from its peg while {{swimmer}} struggles in the deep water. The line is meant to hold a small raft, not a person; it may give you something to guide by, but cannot promise a rescue.',
      choices: [
        { id: 'takeThrownLine', label: 'Catch the line and guide it to them', timeCost: 2, chance: { probability: 0.63, bonusSelections: { victimState: 'tired and responsive' }, bonusProbability: 0.15, penaltySelections: { victimState: 'briefly submerged' }, penaltyProbability: 0.24, successNext: 'bothReachBank', failureNext: 'victimLost', successMessage: 'The line reaches {{swimmer}} and {{helper}} draws it steadily toward the shallows.', failureMessage: 'The line cannot reach in time. {{swimmer}} slips beneath the surface.' , successEffects: { historyFlags: ['rescued_drowning_swimmer', 'called_others_for_help'] }, failureEffects: { historyFlags: ['called_others_for_help'] } } },
        { id: 'keepCalling', label: 'Keep calling while {{helper}} brings help', timeCost: 3, chance: { probability: 0.5, successNext: 'bothReachBank', failureNext: 'victimLost', successMessage: '{{helper}} and another swimmer reach the edge together.', failureMessage: 'The wait is too long. The other swimmers reach {{swimmer}} only after they have gone under.' , successEffects: { historyFlags: ['rescued_drowning_swimmer', 'called_others_for_help'] }, failureEffects: { historyFlags: ['called_others_for_help'] } } },
        { id: 'swimFromLine', label: 'Use the line as you swim closer', hint: 'It may steady you, but the victim can still panic.', timeCost: 2, chance: { probability: 0.34, bonusSelections: { victimState: 'tired and responsive' }, bonusProbability: 0.2, penaltySelections: { victimState: 'panicking' }, penaltyProbability: 0.2, successNext: 'bothReachBank', failureNext: 'waterStruggle', successMessage: 'The line steadies you and {{helper}} draws both swimmers in.', failureMessage: 'The struggling swimmer catches you before the line can help.' , successEffects: { health: -1, historyFlags: ['attempted_water_rescue', 'rescued_drowning_swimmer', 'called_others_for_help'] }, failureEffects: { health: -4, historyFlags: ['attempted_water_rescue', 'called_others_for_help', 'survived_near_drowning'] } } },
      ] },
    waterStruggle: { id: 'waterStruggle', title: 'Too Close to the Drop', tone: 'danger',
      text: 'You break free, but the struggle has taken your breath. {{swimmer}} is still in trouble. The blue shelf drops below you; the shore and the line at the landing are behind you. A final push may leave you unable to keep afloat.',
      choices: [
        { id: 'kickForShallows', label: 'Turn onto your back and kick for shore', hint: 'You are exhausted; failing may leave you unable to stay afloat.', timeCost: 2, chance: { probability: 0.58, successNext: 'victimLost', failureNext: 'playerLost', successMessage: 'You reach the shallows. Others pull {{swimmer}} from the water too late.', failureMessage: 'Your strength gives out before the bank is near.', successEffects: { health: -1, historyFlags: ['survived_near_drowning'] }, failureEffects: { health: -10 } } },
        { id: 'floatForHelp', label: 'Float and call for the shore line', timeCost: 2, chance: { probability: 0.48, successNext: 'victimLost', failureNext: 'playerLost', successMessage: '{{helper}} reaches you with the line; the others cannot reach {{swimmer}} in time.', failureMessage: 'The line falls short and your strength fades.', successEffects: { historyFlags: ['survived_near_drowning', 'called_others_for_help'] }, failureEffects: { health: -10, historyFlags: ['called_others_for_help'] } } },
      ] },
    bothReachBank: { id: 'bothReachBank', title: 'Back in the Shallows', tone: 'warning',
      text: '{{swimmer}} reaches the bank alive, coughing and exhausted. {{helper}} and the others lift them onto the grass. Your palms sting from the rough bank stones, but you are steady. Your clothes and pack are within reach again. The rescue could have ended differently.',
      choices: [
        { id: 'warmAfterRescue', label: 'Use your wool blanket to warm them', requirements: { anyItems: ['woolTravelBlanket', 'weatherproofBlanket'] }, effects: { historyFlags: ['rescued_drowning_swimmer', 'warmed_swimmer_with_blanket'] }, next: 'rescueAftercare' },
        { id: 'bandageAfterRescue', label: 'Dress your scraped palms with a bandage', requirements: { items: ['fieldBandageRoll'] }, effects: { health: 1, loseItems: ['fieldBandageRoll'], historyFlags: ['rescued_drowning_swimmer'] }, next: 'rescueAftercare' },
        { id: 'letOthersCare', label: 'Let the others take over', effects: { historyFlags: ['rescued_drowning_swimmer', 'left_swimmer_aftercare_to_others'] }, next: 'rescueAftercare' },
      ] },
    rescueAftercare: { id: 'rescueAftercare', title: 'A Long Afternoon', tone: 'safe', text: '{{helper}} stays with {{swimmer}} while someone fetches a doctor from the nearby road. Your gear is back with you on shore; nothing you carried could have reached the water in time.', textVariants: [
      { requirements: { historyFlags: ['warmed_swimmer_with_blanket'] }, text: 'You wrap {{swimmer}} in your wool blanket while {{helper}} stays close and someone fetches a doctor from the nearby road. The blanket helps with the cold, but the swimmer still needs trained care.' },
      { requirements: { historyFlags: ['left_swimmer_aftercare_to_others'] }, text: '{{helper}} and the others take over keeping {{swimmer}} warm while someone fetches a doctor from the nearby road. You step back; the swimmer is alive but still needs trained care.' },
    ], ending: 'success', choices: [] },
    minorRecovered: { id: 'minorRecovered', title: 'A Cramp, No More', tone: 'safe', text: 'The pain eases in the shallows. Someone offers you a hand at the bank, and the afternoon settles again. The scare was real, but no one was in danger of drowning.', ending: 'success', choices: [] },
    foundToken: { id: 'foundToken', title: 'A Small Find', tone: 'safe', text: 'You put the copper token away and swim back to shore. It is worth little; its fish mark is the more interesting part. The others are still talking by the landing.', ending: 'success', choices: [] },
    victimLost: { id: 'victimLost', title: 'Too Late', tone: 'danger', text: '{{swimmer}} dies in the water before the others can reach them. You are brought to shore alive. No one can say that a different choice would certainly have changed the outcome.', ending: 'success', choices: [] },
    playerLost: { id: 'playerLost', title: 'The Water Takes Its Due', tone: 'danger', text: 'You cannot keep your head above water. The others bring {{swimmer}} to shore, but they cannot reach you in time.', ending: 'death', choices: [] },
    quietRest: { id: 'quietRest', title: 'A Good Place to Stop', tone: 'safe', text: 'The afternoon passes without a great event. The water, shade, and company were enough. You gather your belongings and continue when you are ready.', ending: 'success', choices: [] },
    leftBank: { id: 'leftBank', title: 'Back on the Road', tone: 'safe', text: 'You keep your clothes and pack dry and leave the pool behind. Nothing unusual happens while you are there.', ending: 'success', choices: [] },
  },
};
