import type { Scenario, ScenarioDiversity, Scene } from '../types';
import { ITEMS } from '../items';
import { largeAdventure, largeEnd, largeScene, largeTags } from './largeContentTools';

const scene = largeScene;
const end = largeEnd;
const tags = (hook: string, setting: string, risk: ScenarioDiversity['riskTier'], activity = 'labor/repair') => largeTags({
  hook, setting, risk, activity, role: 'helper/rescuer', tone: risk === 'HIGH' ? 'tense/dangerous' : 'adventurous', fantasy: 'NONE', combat: 'NONE',
  structures: ['trade diagnosis', 'field complication', 'work-quality consequence'], entry: ['hired/posted work'],
  rewards: ['Gear', 'coins', 'reusable Knowledge'], outcomes: ['success/partial success', 'walk-away/refusal', 'negotiated compromise'],
});
const make = (id: string, title: string, subtitle: string, hook: string, setting: string, risk: ScenarioDiversity['riskTier'], start: string, authoredScenes: Record<string, Scene>, activity?: string): Scenario => {
  const scenes = structuredClone(authoredScenes);
  const settlement = scenes.settlement;
  if (settlement?.choices.some(({ id: choiceId }) => ['takeTool', 'takeCoins', 'learnMethod', 'decline', 'repairOwnRope', 'spliceOwnRope'].includes(choiceId))) {
    const gear = settlement.choices.find(({ id: choiceId }) => choiceId === 'takeTool')?.effects?.gainItems?.[0];
    const knowledge = settlement.choices.find(({ id: choiceId }) => choiceId === 'learnMethod')?.effects?.knowledge?.[0];
    const coinAmount = settlement.choices.find(({ id: choiceId }) => choiceId === 'takeCoins')?.effects?.money ?? 2;
    for (const option of settlement.choices) if (['takeTool', 'takeCoins', 'learnMethod', 'decline', 'repairOwnRope', 'spliceOwnRope'].includes(option.id)) {
      option.next = 'workResolved';
      const flag = ({ takeTool: 'trade_batch4_tool_chosen', takeCoins: 'trade_batch4_coins_chosen', learnMethod: 'trade_batch4_knowledge_chosen', decline: 'trade_batch4_declined' } as Record<string, string>)[option.id];
      if (flag) option.effects = { ...option.effects, setFlags: [...(option.effects?.setFlags ?? []), flag] };
    }
    delete scenes.paidTool;
    for (const option of settlement.choices) {
      const oldTarget = authoredScenes.settlement.choices.find(({ id }) => id === option.id)?.next;
      if (oldTarget && oldTarget !== 'workResolved' && scenes[oldTarget]?.ending) delete scenes[oldTarget];
    }
    scenes.workResolved = {
      ...end('workResolved', 'The Work Is Accounted For', 'The craftsperson records the completed work and the arrangement you chose.'),
      textVariants: [
        ...(gear ? [{ requirements: { flags: ['trade_batch4_tool_chosen'] }, text: `The work is complete. ${ITEMS[gear]?.name ?? gear} is explicitly transferred to you as your share and entered into the carried-kit reward placement.` }] : []),
        { requirements: { flags: ['trade_batch4_coins_chosen'] }, text: `The work is complete. You accept the ${coinAmount}-coin wage, which is added to your money.` },
        { requirements: { flags: ['trade_batch4_rope_repaired'] }, text: 'Bram cuts the frayed end back to sound braid, whips it securely, and records the repair on your Travel Rope. It is whole again, though slightly shorter.' },
        { requirements: { flags: ['trade_batch4_rope_upgraded'] }, text: 'Bram adds a leather whipping around your Travel Rope’s hook eye. The reinforced eye is recorded on the rope; its safe load remains unchanged.' },
        ...(knowledge ? [{ requirements: { flags: ['trade_batch4_knowledge_chosen'] }, text: `The work is complete. You take no material share; you record the method: ${knowledge}` }] : []),
        { requirements: { flags: ['trade_batch4_declined'] }, text: 'The work is complete. You decline the extra share and leave without additional pay.' },
      ],
    };
  }
  if (id === 'the-ropewalk-splice' && settlement) {
    settlement.choices.push(
      { id: 'repairOwnRope', label: 'Have Bram mend your damaged Travel Rope instead of taking a share', requirements: { items: ['travelRope'], itemConditions: { travelRope: ['DAMAGED', 'BROKEN'] } }, effects: { repairItems: ['travelRope'], repairItemProvenance: { travelRope: 'Mended by Bram Saye at the ropewalk' }, setFlags: ['trade_batch4_rope_repaired'] }, next: 'workResolved' },
      { id: 'spliceOwnRope', label: 'Ask Bram to reinforce the hook eye on your sound Travel Rope', requirements: { items: ['travelRope'], itemConditions: { travelRope: ['NORMAL'] }, notItemUpgrades: { travelRope: ['splicedEyes'] } }, effects: { addItemUpgrades: [{ itemId: 'travelRope', upgradeId: 'splicedEyes', provenance: 'Leather-whipped by Bram Saye at the ropewalk' }], setFlags: ['trade_batch4_rope_upgraded'] }, next: 'workResolved' },
    );
  }
  return largeAdventure(id, title, subtitle, tags(hook, setting, risk, activity), start, scenes);
};
const itemOffer = (id: string, name: string, _next: string, provenance: string, knowledge: string) => [
  { id: 'takeTool', label: `Take the ${name} as your share instead of coins`, requirements: { notOwnedItems: [id] }, effects: { gainItems: [id], inventorySources: { [id]: 'found' as const }, setFlags: ['trade_batch4_tool_chosen'], historyFlags: [`received_${id}_for_trade_work`] }, next: 'workResolved', hint: `${provenance} The item is offered instead of the two coins.` },
  { id: 'takeCoins', label: 'Take the two-coin wage', effects: { money: 2, setFlags: ['trade_batch4_coins_chosen'], historyFlags: ['earned_trade_wages'] }, next: 'workResolved' },
  { id: 'learnMethod', label: 'Ask the craftsperson to show you the method', effects: { knowledge: [knowledge], setFlags: ['trade_batch4_knowledge_chosen'], historyFlags: ['learned_trade_method'] }, next: 'workResolved' },
  { id: 'decline', label: 'Decline the extra share and finish the work', effects: { setFlags: ['trade_batch4_declined'] }, next: 'workResolved' },
];

// The graph shapes and trade problems are authored separately; the shared reward
// options only keep the canonical ownership transfer and payment semantics legible.
export const TRADES_APPRENTICESHIP_GENRE_BATCH: Scenario[] = [
  make('the-second-brace', 'The Second Brace', 'A joiner asks you to help shore a public stair before the market crowd arrives.', 'A measuring choice reveals the wall itself is out of square.', 'town hall stair', 'MODERATE', 'frame', {
    frame: scene('frame', 'A Stair out of True', 'Master joiner Elian Voss lays a new brace against an old stair frame. The lower post is sound, but the landing leans a finger-width toward the crowd. He asks you to check the fit before he cuts.', [{ id: 'measure', label: 'Measure both diagonals with the folding rule', requirements: { items: ['joinersFoldingRule'] }, next: 'hiddenRot', effects: { setFlags: ['checked_diagonals'] } }, { id: 'square', label: 'Check the corner with the shop’s carpenter square', next: 'hiddenRot' }, { id: 'rush', label: 'Cut the brace to match the visible edge', next: 'badFit' }]),
    hiddenRot: scene('hiddenRot', 'The Post behind the Plaster', 'A hairline opens when the brace is dry-fitted. The post has shifted where damp plaster hid a split; a longer brace would hold only if the rotten end is cut back.', [{ id: 'replace', label: 'Cut back to sound wood and fit a shorter brace', next: 'settlement', effects: { setFlags: ['sound_repair'] } }, { id: 'shore', label: 'Brace the landing temporarily and close the stair', next: 'settlement', effects: { setFlags: ['temporary_repair'] } }, { id: 'conceal', label: 'Cover the split and finish before the market', next: 'badFit' }]),
    settlement: scene('settlement', 'A Safe Landing', 'The stair is closed until the brace is tested. Elian walks the frame with you; the new joint holds, though the market opens a little late. He has a spare square from his old kit and offers a choice of share.', itemOffer('carpenterSquare', 'Carpenter’s Square', 'paidTool', 'Elian releases his retired shop square to you after the repair passes his weight test.', 'A stair frame can look straight at the front while its diagonals reveal racking.')),
    paidTool: end('paidTool', 'A Square in Your Roll', 'Elian marks the square as yours and shows you how he checked the diagonals.'),
    badFit: end('badFit', 'A Repair Sent Back', 'The brace shifts under the first careful test. Elian closes the stair and starts again; you receive no share, but the crowd is kept clear.'),
  }),
  make('a-rim-before-rain', 'A Rim before Rain', 'A wheelwright needs a second pair of hands while a wagon wheel is trued outdoors.', 'A tight iron rim may conceal a cracked spoke beneath fresh paint.', 'roadside wheelwright shed', 'MODERATE', 'wheel', {
    wheel: scene('wheel', 'The Wheel on Blocks', 'Wheelwright Ada Pike sets a wagon wheel on two blocks. The iron tire is nearly seated and rain is moving over the ridge. She asks whether to tighten the last wedge now or inspect a dark spoke first.', [{ id: 'inspect', label: 'Turn the wheel and listen to each spoke', next: 'crack' }, { id: 'wrench', label: 'Use your Compact Wheel Wrench to hold the hub steady', requirements: { items: ['compactWheelWrench'] }, next: 'crack' }, { id: 'finish', label: 'Drive the last wedge before the rain', next: 'split' }]),
    crack: scene('crack', 'A Different Sound', 'One spoke answers dull. The tire is sound; the wood beneath the paint is split at the shoulder. Ada can replace it now, but the customer needs the wagon by afternoon.', [{ id: 'replace', label: 'Fit a sound spoke and reset the tire', next: 'settlement' }, { id: 'delay', label: 'Tell the customer the wheel must wait for a proper spoke', next: 'settlement', effects: { knowledge: ['A dull note at one spoke can reveal a split beneath paint; a tight iron tire does not prove the wheel is sound.'] } }]),
    settlement: scene('settlement', 'The Wheel Rolls True', 'The customer accepts the delay after Ada demonstrates the crack. She has an older wheel wrench that still fits common hub bands; your wage can be coin or the tool.', itemOffer('compactWheelWrench', 'Compact Wheel Wrench', 'paidTool', 'Ada gives you her retired wrench after the repaired wheel rolls true.', 'A wheel can be round at the rim while a split spoke shifts under the hub load.')),
    paidTool: end('paidTool', 'An Old Wrench, Still Useful', 'Ada wipes the wrench clean and transfers it to your kit.'),
    split: end('split', 'A Rim that Will Not Hold', 'The spoke opens under the wedge. Ada pulls the wheel from service; the wagon waits for a safer repair.'),
  }, 'labor/repair'),
  make('the-iron-that-went-blue', 'The Iron That Went Blue', 'A blacksmith asks for help finishing a replacement hinge before the forge cools.', 'Color and sound matter more than speed when a bar has been overheated.', 'blacksmith forge', 'LOW', 'forge', {
    forge: scene('forge', 'A Hinge at the Anvil', 'Smith Miriam Holt heats a hinge leaf for a gate that must close before the stock is moved. The iron’s edge has turned blue sooner than expected. She asks you to work the bellows or check the bar.', [{ id: 'check', label: 'Check the thin edge before another heat', next: 'grain' }, { id: 'bellows', label: 'Keep the bellows even while Miriam watches the color', next: 'grain' }, { id: 'strike', label: 'Strike now while the bar is bright', next: 'brittle' }]),
    grain: scene('grain', 'A Hairline at the Eye', 'A fine line runs from the hinge eye. The gate can be held shut with a wooden pin while Miriam cuts away the weakened end and draws a new eye.', [{ id: 'redraw', label: 'Help draw a new eye from sound iron', next: 'settlement' }, { id: 'pin', label: 'Set a temporary wooden pin and return tomorrow', next: 'settlement', effects: { knowledge: ['A blue edge can mean thin iron has lost a safe working temper; inspect the eye before striking again.'] } }]),
    settlement: scene('settlement', 'The Gate Closes', 'The hinge swings without binding. Miriam offers the compact hammer she used as an apprentice; it is sound, but she now keeps a heavier shop hammer.', itemOffer('bridgewrightHammer', 'Bridgewright’s Hammer', 'paidTool', 'Miriam gives you her personal field hammer as payment for the careful work.', 'A hinge eye can hide a crack that appears only after the first fit test.')),
    paidTool: end('paidTool', 'A Hammer with a History', 'Miriam initials the old handle and tells you to use it for pegs and careful fitting, not heavy demolition.'),
    brittle: end('brittle', 'A Hinge Rejected', 'The eye opens under the first strike. Miriam sets the hinge aside and explains why a second heat was needed.'),
  }),
  make('the-harness-stitch', 'The Harness Stitch', 'A saddler needs help repairing tack before a team can leave for the upland farms.', 'A polished strap has hidden wear where it bends around a buckle.', 'saddler shop and farm lane', 'MODERATE', 'strap', {
    strap: scene('strap', 'The Shining Surface', 'Saddler Ren Vale lays out a trace strap that looks clean on top but has stiffened at the buckle fold. The teamster insists it held yesterday. Ren asks you to flex it or replace it outright.', [{ id: 'flex', label: 'Flex the strap slowly and inspect the underside', next: 'threads' }, { id: 'punch', label: 'Use the shop’s punch to test the worn hole edges', next: 'threads' }, { id: 'reuse', label: 'Oil the surface and send the team on time', next: 'snap' }]),
    threads: scene('threads', 'Threads under the Fold', 'Two inner plies have separated. Ren has enough leather for one replacement trace, but not a full harness. The other side can be reinforced if the teamster accepts a slower load.', [{ id: 'replace', label: 'Replace the failed trace and reduce the load', next: 'settlement' }, { id: 'reinforce', label: 'Reinforce both traces and send one wagon at a time', next: 'settlement', effects: { knowledge: ['Harness leather often fails inside the buckle fold before the polished outside looks worn.'] } }]),
    settlement: scene('settlement', 'A Team Sent Safely', 'The teamster agrees to the slower trips. Ren has a small leather mending roll he no longer carries on field calls and offers it as your share.', itemOffer('leatherRepairRoll', 'Leather Repair Roll', 'paidTool', 'Ren gives you his spare mending roll, including needles, waxed thread, and a small punch.', 'A harness strap must be checked at its folds and holes, not judged by its polished face.')),
    paidTool: end('paidTool', 'The Roll Is Yours', 'Ren shows you how he keeps the needles wrapped so they do not pierce the thread pouch.'),
    snap: end('snap', 'The Trace Gives Way', 'The strap parts under a light pull. The horses are stopped before the wagon moves; the teamster loses the morning but avoids a runaway load.'),
  }, 'animals'),
  make('the-lantern-on-the-lower-hook', 'The Lantern on the Lower Hook', 'A tinsmith asks you to test a lantern housing before it returns to a night crew.', 'The glass is sound, but a loose guard rattles against the chimney.', 'tin and lamp shop', 'LOW', 'lamp', {
    lamp: scene('lamp', 'A Rattle in the Housing', 'Tinsmith Oren Bell has replaced a lantern’s lower hinge. The flame burns steady, but the wire guard taps the glass whenever the door swings. He asks you to walk it or tighten the hinge first.', [{ id: 'walk', label: 'Carry it along the alley and listen for the rattle', next: 'hinge' }, { id: 'fit', label: 'Fit your Lantern Guard over the glass for a field test', requirements: { items: ['lanternGuard'] }, next: 'hinge' }, { id: 'ship', label: 'Send it back because the flame is steady', next: 'complaint' }]),
    hinge: scene('hinge', 'The Guard Has Shifted', 'The hinge is square; the guard’s bottom loop was bent during the repair. Oren can reshape it cold, but the crew is waiting for its night signal lamp.', [{ id: 'reshape', label: 'Hold the housing while Oren reshapes the loop', next: 'settlement' }, { id: 'replace', label: 'Fit a spare guard and keep the bent one for later', next: 'settlement' }]),
    settlement: scene('settlement', 'A Quiet Walk Test', 'The guard clears the chimney and no longer touches the glass. Oren has a spare cage from a retired road lamp and offers it instead of the two-coin rush wage.', itemOffer('lanternGuard', 'Lantern Guard', 'paidTool', 'Oren releases the spare guard after the lamp passes its carry test.', 'A lantern guard protects glass from knocks, but cannot correct a bad hinge or improve the flame.')),
    paidTool: end('paidTool', 'A Guard for the Road', 'Oren marks the spare as yours and reminds you to check that it clears the chimney.'),
    complaint: end('complaint', 'A Second Return', 'The crew brings the lamp back when the guard taps the glass. Oren delays the handoff and repairs the loop properly.'),
  }),
  make('the-roofline-in-wind', 'The Roofline in Wind', 'A roofer needs help keeping slate and tools secure as a squall crosses the ridge.', 'A sound anchor point matters more than climbing quickly.', 'inn roof and ridge road', 'HIGH', 'roof', {
    roof: scene('roof', 'Slates over the Yard', 'Roofer Tamsin Reed is halfway along an inn roof when the wind lifts a loose slate. The ladder is tied to a porch post; a gutter is pulling away above the public yard. She asks you to secure the ladder or clear the yard.', [{ id: 'rope', label: 'Use your Travel Rope to add a second ladder tie', requirements: { items: ['travelRope'] }, next: 'gutter' }, { id: 'clear', label: 'Move people out of the fall line before touching the gutter', next: 'gutter' }, { id: 'climb', label: 'Climb up and hold the gutter while Tamsin nails it', next: 'fall' }]),
    gutter: scene('gutter', 'A Nail in Rotten Fascia', 'The gutter is attached to rotten fascia. The roof edge is not safe to load; Tamsin can reach a sound rafter from above, but the ladder must stay braced and the yard below clear.', [{ id: 'brace', label: 'Brace the ladder and pass up a longer batten', next: 'settlement' }, { id: 'close', label: 'Close the yard and wait for calmer weather', next: 'settlement', effects: { knowledge: ['A roof edge can appear firm while rotten fascia fails under a person’s weight; brace to a sound frame, not the gutter.'] } }]),
    settlement: scene('settlement', 'The Yard Reopens', 'The fascia is replaced from the sound rafter and the inn yard remains closed until the last slate is fixed. Tamsin offers her shorter field rope as a work share.', itemOffer('travelRope', 'Travel Rope', 'paidTool', 'Tamsin transfers her retired field rope after inspecting its full length and hook.', 'When securing a ladder, anchor to a sound structural post rather than the gutter or fascia.')),
    paidTool: end('paidTool', 'A Rope Checked End to End', 'Tamsin shows you the worn section she removed from the old line; the rope she gives you has passed inspection.'),
    fall: end('fall', 'A Fall Avoided', 'The gutter tears free as the fascia breaks. You drop to the porch roof, bruised; Tamsin clears the yard and stops work until the frame is inspected.'),
  }),
  make('the-line-that-would-not-hold', 'The Line That Would Not Hold', 'A telegraph repairer asks for help tracing a signal fault before the next train.', 'The trouble is at a wet splice, not the distant pole everyone blamed.', 'telegraph siding', 'MODERATE', 'signal', {
    signal: scene('signal', 'A Dead Instrument', 'Line worker Asa Morrow hears no answer from the north station. A replacement insulator is ready, but the wire at the near post sags over wet grass. He asks you to inspect the ground connection or climb to the pole.', [{ id: 'inspect', label: 'Inspect the near splice from the dry side', next: 'splice' }, { id: 'tool', label: 'Use your Pocket Toolkit to tighten the instrument binding', requirements: { items: ['pocketToolkit'] }, next: 'splice' }, { id: 'lineTester', label: 'Use your Telegraph Line Tester to compare the near section from dry ground', requirements: { items: ['telegraphLineTester'] }, next: 'splice', effects: { setFlags: ['batch9_tester_used_at_wet_splice'], historyFlags: ['used_telegraph_line_tester_at_wet_splice'] } }, { id: 'climb', label: 'Climb first and replace the far insulator', next: 'shock' }]),
    splice: scene('splice', 'A Wet Binding', 'The binding screw is loose, and damp has crept beneath the insulation. The far insulator is intact. Asa can dry and rewrap the splice, but the office needs a hand-carried message meanwhile.', [{ id: 'wrap', label: 'Help dry and rewrap the splice before testing', next: 'settlement' }, { id: 'relay', label: 'Send the message by rider, then repair without rushing', next: 'settlement', effects: { knowledge: ['A silent telegraph instrument can result from a wet near splice even when the distant insulator is sound.'] } }]),
    settlement: scene('settlement', 'The Key Clicks', 'The station answers after the dry wrap is tested under load. Asa has a retired small service toolkit that he no longer carries on the line.', itemOffer('pocketToolkit', 'Pocket Toolkit', 'paidTool', 'Asa gives you his service kit after the line passes a second test.', 'Test a telegraph line at the near splice before climbing to replace a distant part.')),
    paidTool: end('paidTool', 'A Kit Released from Service', 'Asa removes the line-office tag and gives you the kit as your work share.'),
    shock: end('shock', 'A Climb Called Off', 'A wet branch touches the wire before you reach the pole. Asa pulls you back to the dry bank and sends for an insulated ladder.'),
  }),
  make('the-press-before-noon', 'The Press before Noon', 'A printer needs help finishing a town notice after the platen begins to skew.', 'A rushed impression hides a loose bed screw and uneven packing.', 'newspaper press room', 'LOW', 'press', {
    press: scene('press', 'Ink Heavy on One Side', 'Printer Cora Dain pulls a test sheet from the hand press. The left edge is dark and the right is pale. The town notice must be posted before noon, but no one has checked whether the bed or packing is at fault.', [{ id: 'measure', label: 'Compare the margins against the Joiner’s Folding Rule', requirements: { items: ['joinersFoldingRule'] }, next: 'test' }, { id: 'wash', label: 'Clean the platen and pull another test sheet', next: 'test' }, { id: 'run', label: 'Print the full stack and sort the worst copies later', next: 'spoiled' }]),
    test: scene('test', 'A Loose Bed Screw', 'The second sheet repeats the dark edge. The press bed shifts a fraction under pressure; Cora can tighten it and reset the packing, but the notice will be late.', [{ id: 'adjust', label: 'Hold the bed square while Cora tightens the screw', next: 'settlement' }, { id: 'post', label: 'Print a short corrected notice and post it after noon', next: 'settlement', effects: { knowledge: ['Uneven ink that repeats in the same margin after cleaning often points to a shifting press bed, not dirty type.'] } }]),
    settlement: scene('settlement', 'A Legible Notice', 'The corrected type prints evenly. Cora has a spare hardwood folding rule from the shop’s first compositor and offers it as your share.', itemOffer('joinersFoldingRule', 'Joiner’s Folding Rule', 'paidTool', 'Cora gives you the unused rule after the press bed is square again.', 'Repeat the test impression after cleaning; a consistent dark margin can reveal a shifting bed.')),
    paidTool: end('paidTool', 'A Rule for Layout Work', 'Cora transfers the shop’s spare rule to you and explains its worn zero edge.'),
    spoiled: end('spoiled', 'A Stack to Reprint', 'The same dark margin runs through the notice. Cora stops the press before more paper is wasted and resets the bed.'),
  }),
  make('the-ferry-gate-pin', 'The Ferry Gate Pin', 'A mechanic asks you to help free a jammed landing gate before the next crossing.', 'A bent retaining pin is the cause; forcing the gate would twist the hinge.', 'ferry landing', 'MODERATE', 'gate', {
    gate: scene('gate', 'A Gate Half Open', 'Mechanic Jonas Vale works the ferry landing gate by hand. It stops halfway and springs back. The ferryman says the hinge has always been stiff; Jonas notices a bright scrape at the lower pin.', [{ id: 'inspect', label: 'Inspect the lower pin before levering the gate', next: 'pin' }, { id: 'tool', label: 'Use your Foreman’s Multi-tool to loosen the cover', requirements: { items: ['foremanMultiTool'] }, next: 'pin' }, { id: 'force', label: 'Pull the gate through the stiff point', next: 'twist' }]),
    pin: scene('pin', 'The Bent Retainer', 'The retainer has curled behind the hinge plate. Jonas can punch it out if you support the gate; the ferry must remain tied off during the work.', [{ id: 'support', label: 'Support the gate and let Jonas drive the pin clear', next: 'settlement' }, { id: 'close', label: 'Keep the landing closed and wait for a replacement pin', next: 'settlement', effects: { knowledge: ['A bright scrape at a hinge can show a bent retainer pin; forcing the gate loads the hinge instead.'] } }]),
    settlement: scene('settlement', 'The Gate Swings Freely', 'The new pin seats and the gate opens without pulling the hinge out of line. Jonas offers a spare folding pry tool from his repair chest.', itemOffer('foldingPryTool', 'Folding Pry Tool', 'paidTool', 'Jonas releases the spare tool after the gate passes repeated open-and-close tests.', 'Inspect a gate’s retainer and scrape marks before applying force to a stiff hinge.')),
    paidTool: end('paidTool', 'A Tool for Careful Leverage', 'Jonas labels the pry tool yours and demonstrates where its short leverage is safe.'),
    twist: end('twist', 'A Hinge Put Out of Line', 'The gate moves, then twists against the damaged pin. Jonas closes the landing and replaces both pin and hinge plate.'),
  }),
  make('the-belt-at-the-mill', 'The Belt at the Mill', 'A millwright asks you to help keep grain moving while a drive belt slips.', 'The belt is tracking crooked because a bearing has begun to seize.', 'country grist mill', 'MODERATE', 'belt', {
    belt: scene('belt', 'A Belt Walking Sideways', 'Millwright Hester Cole stops the wheel before the drive belt walks off its pulley. The grain bins are near full. She asks you to check the belt alignment or carry out sacks while the mill stands still.', [{ id: 'align', label: 'Sight the pulley faces while the wheel is stopped', next: 'bearing' }, { id: 'tool', label: 'Use your Pocket Toolkit to inspect the bearing cap', requirements: { items: ['pocketToolkit'] }, next: 'bearing' }, { id: 'run', label: 'Restart slowly and watch the belt under load', next: 'spill' }]),
    bearing: scene('bearing', 'Warm Grease and Fine Dust', 'The belt is aligned, but the near bearing is warmer and gritty. Hester can clean and oil it; the flour order will miss the cart if the wheel stays stopped another hour.', [{ id: 'clean', label: 'Clean the bearing and test the wheel unloaded', next: 'settlement' }, { id: 'divert', label: 'Send the flour by handcart and finish the repair safely', next: 'settlement', effects: { knowledge: ['A belt that walks off a correctly aligned pulley may be tracking a hot or gritty bearing.'] } }]),
    settlement: scene('settlement', 'The Mill Turns Slowly', 'The bearing runs cool after an unloaded test, then Hester feeds the mill gradually. She offers her compact stove tool, which fits the mill’s small covers and latch screws.', itemOffer('compactStoveTool', 'Compact Stove Tool', 'paidTool', 'Hester releases her retired fitting tool as your work share.', 'After aligning pulleys, test bearings unloaded for heat and grit before restoring the full belt load.')),
    paidTool: end('paidTool', 'A Fitting Tool for the Road', 'Hester confirms the tool is yours and not needed for the mill’s larger fasteners.'),
    spill: end('spill', 'Grain on the Floor', 'The belt slips under load and shakes a bin chute loose. Hester stops the wheel; the spilled grain is swept up before the bearing is examined.'),
  }),
  make('the-stone-quoin', 'The Stone Quoin', 'A mason asks for help stabilizing a corner before rain reaches the mortar.', 'The wall’s visible crack is old; a loose corner stone is the immediate risk.', 'town retaining wall', 'MODERATE', 'wall', {
    wall: scene('wall', 'A Crack above the Lane', 'Mason Della Frost points out a diagonal crack in a retaining wall. A cart road runs below it. The corner stone has shifted outward, while the deeper crack is dry and old.', [{ id: 'close', label: 'Close the lane before touching the wall', next: 'quoin' }, { id: 'probe', label: 'Use a Collapsible Sounding Rod to check the packed soil', requirements: { items: ['collapsibleSoundingRod'] }, next: 'quoin' }, { id: 'mortar', label: 'Pack fresh mortar into the visible crack', next: 'fall' }]),
    quoin: scene('quoin', 'The Corner that Moves', 'The corner stone rocks under pressure. Della can ease it back only after the wall is shored; rain is approaching and the lane closure angers a nearby shopkeeper.', [{ id: 'shore', label: 'Set a timber shore, then reset the corner stone', next: 'settlement' }, { id: 'delay', label: 'Keep the lane closed and wait for a second mason', next: 'settlement', effects: { knowledge: ['A moving corner stone needs shoring before mortar; filling a crack does not stabilize the wall.'] } }]),
    settlement: scene('settlement', 'The Lane Reopens', 'The corner is reset on a sound bed and the old crack is marked for later survey. Della gives you a steel wedge she no longer uses after changing her kit.', itemOffer('steelWedge', 'Steel Wedge', 'paidTool', 'Della releases the wedge as a tool share once the wall is stable.', 'A wall crack may be old while one loose quoin is an immediate structural hazard.')),
    paidTool: end('paidTool', 'A Wedge with a Clear Purpose', 'Della transfers the wedge and cautions you to shore before driving it.'),
    fall: end('fall', 'Mortar without Support', 'The fresh mortar hides the crack but the corner stone shifts again. Della keeps the lane closed and resets the work safely.'),
  }),
  make('the-last-at-the-cobbler', 'The Last at the Cobbler', 'A cobbler asks you to help settle a dispute over a boot that split on its first wet day.', 'The customer’s sole was sound; the upper tore where the last was too narrow.', 'cobbler shop', 'LOW', 'boot', {
    boot: scene('boot', 'A Split at the Welt', 'Cobbler Emmett Shaw sets the boot beside its mate. The customer says the repair failed; Emmett says the leather was already cracked. The split follows the welt but stops before the sole.', [{ id: 'inspect', label: 'Compare the two boots at the welt and toe', next: 'fit' }, { id: 'awl', label: 'Use the shop awl to trace where the seam first opened', next: 'fit' }, { id: 'blame', label: 'Tell the customer the repair should be free', next: 'argument' }]),
    fit: scene('fit', 'A Last Too Narrow', 'The mate boot shows matching pressure marks. Emmett admits he used a narrow last to meet the rush deadline. The leather can be patched, but the customer needs a dry pair tomorrow.', [{ id: 'patch', label: 'Patch the upper and let it dry overnight', next: 'settlement' }, { id: 'replace', label: 'Offer a replacement upper at the shop’s cost', next: 'settlement', effects: { knowledge: ['Pressure marks on both boots can reveal a poor fit even when only one upper has split.'] } }]),
    settlement: scene('settlement', 'A Fair Repair', 'The customer accepts the patch after Emmett takes responsibility for the narrow fit. He offers a small repair roll that he keeps for field visits.', itemOffer('leatherRepairRoll', 'Leather Repair Roll', 'paidTool', 'Emmett gives you his duplicate field roll after showing its contents and transferring ownership.', 'Compare wear on both boots; matching pressure marks may point to the last, not a single bad seam.')),
    paidTool: end('paidTool', 'A Roll for Small Repairs', 'Emmett marks the roll as yours and replaces its waxed thread before you leave.'),
    argument: end('argument', 'A Dispute without a Test', 'The customer refuses to decide before the boots are compared. Emmett offers to inspect them in daylight and no repair is charged today.'),
  }),
  make('the-ropewalk-splice', 'The Ropewalk Splice', 'A rope-maker needs help testing a new splice before it is sent to a ferry crew.', 'A neat splice can still slip if the strands were laid against their lay.', 'ropewalk and ferry yard', 'LOW', 'splice', {
    splice: scene('splice', 'Three Strands on the Bench', 'Rope-maker Bram Saye lays a new eye splice beside an older line. The strands look even, but the eye narrows when pulled. He asks you to mark the lay or test under a light load.', [{ id: 'mark', label: 'Mark each strand before opening the splice', next: 'load' }, { id: 'clamp', label: 'Use the Iron Rope Clamp to hold the standing line', requirements: { items: ['ironRopeClamp'] }, next: 'load' }, { id: 'full', label: 'Put the full ferry load on it at once', next: 'slip' }]),
    load: scene('load', 'A Turn against the Lay', 'The strands were tucked against their lay. Under a light load the eye begins to creep; Bram can open and lay it again, but the ferry crew will miss a tide window.', [{ id: 'relay', label: 'Help relay the ferry crew’s message while Bram resplices', next: 'settlement' }, { id: 'wait', label: 'Hold the line and wait for the corrected test', next: 'settlement', effects: { knowledge: ['A splice can look even but creep under load when its tucks oppose the rope’s lay.'] } }]),
    settlement: scene('settlement', 'The Eye Holds', 'The corrected splice holds through a gradual test. Bram releases a spare iron clamp from his old rigging kit as part of your wages.', itemOffer('ironRopeClamp', 'Iron Rope Clamp', 'paidTool', 'Bram transfers the spare clamp after the corrected line passes its load test.', 'Load-test a new eye splice gradually; a narrowing eye can expose a tuck laid against the rope.')),
    paidTool: end('paidTool', 'A Clamp for Wet Lines', 'Bram marks the clamp as yours and explains how it protects a line when wet knots cannot be trusted.'),
    slip: end('slip', 'A Failed Test, Not a Ferry Failure', 'The eye slips under the heavy test. Bram catches the line on the secondary post and refuses to send it to the ferry until respliced.'),
  }),
  make('the-door-that-swelled', 'The Door that Swelled', 'A carpenter asks you to help free a store-room door after days of rain.', 'The door is binding at the sill because the frame has settled, not because the lock is stuck.', 'farm storehouse', 'LOW', 'door', {
    door: scene('door', 'A Lock that Turns', 'Carpenter Nessa Vale turns the store-room key cleanly, but the door will not open. The owner asks her to plane the latch side quickly; damp has raised the sill and flour sacks wait inside.', [{ id: 'inspect', label: 'Check the gap at sill and hinge before planing', next: 'settle' }, { id: 'tool', label: 'Use a Folding Pry Tool only to lift the door slightly', requirements: { items: ['foldingPryTool'] }, next: 'settle' }, { id: 'plane', label: 'Plane the latch edge until it clears', next: 'bind' }]),
    settle: scene('settle', 'A Settled Hinge', 'The lower hinge screws have loosened in the damp frame. Nessa can reset the hinge into sound wood; the door will still swell in heavy rain unless the owner keeps the sill clear.', [{ id: 'reset', label: 'Reset the hinge and test the door before trimming', next: 'settlement' }, { id: 'explain', label: 'Explain the seasonal swell and schedule a dry-day trim', next: 'settlement', effects: { knowledge: ['A door that binds at the sill after rain may have a settled hinge or swollen frame, not a faulty lock.'] } }]),
    settlement: scene('settlement', 'The Door Opens without Force', 'The hinge holds and the latch turns freely. Nessa gives you her retired pry tool rather than charge for the extra diagnosis.', itemOffer('foldingPryTool', 'Folding Pry Tool', 'paidTool', 'Nessa releases her old tool once the door swings under its own weight.', 'Check the hinge and sill gap before removing material from a swollen door.')),
    paidTool: end('paidTool', 'A Retired Tool Released', 'Nessa scratches her initials off the handle and transfers the tool to you.'),
    bind: end('bind', 'A Door Made Worse', 'The latch edge is thinner, but the door still binds at the sill. Nessa resets the hinge before any more wood is removed.'),
  }),
  make('paper-under-the-press', 'Paper under the Press', 'A bookbinder asks for help rescuing a damp ledger without separating its signatures.', 'The cover is swollen, but the ink has not yet run through the folded sections.', 'county records room', 'LOW', 'ledger', {
    ledger: scene('ledger', 'A Wet Spine', 'Bookbinder Lio March finds a ledger damp at the spine after a roof leak. The clerk wants it opened flat so the entries can be copied. Lio warns the sewing may tear if the pages are forced.', [{ id: 'support', label: 'Support the spine and open only one gathering at a time', next: 'ink' }, { id: 'canvas', label: 'Lay your Waxed Canvas Sheet beneath the volume', requirements: { items: ['waxedCanvasSheet'] }, next: 'ink' }, { id: 'press', label: 'Press the volume flat before the ink dries', next: 'tear' }]),
    ink: scene('ink', 'The Ink at the Fold', 'The outer page is blurred, but the inner gatherings remain legible. The clerk needs a usable copy today; Lio proposes a partial transcription while the book dries under weight.', [{ id: 'copy', label: 'Help copy the intact gatherings first', next: 'settlement' }, { id: 'wait', label: 'Refuse to open it further until it dries', next: 'settlement', effects: { knowledge: ['A damp book can be opened by supported gatherings; forcing the whole spine flat risks tearing the sewing.'] } }]),
    settlement: scene('settlement', 'The Ledger Kept Together', 'The intact entries are copied and the volume dries without losing its sewing. Lio offers a lockable map case he has replaced with a larger one.', itemOffer('lockableMapCase', 'Lockable Map Case', 'paidTool', 'Lio gives you his retired case after removing the county office mark.', 'Support a damp book at its spine and work gathering by gathering rather than forcing it flat.')),
    paidTool: end('paidTool', 'A Case for Your Papers', 'Lio transfers the case as your share; it is yours to use for maps or papers.'),
    tear: end('tear', 'A Torn Gathering', 'The sewing strains before the volume lies flat. Lio stops the press and begins a slower drying process.'),
  }),
  make('the-boat-seam-in-the-yard', 'The Boat Seam in the Yard', 'A boatwright needs help deciding whether a skiff can be launched after a patch.', 'The seam is dry above the waterline but still weeps when the hull flexes.', 'river boatyard', 'MODERATE', 'seam', {
    seam: scene('seam', 'A Patch before Launch', 'Boatwright Sella Ward has patched a skiff’s side seam. The owner wants to launch before the river drops. The patch looks dry, though the hull rests unevenly on two blocks.', [{ id: 'level', label: 'Level the hull before testing the seam', next: 'leak' }, { id: 'canvas', label: 'Use your Waxed Canvas Sheet to keep the patch covered', requirements: { items: ['waxedCanvasSheet'] }, next: 'leak' }, { id: 'launch', label: 'Launch now and watch from the bank', next: 'leak' }]),
    leak: scene('leak', 'Water at the Lower Plank', 'A bead appears where the plank flexes near the lower block. Sella can reset the block and let the pitch cure another hour, but the owner’s cargo will miss the afternoon ferry.', [{ id: 'cure', label: 'Keep the skiff ashore until the pitch cures', next: 'settlement' }, { id: 'transfer', label: 'Move the cargo to a sound ferry and finish the patch', next: 'settlement', effects: { knowledge: ['Test a hull patch while the boat is level; a seam may open only when the planks flex under water.'] } }]),
    settlement: scene('settlement', 'A Dry Bilge Test', 'The skiff stays ashore until the seam holds a bucket test. Sella offers a spare waxed sheet from her repair kit as your share.', itemOffer('waxedCanvasSheet', 'Waxed Canvas Sheet', 'paidTool', 'Sella releases her spare cover after the patched hull passes a dry bilge test.', 'A seam that beads only under hull flex needs a level test before launch.')),
    paidTool: end('paidTool', 'A Sheet for Rough Cover', 'Sella transfers the spare canvas and explains it is for temporary cover, not a permanent hull patch.'),
  }),
  make('the-horse-that-wore-one-strap', 'The Horse that Wore One Strap', 'A harness-maker asks for help fitting a replacement trace before a farm team leaves.', 'A crooked load, not poor stitching alone, wore the old trace unevenly.', 'harness shop and farm track', 'LOW', 'trace', {
    trace: scene('trace', 'Wear on One Side', 'Harness-maker Rosa Pike shows you a trace worn thin on its outside edge. The farmer blames the leather, but the collar sits lower on one shoulder. She asks you to check the fit under a light pull.', [{ id: 'fit', label: 'Walk the horse in harness and watch the collar settle', next: 'load' }, { id: 'gloves', label: 'Use Heavy Leather Gloves to handle the worn buckle safely', requirements: { items: ['heavyLeatherGloves'] }, next: 'load' }, { id: 'replace', label: 'Replace the trace without changing the fit', next: 'chafe' }]),
    load: scene('load', 'A Shoulder under Load', 'The collar rides low when the wagon turns left. Rosa can refit it and sew a replacement trace; the farmer must leave part of the crop at the field until the team is balanced.', [{ id: 'refit', label: 'Refit the collar and test with a lighter wagon', next: 'settlement' }, { id: 'teach', label: 'Show the farmer the fit marks before the next load', next: 'settlement', effects: { knowledge: ['Uneven trace wear can come from a collar that rides low on one shoulder; check fit under a turn.'] } }]),
    settlement: scene('settlement', 'A Team Moving Evenly', 'The traces share the pull after the collar is refit. Rosa offers a spare leather repair roll left from her traveling kit.', itemOffer('leatherRepairRoll', 'Leather Repair Roll', 'paidTool', 'Rosa transfers the spare kit after the harness passes a light-load turn test.', 'Watch the collar under a turn when one trace wears faster than its mate.')),
    paidTool: end('paidTool', 'A Saddler’s Spare', 'Rosa marks the leather roll as yours and explains which repairs should still go to a saddler.'),
    chafe: end('chafe', 'The Same Wear Returns', 'The replacement trace wears at the same edge. Rosa stops the team and refits the collar before another load.'),
  }, 'animals'),
  make('the-clock-above-the-market', 'The Clock above the Market', 'A clock repairer asks you to help test the town clock after a rushed cleaning.', 'The clock loses time only when the striking train is engaged.', 'market square clock room', 'LOW', 'clock', {
    clock: scene('clock', 'A Minute Lost', 'Clockmaker Beatrice Cole has cleaned the public clock, but it loses a minute each hour. The hands move freely. The bell mechanism is due to strike at noon, when the square will be crowded.', [{ id: 'observe', label: 'Compare the hands with a pocket watch through one cycle', next: 'strike' }, { id: 'listen', label: 'Listen to the escapement with the strike train disengaged', next: 'strike' }, { id: 'adjust', label: 'Move the regulator before checking the bell', next: 'wrong' }]),
    strike: scene('strike', 'The Weight of the Bell', 'The clock keeps time while the strike train is disengaged. A worn lifting lever drags only when the bell weight rises. Beatrice can repair it after the noon crowd clears, or silence the bell today.', [{ id: 'silence', label: 'Silence the bell and keep the clock running', next: 'settlement' }, { id: 'repair', label: 'Repair the lever now with the square closed to visitors', next: 'settlement' }]),
    settlement: scene('settlement', 'Noon without a False Chime', 'The hands keep honest time and the bell is tested after the square empties. Beatrice offers to teach you the timing test, or pays the agreed two coins.', [{ id: 'learnMethod', label: 'Learn how to isolate the striking train', effects: { knowledge: ['If a clock keeps time with the striking train disengaged, inspect the lifting lever and bell weight before changing the regulator.'] }, next: 'learned' }, { id: 'takeCoins', label: 'Take the two-coin wage', effects: { money: 2 }, next: 'paid' }, { id: 'decline', label: 'Decline payment and leave the clock to Beatrice', next: 'declined' }]),
    learned: end('learned', 'A Clock without Guesswork', 'Beatrice writes the sequence in your notebook and lets you observe the next strike.'),
    paid: end('paid', 'A Square Noon', 'Beatrice pays the agreed two coins after the clock passes the full test.'),
    declined: end('declined', 'A Quiet Noon', 'The market hears one true chime, and you leave without pay.'),
    wrong: end('wrong', 'The Hands Now Lie', 'The regulator cannot fix a drag that occurs only during the strike. Beatrice resets it and keeps the bell silent until repaired.'),
  }),
  make('the-drill-at-old-number-seven', 'The Drill at Old Number Seven', 'A mine mechanic needs help freeing a jammed hand drill before the crew advances.', 'A buried bit is binding against a knot in the timber, not rock below.', 'mine entry and timber bay', 'HIGH', 'drill', {
    drill: scene('drill', 'A Handle under Strain', 'Mine mechanic Tomas Reed has stopped a hand drill that began to bind in a roof support. The crew waits behind a timber line. He asks you to withdraw the bit or inspect the support first.', [{ id: 'withdraw', label: 'Back the bit out slowly while Tomas holds the frame', next: 'knot' }, { id: 'gloves', label: 'Use Heavy Leather Gloves to inspect the hot collar', requirements: { items: ['heavyLeatherGloves'] }, next: 'knot' }, { id: 'force', label: 'Turn the handle harder to finish the hole', next: 'crush' }]),
    knot: scene('knot', 'A Knot in the Brace', 'The bit catches in a hard knot at the edge of the support. The roof has not shifted, but the hole is too close to the brace’s edge for the planned peg. Tomas can move the fixing point or shore the timber first.', [{ id: 'move', label: 'Mark a new hole in sound timber', next: 'settlement' }, { id: 'shore', label: 'Add a second shore before drilling again', next: 'settlement', effects: { knowledge: ['A hand drill binding in a roof support may have caught a knot; inspect the brace edge before increasing force.'] } }]),
    settlement: scene('settlement', 'A Support that Holds', 'The new fixing point holds under a light test and the crew moves forward only after the roof is checked. Tomas offers a hand auger he has replaced with a newer shop tool.', itemOffer('handAuger', 'Hand Auger', 'paidTool', 'Tomas signs his retired auger over after the support passes inspection.', 'When a bit binds near a mine brace, inspect timber grain and support before applying more force.')),
    paidTool: end('paidTool', 'An Auger Released from the Mine', 'Tomas transfers the auger and shows you its limited pilot-hole use in timber.'),
    crush: end('crush', 'A Brace under Pressure', 'The bit twists and the support groans. Tomas calls the crew back; no one advances until the brace is replaced.'),
  }),
  make('the-long-measure-at-milepost-nine', 'The Long Measure at Milepost Nine', 'A railway surveyor needs help resolving a disagreement about a siding grade.', 'The old chain was stretched at one joint, making the incline look shallower.', 'rail siding and survey stake', 'MODERATE', 'grade', {
    grade: scene('grade', 'Two Marks Do Not Meet', 'Surveyor Ada Senn and a track foreman disagree over whether a siding rises enough to hold a loaded car. The old survey chain has a link bent flat; the car is not on the track yet.', [{ id: 'chain', label: 'Check the line with your Survey Chain', requirements: { items: ['surveyChain'] }, next: 'repeat' }, { id: 'level', label: 'Repeat the measurement from the lower stake', next: 'repeat' }, { id: 'load', label: 'Bring an empty handcar onto the siding as a test', next: 'roll' }]),
    repeat: scene('repeat', 'A Bent Link', 'The bent link adds a small error over the full length. The grade is steeper than the foreman believed, but still safe if a stop block is placed before the curve.', [{ id: 'mark', label: 'Set the stop-block mark and record the corrected grade', next: 'settlement' }, { id: 'close', label: 'Close the siding until the railway rechecks it', next: 'settlement', effects: { knowledge: ['A flattened survey-chain link can accumulate enough error to hide a meaningful siding grade.'] } }]),
    settlement: scene('settlement', 'A Car Held above the Curve', 'The stop block catches the empty test car well before the curve. Ada offers a spare chain section, or the railway pays the agreed field fee.', [{ id: 'takeTool', label: 'Take the spare survey chain as your share instead of coins', requirements: { notOwnedItems: ['surveyChain'] }, effects: { gainItems: ['surveyChain'], historyFlags: ['received_survey_chain_after_grade_check'] }, next: 'tool' }, { id: 'takeCoins', label: 'Take the three-coin field fee', effects: { money: 3 }, next: 'paid' }, { id: 'learnMethod', label: 'Learn how Ada checks chain stretch against a known span', effects: { knowledge: ['Compare a field chain to a known span before trusting a long grade measurement.'] }, next: 'learned' }, { id: 'decline', label: 'Decline the fee and leave the siding closed until inspection', next: 'declined' }]),
    tool: end('tool', 'A Section for Your Kit', 'Ada removes the railway tag and releases the checked spare chain to you.'),
    paid: end('paid', 'The Corrected Grade', 'The foreman records the mark and pays three coins for the field measurement.'),
    learned: end('learned', 'A Measurement Worth Repeating', 'Ada demonstrates the check against a known span before packing the chain.'),
    declined: end('declined', 'A Siding Left Closed', 'The siding stays closed until the railway inspector reviews the record.'),
    roll: end('roll', 'A Car Starts to Roll', 'The empty car moves farther than expected before the foreman catches it. The siding is closed while the grade is measured again.'),
  }),
  make('the-door-at-the-telephone-office', 'The Door at the Telephone Office', 'A locksmith asks you to help repair a service-room latch without replacing the old lock.', 'The latch tongue is sound; the swollen door has dropped on one hinge.', 'telegraph office', 'LOW', 'lock', {
    lock: scene('lock', 'A Key that Turns', 'Locksmith Farah Bell tests the office key. It turns fully, but the latch will not retract unless someone lifts the door. The clerk wants a new lock before the dispatch riders arrive.', [{ id: 'lift', label: 'Lift the door while Farah tests the latch tongue', next: 'hinge' }, { id: 'tool', label: 'Use your Pocket Toolkit to remove the strike plate', requirements: { items: ['pocketToolkit'] }, next: 'hinge' }, { id: 'replace', label: 'Replace the lock before the office opens', next: 'waste' }]),
    hinge: scene('hinge', 'A Hinge Screw in Soft Wood', 'The lower hinge screw has pulled loose from wet wood. Farah can move the plate to sound timber and refit the same lock; the clerk must accept a short delay.', [{ id: 'refit', label: 'Refit the hinge plate in sound wood', next: 'settlement' }, { id: 'explain', label: 'Show the clerk why the lock itself is not faulty', next: 'settlement', effects: { knowledge: ['When a key turns but a latch binds only under door weight, inspect the hinge and strike alignment before replacing the lock.'] } }]),
    settlement: scene('settlement', 'The Key Turns Easily', 'The door closes without lifting and the original lock stays in service. Farah offers her small folding card mirror for future close inspection, or the clerk pays the repair fee.', [{ id: 'takeTool', label: 'Take the Folding Card Mirror instead of the fee', requirements: { notOwnedItems: ['foldingCardMirror'] }, effects: { gainItems: ['foldingCardMirror'], historyFlags: ['received_folding_card_mirror_for_latch_repair'] }, next: 'tool' }, { id: 'takeCoins', label: 'Take two coins for the repair', effects: { money: 2 }, next: 'paid' }, { id: 'learnMethod', label: 'Learn how to read latch alignment under door weight', effects: { knowledge: ['A latch that binds under door weight can be a hinge-alignment problem rather than a lock failure.'] }, next: 'learned' }]),
    tool: end('tool', 'A Mirror for Close Work', 'Farah transfers the mirror and shows how it sees behind a strike plate without dismantling the lock.'),
    paid: end('paid', 'A Repair, Not a Replacement', 'The clerk pays the agreed repair fee and keeps the original lock.'),
    learned: end('learned', 'A Lock Kept in Service', 'Farah records the alignment check in the office ledger.'),
    waste: end('waste', 'A New Lock, Same Trouble', 'The replacement lock binds under the same door weight. Farah stops the fitting and checks the hinge.'),
  }),
  make('the-pump-between-fields', 'The Pump between Fields', 'A pumpwright needs help restoring water without flooding the lower garden.', 'A leather valve cup has dried and narrowed; the well itself is not failing.', 'farm pump house', 'MODERATE', 'pump', {
    pump: scene('pump', 'A Handle without Water', 'Pumpwright Silas Crow works the handle while a farmer watches the dry spout. The well level is normal on the measuring rod. Silas asks you to check the upper joint or open the lower drain.', [{ id: 'joint', label: 'Inspect the upper joint for air leaks', next: 'valve' }, { id: 'tool', label: 'Use the Pocket Toolkit to lift the valve cover', requirements: { items: ['pocketToolkit'] }, next: 'valve' }, { id: 'drain', label: 'Open the lower drain to flush the pipe', next: 'flood' }]),
    valve: scene('valve', 'A Cup Drawn Tight', 'The leather valve cup has dried and curled. It can be softened and reseated, but the first water should be caught in a trough while the seal is tested.', [{ id: 'test', label: 'Reseat the cup and test into the trough', next: 'settlement' }, { id: 'replace', label: 'Fit a new cup and keep the old one for comparison', next: 'settlement', effects: { knowledge: ['A normal well level with a dry pump handle can point to a leaking joint or shrunken valve cup rather than an empty well.'] } }]),
    settlement: scene('settlement', 'Water without a Flood', 'The first bucket runs clear into the trough and the garden stays dry. Silas offers a brass bottle opener from his retired repair kit, useful for small caps and covers.', itemOffer('brassBottleOpener', 'Brass Bottle Opener', 'paidTool', 'Silas transfers the spare tool after the pump holds prime through several strokes.', 'Check the well level and upper joint before assuming a hand pump has run dry.')),
    paidTool: end('paidTool', 'A Small Lever for Covers', 'Silas gives you the tool and demonstrates its narrow use on small caps, not heavy lids.'),
    flood: end('flood', 'A Drain Opened Too Soon', 'Water rushes into the lower garden. Silas closes the drain and clears the valve after the farmer moves the seed trays.'),
  }),
  make('the-slate-on-the-schoolhouse', 'The Slate on the Schoolhouse', 'A roofer asks you to help secure a loose slate before children leave class.', 'The slate’s hook is sound, but a neighboring lath has split.', 'schoolhouse roof', 'MODERATE', 'slate', {
    slate: scene('slate', 'A Loose Corner above the Door', 'Roofer Emmett Vale spots one slate lifting above the schoolhouse entrance. Class has ended, but children are still in the yard. He asks you to hold the ladder or clear the doorway before he climbs.', [{ id: 'clear', label: 'Move the children and close the doorway below', next: 'lath' }, { id: 'rope', label: 'Tie the ladder to a sound porch post with your rope', requirements: { items: ['travelRope'] }, next: 'lath' }, { id: 'hold', label: 'Hold the ladder while Emmett climbs quickly', next: 'slip' }]),
    lath: scene('lath', 'A Split under the Slate', 'The slate hook is intact, but the lath beneath it has split. Emmett can shift the hook to the next sound lath; two neighboring slates may need to come down first.', [{ id: 'shift', label: 'Remove both slates and refit across sound lath', next: 'settlement' }, { id: 'mark', label: 'Mark the section and close the entrance until tomorrow', next: 'settlement', effects: { knowledge: ['A slate hook can remain sound while a split lath beneath it makes the roof edge unsafe.'] } }]),
    settlement: scene('settlement', 'The Entrance Reopens', 'The patched section survives a hose test and the school keeps the entrance closed until the ladder is down. Emmett offers a folding brush saw for your careful help clearing a branch from his ladder path.', itemOffer('foldingBrushSaw', 'Folding Brush Saw', 'paidTool', 'Emmett transfers his spare brush saw after the roof work is inspected.', 'Inspect the lath beneath a roof slate; an intact hook cannot compensate for split support timber.')),
    paidTool: end('paidTool', 'A Saw for Light Brush', 'Emmett gives you the folding saw and explains it is for branches, not structural timber.'),
    slip: end('slip', 'A Ladder Pulled Aside', 'The ladder shifts when a slate falls. Emmett climbs down safely; the entrance is closed until a second tie is fitted.'),
  }),
  make('the-glasshouse-lanterns', 'The Glasshouse Lanterns', 'A glazier needs help checking signal lamps before the rail crew returns after dusk.', 'The colored panes are intact, but one chimney draws poorly because its cap is fitted backward.', 'rail signal glasshouse', 'LOW', 'glass', {
    glass: scene('glass', 'A Red Pane and a Dark Flame', 'Glazier Niko Bell cleans two signal lamps. The red pane is uncracked, but one flame gutters when the door closes. A rail crew needs both lamps after dark.', [{ id: 'chimney', label: 'Inspect the chimney draft before replacing glass', next: 'draft' }, { id: 'gloves', label: 'Use Heavy Leather Gloves to lift the hot housing', requirements: { items: ['heavyLeatherGloves'] }, next: 'draft' }, { id: 'replace', label: 'Replace the red pane while the lamp is still warm', next: 'crack' }]),
    draft: scene('draft', 'A Cap Turned Backward', 'The chimney cap faces into the draft. The glass is sound; Niko can turn the cap and clean the air holes, then test it outdoors away from the glasshouse.', [{ id: 'test', label: 'Turn the cap and test the lamp outside', next: 'settlement' }, { id: 'record', label: 'Record the airflow pattern for the rail crew', next: 'settlement', effects: { knowledge: ['A lamp flame that gutters when closed may have a backward chimney cap or blocked draft holes, not faulty glass.'] } }]),
    settlement: scene('settlement', 'A Steady Signal Flame', 'Both lamps burn steadily in the open air. Niko offers a retired lantern guard from the shop’s road kit instead of the two-coin test fee.', itemOffer('lanternGuard', 'Lantern Guard', 'paidTool', 'Niko releases the spare guard after it clears the lamp chimney in the test.', 'Check draft and cap direction before replacing an intact signal-glass pane.')),
    paidTool: end('paidTool', 'A Guard Released by the Glazier', 'Niko removes the old rail tag and transfers the guard to you.'),
    crack: end('crack', 'A Pane Broken without Cause', 'The warm pane cracks during removal. Niko replaces it after the lamp cools and tests the draft separately.'),
  }),
];
