import type { Scenario } from '../types';

export const THE_WASHOUT: Scenario = {
  id: 'the-washout', title: 'The Washout', subtitle: 'A road disappears beneath a fresh hillside slide.', startScene: 'upperRoad',
  timePhases: [{ id: 'afternoon', label: 'Afternoon Rain', atMinutes: 0 }, { id: 'worsening', label: 'Rain Strengthens', atMinutes: 12 }, { id: 'dusk', label: 'Dusk', atMinutes: 24 }],
  runRandomSelections: [{ id: 'courier', values: ['Euphemia', 'Cato', 'Ysolde', 'Pell', 'Orla'].map((value) => ({ value })) }],
  scenes: {
    upperRoad: { id: 'upperRoad', title: 'Where the Road Ends', tone: 'warning', text: 'You approach from the uphill side. Rain has eaten a thirty-foot section from the road above a steep ravine; the broken edge ends well before the opposite bank. A courier, {{courier}}, is stranded on a firm shelf across the gap with a small handcart. The hillside above you is still shedding stones.', choices: [
      { id: 'markRoad', label: 'Mark the broken road for anyone behind you', hint: 'A bright marker warns travelers without putting you near the edge.', timeCost: 2, next: 'roadMarked', effects: { knowledge: ['The road is gone across the ravine; the uphill edge still sheds stones.'] } },
      { id: 'callCourier', label: 'Call to {{courier}} across the gap', hint: 'They can hear you from the far shelf.', timeCost: 1, next: 'courierAnswers' },
      { id: 'findUpperTrail', label: 'Look for the old upper footpath', hint: 'It may reach the far shelf, but wet ground makes the slope risky.', timeCost: 8, chance: { probability: 0.67, lateProbability: 0.48, lateAfterMinutes: 12, bonusItems: ['trailCompass', 'minerHeadlamp'], bonusProbability: 0.1, successNext: 'upperTrailFound', failureNext: 'roadMarked', successMessage: 'You find a narrow path above the slide, marked by two old stone posts.', failureMessage: 'The slope crumbles before you reach the ridge. You retreat to firm ground.' } },
      { id: 'stepAcrossGap', label: 'Try to jump the broken road', hint: 'The gap is far wider than a safe jump; the loose edge could collapse.', timeCost: 1, chance: { probability: 0.08, successNext: 'courierAnswers', failureNext: 'edgeCollapse', successMessage: 'You reach the far shelf by a narrow ledge just below the road.', failureMessage: 'The wet lip breaks beneath you; you catch a root below the road.', failureEffects: { health: -4, historyFlags: ['fell_at_washout_edge'] } } },
    ] },
    courierAnswers: { id: 'courierAnswers', title: 'A Voice Across the Ravine', tone: 'warning', text: '{{courier}} calls back from the far shelf. They are standing safely, but the handcart is loaded with medicine for the next village. They cannot climb down the wet ravine wall, and the old footpath may still connect to their side.', choices: [
      { id: 'shareSafePlan', label: 'Ask {{courier}} to leave the cart and use the upper trail', next: 'upperTrailFound', effects: { knowledge: ['The courier can walk away from the cart; the medicines are not worth a fall.'] } },
      { id: 'walkForHelp', label: 'Go to the farm for a rope team', hint: 'Help may bring the cart back, but rain keeps falling.', timeCost: 18, next: 'rescueAfterRain' },
      { id: 'signalForHelp', label: 'Signal the far-bank farm', requirements: { anyItems: ['trailWhistle', 'conductorWhistle', 'roadsideSignalMirror', 'farmWhistle'] }, timeCost: 2, next: 'rescueAfterRain', effects: { historyFlags: ['signaled_far_bank_farm_at_washout'] } },
      { id: 'returnByMarkedRoad', label: 'Leave by the marked road and seek help', next: 'roadMarked' },
    ] },
    roadMarked: { id: 'roadMarked', title: 'The Road Is Closed', tone: 'warning', text: 'The broken section is clearly marked from the uphill approach. {{courier}} remains on the firm far shelf beside the handcart. The old footpath is the only route across without climbing into the ravine; rain is making the exposed hillside less stable.', choices: [
      { id: 'takeUpperTrail', label: 'Follow the old footpath above the slide', timeCost: 7, chance: { probability: 0.68, lateProbability: 0.48, lateAfterMinutes: 12, bonusItems: ['trailCompass', 'minerHeadlamp'], bonusProbability: 0.1, successNext: 'upperTrailFound', failureNext: 'edgeCollapse', successMessage: 'The stone posts lead you around the broken road to the far shelf.', failureMessage: 'The path slumps under your boot. You catch a root below the road edge.', failureEffects: { health: -3 } } },
      { id: 'secureEdge', label: 'Secure the near edge with a rope', requirements: { items: ['travelRope'] }, hint: 'The rope can keep you from falling while you inspect the path; it cannot bridge the ravine.', timeCost: 4, next: 'ropeAtEdge', effects: { knowledge: ['A rope protects the near approach but cannot span the washout.'] } },
      { id: 'returnForTeam', label: 'Return to the village for a rope team', timeCost: 20, next: 'rescueAfterRain' },
    ] },
    upperTrailFound: { id: 'upperTrailFound', title: 'The Old Footpath', tone: 'warning', text: 'The footpath follows the ridge above the slide and reaches the far shelf behind {{courier}}. The handcart is too heavy to carry over the narrow path. The courier can walk out safely if the load is left for a later team.', choices: [
      { id: 'leadCourierOut', label: 'Lead {{courier}} over the ridge path', hint: 'Leave the heavy cart where it is; both of you stay above the ravine.', timeCost: 10, next: 'courierSafe', effects: { historyFlags: ['led_courier_away_from_washout'] } },
      { id: 'sendCourierFirst', label: 'Let {{courier}} walk ahead while you guide the cart', hint: 'The cart could pull you off the narrow path.', requirements: { items: ['travelRope'] }, timeCost: 7, chance: { probability: 0.52, lateProbability: 0.34, lateAfterMinutes: 12, bonusItems: ['ironRopeClamp', 'freightmansStrap'], bonusProbability: 0.1, successNext: 'cartRecovered', failureNext: 'courierSafe', successMessage: 'You steady the handcart with the rope until it reaches the ridge.', failureMessage: 'The cart shifts toward the slope. You let go and step back to safety.' } },
      { id: 'leaveLoad', label: 'Leave the cart for a recovery team', next: 'courierSafe', effects: { historyFlags: ['left_medicine_cart_for_later_recovery'] } },
    ] },
    ropeAtEdge: { id: 'ropeAtEdge', title: 'A Secure Near Edge', tone: 'warning', text: 'You anchor the rope to a buried roadside post. It steadies you on the near slope, but the ravine remains too wide to cross. The ridge path starts farther uphill; {{courier}} waits across the break.', choices: [
      { id: 'followRidgeRope', label: 'Use the rope while climbing to the ridge path', timeCost: 8, chance: { probability: 0.8, lateProbability: 0.63, lateAfterMinutes: 12, successNext: 'upperTrailFound', failureNext: 'edgeCollapse', successMessage: 'The rope holds as you climb to the marked ridge path.', failureMessage: 'The soaked bank gives way, but the rope catches you below the road.', failureEffects: { health: -2 } } },
      { id: 'waitRopeTeam', label: 'Stay on firm ground and wait for help', timeCost: 16, next: 'rescueAfterRain' },
    ] },
    edgeCollapse: { id: 'edgeCollapse', title: 'The Bank Gives Way', tone: 'danger', text: 'The wet edge collapses. You catch a root below the road; the ravine floor is still several feet beneath you. {{courier}} remains on the far shelf, out of reach. Your rope or a low branch may help you climb back.', choices: [
      { id: 'climbRoot', label: 'Climb back to the marked road', hint: 'The root may tear free under your weight; a fall from this height into the ravine could be fatal.', timeCost: 2, chance: { probability: 0.69, lateProbability: 0.49, lateAfterMinutes: 12, successNext: 'safeRetreat', failureNext: 'playerLost', successMessage: 'You pull yourself onto firm ground, scraped but alive.', failureMessage: 'The root tears free and the slope carries you into the ravine.', failureEffects: { health: -3 } } },
      { id: 'useRopeClimb', label: 'Climb your anchored rope', requirements: { items: ['travelRope'] }, next: 'safeRetreat' },
      { id: 'callForHelp', label: 'Call for the team and hold on', timeCost: 8, next: 'rescuedEdge' },
    ] },
    rescueAfterRain: { id: 'rescueAfterRain', title: 'A Team from the Village', tone: 'warning', text: 'A farm team arrives from the uphill road with a long line and carrying poles. The rain has stopped, but more earth could still slide. {{courier}} is visible on the far shelf, and the handcart remains there.', choices: [
      { id: 'guideCourierRope', label: 'Guide {{courier}} along the secured ridge', hint: 'The team anchors both ends before anyone moves.', timeCost: 12, chance: { probability: 0.82, lateProbability: 0.68, lateAfterMinutes: 24, successNext: 'courierSafe', failureNext: 'cartRecovered', successMessage: '{{courier}} crosses the ridge with the team’s line secured.', failureMessage: 'The line holds, but the cart catches at the trail bend and the courier must go on alone.' } },
      { id: 'recoverCartWithTeam', label: 'Rig the handcart for a slow recovery', hint: 'This risks the medicine load and costs time; the courier stays on firm ground.', timeCost: 15, chance: { probability: 0.65, lateProbability: 0.47, lateAfterMinutes: 24, successNext: 'cartRecovered', failureNext: 'courierSafe', successMessage: 'The team hauls the cart onto the ridge without crossing the broken road.', failureMessage: 'The load slips, so the team abandons the cart and brings {{courier}} to safety.' } },
      { id: 'rescuePeopleOnly', label: 'Bring {{courier}} across and leave the cart', next: 'courierSafe' },
    ] },
    rescuedEdge: { id: 'rescuedEdge', title: 'Pulled from the Slope', tone: 'warning', text: 'The farm team reaches you from the uphill road and pulls you onto firm ground. {{courier}} is still on the far shelf. The ridge path is now marked, though the handcart will need a separate recovery.', choices: [
      { id: 'walkWithTeam', label: 'Join the team on the ridge path', next: 'courierSafe' },
      { id: 'letTeamWork', label: 'Leave the rescue to the team', next: 'cartRecovered' },
    ] },
    courierSafe: { id: 'courierSafe', title: 'The Courier Is Safe', tone: 'safe', ending: 'success', choices: [], text: '{{courier}} reaches the uphill road without crossing the missing section. The handcart remains on the far shelf for a later crew. The road stays closed until the hillside is stable.' },
    cartRecovered: { id: 'cartRecovered', title: 'The Load Comes Through', tone: 'safe', ending: 'success', choices: [], text: 'The farm team brings {{courier}} and the medicine cart around the ridge. The washed-out road remains impassable, but the supplies reach the village without anyone crossing the ravine.' },
    safeRetreat: { id: 'safeRetreat', title: 'Back on Firm Ground', tone: 'safe', ending: 'success', choices: [], text: 'You reach firm ground above the washout and retreat from the unstable edge. {{courier}} remains on the far shelf, where the farm team can reach them by the ridge path.' },
    playerLost: { id: 'playerLost', title: 'Below the Road', tone: 'danger', ending: 'death', choices: [], text: 'The root gives way and you fall into the ravine. The farm team reaches {{courier}} by the ridge path, but cannot reach you in time.' },
  },
};
